// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: afip_config.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAfipConfig = `-- name: CreateAfipConfig :one
INSERT INTO afip_config (sucursal_id, cuit, punto_venta, certificado_pem, clave_privada_pem, modo, activo, usuario_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, sucursal_id, cuit, punto_venta, certificado_pem, clave_privada_pem, modo, activo, token, sign, token_expiracion, usuario_id, created_at, updated_at
`

type CreateAfipConfigParams struct {
	SucursalID      pgtype.UUID `json:"sucursal_id"`
	Cuit            string      `json:"cuit"`
	PuntoVenta      int32       `json:"punto_venta"`
	CertificadoPem  pgtype.Text `json:"certificado_pem"`
	ClavePrivadaPem pgtype.Text `json:"clave_privada_pem"`
	Modo            string      `json:"modo"`
	Activo          bool        `json:"activo"`
	UsuarioID       pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) CreateAfipConfig(ctx context.Context, arg CreateAfipConfigParams) (AfipConfig, error) {
	row := q.db.QueryRow(ctx, createAfipConfig,
		arg.SucursalID,
		arg.Cuit,
		arg.PuntoVenta,
		arg.CertificadoPem,
		arg.ClavePrivadaPem,
		arg.Modo,
		arg.Activo,
		arg.UsuarioID,
	)
	var i AfipConfig
	err := row.Scan(
		&i.ID,
		&i.SucursalID,
		&i.Cuit,
		&i.PuntoVenta,
		&i.CertificadoPem,
		&i.ClavePrivadaPem,
		&i.Modo,
		&i.Activo,
		&i.Token,
		&i.Sign,
		&i.TokenExpiracion,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAfipConfig = `-- name: DeleteAfipConfig :exec
DELETE FROM afip_config WHERE sucursal_id = $1 AND usuario_id = $2
`

type DeleteAfipConfigParams struct {
	SucursalID pgtype.UUID `json:"sucursal_id"`
	UsuarioID  pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) DeleteAfipConfig(ctx context.Context, arg DeleteAfipConfigParams) error {
	_, err := q.db.Exec(ctx, deleteAfipConfig, arg.SucursalID, arg.UsuarioID)
	return err
}

const getAfipConfigBySucursal = `-- name: GetAfipConfigBySucursal :one
SELECT ac.id, ac.sucursal_id, ac.cuit, ac.punto_venta, ac.certificado_pem, ac.clave_privada_pem, ac.modo, ac.activo, ac.token, ac.sign, ac.token_expiracion, ac.usuario_id, ac.created_at, ac.updated_at, s.nombre AS sucursal_nombre
FROM afip_config ac
JOIN sucursales s ON s.id = ac.sucursal_id
WHERE ac.sucursal_id = $1 AND ac.usuario_id = $2
`

type GetAfipConfigBySucursalParams struct {
	SucursalID pgtype.UUID `json:"sucursal_id"`
	UsuarioID  pgtype.UUID `json:"usuario_id"`
}

type GetAfipConfigBySucursalRow struct {
	ID              pgtype.UUID        `json:"id"`
	SucursalID      pgtype.UUID        `json:"sucursal_id"`
	Cuit            string             `json:"cuit"`
	PuntoVenta      int32              `json:"punto_venta"`
	CertificadoPem  pgtype.Text        `json:"certificado_pem"`
	ClavePrivadaPem pgtype.Text        `json:"clave_privada_pem"`
	Modo            string             `json:"modo"`
	Activo          bool               `json:"activo"`
	Token           pgtype.Text        `json:"token"`
	Sign            pgtype.Text        `json:"sign"`
	TokenExpiracion pgtype.Timestamptz `json:"token_expiracion"`
	UsuarioID       pgtype.UUID        `json:"usuario_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	SucursalNombre  string             `json:"sucursal_nombre"`
}

func (q *Queries) GetAfipConfigBySucursal(ctx context.Context, arg GetAfipConfigBySucursalParams) (GetAfipConfigBySucursalRow, error) {
	row := q.db.QueryRow(ctx, getAfipConfigBySucursal, arg.SucursalID, arg.UsuarioID)
	var i GetAfipConfigBySucursalRow
	err := row.Scan(
		&i.ID,
		&i.SucursalID,
		&i.Cuit,
		&i.PuntoVenta,
		&i.CertificadoPem,
		&i.ClavePrivadaPem,
		&i.Modo,
		&i.Activo,
		&i.Token,
		&i.Sign,
		&i.TokenExpiracion,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SucursalNombre,
	)
	return i, err
}

const listAfipConfigs = `-- name: ListAfipConfigs :many
SELECT ac.id, ac.sucursal_id, ac.cuit, ac.punto_venta, ac.certificado_pem, ac.clave_privada_pem, ac.modo, ac.activo, ac.token, ac.sign, ac.token_expiracion, ac.usuario_id, ac.created_at, ac.updated_at, s.nombre AS sucursal_nombre
FROM afip_config ac
JOIN sucursales s ON s.id = ac.sucursal_id
WHERE ac.usuario_id = $1
ORDER BY s.nombre
`

type ListAfipConfigsRow struct {
	ID              pgtype.UUID        `json:"id"`
	SucursalID      pgtype.UUID        `json:"sucursal_id"`
	Cuit            string             `json:"cuit"`
	PuntoVenta      int32              `json:"punto_venta"`
	CertificadoPem  pgtype.Text        `json:"certificado_pem"`
	ClavePrivadaPem pgtype.Text        `json:"clave_privada_pem"`
	Modo            string             `json:"modo"`
	Activo          bool               `json:"activo"`
	Token           pgtype.Text        `json:"token"`
	Sign            pgtype.Text        `json:"sign"`
	TokenExpiracion pgtype.Timestamptz `json:"token_expiracion"`
	UsuarioID       pgtype.UUID        `json:"usuario_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	SucursalNombre  string             `json:"sucursal_nombre"`
}

func (q *Queries) ListAfipConfigs(ctx context.Context, usuarioID pgtype.UUID) ([]ListAfipConfigsRow, error) {
	rows, err := q.db.Query(ctx, listAfipConfigs, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAfipConfigsRow
	for rows.Next() {
		var i ListAfipConfigsRow
		if err := rows.Scan(
			&i.ID,
			&i.SucursalID,
			&i.Cuit,
			&i.PuntoVenta,
			&i.CertificadoPem,
			&i.ClavePrivadaPem,
			&i.Modo,
			&i.Activo,
			&i.Token,
			&i.Sign,
			&i.TokenExpiracion,
			&i.UsuarioID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SucursalNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAfipConfig = `-- name: UpdateAfipConfig :one
UPDATE afip_config
SET cuit = $3, punto_venta = $4, certificado_pem = $5, clave_privada_pem = $6, modo = $7, activo = $8, updated_at = NOW()
WHERE sucursal_id = $1 AND usuario_id = $2
RETURNING id, sucursal_id, cuit, punto_venta, certificado_pem, clave_privada_pem, modo, activo, token, sign, token_expiracion, usuario_id, created_at, updated_at
`

type UpdateAfipConfigParams struct {
	SucursalID      pgtype.UUID `json:"sucursal_id"`
	UsuarioID       pgtype.UUID `json:"usuario_id"`
	Cuit            string      `json:"cuit"`
	PuntoVenta      int32       `json:"punto_venta"`
	CertificadoPem  pgtype.Text `json:"certificado_pem"`
	ClavePrivadaPem pgtype.Text `json:"clave_privada_pem"`
	Modo            string      `json:"modo"`
	Activo          bool        `json:"activo"`
}

func (q *Queries) UpdateAfipConfig(ctx context.Context, arg UpdateAfipConfigParams) (AfipConfig, error) {
	row := q.db.QueryRow(ctx, updateAfipConfig,
		arg.SucursalID,
		arg.UsuarioID,
		arg.Cuit,
		arg.PuntoVenta,
		arg.CertificadoPem,
		arg.ClavePrivadaPem,
		arg.Modo,
		arg.Activo,
	)
	var i AfipConfig
	err := row.Scan(
		&i.ID,
		&i.SucursalID,
		&i.Cuit,
		&i.PuntoVenta,
		&i.CertificadoPem,
		&i.ClavePrivadaPem,
		&i.Modo,
		&i.Activo,
		&i.Token,
		&i.Sign,
		&i.TokenExpiracion,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAfipToken = `-- name: UpdateAfipToken :exec
UPDATE afip_config
SET token = $3, sign = $4, token_expiracion = $5, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2
`

type UpdateAfipTokenParams struct {
	ID              pgtype.UUID        `json:"id"`
	UsuarioID       pgtype.UUID        `json:"usuario_id"`
	Token           pgtype.Text        `json:"token"`
	Sign            pgtype.Text        `json:"sign"`
	TokenExpiracion pgtype.Timestamptz `json:"token_expiracion"`
}

func (q *Queries) UpdateAfipToken(ctx context.Context, arg UpdateAfipTokenParams) error {
	_, err := q.db.Exec(ctx, updateAfipToken,
		arg.ID,
		arg.UsuarioID,
		arg.Token,
		arg.Sign,
		arg.TokenExpiracion,
	)
	return err
}

const updateComprobanteAfipEstado = `-- name: UpdateComprobanteAfipEstado :exec
UPDATE comprobantes SET afip_estado = $2::afip_estado WHERE id = $1
`

type UpdateComprobanteAfipEstadoParams struct {
	ID      pgtype.UUID `json:"id"`
	Column2 AfipEstado  `json:"column_2"`
}

func (q *Queries) UpdateComprobanteAfipEstado(ctx context.Context, arg UpdateComprobanteAfipEstadoParams) error {
	_, err := q.db.Exec(ctx, updateComprobanteAfipEstado, arg.ID, arg.Column2)
	return err
}
