// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApiClient struct {
	ID            pgtype.UUID        `json:"id"`
	Nombre        string             `json:"nombre"`
	ApiKey        string             `json:"api_key"`
	ApiSecretHash string             `json:"api_secret_hash"`
	CorsOrigins   []string           `json:"cors_origins"`
	Activo        bool               `json:"activo"`
	LastUsedAt    pgtype.Timestamptz `json:"last_used_at"`
	UsuarioID     pgtype.UUID        `json:"usuario_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// ListApiClients row (excludes api_secret_hash)
type ListApiClientsRow struct {
	ID          pgtype.UUID        `json:"id"`
	Nombre      string             `json:"nombre"`
	ApiKey      string             `json:"api_key"`
	CorsOrigins []string           `json:"cors_origins"`
	Activo      bool               `json:"activo"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

const createApiClient = `-- name: CreateApiClient :one
INSERT INTO api_clients (nombre, api_key, api_secret_hash, cors_origins, usuario_id)
VALUES ($1, $2, $3, $4, $5) RETURNING id, nombre, api_key, api_secret_hash, cors_origins, activo, last_used_at, usuario_id, created_at, updated_at
`

type CreateApiClientParams struct {
	Nombre        string      `json:"nombre"`
	ApiKey        string      `json:"api_key"`
	ApiSecretHash string      `json:"api_secret_hash"`
	CorsOrigins   []string    `json:"cors_origins"`
	UsuarioID     pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) CreateApiClient(ctx context.Context, arg CreateApiClientParams) (ApiClient, error) {
	row := q.db.QueryRow(ctx, createApiClient,
		arg.Nombre, arg.ApiKey, arg.ApiSecretHash, arg.CorsOrigins, arg.UsuarioID,
	)
	var i ApiClient
	err := row.Scan(
		&i.ID, &i.Nombre, &i.ApiKey, &i.ApiSecretHash, &i.CorsOrigins,
		&i.Activo, &i.LastUsedAt, &i.UsuarioID, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const listApiClients = `-- name: ListApiClients :many
SELECT id, nombre, api_key, cors_origins, activo, last_used_at, created_at, updated_at
FROM api_clients WHERE usuario_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListApiClientsParams struct {
	UsuarioID   pgtype.UUID `json:"usuario_id"`
	QueryLimit  int32       `json:"query_limit"`
	QueryOffset int32       `json:"query_offset"`
}

func (q *Queries) ListApiClients(ctx context.Context, arg ListApiClientsParams) ([]ListApiClientsRow, error) {
	rows, err := q.db.Query(ctx, listApiClients, arg.UsuarioID, arg.QueryLimit, arg.QueryOffset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApiClientsRow
	for rows.Next() {
		var i ListApiClientsRow
		if err := rows.Scan(
			&i.ID, &i.Nombre, &i.ApiKey, &i.CorsOrigins,
			&i.Activo, &i.LastUsedAt, &i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const countApiClients = `-- name: CountApiClients :one
SELECT COUNT(*) FROM api_clients WHERE usuario_id = $1
`

func (q *Queries) CountApiClients(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countApiClients, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getApiClient = `-- name: GetApiClient :one
SELECT id, nombre, api_key, api_secret_hash, cors_origins, activo, last_used_at, usuario_id, created_at, updated_at
FROM api_clients WHERE id = $1 AND usuario_id = $2
`

type GetApiClientParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) GetApiClient(ctx context.Context, arg GetApiClientParams) (ApiClient, error) {
	row := q.db.QueryRow(ctx, getApiClient, arg.ID, arg.UsuarioID)
	var i ApiClient
	err := row.Scan(
		&i.ID, &i.Nombre, &i.ApiKey, &i.ApiSecretHash, &i.CorsOrigins,
		&i.Activo, &i.LastUsedAt, &i.UsuarioID, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const getApiClientByKey = `-- name: GetApiClientByKey :one
SELECT id, nombre, api_key, api_secret_hash, cors_origins, activo, last_used_at, usuario_id, created_at, updated_at
FROM api_clients WHERE api_key = $1 AND activo = true
`

func (q *Queries) GetApiClientByKey(ctx context.Context, apiKey string) (ApiClient, error) {
	row := q.db.QueryRow(ctx, getApiClientByKey, apiKey)
	var i ApiClient
	err := row.Scan(
		&i.ID, &i.Nombre, &i.ApiKey, &i.ApiSecretHash, &i.CorsOrigins,
		&i.Activo, &i.LastUsedAt, &i.UsuarioID, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const updateApiClient = `-- name: UpdateApiClient :one
UPDATE api_clients SET nombre = $1, cors_origins = $2, activo = $3, updated_at = NOW()
WHERE id = $4 AND usuario_id = $5 RETURNING id, nombre, api_key, api_secret_hash, cors_origins, activo, last_used_at, usuario_id, created_at, updated_at
`

type UpdateApiClientParams struct {
	Nombre      string      `json:"nombre"`
	CorsOrigins []string    `json:"cors_origins"`
	Activo      bool        `json:"activo"`
	ID          pgtype.UUID `json:"id"`
	UsuarioID   pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) UpdateApiClient(ctx context.Context, arg UpdateApiClientParams) (ApiClient, error) {
	row := q.db.QueryRow(ctx, updateApiClient,
		arg.Nombre, arg.CorsOrigins, arg.Activo, arg.ID, arg.UsuarioID,
	)
	var i ApiClient
	err := row.Scan(
		&i.ID, &i.Nombre, &i.ApiKey, &i.ApiSecretHash, &i.CorsOrigins,
		&i.Activo, &i.LastUsedAt, &i.UsuarioID, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const deleteApiClient = `-- name: DeleteApiClient :exec
DELETE FROM api_clients WHERE id = $1 AND usuario_id = $2
`

type DeleteApiClientParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) DeleteApiClient(ctx context.Context, arg DeleteApiClientParams) error {
	_, err := q.db.Exec(ctx, deleteApiClient, arg.ID, arg.UsuarioID)
	return err
}

const updateApiClientLastUsed = `-- name: UpdateApiClientLastUsed :exec
UPDATE api_clients SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateApiClientLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateApiClientLastUsed, id)
	return err
}

const rotateApiSecret = `-- name: RotateApiSecret :one
UPDATE api_clients SET api_secret_hash = $1, updated_at = NOW()
WHERE id = $2 AND usuario_id = $3 RETURNING id, nombre, api_key, api_secret_hash, cors_origins, activo, last_used_at, usuario_id, created_at, updated_at
`

type RotateApiSecretParams struct {
	ApiSecretHash string      `json:"api_secret_hash"`
	ID            pgtype.UUID `json:"id"`
	UsuarioID     pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) RotateApiSecret(ctx context.Context, arg RotateApiSecretParams) (ApiClient, error) {
	row := q.db.QueryRow(ctx, rotateApiSecret, arg.ApiSecretHash, arg.ID, arg.UsuarioID)
	var i ApiClient
	err := row.Scan(
		&i.ID, &i.Nombre, &i.ApiKey, &i.ApiSecretHash, &i.CorsOrigins,
		&i.Activo, &i.LastUsedAt, &i.UsuarioID, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}
