// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: arqueos_caja.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countArqueosByCaja = `-- name: CountArqueosByCaja :one
SELECT COUNT(*) FROM arqueos_caja
WHERE caja_id = $1 AND usuario_id = $2
`

type CountArqueosByCajaParams struct {
	CajaID    pgtype.UUID `json:"caja_id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) CountArqueosByCaja(ctx context.Context, arg CountArqueosByCajaParams) (int64, error) {
	row := q.db.QueryRow(ctx, countArqueosByCaja, arg.CajaID, arg.UsuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArqueoCaja = `-- name: CreateArqueoCaja :one
INSERT INTO arqueos_caja (caja_id, monto_sistema, monto_fisico, diferencia, estado, observaciones, desglose, usuario_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, caja_id, monto_sistema, monto_fisico, diferencia, estado, observaciones, desglose, usuario_id, created_at, updated_at
`

type CreateArqueoCajaParams struct {
	CajaID        pgtype.UUID    `json:"caja_id"`
	MontoSistema  pgtype.Numeric `json:"monto_sistema"`
	MontoFisico   pgtype.Numeric `json:"monto_fisico"`
	Diferencia    pgtype.Numeric `json:"diferencia"`
	Estado        EstadoArqueo   `json:"estado"`
	Observaciones pgtype.Text    `json:"observaciones"`
	Desglose      []byte         `json:"desglose"`
	UsuarioID     pgtype.UUID    `json:"usuario_id"`
}

func (q *Queries) CreateArqueoCaja(ctx context.Context, arg CreateArqueoCajaParams) (ArqueosCaja, error) {
	row := q.db.QueryRow(ctx, createArqueoCaja,
		arg.CajaID,
		arg.MontoSistema,
		arg.MontoFisico,
		arg.Diferencia,
		arg.Estado,
		arg.Observaciones,
		arg.Desglose,
		arg.UsuarioID,
	)
	var i ArqueosCaja
	err := row.Scan(
		&i.ID,
		&i.CajaID,
		&i.MontoSistema,
		&i.MontoFisico,
		&i.Diferencia,
		&i.Estado,
		&i.Observaciones,
		&i.Desglose,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArqueosByCaja = `-- name: ListArqueosByCaja :many
SELECT id, caja_id, monto_sistema, monto_fisico, diferencia, estado, observaciones, desglose, usuario_id, created_at, updated_at FROM arqueos_caja
WHERE caja_id = $1 AND usuario_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListArqueosByCajaParams struct {
	CajaID    pgtype.UUID `json:"caja_id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListArqueosByCaja(ctx context.Context, arg ListArqueosByCajaParams) ([]ArqueosCaja, error) {
	rows, err := q.db.Query(ctx, listArqueosByCaja,
		arg.CajaID,
		arg.UsuarioID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArqueosCaja
	for rows.Next() {
		var i ArqueosCaja
		if err := rows.Scan(
			&i.ID,
			&i.CajaID,
			&i.MontoSistema,
			&i.MontoFisico,
			&i.Diferencia,
			&i.Estado,
			&i.Observaciones,
			&i.Desglose,
			&i.UsuarioID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArqueoEstado = `-- name: UpdateArqueoEstado :one
UPDATE arqueos_caja
SET estado = $3, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2
RETURNING id, caja_id, monto_sistema, monto_fisico, diferencia, estado, observaciones, desglose, usuario_id, created_at, updated_at
`

type UpdateArqueoEstadoParams struct {
	ID        pgtype.UUID  `json:"id"`
	UsuarioID pgtype.UUID  `json:"usuario_id"`
	Estado    EstadoArqueo `json:"estado"`
}

func (q *Queries) UpdateArqueoEstado(ctx context.Context, arg UpdateArqueoEstadoParams) (ArqueosCaja, error) {
	row := q.db.QueryRow(ctx, updateArqueoEstado, arg.ID, arg.UsuarioID, arg.Estado)
	var i ArqueosCaja
	err := row.Scan(
		&i.ID,
		&i.CajaID,
		&i.MontoSistema,
		&i.MontoFisico,
		&i.Diferencia,
		&i.Estado,
		&i.Observaciones,
		&i.Desglose,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
