// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branches.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBranchesByUser = `-- name: CountBranchesByUser :one
SELECT COUNT(*) FROM sucursales WHERE usuario_id = $1 AND active = TRUE
`

func (q *Queries) CountBranchesByUser(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBranchesByUser, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBranch = `-- name: CreateBranch :one
INSERT INTO sucursales (nombre, direccion, telefono, usuario_id)
VALUES ($1, $2, $3, $4)
RETURNING id, nombre, direccion, telefono, usuario_id, active, created_at, updated_at
`

type CreateBranchParams struct {
	Nombre    string      `json:"nombre"`
	Direccion pgtype.Text `json:"direccion"`
	Telefono  pgtype.Text `json:"telefono"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (Sucursale, error) {
	row := q.db.QueryRow(ctx, createBranch,
		arg.Nombre,
		arg.Direccion,
		arg.Telefono,
		arg.UsuarioID,
	)
	var i Sucursale
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Direccion,
		&i.Telefono,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBranchByID = `-- name: GetBranchByID :one
SELECT id, nombre, direccion, telefono, usuario_id, active, created_at, updated_at FROM sucursales WHERE id = $1
`

func (q *Queries) GetBranchByID(ctx context.Context, id pgtype.UUID) (Sucursale, error) {
	row := q.db.QueryRow(ctx, getBranchByID, id)
	var i Sucursale
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Direccion,
		&i.Telefono,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBranchesByUser = `-- name: ListBranchesByUser :many
SELECT id, nombre, direccion, telefono, usuario_id, active, created_at, updated_at FROM sucursales WHERE usuario_id = $1 AND active = TRUE ORDER BY nombre
`

func (q *Queries) ListBranchesByUser(ctx context.Context, usuarioID pgtype.UUID) ([]Sucursale, error) {
	rows, err := q.db.Query(ctx, listBranchesByUser, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sucursale
	for rows.Next() {
		var i Sucursale
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Direccion,
			&i.Telefono,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteBranch = `-- name: SoftDeleteBranch :exec
UPDATE sucursales SET active = FALSE, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
`

type SoftDeleteBranchParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) SoftDeleteBranch(ctx context.Context, arg SoftDeleteBranchParams) error {
	_, err := q.db.Exec(ctx, softDeleteBranch, arg.ID, arg.UsuarioID)
	return err
}

const updateBranch = `-- name: UpdateBranch :one
UPDATE sucursales
SET nombre = $3, direccion = $4, telefono = $5, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
RETURNING id, nombre, direccion, telefono, usuario_id, active, created_at, updated_at
`

type UpdateBranchParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Nombre    string      `json:"nombre"`
	Direccion pgtype.Text `json:"direccion"`
	Telefono  pgtype.Text `json:"telefono"`
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) (Sucursale, error) {
	row := q.db.QueryRow(ctx, updateBranch,
		arg.ID,
		arg.UsuarioID,
		arg.Nombre,
		arg.Direccion,
		arg.Telefono,
	)
	var i Sucursale
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Direccion,
		&i.Telefono,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
