// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cajas.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCajas = `-- name: CountCajas :one
SELECT COUNT(*) FROM cajas
WHERE usuario_id = $1 AND activa = TRUE
`

func (q *Queries) CountCajas(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCajas, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCajasBySucursal = `-- name: CountCajasBySucursal :one
SELECT COUNT(*) FROM cajas
WHERE usuario_id = $1 AND sucursal_id = $2 AND activa = TRUE
`

type CountCajasBySucursalParams struct {
	UsuarioID  pgtype.UUID `json:"usuario_id"`
	SucursalID pgtype.UUID `json:"sucursal_id"`
}

func (q *Queries) CountCajasBySucursal(ctx context.Context, arg CountCajasBySucursalParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCajasBySucursal, arg.UsuarioID, arg.SucursalID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCaja = `-- name: CreateCaja :one
INSERT INTO cajas (nombre, sucursal_id, tipo, saldo, usuario_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, nombre, sucursal_id, tipo, saldo, activa, usuario_id, created_at, updated_at
`

type CreateCajaParams struct {
	Nombre     string         `json:"nombre"`
	SucursalID pgtype.UUID    `json:"sucursal_id"`
	Tipo       TipoCaja       `json:"tipo"`
	Saldo      pgtype.Numeric `json:"saldo"`
	UsuarioID  pgtype.UUID    `json:"usuario_id"`
}

func (q *Queries) CreateCaja(ctx context.Context, arg CreateCajaParams) (Caja, error) {
	row := q.db.QueryRow(ctx, createCaja,
		arg.Nombre,
		arg.SucursalID,
		arg.Tipo,
		arg.Saldo,
		arg.UsuarioID,
	)
	var i Caja
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.SucursalID,
		&i.Tipo,
		&i.Saldo,
		&i.Activa,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCajaByID = `-- name: GetCajaByID :one
SELECT id, nombre, sucursal_id, tipo, saldo, activa, usuario_id, created_at, updated_at FROM cajas
WHERE id = $1 AND usuario_id = $2 AND activa = TRUE
`

type GetCajaByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) GetCajaByID(ctx context.Context, arg GetCajaByIDParams) (Caja, error) {
	row := q.db.QueryRow(ctx, getCajaByID, arg.ID, arg.UsuarioID)
	var i Caja
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.SucursalID,
		&i.Tipo,
		&i.Saldo,
		&i.Activa,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCajas = `-- name: ListCajas :many
SELECT id, nombre, sucursal_id, tipo, saldo, activa, usuario_id, created_at, updated_at FROM cajas
WHERE usuario_id = $1 AND activa = TRUE
ORDER BY nombre
LIMIT $2 OFFSET $3
`

type ListCajasParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListCajas(ctx context.Context, arg ListCajasParams) ([]Caja, error) {
	rows, err := q.db.Query(ctx, listCajas, arg.UsuarioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Caja
	for rows.Next() {
		var i Caja
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.SucursalID,
			&i.Tipo,
			&i.Saldo,
			&i.Activa,
			&i.UsuarioID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCajasBySucursal = `-- name: ListCajasBySucursal :many
SELECT id, nombre, sucursal_id, tipo, saldo, activa, usuario_id, created_at, updated_at FROM cajas
WHERE usuario_id = $1 AND sucursal_id = $2 AND activa = TRUE
ORDER BY nombre
LIMIT $3 OFFSET $4
`

type ListCajasBySucursalParams struct {
	UsuarioID  pgtype.UUID `json:"usuario_id"`
	SucursalID pgtype.UUID `json:"sucursal_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListCajasBySucursal(ctx context.Context, arg ListCajasBySucursalParams) ([]Caja, error) {
	rows, err := q.db.Query(ctx, listCajasBySucursal,
		arg.UsuarioID,
		arg.SucursalID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Caja
	for rows.Next() {
		var i Caja
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.SucursalID,
			&i.Tipo,
			&i.Saldo,
			&i.Activa,
			&i.UsuarioID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCaja = `-- name: SoftDeleteCaja :exec
UPDATE cajas
SET activa = FALSE, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2
`

type SoftDeleteCajaParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) SoftDeleteCaja(ctx context.Context, arg SoftDeleteCajaParams) error {
	_, err := q.db.Exec(ctx, softDeleteCaja, arg.ID, arg.UsuarioID)
	return err
}

const updateCaja = `-- name: UpdateCaja :one
UPDATE cajas
SET nombre = $3, sucursal_id = $4, tipo = $5, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND activa = TRUE
RETURNING id, nombre, sucursal_id, tipo, saldo, activa, usuario_id, created_at, updated_at
`

type UpdateCajaParams struct {
	ID         pgtype.UUID `json:"id"`
	UsuarioID  pgtype.UUID `json:"usuario_id"`
	Nombre     string      `json:"nombre"`
	SucursalID pgtype.UUID `json:"sucursal_id"`
	Tipo       TipoCaja    `json:"tipo"`
}

func (q *Queries) UpdateCaja(ctx context.Context, arg UpdateCajaParams) (Caja, error) {
	row := q.db.QueryRow(ctx, updateCaja,
		arg.ID,
		arg.UsuarioID,
		arg.Nombre,
		arg.SucursalID,
		arg.Tipo,
	)
	var i Caja
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.SucursalID,
		&i.Tipo,
		&i.Saldo,
		&i.Activa,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCajaSaldo = `-- name: UpdateCajaSaldo :exec
UPDATE cajas
SET saldo = $3, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND activa = TRUE
`

type UpdateCajaSaldoParams struct {
	ID        pgtype.UUID    `json:"id"`
	UsuarioID pgtype.UUID    `json:"usuario_id"`
	Saldo     pgtype.Numeric `json:"saldo"`
}

func (q *Queries) UpdateCajaSaldo(ctx context.Context, arg UpdateCajaSaldoParams) error {
	_, err := q.db.Exec(ctx, updateCajaSaldo, arg.ID, arg.UsuarioID, arg.Saldo)
	return err
}
