// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalogo_productos.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCatalogoBySucursal = `-- name: CountCatalogoBySucursal :one
SELECT COUNT(*)
FROM catalogo_productos cp
JOIN productos p ON p.id = cp.producto_id
WHERE cp.sucursal_id = $1 AND cp.active = TRUE AND p.active = TRUE
`

func (q *Queries) CountCatalogoBySucursal(ctx context.Context, sucursalID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCatalogoBySucursal, sucursalID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCatalogoProducto = `-- name: GetCatalogoProducto :one
SELECT id, producto_id, sucursal_id, precio, stock, active, created_at, updated_at FROM catalogo_productos
WHERE producto_id = $1 AND sucursal_id = $2 AND active = TRUE
`

type GetCatalogoProductoParams struct {
	ProductoID pgtype.UUID `json:"producto_id"`
	SucursalID pgtype.UUID `json:"sucursal_id"`
}

func (q *Queries) GetCatalogoProducto(ctx context.Context, arg GetCatalogoProductoParams) (CatalogoProducto, error) {
	row := q.db.QueryRow(ctx, getCatalogoProducto, arg.ProductoID, arg.SucursalID)
	var i CatalogoProducto
	err := row.Scan(
		&i.ID,
		&i.ProductoID,
		&i.SucursalID,
		&i.Precio,
		&i.Stock,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCatalogoBySucursal = `-- name: ListCatalogoBySucursal :many
SELECT cp.id, cp.producto_id, cp.sucursal_id, cp.precio, cp.stock, cp.active, cp.created_at, cp.updated_at,
       p.nombre AS producto_nombre,
       p.codigo AS producto_codigo,
       p.unidad AS producto_unidad,
       p.precio_base AS producto_precio_base
FROM catalogo_productos cp
JOIN productos p ON p.id = cp.producto_id
WHERE cp.sucursal_id = $1 AND cp.active = TRUE AND p.active = TRUE
ORDER BY p.nombre
LIMIT $2 OFFSET $3
`

type ListCatalogoBySucursalParams struct {
	SucursalID pgtype.UUID `json:"sucursal_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

type ListCatalogoBySucursalRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ProductoID         pgtype.UUID        `json:"producto_id"`
	SucursalID         pgtype.UUID        `json:"sucursal_id"`
	Precio             pgtype.Numeric     `json:"precio"`
	Stock              int32              `json:"stock"`
	Active             bool               `json:"active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ProductoNombre     string             `json:"producto_nombre"`
	ProductoCodigo     pgtype.Text        `json:"producto_codigo"`
	ProductoUnidad     UnidadDeMedida     `json:"producto_unidad"`
	ProductoPrecioBase pgtype.Numeric     `json:"producto_precio_base"`
}

func (q *Queries) ListCatalogoBySucursal(ctx context.Context, arg ListCatalogoBySucursalParams) ([]ListCatalogoBySucursalRow, error) {
	rows, err := q.db.Query(ctx, listCatalogoBySucursal, arg.SucursalID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCatalogoBySucursalRow
	for rows.Next() {
		var i ListCatalogoBySucursalRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductoID,
			&i.SucursalID,
			&i.Precio,
			&i.Stock,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductoNombre,
			&i.ProductoCodigo,
			&i.ProductoUnidad,
			&i.ProductoPrecioBase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLowStockBySucursal = `-- name: ListLowStockBySucursal :many
SELECT cp.id, cp.producto_id, cp.sucursal_id, cp.precio, cp.stock, cp.active, cp.created_at, cp.updated_at,
       p.nombre AS producto_nombre,
       p.codigo AS producto_codigo,
       p.unidad AS producto_unidad,
       p.precio_base AS producto_precio_base
FROM catalogo_productos cp
JOIN productos p ON p.id = cp.producto_id
WHERE cp.sucursal_id = $1 AND cp.active = TRUE AND p.active = TRUE
  AND cp.stock <= $2
ORDER BY cp.stock ASC
LIMIT $3 OFFSET $4
`

type ListLowStockBySucursalParams struct {
	SucursalID pgtype.UUID `json:"sucursal_id"`
	Stock      int32       `json:"stock"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

type ListLowStockBySucursalRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ProductoID         pgtype.UUID        `json:"producto_id"`
	SucursalID         pgtype.UUID        `json:"sucursal_id"`
	Precio             pgtype.Numeric     `json:"precio"`
	Stock              int32              `json:"stock"`
	Active             bool               `json:"active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ProductoNombre     string             `json:"producto_nombre"`
	ProductoCodigo     pgtype.Text        `json:"producto_codigo"`
	ProductoUnidad     UnidadDeMedida     `json:"producto_unidad"`
	ProductoPrecioBase pgtype.Numeric     `json:"producto_precio_base"`
}

func (q *Queries) ListLowStockBySucursal(ctx context.Context, arg ListLowStockBySucursalParams) ([]ListLowStockBySucursalRow, error) {
	rows, err := q.db.Query(ctx, listLowStockBySucursal,
		arg.SucursalID,
		arg.Stock,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLowStockBySucursalRow
	for rows.Next() {
		var i ListLowStockBySucursalRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductoID,
			&i.SucursalID,
			&i.Precio,
			&i.Stock,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductoNombre,
			&i.ProductoCodigo,
			&i.ProductoUnidad,
			&i.ProductoPrecioBase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCatalogoProducto = `-- name: SoftDeleteCatalogoProducto :exec
UPDATE catalogo_productos
SET active = FALSE, updated_at = NOW()
WHERE producto_id = $1 AND sucursal_id = $2
`

type SoftDeleteCatalogoProductoParams struct {
	ProductoID pgtype.UUID `json:"producto_id"`
	SucursalID pgtype.UUID `json:"sucursal_id"`
}

func (q *Queries) SoftDeleteCatalogoProducto(ctx context.Context, arg SoftDeleteCatalogoProductoParams) error {
	_, err := q.db.Exec(ctx, softDeleteCatalogoProducto, arg.ProductoID, arg.SucursalID)
	return err
}

const updateCatalogoStock = `-- name: UpdateCatalogoStock :one
UPDATE catalogo_productos
SET stock = $3, updated_at = NOW()
WHERE producto_id = $1 AND sucursal_id = $2 AND active = TRUE
RETURNING id, producto_id, sucursal_id, precio, stock, active, created_at, updated_at
`

type UpdateCatalogoStockParams struct {
	ProductoID pgtype.UUID `json:"producto_id"`
	SucursalID pgtype.UUID `json:"sucursal_id"`
	Stock      int32       `json:"stock"`
}

func (q *Queries) UpdateCatalogoStock(ctx context.Context, arg UpdateCatalogoStockParams) (CatalogoProducto, error) {
	row := q.db.QueryRow(ctx, updateCatalogoStock, arg.ProductoID, arg.SucursalID, arg.Stock)
	var i CatalogoProducto
	err := row.Scan(
		&i.ID,
		&i.ProductoID,
		&i.SucursalID,
		&i.Precio,
		&i.Stock,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCatalogoProducto = `-- name: UpsertCatalogoProducto :one
INSERT INTO catalogo_productos (producto_id, sucursal_id, precio, stock)
VALUES ($1, $2, $3, $4)
ON CONFLICT (producto_id, sucursal_id)
DO UPDATE SET precio = EXCLUDED.precio, stock = EXCLUDED.stock, active = TRUE, updated_at = NOW()
RETURNING id, producto_id, sucursal_id, precio, stock, active, created_at, updated_at
`

type UpsertCatalogoProductoParams struct {
	ProductoID pgtype.UUID    `json:"producto_id"`
	SucursalID pgtype.UUID    `json:"sucursal_id"`
	Precio     pgtype.Numeric `json:"precio"`
	Stock      int32          `json:"stock"`
}

func (q *Queries) UpsertCatalogoProducto(ctx context.Context, arg UpsertCatalogoProductoParams) (CatalogoProducto, error) {
	row := q.db.QueryRow(ctx, upsertCatalogoProducto,
		arg.ProductoID,
		arg.SucursalID,
		arg.Precio,
		arg.Stock,
	)
	var i CatalogoProducto
	err := row.Scan(
		&i.ID,
		&i.ProductoID,
		&i.SucursalID,
		&i.Precio,
		&i.Stock,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
