// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categorias_producto.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCategoriasProducto = `-- name: CountCategoriasProducto :one
SELECT COUNT(*) FROM categorias_producto
WHERE usuario_id = $1 AND active = TRUE
`

func (q *Queries) CountCategoriasProducto(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCategoriasProducto, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategoriaProducto = `-- name: CreateCategoriaProducto :one
INSERT INTO categorias_producto (nombre, descripcion, familia_id, usuario_id)
VALUES ($1, $2, $3, $4)
RETURNING id, nombre, descripcion, familia_id, usuario_id, active, created_at, updated_at
`

type CreateCategoriaProductoParams struct {
	Nombre      string      `json:"nombre"`
	Descripcion pgtype.Text `json:"descripcion"`
	FamiliaID   pgtype.UUID `json:"familia_id"`
	UsuarioID   pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) CreateCategoriaProducto(ctx context.Context, arg CreateCategoriaProductoParams) (CategoriasProducto, error) {
	row := q.db.QueryRow(ctx, createCategoriaProducto,
		arg.Nombre,
		arg.Descripcion,
		arg.FamiliaID,
		arg.UsuarioID,
	)
	var i CategoriasProducto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.FamiliaID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoriaProductoByID = `-- name: GetCategoriaProductoByID :one
SELECT id, nombre, descripcion, familia_id, usuario_id, active, created_at, updated_at FROM categorias_producto
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
`

type GetCategoriaProductoByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) GetCategoriaProductoByID(ctx context.Context, arg GetCategoriaProductoByIDParams) (CategoriasProducto, error) {
	row := q.db.QueryRow(ctx, getCategoriaProductoByID, arg.ID, arg.UsuarioID)
	var i CategoriasProducto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.FamiliaID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoriasProducto = `-- name: ListCategoriasProducto :many
SELECT id, nombre, descripcion, familia_id, usuario_id, active, created_at, updated_at FROM categorias_producto
WHERE usuario_id = $1 AND active = TRUE
ORDER BY nombre
LIMIT $2 OFFSET $3
`

type ListCategoriasProductoParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListCategoriasProducto(ctx context.Context, arg ListCategoriasProductoParams) ([]CategoriasProducto, error) {
	rows, err := q.db.Query(ctx, listCategoriasProducto, arg.UsuarioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoriasProducto
	for rows.Next() {
		var i CategoriasProducto
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Descripcion,
			&i.FamiliaID,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriasProductoByFamilia = `-- name: ListCategoriasProductoByFamilia :many
SELECT id, nombre, descripcion, familia_id, usuario_id, active, created_at, updated_at FROM categorias_producto
WHERE familia_id = $1 AND usuario_id = $2 AND active = TRUE
ORDER BY nombre
`

type ListCategoriasProductoByFamiliaParams struct {
	FamiliaID pgtype.UUID `json:"familia_id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) ListCategoriasProductoByFamilia(ctx context.Context, arg ListCategoriasProductoByFamiliaParams) ([]CategoriasProducto, error) {
	rows, err := q.db.Query(ctx, listCategoriasProductoByFamilia, arg.FamiliaID, arg.UsuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoriasProducto
	for rows.Next() {
		var i CategoriasProducto
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Descripcion,
			&i.FamiliaID,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCategoriaProducto = `-- name: SoftDeleteCategoriaProducto :exec
UPDATE categorias_producto
SET active = FALSE, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2
`

type SoftDeleteCategoriaProductoParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) SoftDeleteCategoriaProducto(ctx context.Context, arg SoftDeleteCategoriaProductoParams) error {
	_, err := q.db.Exec(ctx, softDeleteCategoriaProducto, arg.ID, arg.UsuarioID)
	return err
}

const updateCategoriaProducto = `-- name: UpdateCategoriaProducto :one
UPDATE categorias_producto
SET nombre = $3, descripcion = $4, familia_id = $5, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
RETURNING id, nombre, descripcion, familia_id, usuario_id, active, created_at, updated_at
`

type UpdateCategoriaProductoParams struct {
	ID          pgtype.UUID `json:"id"`
	UsuarioID   pgtype.UUID `json:"usuario_id"`
	Nombre      string      `json:"nombre"`
	Descripcion pgtype.Text `json:"descripcion"`
	FamiliaID   pgtype.UUID `json:"familia_id"`
}

func (q *Queries) UpdateCategoriaProducto(ctx context.Context, arg UpdateCategoriaProductoParams) (CategoriasProducto, error) {
	row := q.db.QueryRow(ctx, updateCategoriaProducto,
		arg.ID,
		arg.UsuarioID,
		arg.Nombre,
		arg.Descripcion,
		arg.FamiliaID,
	)
	var i CategoriasProducto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.FamiliaID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
