// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: promociones.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCategoriasCliente = `-- name: CountCategoriasCliente :one
SELECT COUNT(*) FROM categorias_cliente
WHERE usuario_id = $1 AND active = TRUE
`

func (q *Queries) CountCategoriasCliente(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCategoriasCliente, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategoriaCliente = `-- name: CreateCategoriaCliente :one
INSERT INTO categorias_cliente (nombre, descripcion, descuento_porcentaje, usuario_id)
VALUES ($1, $2, $3, $4)
RETURNING id, nombre, descripcion, descuento_porcentaje, usuario_id, active, created_at
`

type CreateCategoriaClienteParams struct {
	Nombre              string         `json:"nombre"`
	Descripcion         pgtype.Text    `json:"descripcion"`
	DescuentoPorcentaje pgtype.Numeric `json:"descuento_porcentaje"`
	UsuarioID           pgtype.UUID    `json:"usuario_id"`
}

func (q *Queries) CreateCategoriaCliente(ctx context.Context, arg CreateCategoriaClienteParams) (CategoriaCliente, error) {
	row := q.db.QueryRow(ctx, createCategoriaCliente,
		arg.Nombre,
		arg.Descripcion,
		arg.DescuentoPorcentaje,
		arg.UsuarioID,
	)
	var i CategoriaCliente
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.DescuentoPorcentaje,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoriaClienteByID = `-- name: GetCategoriaClienteByID :one
SELECT * FROM categorias_cliente
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
`

type GetCategoriaClienteByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) GetCategoriaClienteByID(ctx context.Context, arg GetCategoriaClienteByIDParams) (CategoriaCliente, error) {
	row := q.db.QueryRow(ctx, getCategoriaClienteByID, arg.ID, arg.UsuarioID)
	var i CategoriaCliente
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.DescuentoPorcentaje,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listCategoriasCliente = `-- name: ListCategoriasCliente :many
SELECT * FROM categorias_cliente
WHERE usuario_id = $1 AND active = TRUE
ORDER BY nombre
LIMIT $2 OFFSET $3
`

type ListCategoriasClienteParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListCategoriasCliente(ctx context.Context, arg ListCategoriasClienteParams) ([]CategoriaCliente, error) {
	rows, err := q.db.Query(ctx, listCategoriasCliente, arg.UsuarioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoriaCliente
	for rows.Next() {
		var i CategoriaCliente
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Descripcion,
			&i.DescuentoPorcentaje,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategoriaCliente = `-- name: UpdateCategoriaCliente :one
UPDATE categorias_cliente
SET nombre = $3, descripcion = $4, descuento_porcentaje = $5
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
RETURNING id, nombre, descripcion, descuento_porcentaje, usuario_id, active, created_at
`

type UpdateCategoriaClienteParams struct {
	ID                  pgtype.UUID    `json:"id"`
	UsuarioID           pgtype.UUID    `json:"usuario_id"`
	Nombre              string         `json:"nombre"`
	Descripcion         pgtype.Text    `json:"descripcion"`
	DescuentoPorcentaje pgtype.Numeric `json:"descuento_porcentaje"`
}

func (q *Queries) UpdateCategoriaCliente(ctx context.Context, arg UpdateCategoriaClienteParams) (CategoriaCliente, error) {
	row := q.db.QueryRow(ctx, updateCategoriaCliente,
		arg.ID,
		arg.UsuarioID,
		arg.Nombre,
		arg.Descripcion,
		arg.DescuentoPorcentaje,
	)
	var i CategoriaCliente
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.DescuentoPorcentaje,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const softDeleteCategoriaCliente = `-- name: SoftDeleteCategoriaCliente :exec
UPDATE categorias_cliente
SET active = FALSE
WHERE id = $1 AND usuario_id = $2
`

type SoftDeleteCategoriaClienteParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) SoftDeleteCategoriaCliente(ctx context.Context, arg SoftDeleteCategoriaClienteParams) error {
	_, err := q.db.Exec(ctx, softDeleteCategoriaCliente, arg.ID, arg.UsuarioID)
	return err
}
