// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cheques.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCheques = `-- name: CountCheques :one
SELECT COUNT(*) FROM cheques
WHERE usuario_id = $1
`

func (q *Queries) CountCheques(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCheques, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChequesByEstado = `-- name: CountChequesByEstado :one
SELECT COUNT(*) FROM cheques
WHERE usuario_id = $1 AND estado = $2
`

type CountChequesByEstadoParams struct {
	UsuarioID pgtype.UUID  `json:"usuario_id"`
	Estado    EstadoCheque `json:"estado"`
}

func (q *Queries) CountChequesByEstado(ctx context.Context, arg CountChequesByEstadoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countChequesByEstado, arg.UsuarioID, arg.Estado)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchCheques = `-- name: CountSearchCheques :one
SELECT COUNT(*) FROM cheques
WHERE usuario_id = $1
  AND (numero ILIKE $2 OR banco ILIKE $2 OR emisor ILIKE $2 OR receptor ILIKE $2)
`

type CountSearchChequesParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Numero    string      `json:"numero"`
}

func (q *Queries) CountSearchCheques(ctx context.Context, arg CountSearchChequesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchCheques, arg.UsuarioID, arg.Numero)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCheque = `-- name: CreateCheque :one
INSERT INTO cheques (numero, monto, fecha_emision, fecha_vencimiento, estado, banco, emisor, receptor, entidad_bancaria_id, sucursal_id, usuario_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, numero, monto, fecha_emision, fecha_vencimiento, estado, banco, emisor, receptor, entidad_bancaria_id, sucursal_id, usuario_id, created_at, updated_at
`

type CreateChequeParams struct {
	Numero            string         `json:"numero"`
	Monto             pgtype.Numeric `json:"monto"`
	FechaEmision      pgtype.Date    `json:"fecha_emision"`
	FechaVencimiento  pgtype.Date    `json:"fecha_vencimiento"`
	Estado            EstadoCheque   `json:"estado"`
	Banco             pgtype.Text    `json:"banco"`
	Emisor            pgtype.Text    `json:"emisor"`
	Receptor          pgtype.Text    `json:"receptor"`
	EntidadBancariaID pgtype.UUID    `json:"entidad_bancaria_id"`
	SucursalID        pgtype.UUID    `json:"sucursal_id"`
	UsuarioID         pgtype.UUID    `json:"usuario_id"`
}

func (q *Queries) CreateCheque(ctx context.Context, arg CreateChequeParams) (Cheque, error) {
	row := q.db.QueryRow(ctx, createCheque,
		arg.Numero,
		arg.Monto,
		arg.FechaEmision,
		arg.FechaVencimiento,
		arg.Estado,
		arg.Banco,
		arg.Emisor,
		arg.Receptor,
		arg.EntidadBancariaID,
		arg.SucursalID,
		arg.UsuarioID,
	)
	var i Cheque
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.Monto,
		&i.FechaEmision,
		&i.FechaVencimiento,
		&i.Estado,
		&i.Banco,
		&i.Emisor,
		&i.Receptor,
		&i.EntidadBancariaID,
		&i.SucursalID,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChequeByID = `-- name: GetChequeByID :one
SELECT id, numero, monto, fecha_emision, fecha_vencimiento, estado, banco, emisor, receptor, entidad_bancaria_id, sucursal_id, usuario_id, created_at, updated_at FROM cheques
WHERE id = $1 AND usuario_id = $2
`

type GetChequeByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) GetChequeByID(ctx context.Context, arg GetChequeByIDParams) (Cheque, error) {
	row := q.db.QueryRow(ctx, getChequeByID, arg.ID, arg.UsuarioID)
	var i Cheque
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.Monto,
		&i.FechaEmision,
		&i.FechaVencimiento,
		&i.Estado,
		&i.Banco,
		&i.Emisor,
		&i.Receptor,
		&i.EntidadBancariaID,
		&i.SucursalID,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCheques = `-- name: ListCheques :many
SELECT id, numero, monto, fecha_emision, fecha_vencimiento, estado, banco, emisor, receptor, entidad_bancaria_id, sucursal_id, usuario_id, created_at, updated_at FROM cheques
WHERE usuario_id = $1
ORDER BY fecha_vencimiento DESC
LIMIT $2 OFFSET $3
`

type ListChequesParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListCheques(ctx context.Context, arg ListChequesParams) ([]Cheque, error) {
	rows, err := q.db.Query(ctx, listCheques, arg.UsuarioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cheque
	for rows.Next() {
		var i Cheque
		if err := rows.Scan(
			&i.ID,
			&i.Numero,
			&i.Monto,
			&i.FechaEmision,
			&i.FechaVencimiento,
			&i.Estado,
			&i.Banco,
			&i.Emisor,
			&i.Receptor,
			&i.EntidadBancariaID,
			&i.SucursalID,
			&i.UsuarioID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChequesByEstado = `-- name: ListChequesByEstado :many
SELECT id, numero, monto, fecha_emision, fecha_vencimiento, estado, banco, emisor, receptor, entidad_bancaria_id, sucursal_id, usuario_id, created_at, updated_at FROM cheques
WHERE usuario_id = $1 AND estado = $2
ORDER BY fecha_vencimiento DESC
LIMIT $3 OFFSET $4
`

type ListChequesByEstadoParams struct {
	UsuarioID pgtype.UUID  `json:"usuario_id"`
	Estado    EstadoCheque `json:"estado"`
	Limit     int32        `json:"limit"`
	Offset    int32        `json:"offset"`
}

func (q *Queries) ListChequesByEstado(ctx context.Context, arg ListChequesByEstadoParams) ([]Cheque, error) {
	rows, err := q.db.Query(ctx, listChequesByEstado,
		arg.UsuarioID,
		arg.Estado,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cheque
	for rows.Next() {
		var i Cheque
		if err := rows.Scan(
			&i.ID,
			&i.Numero,
			&i.Monto,
			&i.FechaEmision,
			&i.FechaVencimiento,
			&i.Estado,
			&i.Banco,
			&i.Emisor,
			&i.Receptor,
			&i.EntidadBancariaID,
			&i.SucursalID,
			&i.UsuarioID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCheques = `-- name: SearchCheques :many
SELECT id, numero, monto, fecha_emision, fecha_vencimiento, estado, banco, emisor, receptor, entidad_bancaria_id, sucursal_id, usuario_id, created_at, updated_at FROM cheques
WHERE usuario_id = $1
  AND (numero ILIKE $2 OR banco ILIKE $2 OR emisor ILIKE $2 OR receptor ILIKE $2)
ORDER BY fecha_vencimiento DESC
LIMIT $3 OFFSET $4
`

type SearchChequesParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Numero    string      `json:"numero"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) SearchCheques(ctx context.Context, arg SearchChequesParams) ([]Cheque, error) {
	rows, err := q.db.Query(ctx, searchCheques,
		arg.UsuarioID,
		arg.Numero,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cheque
	for rows.Next() {
		var i Cheque
		if err := rows.Scan(
			&i.ID,
			&i.Numero,
			&i.Monto,
			&i.FechaEmision,
			&i.FechaVencimiento,
			&i.Estado,
			&i.Banco,
			&i.Emisor,
			&i.Receptor,
			&i.EntidadBancariaID,
			&i.SucursalID,
			&i.UsuarioID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCheque = `-- name: UpdateCheque :one
UPDATE cheques
SET numero = $3, monto = $4, fecha_emision = $5, fecha_vencimiento = $6,
    banco = $7, emisor = $8, receptor = $9, entidad_bancaria_id = $10,
    updated_at = NOW()
WHERE id = $1 AND usuario_id = $2
RETURNING id, numero, monto, fecha_emision, fecha_vencimiento, estado, banco, emisor, receptor, entidad_bancaria_id, sucursal_id, usuario_id, created_at, updated_at
`

type UpdateChequeParams struct {
	ID                pgtype.UUID    `json:"id"`
	UsuarioID         pgtype.UUID    `json:"usuario_id"`
	Numero            string         `json:"numero"`
	Monto             pgtype.Numeric `json:"monto"`
	FechaEmision      pgtype.Date    `json:"fecha_emision"`
	FechaVencimiento  pgtype.Date    `json:"fecha_vencimiento"`
	Banco             pgtype.Text    `json:"banco"`
	Emisor            pgtype.Text    `json:"emisor"`
	Receptor          pgtype.Text    `json:"receptor"`
	EntidadBancariaID pgtype.UUID    `json:"entidad_bancaria_id"`
}

func (q *Queries) UpdateCheque(ctx context.Context, arg UpdateChequeParams) (Cheque, error) {
	row := q.db.QueryRow(ctx, updateCheque,
		arg.ID,
		arg.UsuarioID,
		arg.Numero,
		arg.Monto,
		arg.FechaEmision,
		arg.FechaVencimiento,
		arg.Banco,
		arg.Emisor,
		arg.Receptor,
		arg.EntidadBancariaID,
	)
	var i Cheque
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.Monto,
		&i.FechaEmision,
		&i.FechaVencimiento,
		&i.Estado,
		&i.Banco,
		&i.Emisor,
		&i.Receptor,
		&i.EntidadBancariaID,
		&i.SucursalID,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChequeEstado = `-- name: UpdateChequeEstado :one
UPDATE cheques
SET estado = $3, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2
RETURNING id, numero, monto, fecha_emision, fecha_vencimiento, estado, banco, emisor, receptor, entidad_bancaria_id, sucursal_id, usuario_id, created_at, updated_at
`

type UpdateChequeEstadoParams struct {
	ID        pgtype.UUID  `json:"id"`
	UsuarioID pgtype.UUID  `json:"usuario_id"`
	Estado    EstadoCheque `json:"estado"`
}

func (q *Queries) UpdateChequeEstado(ctx context.Context, arg UpdateChequeEstadoParams) (Cheque, error) {
	row := q.db.QueryRow(ctx, updateChequeEstado, arg.ID, arg.UsuarioID, arg.Estado)
	var i Cheque
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.Monto,
		&i.FechaEmision,
		&i.FechaVencimiento,
		&i.Estado,
		&i.Banco,
		&i.Emisor,
		&i.Receptor,
		&i.EntidadBancariaID,
		&i.SucursalID,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
