// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comprobantes.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countComprobantes = `-- name: CountComprobantes :one
SELECT COUNT(*) FROM comprobantes
WHERE usuario_id = $1 AND active = TRUE
`

func (q *Queries) CountComprobantes(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countComprobantes, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countComprobantesByCliente = `-- name: CountComprobantesByCliente :one
SELECT COUNT(*) FROM comprobantes
WHERE usuario_id = $1 AND cliente_id = $2 AND active = TRUE
`

type CountComprobantesByClienteParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	ClienteID pgtype.UUID `json:"cliente_id"`
}

func (q *Queries) CountComprobantesByCliente(ctx context.Context, arg CountComprobantesByClienteParams) (int64, error) {
	row := q.db.QueryRow(ctx, countComprobantesByCliente, arg.UsuarioID, arg.ClienteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countComprobantesByEstado = `-- name: CountComprobantesByEstado :one
SELECT COUNT(*) FROM comprobantes
WHERE usuario_id = $1 AND estado = $2 AND active = TRUE
`

type CountComprobantesByEstadoParams struct {
	UsuarioID pgtype.UUID       `json:"usuario_id"`
	Estado    EstadoComprobante `json:"estado"`
}

func (q *Queries) CountComprobantesByEstado(ctx context.Context, arg CountComprobantesByEstadoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countComprobantesByEstado, arg.UsuarioID, arg.Estado)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchComprobantes = `-- name: CountSearchComprobantes :one
SELECT COUNT(*)
FROM comprobantes c
JOIN clientes cl ON cl.id = c.cliente_id
WHERE c.usuario_id = $1 AND c.active = TRUE
  AND (c.numero ILIKE $2 OR cl.nombre ILIKE $2 OR cl.apellido ILIKE $2 OR cl.razon_social ILIKE $2)
`

type CountSearchComprobantesParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Numero    string      `json:"numero"`
}

func (q *Queries) CountSearchComprobantes(ctx context.Context, arg CountSearchComprobantesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchComprobantes, arg.UsuarioID, arg.Numero)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComprobante = `-- name: CreateComprobante :one
INSERT INTO comprobantes (
  tipo, letra, numero, estado,
  pedido_id, cliente_id, sucursal_id,
  subtotal, descuento_monto, base_imponible,
  total_impuestos, total, impuestos,
  fecha_emision, condicion_pago, observaciones,
  usuario_id
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8, $9, $10,
  $11, $12, $13,
  $14, $15, $16,
  $17
) RETURNING id, tipo, letra, numero, estado, pedido_id, cliente_id, sucursal_id, subtotal, descuento_monto, base_imponible, total_impuestos, total, impuestos, cae, fecha_vencimiento_cae, fecha_emision, condicion_pago, observaciones, usuario_id, active, created_at, updated_at
`

type CreateComprobanteParams struct {
	Tipo           TipoComprobante   `json:"tipo"`
	Letra          LetraComprobante  `json:"letra"`
	Numero         string            `json:"numero"`
	Estado         EstadoComprobante `json:"estado"`
	PedidoID       pgtype.UUID       `json:"pedido_id"`
	ClienteID      pgtype.UUID       `json:"cliente_id"`
	SucursalID     pgtype.UUID       `json:"sucursal_id"`
	Subtotal       pgtype.Numeric    `json:"subtotal"`
	DescuentoMonto pgtype.Numeric    `json:"descuento_monto"`
	BaseImponible  pgtype.Numeric    `json:"base_imponible"`
	TotalImpuestos pgtype.Numeric    `json:"total_impuestos"`
	Total          pgtype.Numeric    `json:"total"`
	Impuestos      []byte            `json:"impuestos"`
	FechaEmision   pgtype.Date       `json:"fecha_emision"`
	CondicionPago  CondicionPago     `json:"condicion_pago"`
	Observaciones  pgtype.Text       `json:"observaciones"`
	UsuarioID      pgtype.UUID       `json:"usuario_id"`
}

func (q *Queries) CreateComprobante(ctx context.Context, arg CreateComprobanteParams) (Comprobante, error) {
	row := q.db.QueryRow(ctx, createComprobante,
		arg.Tipo,
		arg.Letra,
		arg.Numero,
		arg.Estado,
		arg.PedidoID,
		arg.ClienteID,
		arg.SucursalID,
		arg.Subtotal,
		arg.DescuentoMonto,
		arg.BaseImponible,
		arg.TotalImpuestos,
		arg.Total,
		arg.Impuestos,
		arg.FechaEmision,
		arg.CondicionPago,
		arg.Observaciones,
		arg.UsuarioID,
	)
	var i Comprobante
	err := row.Scan(
		&i.ID,
		&i.Tipo,
		&i.Letra,
		&i.Numero,
		&i.Estado,
		&i.PedidoID,
		&i.ClienteID,
		&i.SucursalID,
		&i.Subtotal,
		&i.DescuentoMonto,
		&i.BaseImponible,
		&i.TotalImpuestos,
		&i.Total,
		&i.Impuestos,
		&i.Cae,
		&i.FechaVencimientoCae,
		&i.FechaEmision,
		&i.CondicionPago,
		&i.Observaciones,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDetalleComprobante = `-- name: CreateDetalleComprobante :one
INSERT INTO detalle_comprobantes (
  comprobante_id, producto_id, producto_nombre,
  producto_codigo, producto_unidad, cantidad,
  precio_unitario, descuento_porcentaje, descuento_monto,
  subtotal, orden
) VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7, $8, $9,
  $10, $11
) RETURNING id, comprobante_id, producto_id, producto_nombre, producto_codigo, producto_unidad, cantidad, precio_unitario, descuento_porcentaje, descuento_monto, subtotal, orden
`

type CreateDetalleComprobanteParams struct {
	ComprobanteID       pgtype.UUID    `json:"comprobante_id"`
	ProductoID          pgtype.UUID    `json:"producto_id"`
	ProductoNombre      string         `json:"producto_nombre"`
	ProductoCodigo      pgtype.Text    `json:"producto_codigo"`
	ProductoUnidad      string         `json:"producto_unidad"`
	Cantidad            pgtype.Numeric `json:"cantidad"`
	PrecioUnitario      pgtype.Numeric `json:"precio_unitario"`
	DescuentoPorcentaje pgtype.Numeric `json:"descuento_porcentaje"`
	DescuentoMonto      pgtype.Numeric `json:"descuento_monto"`
	Subtotal            pgtype.Numeric `json:"subtotal"`
	Orden               int32          `json:"orden"`
}

func (q *Queries) CreateDetalleComprobante(ctx context.Context, arg CreateDetalleComprobanteParams) (DetalleComprobante, error) {
	row := q.db.QueryRow(ctx, createDetalleComprobante,
		arg.ComprobanteID,
		arg.ProductoID,
		arg.ProductoNombre,
		arg.ProductoCodigo,
		arg.ProductoUnidad,
		arg.Cantidad,
		arg.PrecioUnitario,
		arg.DescuentoPorcentaje,
		arg.DescuentoMonto,
		arg.Subtotal,
		arg.Orden,
	)
	var i DetalleComprobante
	err := row.Scan(
		&i.ID,
		&i.ComprobanteID,
		&i.ProductoID,
		&i.ProductoNombre,
		&i.ProductoCodigo,
		&i.ProductoUnidad,
		&i.Cantidad,
		&i.PrecioUnitario,
		&i.DescuentoPorcentaje,
		&i.DescuentoMonto,
		&i.Subtotal,
		&i.Orden,
	)
	return i, err
}

const getComprobanteByID = `-- name: GetComprobanteByID :one
SELECT c.id, c.tipo, c.letra, c.numero, c.estado, c.pedido_id, c.cliente_id, c.sucursal_id, c.subtotal, c.descuento_monto, c.base_imponible, c.total_impuestos, c.total, c.impuestos, c.cae, c.fecha_vencimiento_cae, c.fecha_emision, c.condicion_pago, c.observaciones, c.usuario_id, c.active, c.created_at, c.updated_at,
       cl.nombre AS cliente_nombre,
       cl.apellido AS cliente_apellido,
       s.nombre AS sucursal_nombre
FROM comprobantes c
JOIN clientes cl ON cl.id = c.cliente_id
JOIN sucursales s ON s.id = c.sucursal_id
WHERE c.id = $1 AND c.usuario_id = $2 AND c.active = TRUE
`

type GetComprobanteByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

type GetComprobanteByIDRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Tipo                TipoComprobante    `json:"tipo"`
	Letra               LetraComprobante   `json:"letra"`
	Numero              string             `json:"numero"`
	Estado              EstadoComprobante  `json:"estado"`
	PedidoID            pgtype.UUID        `json:"pedido_id"`
	ClienteID           pgtype.UUID        `json:"cliente_id"`
	SucursalID          pgtype.UUID        `json:"sucursal_id"`
	Subtotal            pgtype.Numeric     `json:"subtotal"`
	DescuentoMonto      pgtype.Numeric     `json:"descuento_monto"`
	BaseImponible       pgtype.Numeric     `json:"base_imponible"`
	TotalImpuestos      pgtype.Numeric     `json:"total_impuestos"`
	Total               pgtype.Numeric     `json:"total"`
	Impuestos           []byte             `json:"impuestos"`
	Cae                 pgtype.Text        `json:"cae"`
	FechaVencimientoCae pgtype.Date        `json:"fecha_vencimiento_cae"`
	FechaEmision        pgtype.Date        `json:"fecha_emision"`
	CondicionPago       CondicionPago      `json:"condicion_pago"`
	Observaciones       pgtype.Text        `json:"observaciones"`
	UsuarioID           pgtype.UUID        `json:"usuario_id"`
	Active              bool               `json:"active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ClienteNombre       string             `json:"cliente_nombre"`
	ClienteApellido     pgtype.Text        `json:"cliente_apellido"`
	SucursalNombre      string             `json:"sucursal_nombre"`
}

func (q *Queries) GetComprobanteByID(ctx context.Context, arg GetComprobanteByIDParams) (GetComprobanteByIDRow, error) {
	row := q.db.QueryRow(ctx, getComprobanteByID, arg.ID, arg.UsuarioID)
	var i GetComprobanteByIDRow
	err := row.Scan(
		&i.ID,
		&i.Tipo,
		&i.Letra,
		&i.Numero,
		&i.Estado,
		&i.PedidoID,
		&i.ClienteID,
		&i.SucursalID,
		&i.Subtotal,
		&i.DescuentoMonto,
		&i.BaseImponible,
		&i.TotalImpuestos,
		&i.Total,
		&i.Impuestos,
		&i.Cae,
		&i.FechaVencimientoCae,
		&i.FechaEmision,
		&i.CondicionPago,
		&i.Observaciones,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClienteNombre,
		&i.ClienteApellido,
		&i.SucursalNombre,
	)
	return i, err
}

const getComprobanteByPedido = `-- name: GetComprobanteByPedido :one
SELECT c.id, c.tipo, c.letra, c.numero, c.estado, c.pedido_id, c.cliente_id, c.sucursal_id, c.subtotal, c.descuento_monto, c.base_imponible, c.total_impuestos, c.total, c.impuestos, c.cae, c.fecha_vencimiento_cae, c.fecha_emision, c.condicion_pago, c.observaciones, c.usuario_id, c.active, c.created_at, c.updated_at,
       cl.nombre AS cliente_nombre,
       cl.apellido AS cliente_apellido,
       s.nombre AS sucursal_nombre
FROM comprobantes c
JOIN clientes cl ON cl.id = c.cliente_id
JOIN sucursales s ON s.id = c.sucursal_id
WHERE c.pedido_id = $1 AND c.usuario_id = $2 AND c.active = TRUE
`

type GetComprobanteByPedidoParams struct {
	PedidoID  pgtype.UUID `json:"pedido_id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

type GetComprobanteByPedidoRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Tipo                TipoComprobante    `json:"tipo"`
	Letra               LetraComprobante   `json:"letra"`
	Numero              string             `json:"numero"`
	Estado              EstadoComprobante  `json:"estado"`
	PedidoID            pgtype.UUID        `json:"pedido_id"`
	ClienteID           pgtype.UUID        `json:"cliente_id"`
	SucursalID          pgtype.UUID        `json:"sucursal_id"`
	Subtotal            pgtype.Numeric     `json:"subtotal"`
	DescuentoMonto      pgtype.Numeric     `json:"descuento_monto"`
	BaseImponible       pgtype.Numeric     `json:"base_imponible"`
	TotalImpuestos      pgtype.Numeric     `json:"total_impuestos"`
	Total               pgtype.Numeric     `json:"total"`
	Impuestos           []byte             `json:"impuestos"`
	Cae                 pgtype.Text        `json:"cae"`
	FechaVencimientoCae pgtype.Date        `json:"fecha_vencimiento_cae"`
	FechaEmision        pgtype.Date        `json:"fecha_emision"`
	CondicionPago       CondicionPago      `json:"condicion_pago"`
	Observaciones       pgtype.Text        `json:"observaciones"`
	UsuarioID           pgtype.UUID        `json:"usuario_id"`
	Active              bool               `json:"active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ClienteNombre       string             `json:"cliente_nombre"`
	ClienteApellido     pgtype.Text        `json:"cliente_apellido"`
	SucursalNombre      string             `json:"sucursal_nombre"`
}

func (q *Queries) GetComprobanteByPedido(ctx context.Context, arg GetComprobanteByPedidoParams) (GetComprobanteByPedidoRow, error) {
	row := q.db.QueryRow(ctx, getComprobanteByPedido, arg.PedidoID, arg.UsuarioID)
	var i GetComprobanteByPedidoRow
	err := row.Scan(
		&i.ID,
		&i.Tipo,
		&i.Letra,
		&i.Numero,
		&i.Estado,
		&i.PedidoID,
		&i.ClienteID,
		&i.SucursalID,
		&i.Subtotal,
		&i.DescuentoMonto,
		&i.BaseImponible,
		&i.TotalImpuestos,
		&i.Total,
		&i.Impuestos,
		&i.Cae,
		&i.FechaVencimientoCae,
		&i.FechaEmision,
		&i.CondicionPago,
		&i.Observaciones,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClienteNombre,
		&i.ClienteApellido,
		&i.SucursalNombre,
	)
	return i, err
}

const getNextComprobanteNumero = `-- name: GetNextComprobanteNumero :one
SELECT nextval('comprobante_numero_seq')::bigint
`

func (q *Queries) GetNextComprobanteNumero(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getNextComprobanteNumero)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listComprobantes = `-- name: ListComprobantes :many
SELECT c.id, c.tipo, c.letra, c.numero, c.estado, c.pedido_id, c.cliente_id, c.sucursal_id, c.subtotal, c.descuento_monto, c.base_imponible, c.total_impuestos, c.total, c.impuestos, c.cae, c.fecha_vencimiento_cae, c.fecha_emision, c.condicion_pago, c.observaciones, c.usuario_id, c.active, c.created_at, c.updated_at,
       cl.nombre AS cliente_nombre,
       cl.apellido AS cliente_apellido,
       s.nombre AS sucursal_nombre
FROM comprobantes c
JOIN clientes cl ON cl.id = c.cliente_id
JOIN sucursales s ON s.id = c.sucursal_id
WHERE c.usuario_id = $1 AND c.active = TRUE
ORDER BY c.fecha_emision DESC, c.created_at DESC
LIMIT $2 OFFSET $3
`

type ListComprobantesParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListComprobantesRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Tipo                TipoComprobante    `json:"tipo"`
	Letra               LetraComprobante   `json:"letra"`
	Numero              string             `json:"numero"`
	Estado              EstadoComprobante  `json:"estado"`
	PedidoID            pgtype.UUID        `json:"pedido_id"`
	ClienteID           pgtype.UUID        `json:"cliente_id"`
	SucursalID          pgtype.UUID        `json:"sucursal_id"`
	Subtotal            pgtype.Numeric     `json:"subtotal"`
	DescuentoMonto      pgtype.Numeric     `json:"descuento_monto"`
	BaseImponible       pgtype.Numeric     `json:"base_imponible"`
	TotalImpuestos      pgtype.Numeric     `json:"total_impuestos"`
	Total               pgtype.Numeric     `json:"total"`
	Impuestos           []byte             `json:"impuestos"`
	Cae                 pgtype.Text        `json:"cae"`
	FechaVencimientoCae pgtype.Date        `json:"fecha_vencimiento_cae"`
	FechaEmision        pgtype.Date        `json:"fecha_emision"`
	CondicionPago       CondicionPago      `json:"condicion_pago"`
	Observaciones       pgtype.Text        `json:"observaciones"`
	UsuarioID           pgtype.UUID        `json:"usuario_id"`
	Active              bool               `json:"active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ClienteNombre       string             `json:"cliente_nombre"`
	ClienteApellido     pgtype.Text        `json:"cliente_apellido"`
	SucursalNombre      string             `json:"sucursal_nombre"`
}

func (q *Queries) ListComprobantes(ctx context.Context, arg ListComprobantesParams) ([]ListComprobantesRow, error) {
	rows, err := q.db.Query(ctx, listComprobantes, arg.UsuarioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListComprobantesRow
	for rows.Next() {
		var i ListComprobantesRow
		if err := rows.Scan(
			&i.ID,
			&i.Tipo,
			&i.Letra,
			&i.Numero,
			&i.Estado,
			&i.PedidoID,
			&i.ClienteID,
			&i.SucursalID,
			&i.Subtotal,
			&i.DescuentoMonto,
			&i.BaseImponible,
			&i.TotalImpuestos,
			&i.Total,
			&i.Impuestos,
			&i.Cae,
			&i.FechaVencimientoCae,
			&i.FechaEmision,
			&i.CondicionPago,
			&i.Observaciones,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClienteNombre,
			&i.ClienteApellido,
			&i.SucursalNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComprobantesByCliente = `-- name: ListComprobantesByCliente :many
SELECT c.id, c.tipo, c.letra, c.numero, c.estado, c.pedido_id, c.cliente_id, c.sucursal_id, c.subtotal, c.descuento_monto, c.base_imponible, c.total_impuestos, c.total, c.impuestos, c.cae, c.fecha_vencimiento_cae, c.fecha_emision, c.condicion_pago, c.observaciones, c.usuario_id, c.active, c.created_at, c.updated_at,
       cl.nombre AS cliente_nombre,
       cl.apellido AS cliente_apellido,
       s.nombre AS sucursal_nombre
FROM comprobantes c
JOIN clientes cl ON cl.id = c.cliente_id
JOIN sucursales s ON s.id = c.sucursal_id
WHERE c.usuario_id = $1 AND c.cliente_id = $2 AND c.active = TRUE
ORDER BY c.fecha_emision DESC, c.created_at DESC
LIMIT $3 OFFSET $4
`

type ListComprobantesByClienteParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	ClienteID pgtype.UUID `json:"cliente_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListComprobantesByClienteRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Tipo                TipoComprobante    `json:"tipo"`
	Letra               LetraComprobante   `json:"letra"`
	Numero              string             `json:"numero"`
	Estado              EstadoComprobante  `json:"estado"`
	PedidoID            pgtype.UUID        `json:"pedido_id"`
	ClienteID           pgtype.UUID        `json:"cliente_id"`
	SucursalID          pgtype.UUID        `json:"sucursal_id"`
	Subtotal            pgtype.Numeric     `json:"subtotal"`
	DescuentoMonto      pgtype.Numeric     `json:"descuento_monto"`
	BaseImponible       pgtype.Numeric     `json:"base_imponible"`
	TotalImpuestos      pgtype.Numeric     `json:"total_impuestos"`
	Total               pgtype.Numeric     `json:"total"`
	Impuestos           []byte             `json:"impuestos"`
	Cae                 pgtype.Text        `json:"cae"`
	FechaVencimientoCae pgtype.Date        `json:"fecha_vencimiento_cae"`
	FechaEmision        pgtype.Date        `json:"fecha_emision"`
	CondicionPago       CondicionPago      `json:"condicion_pago"`
	Observaciones       pgtype.Text        `json:"observaciones"`
	UsuarioID           pgtype.UUID        `json:"usuario_id"`
	Active              bool               `json:"active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ClienteNombre       string             `json:"cliente_nombre"`
	ClienteApellido     pgtype.Text        `json:"cliente_apellido"`
	SucursalNombre      string             `json:"sucursal_nombre"`
}

func (q *Queries) ListComprobantesByCliente(ctx context.Context, arg ListComprobantesByClienteParams) ([]ListComprobantesByClienteRow, error) {
	rows, err := q.db.Query(ctx, listComprobantesByCliente,
		arg.UsuarioID,
		arg.ClienteID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListComprobantesByClienteRow
	for rows.Next() {
		var i ListComprobantesByClienteRow
		if err := rows.Scan(
			&i.ID,
			&i.Tipo,
			&i.Letra,
			&i.Numero,
			&i.Estado,
			&i.PedidoID,
			&i.ClienteID,
			&i.SucursalID,
			&i.Subtotal,
			&i.DescuentoMonto,
			&i.BaseImponible,
			&i.TotalImpuestos,
			&i.Total,
			&i.Impuestos,
			&i.Cae,
			&i.FechaVencimientoCae,
			&i.FechaEmision,
			&i.CondicionPago,
			&i.Observaciones,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClienteNombre,
			&i.ClienteApellido,
			&i.SucursalNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComprobantesByEstado = `-- name: ListComprobantesByEstado :many
SELECT c.id, c.tipo, c.letra, c.numero, c.estado, c.pedido_id, c.cliente_id, c.sucursal_id, c.subtotal, c.descuento_monto, c.base_imponible, c.total_impuestos, c.total, c.impuestos, c.cae, c.fecha_vencimiento_cae, c.fecha_emision, c.condicion_pago, c.observaciones, c.usuario_id, c.active, c.created_at, c.updated_at,
       cl.nombre AS cliente_nombre,
       cl.apellido AS cliente_apellido,
       s.nombre AS sucursal_nombre
FROM comprobantes c
JOIN clientes cl ON cl.id = c.cliente_id
JOIN sucursales s ON s.id = c.sucursal_id
WHERE c.usuario_id = $1 AND c.estado = $2 AND c.active = TRUE
ORDER BY c.fecha_emision DESC, c.created_at DESC
LIMIT $3 OFFSET $4
`

type ListComprobantesByEstadoParams struct {
	UsuarioID pgtype.UUID       `json:"usuario_id"`
	Estado    EstadoComprobante `json:"estado"`
	Limit     int32             `json:"limit"`
	Offset    int32             `json:"offset"`
}

type ListComprobantesByEstadoRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Tipo                TipoComprobante    `json:"tipo"`
	Letra               LetraComprobante   `json:"letra"`
	Numero              string             `json:"numero"`
	Estado              EstadoComprobante  `json:"estado"`
	PedidoID            pgtype.UUID        `json:"pedido_id"`
	ClienteID           pgtype.UUID        `json:"cliente_id"`
	SucursalID          pgtype.UUID        `json:"sucursal_id"`
	Subtotal            pgtype.Numeric     `json:"subtotal"`
	DescuentoMonto      pgtype.Numeric     `json:"descuento_monto"`
	BaseImponible       pgtype.Numeric     `json:"base_imponible"`
	TotalImpuestos      pgtype.Numeric     `json:"total_impuestos"`
	Total               pgtype.Numeric     `json:"total"`
	Impuestos           []byte             `json:"impuestos"`
	Cae                 pgtype.Text        `json:"cae"`
	FechaVencimientoCae pgtype.Date        `json:"fecha_vencimiento_cae"`
	FechaEmision        pgtype.Date        `json:"fecha_emision"`
	CondicionPago       CondicionPago      `json:"condicion_pago"`
	Observaciones       pgtype.Text        `json:"observaciones"`
	UsuarioID           pgtype.UUID        `json:"usuario_id"`
	Active              bool               `json:"active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ClienteNombre       string             `json:"cliente_nombre"`
	ClienteApellido     pgtype.Text        `json:"cliente_apellido"`
	SucursalNombre      string             `json:"sucursal_nombre"`
}

func (q *Queries) ListComprobantesByEstado(ctx context.Context, arg ListComprobantesByEstadoParams) ([]ListComprobantesByEstadoRow, error) {
	rows, err := q.db.Query(ctx, listComprobantesByEstado,
		arg.UsuarioID,
		arg.Estado,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListComprobantesByEstadoRow
	for rows.Next() {
		var i ListComprobantesByEstadoRow
		if err := rows.Scan(
			&i.ID,
			&i.Tipo,
			&i.Letra,
			&i.Numero,
			&i.Estado,
			&i.PedidoID,
			&i.ClienteID,
			&i.SucursalID,
			&i.Subtotal,
			&i.DescuentoMonto,
			&i.BaseImponible,
			&i.TotalImpuestos,
			&i.Total,
			&i.Impuestos,
			&i.Cae,
			&i.FechaVencimientoCae,
			&i.FechaEmision,
			&i.CondicionPago,
			&i.Observaciones,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClienteNombre,
			&i.ClienteApellido,
			&i.SucursalNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDetallesByComprobante = `-- name: ListDetallesByComprobante :many
SELECT id, comprobante_id, producto_id, producto_nombre, producto_codigo, producto_unidad, cantidad, precio_unitario, descuento_porcentaje, descuento_monto, subtotal, orden FROM detalle_comprobantes
WHERE comprobante_id = $1
ORDER BY orden ASC
`

func (q *Queries) ListDetallesByComprobante(ctx context.Context, comprobanteID pgtype.UUID) ([]DetalleComprobante, error) {
	rows, err := q.db.Query(ctx, listDetallesByComprobante, comprobanteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DetalleComprobante
	for rows.Next() {
		var i DetalleComprobante
		if err := rows.Scan(
			&i.ID,
			&i.ComprobanteID,
			&i.ProductoID,
			&i.ProductoNombre,
			&i.ProductoCodigo,
			&i.ProductoUnidad,
			&i.Cantidad,
			&i.PrecioUnitario,
			&i.DescuentoPorcentaje,
			&i.DescuentoMonto,
			&i.Subtotal,
			&i.Orden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchComprobantes = `-- name: SearchComprobantes :many
SELECT c.id, c.tipo, c.letra, c.numero, c.estado, c.pedido_id, c.cliente_id, c.sucursal_id, c.subtotal, c.descuento_monto, c.base_imponible, c.total_impuestos, c.total, c.impuestos, c.cae, c.fecha_vencimiento_cae, c.fecha_emision, c.condicion_pago, c.observaciones, c.usuario_id, c.active, c.created_at, c.updated_at,
       cl.nombre AS cliente_nombre,
       cl.apellido AS cliente_apellido,
       s.nombre AS sucursal_nombre
FROM comprobantes c
JOIN clientes cl ON cl.id = c.cliente_id
JOIN sucursales s ON s.id = c.sucursal_id
WHERE c.usuario_id = $1 AND c.active = TRUE
  AND (c.numero ILIKE $2 OR cl.nombre ILIKE $2 OR cl.apellido ILIKE $2 OR cl.razon_social ILIKE $2)
ORDER BY c.fecha_emision DESC, c.created_at DESC
LIMIT $3 OFFSET $4
`

type SearchComprobantesParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Numero    string      `json:"numero"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type SearchComprobantesRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Tipo                TipoComprobante    `json:"tipo"`
	Letra               LetraComprobante   `json:"letra"`
	Numero              string             `json:"numero"`
	Estado              EstadoComprobante  `json:"estado"`
	PedidoID            pgtype.UUID        `json:"pedido_id"`
	ClienteID           pgtype.UUID        `json:"cliente_id"`
	SucursalID          pgtype.UUID        `json:"sucursal_id"`
	Subtotal            pgtype.Numeric     `json:"subtotal"`
	DescuentoMonto      pgtype.Numeric     `json:"descuento_monto"`
	BaseImponible       pgtype.Numeric     `json:"base_imponible"`
	TotalImpuestos      pgtype.Numeric     `json:"total_impuestos"`
	Total               pgtype.Numeric     `json:"total"`
	Impuestos           []byte             `json:"impuestos"`
	Cae                 pgtype.Text        `json:"cae"`
	FechaVencimientoCae pgtype.Date        `json:"fecha_vencimiento_cae"`
	FechaEmision        pgtype.Date        `json:"fecha_emision"`
	CondicionPago       CondicionPago      `json:"condicion_pago"`
	Observaciones       pgtype.Text        `json:"observaciones"`
	UsuarioID           pgtype.UUID        `json:"usuario_id"`
	Active              bool               `json:"active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ClienteNombre       string             `json:"cliente_nombre"`
	ClienteApellido     pgtype.Text        `json:"cliente_apellido"`
	SucursalNombre      string             `json:"sucursal_nombre"`
}

func (q *Queries) SearchComprobantes(ctx context.Context, arg SearchComprobantesParams) ([]SearchComprobantesRow, error) {
	rows, err := q.db.Query(ctx, searchComprobantes,
		arg.UsuarioID,
		arg.Numero,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchComprobantesRow
	for rows.Next() {
		var i SearchComprobantesRow
		if err := rows.Scan(
			&i.ID,
			&i.Tipo,
			&i.Letra,
			&i.Numero,
			&i.Estado,
			&i.PedidoID,
			&i.ClienteID,
			&i.SucursalID,
			&i.Subtotal,
			&i.DescuentoMonto,
			&i.BaseImponible,
			&i.TotalImpuestos,
			&i.Total,
			&i.Impuestos,
			&i.Cae,
			&i.FechaVencimientoCae,
			&i.FechaEmision,
			&i.CondicionPago,
			&i.Observaciones,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClienteNombre,
			&i.ClienteApellido,
			&i.SucursalNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteComprobante = `-- name: SoftDeleteComprobante :exec
UPDATE comprobantes
SET active = FALSE, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND estado = 'BORRADOR'
`

type SoftDeleteComprobanteParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) SoftDeleteComprobante(ctx context.Context, arg SoftDeleteComprobanteParams) error {
	_, err := q.db.Exec(ctx, softDeleteComprobante, arg.ID, arg.UsuarioID)
	return err
}

const updateComprobanteCae = `-- name: UpdateComprobanteCae :exec
UPDATE comprobantes
SET cae = $3, fecha_vencimiento_cae = $4, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2
`

type UpdateComprobanteCaeParams struct {
	ID                  pgtype.UUID `json:"id"`
	UsuarioID           pgtype.UUID `json:"usuario_id"`
	Cae                 pgtype.Text `json:"cae"`
	FechaVencimientoCae pgtype.Date `json:"fecha_vencimiento_cae"`
}

func (q *Queries) UpdateComprobanteCae(ctx context.Context, arg UpdateComprobanteCaeParams) error {
	_, err := q.db.Exec(ctx, updateComprobanteCae,
		arg.ID,
		arg.UsuarioID,
		arg.Cae,
		arg.FechaVencimientoCae,
	)
	return err
}

const updateComprobanteEstado = `-- name: UpdateComprobanteEstado :one
UPDATE comprobantes
SET estado = $3, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
RETURNING id, tipo, letra, numero, estado, pedido_id, cliente_id, sucursal_id, subtotal, descuento_monto, base_imponible, total_impuestos, total, impuestos, cae, fecha_vencimiento_cae, fecha_emision, condicion_pago, observaciones, usuario_id, active, created_at, updated_at
`

type UpdateComprobanteEstadoParams struct {
	ID        pgtype.UUID       `json:"id"`
	UsuarioID pgtype.UUID       `json:"usuario_id"`
	Estado    EstadoComprobante `json:"estado"`
}

func (q *Queries) UpdateComprobanteEstado(ctx context.Context, arg UpdateComprobanteEstadoParams) (Comprobante, error) {
	row := q.db.QueryRow(ctx, updateComprobanteEstado, arg.ID, arg.UsuarioID, arg.Estado)
	var i Comprobante
	err := row.Scan(
		&i.ID,
		&i.Tipo,
		&i.Letra,
		&i.Numero,
		&i.Estado,
		&i.PedidoID,
		&i.ClienteID,
		&i.SucursalID,
		&i.Subtotal,
		&i.DescuentoMonto,
		&i.BaseImponible,
		&i.TotalImpuestos,
		&i.Total,
		&i.Impuestos,
		&i.Cae,
		&i.FechaVencimientoCae,
		&i.FechaEmision,
		&i.CondicionPago,
		&i.Observaciones,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
