// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: convenios.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countConvenios = `-- name: CountConvenios :one
SELECT COUNT(*) FROM convenios_proveedor
WHERE usuario_id = $1 AND active = TRUE
`

func (q *Queries) CountConvenios(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countConvenios, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConvenio = `-- name: CreateConvenio :one
INSERT INTO convenios_proveedor (proveedor_id, nombre, fecha_inicio, fecha_fin, activo, usuario_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, proveedor_id, nombre, fecha_inicio, fecha_fin, activo, usuario_id, active, created_at
`

type CreateConvenioParams struct {
	ProveedorID pgtype.UUID `json:"proveedor_id"`
	Nombre      string      `json:"nombre"`
	FechaInicio pgtype.Date `json:"fecha_inicio"`
	FechaFin    pgtype.Date `json:"fecha_fin"`
	Activo      bool        `json:"activo"`
	UsuarioID   pgtype.UUID `json:"usuario_id"`
}

type ConvenioProveedor struct {
	ID          pgtype.UUID        `json:"id"`
	ProveedorID pgtype.UUID        `json:"proveedor_id"`
	Nombre      string             `json:"nombre"`
	FechaInicio pgtype.Date        `json:"fecha_inicio"`
	FechaFin    pgtype.Date        `json:"fecha_fin"`
	Activo      bool               `json:"activo"`
	UsuarioID   pgtype.UUID        `json:"usuario_id"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateConvenio(ctx context.Context, arg CreateConvenioParams) (ConvenioProveedor, error) {
	row := q.db.QueryRow(ctx, createConvenio,
		arg.ProveedorID,
		arg.Nombre,
		arg.FechaInicio,
		arg.FechaFin,
		arg.Activo,
		arg.UsuarioID,
	)
	var i ConvenioProveedor
	err := row.Scan(
		&i.ID,
		&i.ProveedorID,
		&i.Nombre,
		&i.FechaInicio,
		&i.FechaFin,
		&i.Activo,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getConvenioByID = `-- name: GetConvenioByID :one
SELECT cp.id, cp.proveedor_id, cp.nombre, cp.fecha_inicio, cp.fecha_fin, cp.activo, cp.usuario_id, cp.active, cp.created_at,
       p.nombre AS proveedor_nombre
FROM convenios_proveedor cp
JOIN proveedores p ON p.id = cp.proveedor_id
WHERE cp.id = $1 AND cp.usuario_id = $2 AND cp.active = TRUE
`

type GetConvenioByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

type GetConvenioByIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	ProveedorID     pgtype.UUID        `json:"proveedor_id"`
	Nombre          string             `json:"nombre"`
	FechaInicio     pgtype.Date        `json:"fecha_inicio"`
	FechaFin        pgtype.Date        `json:"fecha_fin"`
	Activo          bool               `json:"activo"`
	UsuarioID       pgtype.UUID        `json:"usuario_id"`
	Active          bool               `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ProveedorNombre string             `json:"proveedor_nombre"`
}

func (q *Queries) GetConvenioByID(ctx context.Context, arg GetConvenioByIDParams) (GetConvenioByIDRow, error) {
	row := q.db.QueryRow(ctx, getConvenioByID, arg.ID, arg.UsuarioID)
	var i GetConvenioByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProveedorID,
		&i.Nombre,
		&i.FechaInicio,
		&i.FechaFin,
		&i.Activo,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.ProveedorNombre,
	)
	return i, err
}

const listConvenios = `-- name: ListConvenios :many
SELECT cp.id, cp.proveedor_id, cp.nombre, cp.fecha_inicio, cp.fecha_fin, cp.activo, cp.usuario_id, cp.active, cp.created_at,
       p.nombre AS proveedor_nombre
FROM convenios_proveedor cp
JOIN proveedores p ON p.id = cp.proveedor_id
WHERE cp.usuario_id = $1 AND cp.active = TRUE
ORDER BY cp.created_at DESC
LIMIT $2 OFFSET $3
`

type ListConveniosParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListConveniosRow struct {
	ID              pgtype.UUID        `json:"id"`
	ProveedorID     pgtype.UUID        `json:"proveedor_id"`
	Nombre          string             `json:"nombre"`
	FechaInicio     pgtype.Date        `json:"fecha_inicio"`
	FechaFin        pgtype.Date        `json:"fecha_fin"`
	Activo          bool               `json:"activo"`
	UsuarioID       pgtype.UUID        `json:"usuario_id"`
	Active          bool               `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ProveedorNombre string             `json:"proveedor_nombre"`
}

func (q *Queries) ListConvenios(ctx context.Context, arg ListConveniosParams) ([]ListConveniosRow, error) {
	rows, err := q.db.Query(ctx, listConvenios, arg.UsuarioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConveniosRow
	for rows.Next() {
		var i ListConveniosRow
		if err := rows.Scan(
			&i.ID,
			&i.ProveedorID,
			&i.Nombre,
			&i.FechaInicio,
			&i.FechaFin,
			&i.Activo,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.ProveedorNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, nil
}

const updateConvenio = `-- name: UpdateConvenio :one
UPDATE convenios_proveedor
SET nombre = $3, fecha_inicio = $4, fecha_fin = $5, activo = $6
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
RETURNING id, proveedor_id, nombre, fecha_inicio, fecha_fin, activo, usuario_id, active, created_at
`

type UpdateConvenioParams struct {
	ID          pgtype.UUID `json:"id"`
	UsuarioID   pgtype.UUID `json:"usuario_id"`
	Nombre      string      `json:"nombre"`
	FechaInicio pgtype.Date `json:"fecha_inicio"`
	FechaFin    pgtype.Date `json:"fecha_fin"`
	Activo      bool        `json:"activo"`
}

func (q *Queries) UpdateConvenio(ctx context.Context, arg UpdateConvenioParams) (ConvenioProveedor, error) {
	row := q.db.QueryRow(ctx, updateConvenio,
		arg.ID,
		arg.UsuarioID,
		arg.Nombre,
		arg.FechaInicio,
		arg.FechaFin,
		arg.Activo,
	)
	var i ConvenioProveedor
	err := row.Scan(
		&i.ID,
		&i.ProveedorID,
		&i.Nombre,
		&i.FechaInicio,
		&i.FechaFin,
		&i.Activo,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const softDeleteConvenio = `-- name: SoftDeleteConvenio :exec
UPDATE convenios_proveedor
SET active = FALSE
WHERE id = $1 AND usuario_id = $2
`

type SoftDeleteConvenioParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) SoftDeleteConvenio(ctx context.Context, arg SoftDeleteConvenioParams) error {
	_, err := q.db.Exec(ctx, softDeleteConvenio, arg.ID, arg.UsuarioID)
	return err
}

const createDetalleConvenio = `-- name: CreateDetalleConvenio :one
INSERT INTO detalle_convenio (convenio_id, producto_id, precio_convenido, cantidad_minima, descuento_porcentaje)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, convenio_id, producto_id, precio_convenido, cantidad_minima, descuento_porcentaje
`

type CreateDetalleConvenioParams struct {
	ConvenioID          pgtype.UUID    `json:"convenio_id"`
	ProductoID          pgtype.UUID    `json:"producto_id"`
	PrecioConvenido     pgtype.Numeric `json:"precio_convenido"`
	CantidadMinima      pgtype.Int4    `json:"cantidad_minima"`
	DescuentoPorcentaje pgtype.Numeric `json:"descuento_porcentaje"`
}

type DetalleConvenio struct {
	ID                  pgtype.UUID    `json:"id"`
	ConvenioID          pgtype.UUID    `json:"convenio_id"`
	ProductoID          pgtype.UUID    `json:"producto_id"`
	PrecioConvenido     pgtype.Numeric `json:"precio_convenido"`
	CantidadMinima      pgtype.Int4    `json:"cantidad_minima"`
	DescuentoPorcentaje pgtype.Numeric `json:"descuento_porcentaje"`
}

func (q *Queries) CreateDetalleConvenio(ctx context.Context, arg CreateDetalleConvenioParams) (DetalleConvenio, error) {
	row := q.db.QueryRow(ctx, createDetalleConvenio,
		arg.ConvenioID,
		arg.ProductoID,
		arg.PrecioConvenido,
		arg.CantidadMinima,
		arg.DescuentoPorcentaje,
	)
	var i DetalleConvenio
	err := row.Scan(
		&i.ID,
		&i.ConvenioID,
		&i.ProductoID,
		&i.PrecioConvenido,
		&i.CantidadMinima,
		&i.DescuentoPorcentaje,
	)
	return i, err
}

const listDetalleConvenio = `-- name: ListDetalleConvenio :many
SELECT dc.id, dc.convenio_id, dc.producto_id, dc.precio_convenido, dc.cantidad_minima, dc.descuento_porcentaje,
       p.nombre AS producto_nombre,
       p.codigo AS producto_codigo
FROM detalle_convenio dc
JOIN productos p ON p.id = dc.producto_id
WHERE dc.convenio_id = $1
`

type ListDetalleConvenioRow struct {
	ID                  pgtype.UUID    `json:"id"`
	ConvenioID          pgtype.UUID    `json:"convenio_id"`
	ProductoID          pgtype.UUID    `json:"producto_id"`
	PrecioConvenido     pgtype.Numeric `json:"precio_convenido"`
	CantidadMinima      pgtype.Int4    `json:"cantidad_minima"`
	DescuentoPorcentaje pgtype.Numeric `json:"descuento_porcentaje"`
	ProductoNombre      string         `json:"producto_nombre"`
	ProductoCodigo      pgtype.Text    `json:"producto_codigo"`
}

func (q *Queries) ListDetalleConvenio(ctx context.Context, convenioID pgtype.UUID) ([]ListDetalleConvenioRow, error) {
	rows, err := q.db.Query(ctx, listDetalleConvenio, convenioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDetalleConvenioRow
	for rows.Next() {
		var i ListDetalleConvenioRow
		if err := rows.Scan(
			&i.ID,
			&i.ConvenioID,
			&i.ProductoID,
			&i.PrecioConvenido,
			&i.CantidadMinima,
			&i.DescuentoPorcentaje,
			&i.ProductoNombre,
			&i.ProductoCodigo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, nil
}

const deleteDetallesByConvenio = `-- name: DeleteDetallesByConvenio :exec
DELETE FROM detalle_convenio WHERE convenio_id = $1
`

func (q *Queries) DeleteDetallesByConvenio(ctx context.Context, convenioID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDetallesByConvenio, convenioID)
	return err
}
