// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dashboardActividadReciente = `-- name: DashboardActividadReciente :many
SELECT h.id,
       h.estado_anterior::TEXT AS estado_anterior,
       h.estado_nuevo::TEXT AS estado_nuevo,
       h.comentario,
       h.created_at,
       p.numero AS pedido_numero,
       c.nombre AS cliente_nombre,
       e.nombre AS empleado_nombre
FROM historial_pedido h
JOIN pedidos p ON p.id = h.pedido_id
JOIN clientes c ON c.id = p.cliente_id
LEFT JOIN empleados e ON e.id = h.empleado_id
WHERE p.usuario_id = $1
ORDER BY h.created_at DESC
LIMIT $2
`

type DashboardActividadRecienteParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
}

type DashboardActividadRecienteRow struct {
	ID             pgtype.UUID        `json:"id"`
	EstadoAnterior string             `json:"estado_anterior"`
	EstadoNuevo    string             `json:"estado_nuevo"`
	Comentario     pgtype.Text        `json:"comentario"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	PedidoNumero   string             `json:"pedido_numero"`
	ClienteNombre  string             `json:"cliente_nombre"`
	EmpleadoNombre pgtype.Text        `json:"empleado_nombre"`
}

func (q *Queries) DashboardActividadReciente(ctx context.Context, arg DashboardActividadRecienteParams) ([]DashboardActividadRecienteRow, error) {
	rows, err := q.db.Query(ctx, dashboardActividadReciente, arg.UsuarioID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardActividadRecienteRow
	for rows.Next() {
		var i DashboardActividadRecienteRow
		if err := rows.Scan(
			&i.ID,
			&i.EstadoAnterior,
			&i.EstadoNuevo,
			&i.Comentario,
			&i.CreatedAt,
			&i.PedidoNumero,
			&i.ClienteNombre,
			&i.EmpleadoNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardCountClientesActivos = `-- name: DashboardCountClientesActivos :one
SELECT COUNT(*) FROM clientes
WHERE usuario_id = $1 AND active = TRUE
`

func (q *Queries) DashboardCountClientesActivos(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, dashboardCountClientesActivos, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dashboardCountPedidosHoy = `-- name: DashboardCountPedidosHoy :one
SELECT COUNT(*) FROM pedidos
WHERE usuario_id = $1
  AND active = TRUE
  AND fecha_pedido >= CURRENT_DATE
  AND fecha_pedido < CURRENT_DATE + INTERVAL '1 day'
`

func (q *Queries) DashboardCountPedidosHoy(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, dashboardCountPedidosHoy, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dashboardCountProductosActivos = `-- name: DashboardCountProductosActivos :one
SELECT COUNT(*) FROM productos
WHERE usuario_id = $1 AND active = TRUE
`

func (q *Queries) DashboardCountProductosActivos(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, dashboardCountProductosActivos, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dashboardFacturacionMes = `-- name: DashboardFacturacionMes :one
SELECT COALESCE(SUM(total), 0)::NUMERIC(14,2) AS total
FROM pedidos
WHERE usuario_id = $1
  AND active = TRUE
  AND estado IN ('ENTREGADO', 'ENTREGADO_PARCIALMENTE')
  AND fecha_pedido >= date_trunc('month', CURRENT_DATE)
  AND fecha_pedido < date_trunc('month', CURRENT_DATE) + INTERVAL '1 month'
`

func (q *Queries) DashboardFacturacionMes(ctx context.Context, usuarioID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, dashboardFacturacionMes, usuarioID)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const dashboardGastosMensuales = `-- name: DashboardGastosMensuales :many
SELECT to_char(date_trunc('month', fecha), 'YYYY-MM') AS month,
       COALESCE(SUM(monto), 0)::NUMERIC(14,2) AS total
FROM gastos
WHERE usuario_id = $1
  AND active = TRUE
  AND fecha >= date_trunc('month', CURRENT_DATE) - INTERVAL '5 months'
GROUP BY date_trunc('month', fecha)
ORDER BY date_trunc('month', fecha)
`

type DashboardGastosMensualesRow struct {
	Month string         `json:"month"`
	Total pgtype.Numeric `json:"total"`
}

func (q *Queries) DashboardGastosMensuales(ctx context.Context, usuarioID pgtype.UUID) ([]DashboardGastosMensualesRow, error) {
	rows, err := q.db.Query(ctx, dashboardGastosMensuales, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardGastosMensualesRow
	for rows.Next() {
		var i DashboardGastosMensualesRow
		if err := rows.Scan(&i.Month, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardIngresosMensuales = `-- name: DashboardIngresosMensuales :many
SELECT to_char(date_trunc('month', fecha_pedido), 'YYYY-MM') AS month,
       COALESCE(SUM(total), 0)::NUMERIC(14,2) AS total
FROM pedidos
WHERE usuario_id = $1
  AND active = TRUE
  AND estado IN ('ENTREGADO', 'ENTREGADO_PARCIALMENTE')
  AND fecha_pedido >= date_trunc('month', CURRENT_DATE) - INTERVAL '5 months'
GROUP BY date_trunc('month', fecha_pedido)
ORDER BY date_trunc('month', fecha_pedido)
`

type DashboardIngresosMensualesRow struct {
	Month string         `json:"month"`
	Total pgtype.Numeric `json:"total"`
}

func (q *Queries) DashboardIngresosMensuales(ctx context.Context, usuarioID pgtype.UUID) ([]DashboardIngresosMensualesRow, error) {
	rows, err := q.db.Query(ctx, dashboardIngresosMensuales, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardIngresosMensualesRow
	for rows.Next() {
		var i DashboardIngresosMensualesRow
		if err := rows.Scan(&i.Month, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardPedidosPorEstado = `-- name: DashboardPedidosPorEstado :many
SELECT estado::TEXT AS estado, COUNT(*) AS count
FROM pedidos
WHERE usuario_id = $1 AND active = TRUE
GROUP BY estado
ORDER BY count DESC
`

type DashboardPedidosPorEstadoRow struct {
	Estado string `json:"estado"`
	Count  int64  `json:"count"`
}

func (q *Queries) DashboardPedidosPorEstado(ctx context.Context, usuarioID pgtype.UUID) ([]DashboardPedidosPorEstadoRow, error) {
	rows, err := q.db.Query(ctx, dashboardPedidosPorEstado, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardPedidosPorEstadoRow
	for rows.Next() {
		var i DashboardPedidosPorEstadoRow
		if err := rows.Scan(&i.Estado, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardPedidosSemana = `-- name: DashboardPedidosSemana :many
SELECT d::DATE AS day, COUNT(p.id) AS count
FROM generate_series(
  CURRENT_DATE - INTERVAL '6 days',
  CURRENT_DATE,
  '1 day'
) AS d
LEFT JOIN pedidos p
  ON p.fecha_pedido >= d AND p.fecha_pedido < d + INTERVAL '1 day'
  AND p.usuario_id = $1
  AND p.active = TRUE
GROUP BY d
ORDER BY d
`

type DashboardPedidosSemanaRow struct {
	Day   pgtype.Date `json:"day"`
	Count int64       `json:"count"`
}

func (q *Queries) DashboardPedidosSemana(ctx context.Context, usuarioID pgtype.UUID) ([]DashboardPedidosSemanaRow, error) {
	rows, err := q.db.Query(ctx, dashboardPedidosSemana, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardPedidosSemanaRow
	for rows.Next() {
		var i DashboardPedidosSemanaRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
