// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: detalle_pedidos.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDetallePedido = `-- name: CreateDetallePedido :one
INSERT INTO detalle_pedidos (
  pedido_id, producto_id, producto_nombre, producto_codigo, producto_unidad,
  cantidad, precio_unitario, descuento_porcentaje, descuento_monto,
  subtotal, cantidad_entregada, orden
) VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8, $9,
  $10, $11, $12
) RETURNING id, pedido_id, producto_id, producto_nombre, producto_codigo, producto_unidad, cantidad, precio_unitario, descuento_porcentaje, descuento_monto, subtotal, cantidad_entregada, orden
`

type CreateDetallePedidoParams struct {
	PedidoID            pgtype.UUID    `json:"pedido_id"`
	ProductoID          pgtype.UUID    `json:"producto_id"`
	ProductoNombre      string         `json:"producto_nombre"`
	ProductoCodigo      pgtype.Text    `json:"producto_codigo"`
	ProductoUnidad      string         `json:"producto_unidad"`
	Cantidad            pgtype.Numeric `json:"cantidad"`
	PrecioUnitario      pgtype.Numeric `json:"precio_unitario"`
	DescuentoPorcentaje pgtype.Numeric `json:"descuento_porcentaje"`
	DescuentoMonto      pgtype.Numeric `json:"descuento_monto"`
	Subtotal            pgtype.Numeric `json:"subtotal"`
	CantidadEntregada   pgtype.Numeric `json:"cantidad_entregada"`
	Orden               int32          `json:"orden"`
}

func (q *Queries) CreateDetallePedido(ctx context.Context, arg CreateDetallePedidoParams) (DetallePedido, error) {
	row := q.db.QueryRow(ctx, createDetallePedido,
		arg.PedidoID,
		arg.ProductoID,
		arg.ProductoNombre,
		arg.ProductoCodigo,
		arg.ProductoUnidad,
		arg.Cantidad,
		arg.PrecioUnitario,
		arg.DescuentoPorcentaje,
		arg.DescuentoMonto,
		arg.Subtotal,
		arg.CantidadEntregada,
		arg.Orden,
	)
	var i DetallePedido
	err := row.Scan(
		&i.ID,
		&i.PedidoID,
		&i.ProductoID,
		&i.ProductoNombre,
		&i.ProductoCodigo,
		&i.ProductoUnidad,
		&i.Cantidad,
		&i.PrecioUnitario,
		&i.DescuentoPorcentaje,
		&i.DescuentoMonto,
		&i.Subtotal,
		&i.CantidadEntregada,
		&i.Orden,
	)
	return i, err
}

const deleteDetallePedidoByPedido = `-- name: DeleteDetallePedidoByPedido :exec
DELETE FROM detalle_pedidos WHERE pedido_id = $1
`

func (q *Queries) DeleteDetallePedidoByPedido(ctx context.Context, pedidoID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDetallePedidoByPedido, pedidoID)
	return err
}

const listDetallePedido = `-- name: ListDetallePedido :many
SELECT id, pedido_id, producto_id, producto_nombre, producto_codigo, producto_unidad, cantidad, precio_unitario, descuento_porcentaje, descuento_monto, subtotal, cantidad_entregada, orden FROM detalle_pedidos
WHERE pedido_id = $1
ORDER BY orden
`

func (q *Queries) ListDetallePedido(ctx context.Context, pedidoID pgtype.UUID) ([]DetallePedido, error) {
	rows, err := q.db.Query(ctx, listDetallePedido, pedidoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DetallePedido
	for rows.Next() {
		var i DetallePedido
		if err := rows.Scan(
			&i.ID,
			&i.PedidoID,
			&i.ProductoID,
			&i.ProductoNombre,
			&i.ProductoCodigo,
			&i.ProductoUnidad,
			&i.Cantidad,
			&i.PrecioUnitario,
			&i.DescuentoPorcentaje,
			&i.DescuentoMonto,
			&i.Subtotal,
			&i.CantidadEntregada,
			&i.Orden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDetalleCantidadEntregada = `-- name: UpdateDetalleCantidadEntregada :exec
UPDATE detalle_pedidos
SET cantidad_entregada = $2
WHERE id = $1
`

type UpdateDetalleCantidadEntregadaParams struct {
	ID                pgtype.UUID    `json:"id"`
	CantidadEntregada pgtype.Numeric `json:"cantidad_entregada"`
}

func (q *Queries) UpdateDetalleCantidadEntregada(ctx context.Context, arg UpdateDetalleCantidadEntregadaParams) error {
	_, err := q.db.Exec(ctx, updateDetalleCantidadEntregada, arg.ID, arg.CantidadEntregada)
	return err
}
