// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: direcciones.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDireccionesByCliente = `-- name: CountDireccionesByCliente :one
SELECT COUNT(*) FROM direcciones
WHERE cliente_id = $1
`

func (q *Queries) CountDireccionesByCliente(ctx context.Context, clienteID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDireccionesByCliente, clienteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDireccion = `-- name: CreateDireccion :one
INSERT INTO direcciones (cliente_id, calle, numero, piso, departamento, ciudad, provincia, codigo_postal, latitud, longitud, principal)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, cliente_id, calle, numero, piso, departamento, ciudad, provincia, codigo_postal, latitud, longitud, principal, created_at, updated_at
`

type CreateDireccionParams struct {
	ClienteID    pgtype.UUID    `json:"cliente_id"`
	Calle        string         `json:"calle"`
	Numero       pgtype.Text    `json:"numero"`
	Piso         pgtype.Text    `json:"piso"`
	Departamento pgtype.Text    `json:"departamento"`
	Ciudad       pgtype.Text    `json:"ciudad"`
	Provincia    pgtype.Text    `json:"provincia"`
	CodigoPostal pgtype.Text    `json:"codigo_postal"`
	Latitud      pgtype.Numeric `json:"latitud"`
	Longitud     pgtype.Numeric `json:"longitud"`
	Principal    bool           `json:"principal"`
}

func (q *Queries) CreateDireccion(ctx context.Context, arg CreateDireccionParams) (Direccione, error) {
	row := q.db.QueryRow(ctx, createDireccion,
		arg.ClienteID,
		arg.Calle,
		arg.Numero,
		arg.Piso,
		arg.Departamento,
		arg.Ciudad,
		arg.Provincia,
		arg.CodigoPostal,
		arg.Latitud,
		arg.Longitud,
		arg.Principal,
	)
	var i Direccione
	err := row.Scan(
		&i.ID,
		&i.ClienteID,
		&i.Calle,
		&i.Numero,
		&i.Piso,
		&i.Departamento,
		&i.Ciudad,
		&i.Provincia,
		&i.CodigoPostal,
		&i.Latitud,
		&i.Longitud,
		&i.Principal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDireccion = `-- name: DeleteDireccion :exec
DELETE FROM direcciones
WHERE id = $1
`

func (q *Queries) DeleteDireccion(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDireccion, id)
	return err
}

const getDireccionByID = `-- name: GetDireccionByID :one
SELECT id, cliente_id, calle, numero, piso, departamento, ciudad, provincia, codigo_postal, latitud, longitud, principal, created_at, updated_at FROM direcciones
WHERE id = $1
`

func (q *Queries) GetDireccionByID(ctx context.Context, id pgtype.UUID) (Direccione, error) {
	row := q.db.QueryRow(ctx, getDireccionByID, id)
	var i Direccione
	err := row.Scan(
		&i.ID,
		&i.ClienteID,
		&i.Calle,
		&i.Numero,
		&i.Piso,
		&i.Departamento,
		&i.Ciudad,
		&i.Provincia,
		&i.CodigoPostal,
		&i.Latitud,
		&i.Longitud,
		&i.Principal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDireccionesByCliente = `-- name: ListDireccionesByCliente :many
SELECT id, cliente_id, calle, numero, piso, departamento, ciudad, provincia, codigo_postal, latitud, longitud, principal, created_at, updated_at FROM direcciones
WHERE cliente_id = $1
ORDER BY principal DESC, created_at
`

func (q *Queries) ListDireccionesByCliente(ctx context.Context, clienteID pgtype.UUID) ([]Direccione, error) {
	rows, err := q.db.Query(ctx, listDireccionesByCliente, clienteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Direccione
	for rows.Next() {
		var i Direccione
		if err := rows.Scan(
			&i.ID,
			&i.ClienteID,
			&i.Calle,
			&i.Numero,
			&i.Piso,
			&i.Departamento,
			&i.Ciudad,
			&i.Provincia,
			&i.CodigoPostal,
			&i.Latitud,
			&i.Longitud,
			&i.Principal,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDireccionPrincipal = `-- name: SetDireccionPrincipal :exec
UPDATE direcciones
SET principal = TRUE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SetDireccionPrincipal(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setDireccionPrincipal, id)
	return err
}

const unsetDireccionesPrincipal = `-- name: UnsetDireccionesPrincipal :exec
UPDATE direcciones
SET principal = FALSE, updated_at = NOW()
WHERE cliente_id = $1
`

func (q *Queries) UnsetDireccionesPrincipal(ctx context.Context, clienteID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unsetDireccionesPrincipal, clienteID)
	return err
}

const updateDireccion = `-- name: UpdateDireccion :one
UPDATE direcciones
SET calle = $2, numero = $3, piso = $4, departamento = $5,
    ciudad = $6, provincia = $7, codigo_postal = $8,
    latitud = $9, longitud = $10, principal = $11,
    updated_at = NOW()
WHERE id = $1
RETURNING id, cliente_id, calle, numero, piso, departamento, ciudad, provincia, codigo_postal, latitud, longitud, principal, created_at, updated_at
`

type UpdateDireccionParams struct {
	ID           pgtype.UUID    `json:"id"`
	Calle        string         `json:"calle"`
	Numero       pgtype.Text    `json:"numero"`
	Piso         pgtype.Text    `json:"piso"`
	Departamento pgtype.Text    `json:"departamento"`
	Ciudad       pgtype.Text    `json:"ciudad"`
	Provincia    pgtype.Text    `json:"provincia"`
	CodigoPostal pgtype.Text    `json:"codigo_postal"`
	Latitud      pgtype.Numeric `json:"latitud"`
	Longitud     pgtype.Numeric `json:"longitud"`
	Principal    bool           `json:"principal"`
}

func (q *Queries) UpdateDireccion(ctx context.Context, arg UpdateDireccionParams) (Direccione, error) {
	row := q.db.QueryRow(ctx, updateDireccion,
		arg.ID,
		arg.Calle,
		arg.Numero,
		arg.Piso,
		arg.Departamento,
		arg.Ciudad,
		arg.Provincia,
		arg.CodigoPostal,
		arg.Latitud,
		arg.Longitud,
		arg.Principal,
	)
	var i Direccione
	err := row.Scan(
		&i.ID,
		&i.ClienteID,
		&i.Calle,
		&i.Numero,
		&i.Piso,
		&i.Departamento,
		&i.Ciudad,
		&i.Provincia,
		&i.CodigoPostal,
		&i.Latitud,
		&i.Longitud,
		&i.Principal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
