// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employees.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkUpdateEmployeeEstado = `-- name: BulkUpdateEmployeeEstado :exec
UPDATE empleados
SET estado = $3, updated_at = NOW()
WHERE id = ANY($1::uuid[]) AND usuario_id = $2 AND active = TRUE
`

type BulkUpdateEmployeeEstadoParams struct {
	Column1   []pgtype.UUID  `json:"column_1"`
	UsuarioID pgtype.UUID    `json:"usuario_id"`
	Estado    EstadoEmpleado `json:"estado"`
}

func (q *Queries) BulkUpdateEmployeeEstado(ctx context.Context, arg BulkUpdateEmployeeEstadoParams) error {
	_, err := q.db.Exec(ctx, bulkUpdateEmployeeEstado, arg.Column1, arg.UsuarioID, arg.Estado)
	return err
}

const bulkUpdateEmployeeRol = `-- name: BulkUpdateEmployeeRol :exec
UPDATE empleados
SET rol = $3, updated_at = NOW()
WHERE id = ANY($1::uuid[]) AND usuario_id = $2 AND active = TRUE
`

type BulkUpdateEmployeeRolParams struct {
	Column1   []pgtype.UUID `json:"column_1"`
	UsuarioID pgtype.UUID   `json:"usuario_id"`
	Rol       Rol           `json:"rol"`
}

func (q *Queries) BulkUpdateEmployeeRol(ctx context.Context, arg BulkUpdateEmployeeRolParams) error {
	_, err := q.db.Exec(ctx, bulkUpdateEmployeeRol, arg.Column1, arg.UsuarioID, arg.Rol)
	return err
}

const countEmployees = `-- name: CountEmployees :one
SELECT COUNT(*) FROM empleados
WHERE usuario_id = $1 AND active = TRUE
`

func (q *Queries) CountEmployees(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployees, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmployeesByEstado = `-- name: CountEmployeesByEstado :one
SELECT COUNT(*) FROM empleados
WHERE usuario_id = $1 AND estado = $2 AND active = TRUE
`

type CountEmployeesByEstadoParams struct {
	UsuarioID pgtype.UUID    `json:"usuario_id"`
	Estado    EstadoEmpleado `json:"estado"`
}

func (q *Queries) CountEmployeesByEstado(ctx context.Context, arg CountEmployeesByEstadoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployeesByEstado, arg.UsuarioID, arg.Estado)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmployeesByRol = `-- name: CountEmployeesByRol :one
SELECT COUNT(*) FROM empleados
WHERE usuario_id = $1 AND rol = $2 AND active = TRUE
`

type CountEmployeesByRolParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Rol       Rol         `json:"rol"`
}

func (q *Queries) CountEmployeesByRol(ctx context.Context, arg CountEmployeesByRolParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployeesByRol, arg.UsuarioID, arg.Rol)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmployeesBySucursal = `-- name: CountEmployeesBySucursal :one
SELECT COUNT(*) FROM empleados
WHERE usuario_id = $1 AND sucursal_id = $2 AND active = TRUE
`

type CountEmployeesBySucursalParams struct {
	UsuarioID  pgtype.UUID `json:"usuario_id"`
	SucursalID pgtype.UUID `json:"sucursal_id"`
}

func (q *Queries) CountEmployeesBySucursal(ctx context.Context, arg CountEmployeesBySucursalParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployeesBySucursal, arg.UsuarioID, arg.SucursalID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchEmployees = `-- name: CountSearchEmployees :one
SELECT COUNT(*) FROM empleados
WHERE usuario_id = $1 AND active = TRUE
  AND (nombre ILIKE $2 OR apellido ILIKE $2 OR email ILIKE $2 OR cuil ILIKE $2)
`

type CountSearchEmployeesParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Nombre    string      `json:"nombre"`
}

func (q *Queries) CountSearchEmployees(ctx context.Context, arg CountSearchEmployeesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchEmployees, arg.UsuarioID, arg.Nombre)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO empleados (nombre, apellido, email, cuil, access_code, rol, sucursal_id, usuario_id,
  telefono, fecha_ingreso, fecha_egreso, estado, dni, direccion, salario_base,
  observaciones, tipo_contrato, obra_social, numero_legajo, banco, cbu)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21)
RETURNING id, nombre, apellido, email, cuil, access_code, rol, sucursal_id, usuario_id, active, created_at, updated_at, telefono, fecha_ingreso, fecha_egreso, estado, dni, direccion, salario_base, observaciones, tipo_contrato, obra_social, numero_legajo, banco, cbu
`

type CreateEmployeeParams struct {
	Nombre        string         `json:"nombre"`
	Apellido      string         `json:"apellido"`
	Email         pgtype.Text    `json:"email"`
	Cuil          pgtype.Text    `json:"cuil"`
	AccessCode    pgtype.Text    `json:"access_code"`
	Rol           Rol            `json:"rol"`
	SucursalID    pgtype.UUID    `json:"sucursal_id"`
	UsuarioID     pgtype.UUID    `json:"usuario_id"`
	Telefono      pgtype.Text    `json:"telefono"`
	FechaIngreso  pgtype.Date    `json:"fecha_ingreso"`
	FechaEgreso   pgtype.Date    `json:"fecha_egreso"`
	Estado        EstadoEmpleado `json:"estado"`
	Dni           pgtype.Text    `json:"dni"`
	Direccion     pgtype.Text    `json:"direccion"`
	SalarioBase   pgtype.Numeric `json:"salario_base"`
	Observaciones pgtype.Text    `json:"observaciones"`
	TipoContrato  TipoContrato   `json:"tipo_contrato"`
	ObraSocial    pgtype.Text    `json:"obra_social"`
	NumeroLegajo  pgtype.Text    `json:"numero_legajo"`
	Banco         pgtype.Text    `json:"banco"`
	Cbu           pgtype.Text    `json:"cbu"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Empleado, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.Nombre,
		arg.Apellido,
		arg.Email,
		arg.Cuil,
		arg.AccessCode,
		arg.Rol,
		arg.SucursalID,
		arg.UsuarioID,
		arg.Telefono,
		arg.FechaIngreso,
		arg.FechaEgreso,
		arg.Estado,
		arg.Dni,
		arg.Direccion,
		arg.SalarioBase,
		arg.Observaciones,
		arg.TipoContrato,
		arg.ObraSocial,
		arg.NumeroLegajo,
		arg.Banco,
		arg.Cbu,
	)
	var i Empleado
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Apellido,
		&i.Email,
		&i.Cuil,
		&i.AccessCode,
		&i.Rol,
		&i.SucursalID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Telefono,
		&i.FechaIngreso,
		&i.FechaEgreso,
		&i.Estado,
		&i.Dni,
		&i.Direccion,
		&i.SalarioBase,
		&i.Observaciones,
		&i.TipoContrato,
		&i.ObraSocial,
		&i.NumeroLegajo,
		&i.Banco,
		&i.Cbu,
	)
	return i, err
}

const createEmployeeBranch = `-- name: CreateEmployeeBranch :exec
INSERT INTO empleado_sucursales (empleado_id, sucursal_id)
VALUES ($1, $2)
ON CONFLICT (empleado_id, sucursal_id) DO NOTHING
`

type CreateEmployeeBranchParams struct {
	EmpleadoID pgtype.UUID `json:"empleado_id"`
	SucursalID pgtype.UUID `json:"sucursal_id"`
}

func (q *Queries) CreateEmployeeBranch(ctx context.Context, arg CreateEmployeeBranchParams) error {
	_, err := q.db.Exec(ctx, createEmployeeBranch, arg.EmpleadoID, arg.SucursalID)
	return err
}

const deleteEmployeeBranches = `-- name: DeleteEmployeeBranches :exec
DELETE FROM empleado_sucursales
WHERE empleado_id = $1
`

func (q *Queries) DeleteEmployeeBranches(ctx context.Context, empleadoID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmployeeBranches, empleadoID)
	return err
}

const getEmployeeByAccessCode = `-- name: GetEmployeeByAccessCode :one
SELECT e.id, e.nombre, e.apellido, e.email, e.cuil, e.access_code, e.rol, e.sucursal_id, e.usuario_id, e.active, e.created_at, e.updated_at, e.telefono, e.fecha_ingreso, e.fecha_egreso, e.estado, e.dni, e.direccion, e.salario_base, e.observaciones, e.tipo_contrato, e.obra_social, e.numero_legajo, e.banco, e.cbu, s.nombre AS sucursal_nombre, u.email AS owner_email
FROM empleados e
JOIN sucursales s ON s.id = e.sucursal_id
JOIN usuarios u ON u.id = e.usuario_id
WHERE e.access_code = $1 AND e.active = TRUE
`

type GetEmployeeByAccessCodeRow struct {
	ID             pgtype.UUID        `json:"id"`
	Nombre         string             `json:"nombre"`
	Apellido       string             `json:"apellido"`
	Email          pgtype.Text        `json:"email"`
	Cuil           pgtype.Text        `json:"cuil"`
	AccessCode     pgtype.Text        `json:"access_code"`
	Rol            Rol                `json:"rol"`
	SucursalID     pgtype.UUID        `json:"sucursal_id"`
	UsuarioID      pgtype.UUID        `json:"usuario_id"`
	Active         bool               `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Telefono       pgtype.Text        `json:"telefono"`
	FechaIngreso   pgtype.Date        `json:"fecha_ingreso"`
	FechaEgreso    pgtype.Date        `json:"fecha_egreso"`
	Estado         EstadoEmpleado     `json:"estado"`
	Dni            pgtype.Text        `json:"dni"`
	Direccion      pgtype.Text        `json:"direccion"`
	SalarioBase    pgtype.Numeric     `json:"salario_base"`
	Observaciones  pgtype.Text        `json:"observaciones"`
	TipoContrato   TipoContrato       `json:"tipo_contrato"`
	ObraSocial     pgtype.Text        `json:"obra_social"`
	NumeroLegajo   pgtype.Text        `json:"numero_legajo"`
	Banco          pgtype.Text        `json:"banco"`
	Cbu            pgtype.Text        `json:"cbu"`
	SucursalNombre string             `json:"sucursal_nombre"`
	OwnerEmail     string             `json:"owner_email"`
}

func (q *Queries) GetEmployeeByAccessCode(ctx context.Context, accessCode pgtype.Text) (GetEmployeeByAccessCodeRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeByAccessCode, accessCode)
	var i GetEmployeeByAccessCodeRow
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Apellido,
		&i.Email,
		&i.Cuil,
		&i.AccessCode,
		&i.Rol,
		&i.SucursalID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Telefono,
		&i.FechaIngreso,
		&i.FechaEgreso,
		&i.Estado,
		&i.Dni,
		&i.Direccion,
		&i.SalarioBase,
		&i.Observaciones,
		&i.TipoContrato,
		&i.ObraSocial,
		&i.NumeroLegajo,
		&i.Banco,
		&i.Cbu,
		&i.SucursalNombre,
		&i.OwnerEmail,
	)
	return i, err
}

const getEmployeeByEmail = `-- name: GetEmployeeByEmail :one
SELECT id, nombre, apellido, email, cuil, access_code, rol, sucursal_id, usuario_id, active, created_at, updated_at, telefono, fecha_ingreso, fecha_egreso, estado, dni, direccion, salario_base, observaciones, tipo_contrato, obra_social, numero_legajo, banco, cbu FROM empleados
WHERE email = $1 AND usuario_id = $2 AND active = TRUE
`

type GetEmployeeByEmailParams struct {
	Email     pgtype.Text `json:"email"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) GetEmployeeByEmail(ctx context.Context, arg GetEmployeeByEmailParams) (Empleado, error) {
	row := q.db.QueryRow(ctx, getEmployeeByEmail, arg.Email, arg.UsuarioID)
	var i Empleado
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Apellido,
		&i.Email,
		&i.Cuil,
		&i.AccessCode,
		&i.Rol,
		&i.SucursalID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Telefono,
		&i.FechaIngreso,
		&i.FechaEgreso,
		&i.Estado,
		&i.Dni,
		&i.Direccion,
		&i.SalarioBase,
		&i.Observaciones,
		&i.TipoContrato,
		&i.ObraSocial,
		&i.NumeroLegajo,
		&i.Banco,
		&i.Cbu,
	)
	return i, err
}

const getEmployeeByID = `-- name: GetEmployeeByID :one
SELECT id, nombre, apellido, email, cuil, access_code, rol, sucursal_id, usuario_id, active, created_at, updated_at, telefono, fecha_ingreso, fecha_egreso, estado, dni, direccion, salario_base, observaciones, tipo_contrato, obra_social, numero_legajo, banco, cbu FROM empleados
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
`

type GetEmployeeByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) GetEmployeeByID(ctx context.Context, arg GetEmployeeByIDParams) (Empleado, error) {
	row := q.db.QueryRow(ctx, getEmployeeByID, arg.ID, arg.UsuarioID)
	var i Empleado
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Apellido,
		&i.Email,
		&i.Cuil,
		&i.AccessCode,
		&i.Rol,
		&i.SucursalID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Telefono,
		&i.FechaIngreso,
		&i.FechaEgreso,
		&i.Estado,
		&i.Dni,
		&i.Direccion,
		&i.SalarioBase,
		&i.Observaciones,
		&i.TipoContrato,
		&i.ObraSocial,
		&i.NumeroLegajo,
		&i.Banco,
		&i.Cbu,
	)
	return i, err
}

const listEmployeeBranches = `-- name: ListEmployeeBranches :many
SELECT s.id, s.nombre, s.direccion
FROM empleado_sucursales es
JOIN sucursales s ON s.id = es.sucursal_id
WHERE es.empleado_id = $1 AND s.active = TRUE
`

type ListEmployeeBranchesRow struct {
	ID        pgtype.UUID `json:"id"`
	Nombre    string      `json:"nombre"`
	Direccion pgtype.Text `json:"direccion"`
}

func (q *Queries) ListEmployeeBranches(ctx context.Context, empleadoID pgtype.UUID) ([]ListEmployeeBranchesRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeBranches, empleadoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmployeeBranchesRow
	for rows.Next() {
		var i ListEmployeeBranchesRow
		if err := rows.Scan(&i.ID, &i.Nombre, &i.Direccion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployees = `-- name: ListEmployees :many
SELECT id, nombre, apellido, email, cuil, access_code, rol, sucursal_id, usuario_id, active, created_at, updated_at, telefono, fecha_ingreso, fecha_egreso, estado, dni, direccion, salario_base, observaciones, tipo_contrato, obra_social, numero_legajo, banco, cbu FROM empleados
WHERE usuario_id = $1 AND active = TRUE
ORDER BY apellido, nombre
LIMIT $2 OFFSET $3
`

type ListEmployeesParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]Empleado, error) {
	rows, err := q.db.Query(ctx, listEmployees, arg.UsuarioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Empleado
	for rows.Next() {
		var i Empleado
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Apellido,
			&i.Email,
			&i.Cuil,
			&i.AccessCode,
			&i.Rol,
			&i.SucursalID,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Telefono,
			&i.FechaIngreso,
			&i.FechaEgreso,
			&i.Estado,
			&i.Dni,
			&i.Direccion,
			&i.SalarioBase,
			&i.Observaciones,
			&i.TipoContrato,
			&i.ObraSocial,
			&i.NumeroLegajo,
			&i.Banco,
			&i.Cbu,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesByEstado = `-- name: ListEmployeesByEstado :many
SELECT id, nombre, apellido, email, cuil, access_code, rol, sucursal_id, usuario_id, active, created_at, updated_at, telefono, fecha_ingreso, fecha_egreso, estado, dni, direccion, salario_base, observaciones, tipo_contrato, obra_social, numero_legajo, banco, cbu FROM empleados
WHERE usuario_id = $1 AND estado = $2 AND active = TRUE
ORDER BY apellido, nombre
LIMIT $3 OFFSET $4
`

type ListEmployeesByEstadoParams struct {
	UsuarioID pgtype.UUID    `json:"usuario_id"`
	Estado    EstadoEmpleado `json:"estado"`
	Limit     int32          `json:"limit"`
	Offset    int32          `json:"offset"`
}

func (q *Queries) ListEmployeesByEstado(ctx context.Context, arg ListEmployeesByEstadoParams) ([]Empleado, error) {
	rows, err := q.db.Query(ctx, listEmployeesByEstado,
		arg.UsuarioID,
		arg.Estado,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Empleado
	for rows.Next() {
		var i Empleado
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Apellido,
			&i.Email,
			&i.Cuil,
			&i.AccessCode,
			&i.Rol,
			&i.SucursalID,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Telefono,
			&i.FechaIngreso,
			&i.FechaEgreso,
			&i.Estado,
			&i.Dni,
			&i.Direccion,
			&i.SalarioBase,
			&i.Observaciones,
			&i.TipoContrato,
			&i.ObraSocial,
			&i.NumeroLegajo,
			&i.Banco,
			&i.Cbu,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesByRol = `-- name: ListEmployeesByRol :many
SELECT id, nombre, apellido, email, cuil, access_code, rol, sucursal_id, usuario_id, active, created_at, updated_at, telefono, fecha_ingreso, fecha_egreso, estado, dni, direccion, salario_base, observaciones, tipo_contrato, obra_social, numero_legajo, banco, cbu FROM empleados
WHERE usuario_id = $1 AND rol = $2 AND active = TRUE
ORDER BY apellido, nombre
LIMIT $3 OFFSET $4
`

type ListEmployeesByRolParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Rol       Rol         `json:"rol"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListEmployeesByRol(ctx context.Context, arg ListEmployeesByRolParams) ([]Empleado, error) {
	rows, err := q.db.Query(ctx, listEmployeesByRol,
		arg.UsuarioID,
		arg.Rol,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Empleado
	for rows.Next() {
		var i Empleado
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Apellido,
			&i.Email,
			&i.Cuil,
			&i.AccessCode,
			&i.Rol,
			&i.SucursalID,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Telefono,
			&i.FechaIngreso,
			&i.FechaEgreso,
			&i.Estado,
			&i.Dni,
			&i.Direccion,
			&i.SalarioBase,
			&i.Observaciones,
			&i.TipoContrato,
			&i.ObraSocial,
			&i.NumeroLegajo,
			&i.Banco,
			&i.Cbu,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesBySucursal = `-- name: ListEmployeesBySucursal :many
SELECT id, nombre, apellido, email, cuil, access_code, rol, sucursal_id, usuario_id, active, created_at, updated_at, telefono, fecha_ingreso, fecha_egreso, estado, dni, direccion, salario_base, observaciones, tipo_contrato, obra_social, numero_legajo, banco, cbu FROM empleados
WHERE usuario_id = $1 AND sucursal_id = $2 AND active = TRUE
ORDER BY apellido, nombre
LIMIT $3 OFFSET $4
`

type ListEmployeesBySucursalParams struct {
	UsuarioID  pgtype.UUID `json:"usuario_id"`
	SucursalID pgtype.UUID `json:"sucursal_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListEmployeesBySucursal(ctx context.Context, arg ListEmployeesBySucursalParams) ([]Empleado, error) {
	rows, err := q.db.Query(ctx, listEmployeesBySucursal,
		arg.UsuarioID,
		arg.SucursalID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Empleado
	for rows.Next() {
		var i Empleado
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Apellido,
			&i.Email,
			&i.Cuil,
			&i.AccessCode,
			&i.Rol,
			&i.SucursalID,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Telefono,
			&i.FechaIngreso,
			&i.FechaEgreso,
			&i.Estado,
			&i.Dni,
			&i.Direccion,
			&i.SalarioBase,
			&i.Observaciones,
			&i.TipoContrato,
			&i.ObraSocial,
			&i.NumeroLegajo,
			&i.Banco,
			&i.Cbu,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesForExport = `-- name: ListEmployeesForExport :many
SELECT id, nombre, apellido, email, cuil, access_code, rol, sucursal_id, usuario_id, active, created_at, updated_at, telefono, fecha_ingreso, fecha_egreso, estado, dni, direccion, salario_base, observaciones, tipo_contrato, obra_social, numero_legajo, banco, cbu FROM empleados
WHERE usuario_id = $1 AND active = TRUE
ORDER BY apellido, nombre
`

func (q *Queries) ListEmployeesForExport(ctx context.Context, usuarioID pgtype.UUID) ([]Empleado, error) {
	rows, err := q.db.Query(ctx, listEmployeesForExport, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Empleado
	for rows.Next() {
		var i Empleado
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Apellido,
			&i.Email,
			&i.Cuil,
			&i.AccessCode,
			&i.Rol,
			&i.SucursalID,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Telefono,
			&i.FechaIngreso,
			&i.FechaEgreso,
			&i.Estado,
			&i.Dni,
			&i.Direccion,
			&i.SalarioBase,
			&i.Observaciones,
			&i.TipoContrato,
			&i.ObraSocial,
			&i.NumeroLegajo,
			&i.Banco,
			&i.Cbu,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEmployees = `-- name: SearchEmployees :many
SELECT id, nombre, apellido, email, cuil, access_code, rol, sucursal_id, usuario_id, active, created_at, updated_at, telefono, fecha_ingreso, fecha_egreso, estado, dni, direccion, salario_base, observaciones, tipo_contrato, obra_social, numero_legajo, banco, cbu FROM empleados
WHERE usuario_id = $1 AND active = TRUE
  AND (nombre ILIKE $2 OR apellido ILIKE $2 OR email ILIKE $2 OR cuil ILIKE $2)
ORDER BY apellido, nombre
LIMIT $3 OFFSET $4
`

type SearchEmployeesParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Nombre    string      `json:"nombre"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) SearchEmployees(ctx context.Context, arg SearchEmployeesParams) ([]Empleado, error) {
	rows, err := q.db.Query(ctx, searchEmployees,
		arg.UsuarioID,
		arg.Nombre,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Empleado
	for rows.Next() {
		var i Empleado
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Apellido,
			&i.Email,
			&i.Cuil,
			&i.AccessCode,
			&i.Rol,
			&i.SucursalID,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Telefono,
			&i.FechaIngreso,
			&i.FechaEgreso,
			&i.Estado,
			&i.Dni,
			&i.Direccion,
			&i.SalarioBase,
			&i.Observaciones,
			&i.TipoContrato,
			&i.ObraSocial,
			&i.NumeroLegajo,
			&i.Banco,
			&i.Cbu,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEmployee = `-- name: SoftDeleteEmployee :exec
UPDATE empleados
SET active = FALSE, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2
`

type SoftDeleteEmployeeParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) SoftDeleteEmployee(ctx context.Context, arg SoftDeleteEmployeeParams) error {
	_, err := q.db.Exec(ctx, softDeleteEmployee, arg.ID, arg.UsuarioID)
	return err
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE empleados
SET nombre = $3, apellido = $4, email = $5, cuil = $6,
    rol = $7, sucursal_id = $8,
    telefono = $9, fecha_ingreso = $10, fecha_egreso = $11, estado = $12,
    dni = $13, direccion = $14, salario_base = $15, observaciones = $16,
    tipo_contrato = $17, obra_social = $18, numero_legajo = $19,
    banco = $20, cbu = $21,
    updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
RETURNING id, nombre, apellido, email, cuil, access_code, rol, sucursal_id, usuario_id, active, created_at, updated_at, telefono, fecha_ingreso, fecha_egreso, estado, dni, direccion, salario_base, observaciones, tipo_contrato, obra_social, numero_legajo, banco, cbu
`

type UpdateEmployeeParams struct {
	ID            pgtype.UUID    `json:"id"`
	UsuarioID     pgtype.UUID    `json:"usuario_id"`
	Nombre        string         `json:"nombre"`
	Apellido      string         `json:"apellido"`
	Email         pgtype.Text    `json:"email"`
	Cuil          pgtype.Text    `json:"cuil"`
	Rol           Rol            `json:"rol"`
	SucursalID    pgtype.UUID    `json:"sucursal_id"`
	Telefono      pgtype.Text    `json:"telefono"`
	FechaIngreso  pgtype.Date    `json:"fecha_ingreso"`
	FechaEgreso   pgtype.Date    `json:"fecha_egreso"`
	Estado        EstadoEmpleado `json:"estado"`
	Dni           pgtype.Text    `json:"dni"`
	Direccion     pgtype.Text    `json:"direccion"`
	SalarioBase   pgtype.Numeric `json:"salario_base"`
	Observaciones pgtype.Text    `json:"observaciones"`
	TipoContrato  TipoContrato   `json:"tipo_contrato"`
	ObraSocial    pgtype.Text    `json:"obra_social"`
	NumeroLegajo  pgtype.Text    `json:"numero_legajo"`
	Banco         pgtype.Text    `json:"banco"`
	Cbu           pgtype.Text    `json:"cbu"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Empleado, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.ID,
		arg.UsuarioID,
		arg.Nombre,
		arg.Apellido,
		arg.Email,
		arg.Cuil,
		arg.Rol,
		arg.SucursalID,
		arg.Telefono,
		arg.FechaIngreso,
		arg.FechaEgreso,
		arg.Estado,
		arg.Dni,
		arg.Direccion,
		arg.SalarioBase,
		arg.Observaciones,
		arg.TipoContrato,
		arg.ObraSocial,
		arg.NumeroLegajo,
		arg.Banco,
		arg.Cbu,
	)
	var i Empleado
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Apellido,
		&i.Email,
		&i.Cuil,
		&i.AccessCode,
		&i.Rol,
		&i.SucursalID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Telefono,
		&i.FechaIngreso,
		&i.FechaEgreso,
		&i.Estado,
		&i.Dni,
		&i.Direccion,
		&i.SalarioBase,
		&i.Observaciones,
		&i.TipoContrato,
		&i.ObraSocial,
		&i.NumeroLegajo,
		&i.Banco,
		&i.Cbu,
	)
	return i, err
}

const updateEmployeeAccessCode = `-- name: UpdateEmployeeAccessCode :one
UPDATE empleados
SET access_code = $3, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
RETURNING id, nombre, apellido, email, cuil, access_code, rol, sucursal_id, usuario_id, active, created_at, updated_at, telefono, fecha_ingreso, fecha_egreso, estado, dni, direccion, salario_base, observaciones, tipo_contrato, obra_social, numero_legajo, banco, cbu
`

type UpdateEmployeeAccessCodeParams struct {
	ID         pgtype.UUID `json:"id"`
	UsuarioID  pgtype.UUID `json:"usuario_id"`
	AccessCode pgtype.Text `json:"access_code"`
}

func (q *Queries) UpdateEmployeeAccessCode(ctx context.Context, arg UpdateEmployeeAccessCodeParams) (Empleado, error) {
	row := q.db.QueryRow(ctx, updateEmployeeAccessCode, arg.ID, arg.UsuarioID, arg.AccessCode)
	var i Empleado
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Apellido,
		&i.Email,
		&i.Cuil,
		&i.AccessCode,
		&i.Rol,
		&i.SucursalID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Telefono,
		&i.FechaIngreso,
		&i.FechaEgreso,
		&i.Estado,
		&i.Dni,
		&i.Direccion,
		&i.SalarioBase,
		&i.Observaciones,
		&i.TipoContrato,
		&i.ObraSocial,
		&i.NumeroLegajo,
		&i.Banco,
		&i.Cbu,
	)
	return i, err
}
