// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entidades_bancarias.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEntidadesBancarias = `-- name: CountEntidadesBancarias :one
SELECT COUNT(*) FROM entidades_bancarias
WHERE usuario_id = $1 AND active = TRUE
`

func (q *Queries) CountEntidadesBancarias(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEntidadesBancarias, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEntidadBancaria = `-- name: CreateEntidadBancaria :one
INSERT INTO entidades_bancarias (nombre, sucursal_banco, numero_cuenta, cbu, alias, sucursal_id, usuario_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, nombre, sucursal_banco, numero_cuenta, cbu, alias, sucursal_id, active, usuario_id, created_at, updated_at
`

type CreateEntidadBancariaParams struct {
	Nombre        string      `json:"nombre"`
	SucursalBanco pgtype.Text `json:"sucursal_banco"`
	NumeroCuenta  pgtype.Text `json:"numero_cuenta"`
	Cbu           pgtype.Text `json:"cbu"`
	Alias         pgtype.Text `json:"alias"`
	SucursalID    pgtype.UUID `json:"sucursal_id"`
	UsuarioID     pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) CreateEntidadBancaria(ctx context.Context, arg CreateEntidadBancariaParams) (EntidadesBancaria, error) {
	row := q.db.QueryRow(ctx, createEntidadBancaria,
		arg.Nombre,
		arg.SucursalBanco,
		arg.NumeroCuenta,
		arg.Cbu,
		arg.Alias,
		arg.SucursalID,
		arg.UsuarioID,
	)
	var i EntidadesBancaria
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.SucursalBanco,
		&i.NumeroCuenta,
		&i.Cbu,
		&i.Alias,
		&i.SucursalID,
		&i.Active,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEntidadBancariaByID = `-- name: GetEntidadBancariaByID :one
SELECT id, nombre, sucursal_banco, numero_cuenta, cbu, alias, sucursal_id, active, usuario_id, created_at, updated_at FROM entidades_bancarias
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
`

type GetEntidadBancariaByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) GetEntidadBancariaByID(ctx context.Context, arg GetEntidadBancariaByIDParams) (EntidadesBancaria, error) {
	row := q.db.QueryRow(ctx, getEntidadBancariaByID, arg.ID, arg.UsuarioID)
	var i EntidadesBancaria
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.SucursalBanco,
		&i.NumeroCuenta,
		&i.Cbu,
		&i.Alias,
		&i.SucursalID,
		&i.Active,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEntidadesBancarias = `-- name: ListEntidadesBancarias :many
SELECT id, nombre, sucursal_banco, numero_cuenta, cbu, alias, sucursal_id, active, usuario_id, created_at, updated_at FROM entidades_bancarias
WHERE usuario_id = $1 AND active = TRUE
ORDER BY nombre
LIMIT $2 OFFSET $3
`

type ListEntidadesBancariasParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListEntidadesBancarias(ctx context.Context, arg ListEntidadesBancariasParams) ([]EntidadesBancaria, error) {
	rows, err := q.db.Query(ctx, listEntidadesBancarias, arg.UsuarioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntidadesBancaria
	for rows.Next() {
		var i EntidadesBancaria
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.SucursalBanco,
			&i.NumeroCuenta,
			&i.Cbu,
			&i.Alias,
			&i.SucursalID,
			&i.Active,
			&i.UsuarioID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEntidadBancaria = `-- name: SoftDeleteEntidadBancaria :exec
UPDATE entidades_bancarias
SET active = FALSE, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2
`

type SoftDeleteEntidadBancariaParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) SoftDeleteEntidadBancaria(ctx context.Context, arg SoftDeleteEntidadBancariaParams) error {
	_, err := q.db.Exec(ctx, softDeleteEntidadBancaria, arg.ID, arg.UsuarioID)
	return err
}

const updateEntidadBancaria = `-- name: UpdateEntidadBancaria :one
UPDATE entidades_bancarias
SET nombre = $3, sucursal_banco = $4, numero_cuenta = $5, cbu = $6, alias = $7, sucursal_id = $8, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
RETURNING id, nombre, sucursal_banco, numero_cuenta, cbu, alias, sucursal_id, active, usuario_id, created_at, updated_at
`

type UpdateEntidadBancariaParams struct {
	ID            pgtype.UUID `json:"id"`
	UsuarioID     pgtype.UUID `json:"usuario_id"`
	Nombre        string      `json:"nombre"`
	SucursalBanco pgtype.Text `json:"sucursal_banco"`
	NumeroCuenta  pgtype.Text `json:"numero_cuenta"`
	Cbu           pgtype.Text `json:"cbu"`
	Alias         pgtype.Text `json:"alias"`
	SucursalID    pgtype.UUID `json:"sucursal_id"`
}

func (q *Queries) UpdateEntidadBancaria(ctx context.Context, arg UpdateEntidadBancariaParams) (EntidadesBancaria, error) {
	row := q.db.QueryRow(ctx, updateEntidadBancaria,
		arg.ID,
		arg.UsuarioID,
		arg.Nombre,
		arg.SucursalBanco,
		arg.NumeroCuenta,
		arg.Cbu,
		arg.Alias,
		arg.SucursalID,
	)
	var i EntidadesBancaria
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.SucursalBanco,
		&i.NumeroCuenta,
		&i.Cbu,
		&i.Alias,
		&i.SucursalID,
		&i.Active,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
