// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: familias_producto.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFamiliasProducto = `-- name: CountFamiliasProducto :one
SELECT COUNT(*) FROM familias_producto
WHERE usuario_id = $1 AND active = TRUE
`

func (q *Queries) CountFamiliasProducto(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFamiliasProducto, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFamiliaProducto = `-- name: CreateFamiliaProducto :one
INSERT INTO familias_producto (nombre, descripcion, usuario_id)
VALUES ($1, $2, $3)
RETURNING id, nombre, descripcion, usuario_id, active, created_at, updated_at
`

type CreateFamiliaProductoParams struct {
	Nombre      string      `json:"nombre"`
	Descripcion pgtype.Text `json:"descripcion"`
	UsuarioID   pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) CreateFamiliaProducto(ctx context.Context, arg CreateFamiliaProductoParams) (FamiliasProducto, error) {
	row := q.db.QueryRow(ctx, createFamiliaProducto, arg.Nombre, arg.Descripcion, arg.UsuarioID)
	var i FamiliasProducto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFamiliaProductoByID = `-- name: GetFamiliaProductoByID :one
SELECT id, nombre, descripcion, usuario_id, active, created_at, updated_at FROM familias_producto
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
`

type GetFamiliaProductoByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) GetFamiliaProductoByID(ctx context.Context, arg GetFamiliaProductoByIDParams) (FamiliasProducto, error) {
	row := q.db.QueryRow(ctx, getFamiliaProductoByID, arg.ID, arg.UsuarioID)
	var i FamiliasProducto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFamiliasProducto = `-- name: ListFamiliasProducto :many
SELECT id, nombre, descripcion, usuario_id, active, created_at, updated_at FROM familias_producto
WHERE usuario_id = $1 AND active = TRUE
ORDER BY nombre
LIMIT $2 OFFSET $3
`

type ListFamiliasProductoParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListFamiliasProducto(ctx context.Context, arg ListFamiliasProductoParams) ([]FamiliasProducto, error) {
	rows, err := q.db.Query(ctx, listFamiliasProducto, arg.UsuarioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FamiliasProducto
	for rows.Next() {
		var i FamiliasProducto
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Descripcion,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFamiliaProducto = `-- name: SoftDeleteFamiliaProducto :exec
UPDATE familias_producto
SET active = FALSE, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2
`

type SoftDeleteFamiliaProductoParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) SoftDeleteFamiliaProducto(ctx context.Context, arg SoftDeleteFamiliaProductoParams) error {
	_, err := q.db.Exec(ctx, softDeleteFamiliaProducto, arg.ID, arg.UsuarioID)
	return err
}

const updateFamiliaProducto = `-- name: UpdateFamiliaProducto :one
UPDATE familias_producto
SET nombre = $3, descripcion = $4, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
RETURNING id, nombre, descripcion, usuario_id, active, created_at, updated_at
`

type UpdateFamiliaProductoParams struct {
	ID          pgtype.UUID `json:"id"`
	UsuarioID   pgtype.UUID `json:"usuario_id"`
	Nombre      string      `json:"nombre"`
	Descripcion pgtype.Text `json:"descripcion"`
}

func (q *Queries) UpdateFamiliaProducto(ctx context.Context, arg UpdateFamiliaProductoParams) (FamiliasProducto, error) {
	row := q.db.QueryRow(ctx, updateFamiliaProducto,
		arg.ID,
		arg.UsuarioID,
		arg.Nombre,
		arg.Descripcion,
	)
	var i FamiliasProducto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
