// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: finance_resumen.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const financeResumenChequesPendientes = `-- name: FinanceResumenChequesPendientes :one
SELECT COUNT(*) FROM cheques
WHERE usuario_id = $1
  AND estado IN ('RECIBIDO', 'DEPOSITADO')
`

func (q *Queries) FinanceResumenChequesPendientes(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, financeResumenChequesPendientes, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const financeResumenChequesPorVencer = `-- name: FinanceResumenChequesPorVencer :many
SELECT id, numero, monto, fecha_vencimiento, estado::TEXT AS estado, banco, emisor
FROM cheques
WHERE usuario_id = $1
  AND estado IN ('RECIBIDO', 'DEPOSITADO')
  AND fecha_vencimiento <= CURRENT_DATE + INTERVAL '30 days'
ORDER BY fecha_vencimiento ASC
LIMIT $2
`

type FinanceResumenChequesPorVencerParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
}

type FinanceResumenChequesPorVencerRow struct {
	ID               pgtype.UUID    `json:"id"`
	Numero           string         `json:"numero"`
	Monto            pgtype.Numeric `json:"monto"`
	FechaVencimiento pgtype.Date    `json:"fecha_vencimiento"`
	Estado           string         `json:"estado"`
	Banco            pgtype.Text    `json:"banco"`
	Emisor           pgtype.Text    `json:"emisor"`
}

func (q *Queries) FinanceResumenChequesPorVencer(ctx context.Context, arg FinanceResumenChequesPorVencerParams) ([]FinanceResumenChequesPorVencerRow, error) {
	rows, err := q.db.Query(ctx, financeResumenChequesPorVencer, arg.UsuarioID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinanceResumenChequesPorVencerRow
	for rows.Next() {
		var i FinanceResumenChequesPorVencerRow
		if err := rows.Scan(
			&i.ID,
			&i.Numero,
			&i.Monto,
			&i.FechaVencimiento,
			&i.Estado,
			&i.Banco,
			&i.Emisor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const financeResumenEgresosMes = `-- name: FinanceResumenEgresosMes :one
SELECT COALESCE(SUM(monto), 0)::NUMERIC(14,2) AS total
FROM movimientos_caja
WHERE usuario_id = $1
  AND tipo = 'EGRESO'
  AND created_at >= date_trunc('month', CURRENT_DATE)
  AND created_at < date_trunc('month', CURRENT_DATE) + INTERVAL '1 month'
`

func (q *Queries) FinanceResumenEgresosMes(ctx context.Context, usuarioID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, financeResumenEgresosMes, usuarioID)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const financeResumenGastosMes = `-- name: FinanceResumenGastosMes :one
SELECT COALESCE(SUM(monto), 0)::NUMERIC(14,2) AS total
FROM gastos
WHERE usuario_id = $1
  AND active = TRUE
  AND fecha >= date_trunc('month', CURRENT_DATE)
  AND fecha < date_trunc('month', CURRENT_DATE) + INTERVAL '1 month'
`

func (q *Queries) FinanceResumenGastosMes(ctx context.Context, usuarioID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, financeResumenGastosMes, usuarioID)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const financeResumenIngresosMes = `-- name: FinanceResumenIngresosMes :one
SELECT COALESCE(SUM(total), 0)::NUMERIC(14,2) AS total
FROM pedidos
WHERE usuario_id = $1
  AND active = TRUE
  AND estado IN ('ENTREGADO', 'ENTREGADO_PARCIALMENTE')
  AND fecha_pedido >= date_trunc('month', CURRENT_DATE)
  AND fecha_pedido < date_trunc('month', CURRENT_DATE) + INTERVAL '1 month'
`

func (q *Queries) FinanceResumenIngresosMes(ctx context.Context, usuarioID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, financeResumenIngresosMes, usuarioID)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const financeResumenSaldoCajas = `-- name: FinanceResumenSaldoCajas :one
SELECT COALESCE(SUM(saldo), 0)::NUMERIC(14,2) AS total
FROM cajas
WHERE usuario_id = $1 AND activa = TRUE
`

func (q *Queries) FinanceResumenSaldoCajas(ctx context.Context, usuarioID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, financeResumenSaldoCajas, usuarioID)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const financeResumenUltimosMovimientos = `-- name: FinanceResumenUltimosMovimientos :many
SELECT mc.id, mc.tipo::TEXT AS tipo, mc.monto, mc.concepto, mc.created_at,
       c.nombre AS caja_nombre
FROM movimientos_caja mc
JOIN cajas c ON c.id = mc.caja_id
WHERE mc.usuario_id = $1
ORDER BY mc.created_at DESC
LIMIT $2
`

type FinanceResumenUltimosMovimientosParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
}

type FinanceResumenUltimosMovimientosRow struct {
	ID         pgtype.UUID        `json:"id"`
	Tipo       string             `json:"tipo"`
	Monto      pgtype.Numeric     `json:"monto"`
	Concepto   string             `json:"concepto"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	CajaNombre string             `json:"caja_nombre"`
}

func (q *Queries) FinanceResumenUltimosMovimientos(ctx context.Context, arg FinanceResumenUltimosMovimientosParams) ([]FinanceResumenUltimosMovimientosRow, error) {
	rows, err := q.db.Query(ctx, financeResumenUltimosMovimientos, arg.UsuarioID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinanceResumenUltimosMovimientosRow
	for rows.Next() {
		var i FinanceResumenUltimosMovimientosRow
		if err := rows.Scan(
			&i.ID,
			&i.Tipo,
			&i.Monto,
			&i.Concepto,
			&i.CreatedAt,
			&i.CajaNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
