// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gastos.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGastos = `-- name: CountGastos :one
SELECT COUNT(*) FROM gastos
WHERE usuario_id = $1 AND active = TRUE
`

func (q *Queries) CountGastos(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGastos, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGastosByCategoria = `-- name: CountGastosByCategoria :one
SELECT COUNT(*) FROM gastos
WHERE usuario_id = $1 AND categoria = $2 AND active = TRUE
`

type CountGastosByCategoriaParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Categoria TipoGasto   `json:"categoria"`
}

func (q *Queries) CountGastosByCategoria(ctx context.Context, arg CountGastosByCategoriaParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGastosByCategoria, arg.UsuarioID, arg.Categoria)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGastosRecurrentes = `-- name: CountGastosRecurrentes :one
SELECT COUNT(*) FROM gastos_recurrentes
WHERE usuario_id = $1 AND activo = TRUE
`

func (q *Queries) CountGastosRecurrentes(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGastosRecurrentes, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGasto = `-- name: CreateGasto :one
INSERT INTO gastos (concepto, monto, categoria, fecha, comprobante, sucursal_id, usuario_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, concepto, monto, categoria, fecha, comprobante, sucursal_id, active, usuario_id, created_at, updated_at
`

type CreateGastoParams struct {
	Concepto    string         `json:"concepto"`
	Monto       pgtype.Numeric `json:"monto"`
	Categoria   TipoGasto      `json:"categoria"`
	Fecha       pgtype.Date    `json:"fecha"`
	Comprobante pgtype.Text    `json:"comprobante"`
	SucursalID  pgtype.UUID    `json:"sucursal_id"`
	UsuarioID   pgtype.UUID    `json:"usuario_id"`
}

func (q *Queries) CreateGasto(ctx context.Context, arg CreateGastoParams) (Gasto, error) {
	row := q.db.QueryRow(ctx, createGasto,
		arg.Concepto,
		arg.Monto,
		arg.Categoria,
		arg.Fecha,
		arg.Comprobante,
		arg.SucursalID,
		arg.UsuarioID,
	)
	var i Gasto
	err := row.Scan(
		&i.ID,
		&i.Concepto,
		&i.Monto,
		&i.Categoria,
		&i.Fecha,
		&i.Comprobante,
		&i.SucursalID,
		&i.Active,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGastoRecurrente = `-- name: CreateGastoRecurrente :one
INSERT INTO gastos_recurrentes (concepto, monto, categoria, frecuencia, proxima_fecha, sucursal_id, usuario_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, concepto, monto, categoria, frecuencia, proxima_fecha, activo, sucursal_id, usuario_id, created_at, updated_at
`

type CreateGastoRecurrenteParams struct {
	Concepto     string         `json:"concepto"`
	Monto        pgtype.Numeric `json:"monto"`
	Categoria    TipoGasto      `json:"categoria"`
	Frecuencia   string         `json:"frecuencia"`
	ProximaFecha pgtype.Date    `json:"proxima_fecha"`
	SucursalID   pgtype.UUID    `json:"sucursal_id"`
	UsuarioID    pgtype.UUID    `json:"usuario_id"`
}

func (q *Queries) CreateGastoRecurrente(ctx context.Context, arg CreateGastoRecurrenteParams) (GastosRecurrente, error) {
	row := q.db.QueryRow(ctx, createGastoRecurrente,
		arg.Concepto,
		arg.Monto,
		arg.Categoria,
		arg.Frecuencia,
		arg.ProximaFecha,
		arg.SucursalID,
		arg.UsuarioID,
	)
	var i GastosRecurrente
	err := row.Scan(
		&i.ID,
		&i.Concepto,
		&i.Monto,
		&i.Categoria,
		&i.Frecuencia,
		&i.ProximaFecha,
		&i.Activo,
		&i.SucursalID,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGastoByID = `-- name: GetGastoByID :one
SELECT id, concepto, monto, categoria, fecha, comprobante, sucursal_id, active, usuario_id, created_at, updated_at FROM gastos
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
`

type GetGastoByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) GetGastoByID(ctx context.Context, arg GetGastoByIDParams) (Gasto, error) {
	row := q.db.QueryRow(ctx, getGastoByID, arg.ID, arg.UsuarioID)
	var i Gasto
	err := row.Scan(
		&i.ID,
		&i.Concepto,
		&i.Monto,
		&i.Categoria,
		&i.Fecha,
		&i.Comprobante,
		&i.SucursalID,
		&i.Active,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGastoRecurrenteByID = `-- name: GetGastoRecurrenteByID :one
SELECT id, concepto, monto, categoria, frecuencia, proxima_fecha, activo, sucursal_id, usuario_id, created_at, updated_at FROM gastos_recurrentes
WHERE id = $1 AND usuario_id = $2 AND activo = TRUE
`

type GetGastoRecurrenteByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) GetGastoRecurrenteByID(ctx context.Context, arg GetGastoRecurrenteByIDParams) (GastosRecurrente, error) {
	row := q.db.QueryRow(ctx, getGastoRecurrenteByID, arg.ID, arg.UsuarioID)
	var i GastosRecurrente
	err := row.Scan(
		&i.ID,
		&i.Concepto,
		&i.Monto,
		&i.Categoria,
		&i.Frecuencia,
		&i.ProximaFecha,
		&i.Activo,
		&i.SucursalID,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGastos = `-- name: ListGastos :many
SELECT id, concepto, monto, categoria, fecha, comprobante, sucursal_id, active, usuario_id, created_at, updated_at FROM gastos
WHERE usuario_id = $1 AND active = TRUE
ORDER BY fecha DESC
LIMIT $2 OFFSET $3
`

type ListGastosParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListGastos(ctx context.Context, arg ListGastosParams) ([]Gasto, error) {
	rows, err := q.db.Query(ctx, listGastos, arg.UsuarioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Gasto
	for rows.Next() {
		var i Gasto
		if err := rows.Scan(
			&i.ID,
			&i.Concepto,
			&i.Monto,
			&i.Categoria,
			&i.Fecha,
			&i.Comprobante,
			&i.SucursalID,
			&i.Active,
			&i.UsuarioID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGastosByCategoria = `-- name: ListGastosByCategoria :many
SELECT id, concepto, monto, categoria, fecha, comprobante, sucursal_id, active, usuario_id, created_at, updated_at FROM gastos
WHERE usuario_id = $1 AND categoria = $2 AND active = TRUE
ORDER BY fecha DESC
LIMIT $3 OFFSET $4
`

type ListGastosByCategoriaParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Categoria TipoGasto   `json:"categoria"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListGastosByCategoria(ctx context.Context, arg ListGastosByCategoriaParams) ([]Gasto, error) {
	rows, err := q.db.Query(ctx, listGastosByCategoria,
		arg.UsuarioID,
		arg.Categoria,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Gasto
	for rows.Next() {
		var i Gasto
		if err := rows.Scan(
			&i.ID,
			&i.Concepto,
			&i.Monto,
			&i.Categoria,
			&i.Fecha,
			&i.Comprobante,
			&i.SucursalID,
			&i.Active,
			&i.UsuarioID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGastosRecurrentes = `-- name: ListGastosRecurrentes :many
SELECT id, concepto, monto, categoria, frecuencia, proxima_fecha, activo, sucursal_id, usuario_id, created_at, updated_at FROM gastos_recurrentes
WHERE usuario_id = $1 AND activo = TRUE
ORDER BY proxima_fecha
LIMIT $2 OFFSET $3
`

type ListGastosRecurrentesParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListGastosRecurrentes(ctx context.Context, arg ListGastosRecurrentesParams) ([]GastosRecurrente, error) {
	rows, err := q.db.Query(ctx, listGastosRecurrentes, arg.UsuarioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GastosRecurrente
	for rows.Next() {
		var i GastosRecurrente
		if err := rows.Scan(
			&i.ID,
			&i.Concepto,
			&i.Monto,
			&i.Categoria,
			&i.Frecuencia,
			&i.ProximaFecha,
			&i.Activo,
			&i.SucursalID,
			&i.UsuarioID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteGasto = `-- name: SoftDeleteGasto :exec
UPDATE gastos
SET active = FALSE, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2
`

type SoftDeleteGastoParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) SoftDeleteGasto(ctx context.Context, arg SoftDeleteGastoParams) error {
	_, err := q.db.Exec(ctx, softDeleteGasto, arg.ID, arg.UsuarioID)
	return err
}

const softDeleteGastoRecurrente = `-- name: SoftDeleteGastoRecurrente :exec
UPDATE gastos_recurrentes
SET activo = FALSE, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2
`

type SoftDeleteGastoRecurrenteParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) SoftDeleteGastoRecurrente(ctx context.Context, arg SoftDeleteGastoRecurrenteParams) error {
	_, err := q.db.Exec(ctx, softDeleteGastoRecurrente, arg.ID, arg.UsuarioID)
	return err
}

const updateGasto = `-- name: UpdateGasto :one
UPDATE gastos
SET concepto = $3, monto = $4, categoria = $5, fecha = $6, comprobante = $7, sucursal_id = $8, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
RETURNING id, concepto, monto, categoria, fecha, comprobante, sucursal_id, active, usuario_id, created_at, updated_at
`

type UpdateGastoParams struct {
	ID          pgtype.UUID    `json:"id"`
	UsuarioID   pgtype.UUID    `json:"usuario_id"`
	Concepto    string         `json:"concepto"`
	Monto       pgtype.Numeric `json:"monto"`
	Categoria   TipoGasto      `json:"categoria"`
	Fecha       pgtype.Date    `json:"fecha"`
	Comprobante pgtype.Text    `json:"comprobante"`
	SucursalID  pgtype.UUID    `json:"sucursal_id"`
}

func (q *Queries) UpdateGasto(ctx context.Context, arg UpdateGastoParams) (Gasto, error) {
	row := q.db.QueryRow(ctx, updateGasto,
		arg.ID,
		arg.UsuarioID,
		arg.Concepto,
		arg.Monto,
		arg.Categoria,
		arg.Fecha,
		arg.Comprobante,
		arg.SucursalID,
	)
	var i Gasto
	err := row.Scan(
		&i.ID,
		&i.Concepto,
		&i.Monto,
		&i.Categoria,
		&i.Fecha,
		&i.Comprobante,
		&i.SucursalID,
		&i.Active,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGastoRecurrente = `-- name: UpdateGastoRecurrente :one
UPDATE gastos_recurrentes
SET concepto = $3, monto = $4, categoria = $5, frecuencia = $6, proxima_fecha = $7, sucursal_id = $8, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND activo = TRUE
RETURNING id, concepto, monto, categoria, frecuencia, proxima_fecha, activo, sucursal_id, usuario_id, created_at, updated_at
`

type UpdateGastoRecurrenteParams struct {
	ID           pgtype.UUID    `json:"id"`
	UsuarioID    pgtype.UUID    `json:"usuario_id"`
	Concepto     string         `json:"concepto"`
	Monto        pgtype.Numeric `json:"monto"`
	Categoria    TipoGasto      `json:"categoria"`
	Frecuencia   string         `json:"frecuencia"`
	ProximaFecha pgtype.Date    `json:"proxima_fecha"`
	SucursalID   pgtype.UUID    `json:"sucursal_id"`
}

func (q *Queries) UpdateGastoRecurrente(ctx context.Context, arg UpdateGastoRecurrenteParams) (GastosRecurrente, error) {
	row := q.db.QueryRow(ctx, updateGastoRecurrente,
		arg.ID,
		arg.UsuarioID,
		arg.Concepto,
		arg.Monto,
		arg.Categoria,
		arg.Frecuencia,
		arg.ProximaFecha,
		arg.SucursalID,
	)
	var i GastosRecurrente
	err := row.Scan(
		&i.ID,
		&i.Concepto,
		&i.Monto,
		&i.Categoria,
		&i.Frecuencia,
		&i.ProximaFecha,
		&i.Activo,
		&i.SucursalID,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
