// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: historial_pedido.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHistorialPedido = `-- name: CreateHistorialPedido :one
INSERT INTO historial_pedido (
  pedido_id, estado_anterior, estado_nuevo, empleado_id, comentario
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, pedido_id, estado_anterior, estado_nuevo, empleado_id, comentario, created_at
`

type CreateHistorialPedidoParams struct {
	PedidoID       pgtype.UUID      `json:"pedido_id"`
	EstadoAnterior NullEstadoPedido `json:"estado_anterior"`
	EstadoNuevo    EstadoPedido     `json:"estado_nuevo"`
	EmpleadoID     pgtype.UUID      `json:"empleado_id"`
	Comentario     pgtype.Text      `json:"comentario"`
}

func (q *Queries) CreateHistorialPedido(ctx context.Context, arg CreateHistorialPedidoParams) (HistorialPedido, error) {
	row := q.db.QueryRow(ctx, createHistorialPedido,
		arg.PedidoID,
		arg.EstadoAnterior,
		arg.EstadoNuevo,
		arg.EmpleadoID,
		arg.Comentario,
	)
	var i HistorialPedido
	err := row.Scan(
		&i.ID,
		&i.PedidoID,
		&i.EstadoAnterior,
		&i.EstadoNuevo,
		&i.EmpleadoID,
		&i.Comentario,
		&i.CreatedAt,
	)
	return i, err
}

const listHistorialPedido = `-- name: ListHistorialPedido :many
SELECT h.id, h.pedido_id, h.estado_anterior, h.estado_nuevo, h.empleado_id, h.comentario, h.created_at,
       e.nombre AS empleado_nombre,
       e.apellido AS empleado_apellido
FROM historial_pedido h
LEFT JOIN empleados e ON e.id = h.empleado_id
WHERE h.pedido_id = $1
ORDER BY h.created_at ASC
`

type ListHistorialPedidoRow struct {
	ID               pgtype.UUID        `json:"id"`
	PedidoID         pgtype.UUID        `json:"pedido_id"`
	EstadoAnterior   NullEstadoPedido   `json:"estado_anterior"`
	EstadoNuevo      EstadoPedido       `json:"estado_nuevo"`
	EmpleadoID       pgtype.UUID        `json:"empleado_id"`
	Comentario       pgtype.Text        `json:"comentario"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	EmpleadoNombre   pgtype.Text        `json:"empleado_nombre"`
	EmpleadoApellido pgtype.Text        `json:"empleado_apellido"`
}

func (q *Queries) ListHistorialPedido(ctx context.Context, pedidoID pgtype.UUID) ([]ListHistorialPedidoRow, error) {
	rows, err := q.db.Query(ctx, listHistorialPedido, pedidoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHistorialPedidoRow
	for rows.Next() {
		var i ListHistorialPedidoRow
		if err := rows.Scan(
			&i.ID,
			&i.PedidoID,
			&i.EstadoAnterior,
			&i.EstadoNuevo,
			&i.EmpleadoID,
			&i.Comentario,
			&i.CreatedAt,
			&i.EmpleadoNombre,
			&i.EmpleadoApellido,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
