// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: impuestos_pedido.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createImpuestoPedido = `-- name: CreateImpuestoPedido :one
INSERT INTO impuestos_pedido (
  pedido_id, tipo, nombre, porcentaje, base_imponible, monto
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, pedido_id, tipo, nombre, porcentaje, base_imponible, monto
`

type CreateImpuestoPedidoParams struct {
	PedidoID      pgtype.UUID    `json:"pedido_id"`
	Tipo          TipoImpuesto   `json:"tipo"`
	Nombre        string         `json:"nombre"`
	Porcentaje    pgtype.Numeric `json:"porcentaje"`
	BaseImponible pgtype.Numeric `json:"base_imponible"`
	Monto         pgtype.Numeric `json:"monto"`
}

func (q *Queries) CreateImpuestoPedido(ctx context.Context, arg CreateImpuestoPedidoParams) (ImpuestosPedido, error) {
	row := q.db.QueryRow(ctx, createImpuestoPedido,
		arg.PedidoID,
		arg.Tipo,
		arg.Nombre,
		arg.Porcentaje,
		arg.BaseImponible,
		arg.Monto,
	)
	var i ImpuestosPedido
	err := row.Scan(
		&i.ID,
		&i.PedidoID,
		&i.Tipo,
		&i.Nombre,
		&i.Porcentaje,
		&i.BaseImponible,
		&i.Monto,
	)
	return i, err
}

const deleteImpuestosPedidoByPedido = `-- name: DeleteImpuestosPedidoByPedido :exec
DELETE FROM impuestos_pedido WHERE pedido_id = $1
`

func (q *Queries) DeleteImpuestosPedidoByPedido(ctx context.Context, pedidoID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteImpuestosPedidoByPedido, pedidoID)
	return err
}

const listImpuestosPedido = `-- name: ListImpuestosPedido :many
SELECT id, pedido_id, tipo, nombre, porcentaje, base_imponible, monto FROM impuestos_pedido
WHERE pedido_id = $1
ORDER BY tipo, nombre
`

func (q *Queries) ListImpuestosPedido(ctx context.Context, pedidoID pgtype.UUID) ([]ImpuestosPedido, error) {
	rows, err := q.db.Query(ctx, listImpuestosPedido, pedidoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImpuestosPedido
	for rows.Next() {
		var i ImpuestosPedido
		if err := rows.Scan(
			&i.ID,
			&i.PedidoID,
			&i.Tipo,
			&i.Nombre,
			&i.Porcentaje,
			&i.BaseImponible,
			&i.Monto,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
