// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CondicionIva string

const (
	CondicionIvaRESPONSABLEINSCRIPTO CondicionIva = "RESPONSABLE_INSCRIPTO"
	CondicionIvaMONOTRIBUTO          CondicionIva = "MONOTRIBUTO"
	CondicionIvaEXENTO               CondicionIva = "EXENTO"
	CondicionIvaNORESPONSABLE        CondicionIva = "NO_RESPONSABLE"
	CondicionIvaCONSUMIDORFINAL      CondicionIva = "CONSUMIDOR_FINAL"
)

func (e *CondicionIva) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CondicionIva(s)
	case string:
		*e = CondicionIva(s)
	default:
		return fmt.Errorf("unsupported scan type for CondicionIva: %T", src)
	}
	return nil
}

type NullCondicionIva struct {
	CondicionIva CondicionIva `json:"condicion_iva"`
	Valid        bool         `json:"valid"` // Valid is true if CondicionIva is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCondicionIva) Scan(value interface{}) error {
	if value == nil {
		ns.CondicionIva, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CondicionIva.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCondicionIva) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CondicionIva), nil
}

type CondicionPago string

const (
	CondicionPagoCONTADO         CondicionPago = "CONTADO"
	CondicionPagoCUENTACORRIENTE CondicionPago = "CUENTA_CORRIENTE"
	CondicionPagoCHEQUE          CondicionPago = "CHEQUE"
	CondicionPagoTRANSFERENCIA   CondicionPago = "TRANSFERENCIA"
	CondicionPagoOTRO            CondicionPago = "OTRO"
)

func (e *CondicionPago) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CondicionPago(s)
	case string:
		*e = CondicionPago(s)
	default:
		return fmt.Errorf("unsupported scan type for CondicionPago: %T", src)
	}
	return nil
}

type NullCondicionPago struct {
	CondicionPago CondicionPago `json:"condicion_pago"`
	Valid         bool          `json:"valid"` // Valid is true if CondicionPago is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCondicionPago) Scan(value interface{}) error {
	if value == nil {
		ns.CondicionPago, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CondicionPago.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCondicionPago) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CondicionPago), nil
}

type EstadoArqueo string

const (
	EstadoArqueoPENDIENTEREVISION EstadoArqueo = "PENDIENTE_REVISION"
	EstadoArqueoAPROBADO          EstadoArqueo = "APROBADO"
	EstadoArqueoRECHAZADO         EstadoArqueo = "RECHAZADO"
)

func (e *EstadoArqueo) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EstadoArqueo(s)
	case string:
		*e = EstadoArqueo(s)
	default:
		return fmt.Errorf("unsupported scan type for EstadoArqueo: %T", src)
	}
	return nil
}

type NullEstadoArqueo struct {
	EstadoArqueo EstadoArqueo `json:"estado_arqueo"`
	Valid        bool         `json:"valid"` // Valid is true if EstadoArqueo is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEstadoArqueo) Scan(value interface{}) error {
	if value == nil {
		ns.EstadoArqueo, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EstadoArqueo.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEstadoArqueo) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EstadoArqueo), nil
}

type EstadoCheque string

const (
	EstadoChequeRECIBIDO   EstadoCheque = "RECIBIDO"
	EstadoChequeDEPOSITADO EstadoCheque = "DEPOSITADO"
	EstadoChequeRECHAZADO  EstadoCheque = "RECHAZADO"
	EstadoChequeENDOSADO   EstadoCheque = "ENDOSADO"
	EstadoChequeCOBRADO    EstadoCheque = "COBRADO"
)

func (e *EstadoCheque) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EstadoCheque(s)
	case string:
		*e = EstadoCheque(s)
	default:
		return fmt.Errorf("unsupported scan type for EstadoCheque: %T", src)
	}
	return nil
}

type NullEstadoCheque struct {
	EstadoCheque EstadoCheque `json:"estado_cheque"`
	Valid        bool         `json:"valid"` // Valid is true if EstadoCheque is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEstadoCheque) Scan(value interface{}) error {
	if value == nil {
		ns.EstadoCheque, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EstadoCheque.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEstadoCheque) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EstadoCheque), nil
}

type EstadoComprobante string

const (
	EstadoComprobanteBORRADOR EstadoComprobante = "BORRADOR"
	EstadoComprobanteEMITIDO  EstadoComprobante = "EMITIDO"
	EstadoComprobanteANULADO  EstadoComprobante = "ANULADO"
)

func (e *EstadoComprobante) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EstadoComprobante(s)
	case string:
		*e = EstadoComprobante(s)
	default:
		return fmt.Errorf("unsupported scan type for EstadoComprobante: %T", src)
	}
	return nil
}

type NullEstadoComprobante struct {
	EstadoComprobante EstadoComprobante `json:"estado_comprobante"`
	Valid             bool              `json:"valid"` // Valid is true if EstadoComprobante is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEstadoComprobante) Scan(value interface{}) error {
	if value == nil {
		ns.EstadoComprobante, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EstadoComprobante.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEstadoComprobante) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EstadoComprobante), nil
}

type EstadoDeuda string

const (
	EstadoDeudaPENDIENTE EstadoDeuda = "PENDIENTE"
	EstadoDeudaPARCIAL   EstadoDeuda = "PARCIAL"
	EstadoDeudaPAGADA    EstadoDeuda = "PAGADA"
	EstadoDeudaVENCIDA   EstadoDeuda = "VENCIDA"
)

func (e *EstadoDeuda) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EstadoDeuda(s)
	case string:
		*e = EstadoDeuda(s)
	default:
		return fmt.Errorf("unsupported scan type for EstadoDeuda: %T", src)
	}
	return nil
}

type NullEstadoDeuda struct {
	EstadoDeuda EstadoDeuda `json:"estado_deuda"`
	Valid       bool        `json:"valid"` // Valid is true if EstadoDeuda is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEstadoDeuda) Scan(value interface{}) error {
	if value == nil {
		ns.EstadoDeuda, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EstadoDeuda.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEstadoDeuda) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EstadoDeuda), nil
}

type EstadoEmpleado string

const (
	EstadoEmpleadoACTIVO       EstadoEmpleado = "ACTIVO"
	EstadoEmpleadoLICENCIA     EstadoEmpleado = "LICENCIA"
	EstadoEmpleadoDESVINCULADO EstadoEmpleado = "DESVINCULADO"
)

func (e *EstadoEmpleado) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EstadoEmpleado(s)
	case string:
		*e = EstadoEmpleado(s)
	default:
		return fmt.Errorf("unsupported scan type for EstadoEmpleado: %T", src)
	}
	return nil
}

type NullEstadoEmpleado struct {
	EstadoEmpleado EstadoEmpleado `json:"estado_empleado"`
	Valid          bool           `json:"valid"` // Valid is true if EstadoEmpleado is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEstadoEmpleado) Scan(value interface{}) error {
	if value == nil {
		ns.EstadoEmpleado, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EstadoEmpleado.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEstadoEmpleado) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EstadoEmpleado), nil
}

type EstadoOrdenCompra string

const (
	EstadoOrdenCompraBORRADOR             EstadoOrdenCompra = "BORRADOR"
	EstadoOrdenCompraAPROBADA             EstadoOrdenCompra = "APROBADA"
	EstadoOrdenCompraENRECEPCION          EstadoOrdenCompra = "EN_RECEPCION"
	EstadoOrdenCompraRECIBIDA             EstadoOrdenCompra = "RECIBIDA"
	EstadoOrdenCompraRECIBIDAPARCIALMENTE EstadoOrdenCompra = "RECIBIDA_PARCIALMENTE"
	EstadoOrdenCompraCANCELADA            EstadoOrdenCompra = "CANCELADA"
)

func (e *EstadoOrdenCompra) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EstadoOrdenCompra(s)
	case string:
		*e = EstadoOrdenCompra(s)
	default:
		return fmt.Errorf("unsupported scan type for EstadoOrdenCompra: %T", src)
	}
	return nil
}

type NullEstadoOrdenCompra struct {
	EstadoOrdenCompra EstadoOrdenCompra `json:"estado_orden_compra"`
	Valid             bool              `json:"valid"` // Valid is true if EstadoOrdenCompra is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEstadoOrdenCompra) Scan(value interface{}) error {
	if value == nil {
		ns.EstadoOrdenCompra, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EstadoOrdenCompra.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEstadoOrdenCompra) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EstadoOrdenCompra), nil
}

type EstadoPedido string

const (
	EstadoPedidoPENDIENTEAPROBACION     EstadoPedido = "PENDIENTE_APROBACION"
	EstadoPedidoENEVALUACION            EstadoPedido = "EN_EVALUACION"
	EstadoPedidoAPROBADO                EstadoPedido = "APROBADO"
	EstadoPedidoAPROBADOREPARTIDOR      EstadoPedido = "APROBADO_REPARTIDOR"
	EstadoPedidoRECHAZADO               EstadoPedido = "RECHAZADO"
	EstadoPedidoENCONSOLIDACION         EstadoPedido = "EN_CONSOLIDACION"
	EstadoPedidoENPREPARACION           EstadoPedido = "EN_PREPARACION"
	EstadoPedidoLISTOPARAENVIO          EstadoPedido = "LISTO_PARA_ENVIO"
	EstadoPedidoENVIADO                 EstadoPedido = "ENVIADO"
	EstadoPedidoENTREGADO               EstadoPedido = "ENTREGADO"
	EstadoPedidoABASTECIDO              EstadoPedido = "ABASTECIDO"
	EstadoPedidoENTREGADOPARCIALMENTE   EstadoPedido = "ENTREGADO_PARCIALMENTE"
	EstadoPedidoCANCELADO               EstadoPedido = "CANCELADO"
	EstadoPedidoRECLAMADO               EstadoPedido = "RECLAMADO"
	EstadoPedidoPENDIENTEABASTECIMIENTO EstadoPedido = "PENDIENTE_ABASTECIMIENTO"
	EstadoPedidoNOENTREGADO             EstadoPedido = "NO_ENTREGADO"
)

func (e *EstadoPedido) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EstadoPedido(s)
	case string:
		*e = EstadoPedido(s)
	default:
		return fmt.Errorf("unsupported scan type for EstadoPedido: %T", src)
	}
	return nil
}

type NullEstadoPedido struct {
	EstadoPedido EstadoPedido `json:"estado_pedido"`
	Valid        bool         `json:"valid"` // Valid is true if EstadoPedido is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEstadoPedido) Scan(value interface{}) error {
	if value == nil {
		ns.EstadoPedido, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EstadoPedido.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEstadoPedido) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EstadoPedido), nil
}

type EstadoPresupuesto string

const (
	EstadoPresupuestoBORRADOR  EstadoPresupuesto = "BORRADOR"
	EstadoPresupuestoENVIADO   EstadoPresupuesto = "ENVIADO"
	EstadoPresupuestoAPROBADO  EstadoPresupuesto = "APROBADO"
	EstadoPresupuestoRECHAZADO EstadoPresupuesto = "RECHAZADO"
	EstadoPresupuestoVENCIDO   EstadoPresupuesto = "VENCIDO"
)

func (e *EstadoPresupuesto) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EstadoPresupuesto(s)
	case string:
		*e = EstadoPresupuesto(s)
	default:
		return fmt.Errorf("unsupported scan type for EstadoPresupuesto: %T", src)
	}
	return nil
}

type NullEstadoPresupuesto struct {
	EstadoPresupuesto EstadoPresupuesto `json:"estado_presupuesto"`
	Valid             bool              `json:"valid"` // Valid is true if EstadoPresupuesto is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEstadoPresupuesto) Scan(value interface{}) error {
	if value == nil {
		ns.EstadoPresupuesto, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EstadoPresupuesto.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEstadoPresupuesto) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EstadoPresupuesto), nil
}

type EstadoReparto string

const (
	EstadoRepartoPLANIFICADO EstadoReparto = "PLANIFICADO"
	EstadoRepartoENCURSO     EstadoReparto = "EN_CURSO"
	EstadoRepartoFINALIZADO  EstadoReparto = "FINALIZADO"
	EstadoRepartoCANCELADO   EstadoReparto = "CANCELADO"
)

func (e *EstadoReparto) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EstadoReparto(s)
	case string:
		*e = EstadoReparto(s)
	default:
		return fmt.Errorf("unsupported scan type for EstadoReparto: %T", src)
	}
	return nil
}

type NullEstadoReparto struct {
	EstadoReparto EstadoReparto `json:"estado_reparto"`
	Valid         bool          `json:"valid"` // Valid is true if EstadoReparto is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEstadoReparto) Scan(value interface{}) error {
	if value == nil {
		ns.EstadoReparto, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EstadoReparto.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEstadoReparto) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EstadoReparto), nil
}

type EstadoTransferencia string

const (
	EstadoTransferenciaPENDIENTE  EstadoTransferencia = "PENDIENTE"
	EstadoTransferenciaAPROBADA   EstadoTransferencia = "APROBADA"
	EstadoTransferenciaENTRANSITO EstadoTransferencia = "EN_TRANSITO"
	EstadoTransferenciaCOMPLETADA EstadoTransferencia = "COMPLETADA"
	EstadoTransferenciaCANCELADA  EstadoTransferencia = "CANCELADA"
)

func (e *EstadoTransferencia) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EstadoTransferencia(s)
	case string:
		*e = EstadoTransferencia(s)
	default:
		return fmt.Errorf("unsupported scan type for EstadoTransferencia: %T", src)
	}
	return nil
}

type NullEstadoTransferencia struct {
	EstadoTransferencia EstadoTransferencia `json:"estado_transferencia"`
	Valid               bool                `json:"valid"` // Valid is true if EstadoTransferencia is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEstadoTransferencia) Scan(value interface{}) error {
	if value == nil {
		ns.EstadoTransferencia, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EstadoTransferencia.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEstadoTransferencia) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EstadoTransferencia), nil
}

type LetraComprobante string

const (
	LetraComprobanteA LetraComprobante = "A"
	LetraComprobanteB LetraComprobante = "B"
	LetraComprobanteC LetraComprobante = "C"
	LetraComprobanteN LetraComprobante = "N"
	LetraComprobanteX LetraComprobante = "X"
)

func (e *LetraComprobante) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LetraComprobante(s)
	case string:
		*e = LetraComprobante(s)
	default:
		return fmt.Errorf("unsupported scan type for LetraComprobante: %T", src)
	}
	return nil
}

type NullLetraComprobante struct {
	LetraComprobante LetraComprobante `json:"letra_comprobante"`
	Valid            bool             `json:"valid"` // Valid is true if LetraComprobante is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLetraComprobante) Scan(value interface{}) error {
	if value == nil {
		ns.LetraComprobante, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LetraComprobante.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLetraComprobante) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LetraComprobante), nil
}

type Reputacion string

const (
	ReputacionDEUDOR    Reputacion = "DEUDOR"
	ReputacionBUENA     Reputacion = "BUENA"
	ReputacionCRITICA   Reputacion = "CRITICA"
	ReputacionEXCELENTE Reputacion = "EXCELENTE"
	ReputacionNORMAL    Reputacion = "NORMAL"
)

func (e *Reputacion) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Reputacion(s)
	case string:
		*e = Reputacion(s)
	default:
		return fmt.Errorf("unsupported scan type for Reputacion: %T", src)
	}
	return nil
}

type NullReputacion struct {
	Reputacion Reputacion `json:"reputacion"`
	Valid      bool       `json:"valid"` // Valid is true if Reputacion is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReputacion) Scan(value interface{}) error {
	if value == nil {
		ns.Reputacion, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Reputacion.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReputacion) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Reputacion), nil
}

type Rol string

const (
	RolADMIN         Rol = "ADMIN"
	RolSUPERVISOR    Rol = "SUPERVISOR"
	RolJEFEVENTAS    Rol = "JEFE_VENTAS"
	RolVENDEDOR      Rol = "VENDEDOR"
	RolVENDEDORCALLE Rol = "VENDEDOR_CALLE"
	RolDEPOSITO      Rol = "DEPOSITO"
	RolFINANZAS      Rol = "FINANZAS"
	RolREPARTIDOR    Rol = "REPARTIDOR"
)

func (e *Rol) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Rol(s)
	case string:
		*e = Rol(s)
	default:
		return fmt.Errorf("unsupported scan type for Rol: %T", src)
	}
	return nil
}

type NullRol struct {
	Rol   Rol  `json:"rol"`
	Valid bool `json:"valid"` // Valid is true if Rol is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRol) Scan(value interface{}) error {
	if value == nil {
		ns.Rol, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Rol.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRol) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Rol), nil
}

type TipoCaja string

const (
	TipoCajaEFECTIVO TipoCaja = "EFECTIVO"
	TipoCajaBANCO    TipoCaja = "BANCO"
)

func (e *TipoCaja) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TipoCaja(s)
	case string:
		*e = TipoCaja(s)
	default:
		return fmt.Errorf("unsupported scan type for TipoCaja: %T", src)
	}
	return nil
}

type NullTipoCaja struct {
	TipoCaja TipoCaja `json:"tipo_caja"`
	Valid    bool     `json:"valid"` // Valid is true if TipoCaja is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTipoCaja) Scan(value interface{}) error {
	if value == nil {
		ns.TipoCaja, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TipoCaja.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTipoCaja) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TipoCaja), nil
}

type TipoComision string

const (
	TipoComisionPORCENTAJE TipoComision = "PORCENTAJE"
	TipoComisionFIJO       TipoComision = "FIJO"
	TipoComisionESCALONADO TipoComision = "ESCALONADO"
)

func (e *TipoComision) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TipoComision(s)
	case string:
		*e = TipoComision(s)
	default:
		return fmt.Errorf("unsupported scan type for TipoComision: %T", src)
	}
	return nil
}

type NullTipoComision struct {
	TipoComision TipoComision `json:"tipo_comision"`
	Valid        bool         `json:"valid"` // Valid is true if TipoComision is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTipoComision) Scan(value interface{}) error {
	if value == nil {
		ns.TipoComision, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TipoComision.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTipoComision) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TipoComision), nil
}

type TipoComprobante string

const (
	TipoComprobanteFACTURA     TipoComprobante = "FACTURA"
	TipoComprobanteNOTACREDITO TipoComprobante = "NOTA_CREDITO"
	TipoComprobanteNOTADEBITO  TipoComprobante = "NOTA_DEBITO"
)

func (e *TipoComprobante) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TipoComprobante(s)
	case string:
		*e = TipoComprobante(s)
	default:
		return fmt.Errorf("unsupported scan type for TipoComprobante: %T", src)
	}
	return nil
}

type NullTipoComprobante struct {
	TipoComprobante TipoComprobante `json:"tipo_comprobante"`
	Valid           bool            `json:"valid"` // Valid is true if TipoComprobante is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTipoComprobante) Scan(value interface{}) error {
	if value == nil {
		ns.TipoComprobante, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TipoComprobante.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTipoComprobante) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TipoComprobante), nil
}

type TipoContrato string

const (
	TipoContratoRELACIONDEPENDENCIA TipoContrato = "RELACION_DEPENDENCIA"
	TipoContratoMONOTRIBUTO         TipoContrato = "MONOTRIBUTO"
	TipoContratoEVENTUAL            TipoContrato = "EVENTUAL"
)

func (e *TipoContrato) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TipoContrato(s)
	case string:
		*e = TipoContrato(s)
	default:
		return fmt.Errorf("unsupported scan type for TipoContrato: %T", src)
	}
	return nil
}

type NullTipoContrato struct {
	TipoContrato TipoContrato `json:"tipo_contrato"`
	Valid        bool         `json:"valid"` // Valid is true if TipoContrato is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTipoContrato) Scan(value interface{}) error {
	if value == nil {
		ns.TipoContrato, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TipoContrato.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTipoContrato) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TipoContrato), nil
}

type TipoEventoReparto string

const (
	TipoEventoRepartoLLEGADA        TipoEventoReparto = "LLEGADA"
	TipoEventoRepartoENTREGA        TipoEventoReparto = "ENTREGA"
	TipoEventoRepartoNOENTREGA      TipoEventoReparto = "NO_ENTREGA"
	TipoEventoRepartoENTREGAPARCIAL TipoEventoReparto = "ENTREGA_PARCIAL"
	TipoEventoRepartoCOBRO          TipoEventoReparto = "COBRO"
)

func (e *TipoEventoReparto) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TipoEventoReparto(s)
	case string:
		*e = TipoEventoReparto(s)
	default:
		return fmt.Errorf("unsupported scan type for TipoEventoReparto: %T", src)
	}
	return nil
}

type NullTipoEventoReparto struct {
	TipoEventoReparto TipoEventoReparto `json:"tipo_evento_reparto"`
	Valid             bool              `json:"valid"` // Valid is true if TipoEventoReparto is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTipoEventoReparto) Scan(value interface{}) error {
	if value == nil {
		ns.TipoEventoReparto, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TipoEventoReparto.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTipoEventoReparto) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TipoEventoReparto), nil
}

type TipoGasto string

const (
	TipoGastoOPERATIVO      TipoGasto = "OPERATIVO"
	TipoGastoADMINISTRATIVO TipoGasto = "ADMINISTRATIVO"
	TipoGastoLOGISTICA      TipoGasto = "LOGISTICA"
	TipoGastoCOMERCIAL      TipoGasto = "COMERCIAL"
	TipoGastoIMPOSITIVO     TipoGasto = "IMPOSITIVO"
)

func (e *TipoGasto) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TipoGasto(s)
	case string:
		*e = TipoGasto(s)
	default:
		return fmt.Errorf("unsupported scan type for TipoGasto: %T", src)
	}
	return nil
}

type NullTipoGasto struct {
	TipoGasto TipoGasto `json:"tipo_gasto"`
	Valid     bool      `json:"valid"` // Valid is true if TipoGasto is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTipoGasto) Scan(value interface{}) error {
	if value == nil {
		ns.TipoGasto, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TipoGasto.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTipoGasto) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TipoGasto), nil
}

type TipoImpuesto string

const (
	TipoImpuestoIVA            TipoImpuesto = "IVA"
	TipoImpuestoIIBB           TipoImpuesto = "IIBB"
	TipoImpuestoPERCEPCIONIVA  TipoImpuesto = "PERCEPCION_IVA"
	TipoImpuestoPERCEPCIONIIBB TipoImpuesto = "PERCEPCION_IIBB"
	TipoImpuestoOTRO           TipoImpuesto = "OTRO"
)

func (e *TipoImpuesto) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TipoImpuesto(s)
	case string:
		*e = TipoImpuesto(s)
	default:
		return fmt.Errorf("unsupported scan type for TipoImpuesto: %T", src)
	}
	return nil
}

type NullTipoImpuesto struct {
	TipoImpuesto TipoImpuesto `json:"tipo_impuesto"`
	Valid        bool         `json:"valid"` // Valid is true if TipoImpuesto is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTipoImpuesto) Scan(value interface{}) error {
	if value == nil {
		ns.TipoImpuesto, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TipoImpuesto.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTipoImpuesto) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TipoImpuesto), nil
}

type TipoMovimiento string

const (
	TipoMovimientoINGRESO TipoMovimiento = "INGRESO"
	TipoMovimientoEGRESO  TipoMovimiento = "EGRESO"
	TipoMovimientoAJUSTE  TipoMovimiento = "AJUSTE"
)

func (e *TipoMovimiento) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TipoMovimiento(s)
	case string:
		*e = TipoMovimiento(s)
	default:
		return fmt.Errorf("unsupported scan type for TipoMovimiento: %T", src)
	}
	return nil
}

type NullTipoMovimiento struct {
	TipoMovimiento TipoMovimiento `json:"tipo_movimiento"`
	Valid          bool           `json:"valid"` // Valid is true if TipoMovimiento is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTipoMovimiento) Scan(value interface{}) error {
	if value == nil {
		ns.TipoMovimiento, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TipoMovimiento.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTipoMovimiento) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TipoMovimiento), nil
}

type TipoMovimientoStock string

const (
	TipoMovimientoStockCOMPRA        TipoMovimientoStock = "COMPRA"
	TipoMovimientoStockVENTA         TipoMovimientoStock = "VENTA"
	TipoMovimientoStockAJUSTE        TipoMovimientoStock = "AJUSTE"
	TipoMovimientoStockTRANSFERENCIA TipoMovimientoStock = "TRANSFERENCIA"
	TipoMovimientoStockDEVOLUCION    TipoMovimientoStock = "DEVOLUCION"
	TipoMovimientoStockQUIEBRE       TipoMovimientoStock = "QUIEBRE"
)

func (e *TipoMovimientoStock) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TipoMovimientoStock(s)
	case string:
		*e = TipoMovimientoStock(s)
	default:
		return fmt.Errorf("unsupported scan type for TipoMovimientoStock: %T", src)
	}
	return nil
}

type NullTipoMovimientoStock struct {
	TipoMovimientoStock TipoMovimientoStock `json:"tipo_movimiento_stock"`
	Valid               bool                `json:"valid"` // Valid is true if TipoMovimientoStock is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTipoMovimientoStock) Scan(value interface{}) error {
	if value == nil {
		ns.TipoMovimientoStock, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TipoMovimientoStock.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTipoMovimientoStock) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TipoMovimientoStock), nil
}

type UnidadDeMedida string

const (
	UnidadDeMedidaKG     UnidadDeMedida = "KG"
	UnidadDeMedidaUNIDAD UnidadDeMedida = "UNIDAD"
	UnidadDeMedidaLITRO  UnidadDeMedida = "LITRO"
	UnidadDeMedidaMETRO  UnidadDeMedida = "METRO"
	UnidadDeMedidaCAJA   UnidadDeMedida = "CAJA"
	UnidadDeMedidaBOLSA  UnidadDeMedida = "BOLSA"
	UnidadDeMedidaPACK   UnidadDeMedida = "PACK"
)

func (e *UnidadDeMedida) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UnidadDeMedida(s)
	case string:
		*e = UnidadDeMedida(s)
	default:
		return fmt.Errorf("unsupported scan type for UnidadDeMedida: %T", src)
	}
	return nil
}

type NullUnidadDeMedida struct {
	UnidadDeMedida UnidadDeMedida `json:"unidad_de_medida"`
	Valid          bool           `json:"valid"` // Valid is true if UnidadDeMedida is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUnidadDeMedida) Scan(value interface{}) error {
	if value == nil {
		ns.UnidadDeMedida, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UnidadDeMedida.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUnidadDeMedida) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UnidadDeMedida), nil
}

type AlicuotaIva string

const (
	AlicuotaIva0         AlicuotaIva = "0"
	AlicuotaIva25        AlicuotaIva = "2.5"
	AlicuotaIva5         AlicuotaIva = "5"
	AlicuotaIva105       AlicuotaIva = "10.5"
	AlicuotaIva21        AlicuotaIva = "21"
	AlicuotaIva27        AlicuotaIva = "27"
	AlicuotaIvaEXENTO    AlicuotaIva = "EXENTO"
	AlicuotaIvaNOGRAVADO AlicuotaIva = "NO_GRAVADO"
)

func (e *AlicuotaIva) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlicuotaIva(s)
	case string:
		*e = AlicuotaIva(s)
	default:
		return fmt.Errorf("unsupported scan type for AlicuotaIva: %T", src)
	}
	return nil
}

type NullAlicuotaIva struct {
	AlicuotaIva AlicuotaIva `json:"alicuota_iva"`
	Valid       bool        `json:"valid"`
}

// Scan implements the Scanner interface.
func (ns *NullAlicuotaIva) Scan(value interface{}) error {
	if value == nil {
		ns.AlicuotaIva, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlicuotaIva.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlicuotaIva) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlicuotaIva), nil
}

type ArqueosCaja struct {
	ID            pgtype.UUID        `json:"id"`
	CajaID        pgtype.UUID        `json:"caja_id"`
	MontoSistema  pgtype.Numeric     `json:"monto_sistema"`
	MontoFisico   pgtype.Numeric     `json:"monto_fisico"`
	Diferencia    pgtype.Numeric     `json:"diferencia"`
	Estado        EstadoArqueo       `json:"estado"`
	Observaciones pgtype.Text        `json:"observaciones"`
	Desglose      []byte             `json:"desglose"`
	UsuarioID     pgtype.UUID        `json:"usuario_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Caja struct {
	ID         pgtype.UUID        `json:"id"`
	Nombre     string             `json:"nombre"`
	SucursalID pgtype.UUID        `json:"sucursal_id"`
	Tipo       TipoCaja           `json:"tipo"`
	Saldo      pgtype.Numeric     `json:"saldo"`
	Activa     bool               `json:"activa"`
	UsuarioID  pgtype.UUID        `json:"usuario_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type CatalogoProducto struct {
	ID         pgtype.UUID        `json:"id"`
	ProductoID pgtype.UUID        `json:"producto_id"`
	SucursalID pgtype.UUID        `json:"sucursal_id"`
	Precio     pgtype.Numeric     `json:"precio"`
	Stock      int32              `json:"stock"`
	Active     bool               `json:"active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type CategoriasProducto struct {
	ID          pgtype.UUID        `json:"id"`
	Nombre      string             `json:"nombre"`
	Descripcion pgtype.Text        `json:"descripcion"`
	FamiliaID   pgtype.UUID        `json:"familia_id"`
	UsuarioID   pgtype.UUID        `json:"usuario_id"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Cheque struct {
	ID                pgtype.UUID        `json:"id"`
	Numero            string             `json:"numero"`
	Monto             pgtype.Numeric     `json:"monto"`
	FechaEmision      pgtype.Date        `json:"fecha_emision"`
	FechaVencimiento  pgtype.Date        `json:"fecha_vencimiento"`
	Estado            EstadoCheque       `json:"estado"`
	Banco             pgtype.Text        `json:"banco"`
	Emisor            pgtype.Text        `json:"emisor"`
	Receptor          pgtype.Text        `json:"receptor"`
	EntidadBancariaID pgtype.UUID        `json:"entidad_bancaria_id"`
	SucursalID        pgtype.UUID        `json:"sucursal_id"`
	UsuarioID         pgtype.UUID        `json:"usuario_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Cliente struct {
	ID           pgtype.UUID        `json:"id"`
	Nombre       string             `json:"nombre"`
	Apellido     pgtype.Text        `json:"apellido"`
	RazonSocial  pgtype.Text        `json:"razon_social"`
	Cuit         pgtype.Text        `json:"cuit"`
	CondicionIva NullCondicionIva   `json:"condicion_iva"`
	Email        pgtype.Text        `json:"email"`
	Telefono     pgtype.Text        `json:"telefono"`
	Reputacion   Reputacion         `json:"reputacion"`
	UsuarioID    pgtype.UUID        `json:"usuario_id"`
	Active       bool               `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ComisionesVendedor struct {
	ID         pgtype.UUID        `json:"id"`
	EmpleadoID pgtype.UUID        `json:"empleado_id"`
	PedidoID   pgtype.UUID        `json:"pedido_id"`
	Monto      pgtype.Numeric     `json:"monto"`
	Porcentaje pgtype.Numeric     `json:"porcentaje"`
	Periodo    pgtype.Text        `json:"periodo"`
	UsuarioID  pgtype.UUID        `json:"usuario_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Comprobante struct {
	ID                  pgtype.UUID        `json:"id"`
	Tipo                TipoComprobante    `json:"tipo"`
	Letra               LetraComprobante   `json:"letra"`
	Numero              string             `json:"numero"`
	Estado              EstadoComprobante  `json:"estado"`
	PedidoID            pgtype.UUID        `json:"pedido_id"`
	ClienteID           pgtype.UUID        `json:"cliente_id"`
	SucursalID          pgtype.UUID        `json:"sucursal_id"`
	Subtotal            pgtype.Numeric     `json:"subtotal"`
	DescuentoMonto      pgtype.Numeric     `json:"descuento_monto"`
	BaseImponible       pgtype.Numeric     `json:"base_imponible"`
	TotalImpuestos      pgtype.Numeric     `json:"total_impuestos"`
	Total               pgtype.Numeric     `json:"total"`
	Impuestos           []byte             `json:"impuestos"`
	Cae                 pgtype.Text        `json:"cae"`
	FechaVencimientoCae pgtype.Date        `json:"fecha_vencimiento_cae"`
	FechaEmision        pgtype.Date        `json:"fecha_emision"`
	CondicionPago       CondicionPago      `json:"condicion_pago"`
	Observaciones       pgtype.Text        `json:"observaciones"`
	UsuarioID           pgtype.UUID        `json:"usuario_id"`
	Active              bool               `json:"active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type ConfiguracionComisione struct {
	ID             pgtype.UUID        `json:"id"`
	EmpleadoID     pgtype.UUID        `json:"empleado_id"`
	TipoComision   TipoComision       `json:"tipo_comision"`
	PorcentajeBase pgtype.Numeric     `json:"porcentaje_base"`
	Escalonamiento []byte             `json:"escalonamiento"`
	Activa         bool               `json:"activa"`
	UsuarioID      pgtype.UUID        `json:"usuario_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ConfiguracionImpuesto struct {
	ID                pgtype.UUID        `json:"id"`
	Nombre            string             `json:"nombre"`
	Tipo              TipoImpuesto       `json:"tipo"`
	Porcentaje        pgtype.Numeric     `json:"porcentaje"`
	AplicarPorDefecto bool               `json:"aplicar_por_defecto"`
	UsuarioID         pgtype.UUID        `json:"usuario_id"`
	Active            bool               `json:"active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type DetalleComprobante struct {
	ID                  pgtype.UUID    `json:"id"`
	ComprobanteID       pgtype.UUID    `json:"comprobante_id"`
	ProductoID          pgtype.UUID    `json:"producto_id"`
	ProductoNombre      string         `json:"producto_nombre"`
	ProductoCodigo      pgtype.Text    `json:"producto_codigo"`
	ProductoUnidad      string         `json:"producto_unidad"`
	Cantidad            pgtype.Numeric `json:"cantidad"`
	PrecioUnitario      pgtype.Numeric `json:"precio_unitario"`
	DescuentoPorcentaje pgtype.Numeric `json:"descuento_porcentaje"`
	DescuentoMonto      pgtype.Numeric `json:"descuento_monto"`
	Subtotal            pgtype.Numeric `json:"subtotal"`
	AlicuotaIva         NullAlicuotaIva `json:"alicuota_iva"`
	Orden               int32          `json:"orden"`
}

type DetalleOrdenesCompra struct {
	ID                  pgtype.UUID    `json:"id"`
	OrdenCompraID       pgtype.UUID    `json:"orden_compra_id"`
	ProductoID          pgtype.UUID    `json:"producto_id"`
	ProductoNombre      string         `json:"producto_nombre"`
	ProductoCodigo      pgtype.Text    `json:"producto_codigo"`
	Cantidad            pgtype.Numeric `json:"cantidad"`
	CantidadRecibida    pgtype.Numeric `json:"cantidad_recibida"`
	PrecioUnitario      pgtype.Numeric `json:"precio_unitario"`
	DescuentoPorcentaje pgtype.Numeric `json:"descuento_porcentaje"`
	DescuentoMonto      pgtype.Numeric `json:"descuento_monto"`
	Subtotal            pgtype.Numeric `json:"subtotal"`
	Orden               int32          `json:"orden"`
}

type DetallePedido struct {
	ID                  pgtype.UUID    `json:"id"`
	PedidoID            pgtype.UUID    `json:"pedido_id"`
	ProductoID          pgtype.UUID    `json:"producto_id"`
	ProductoNombre      string         `json:"producto_nombre"`
	ProductoCodigo      pgtype.Text    `json:"producto_codigo"`
	ProductoUnidad      string         `json:"producto_unidad"`
	Cantidad            pgtype.Numeric `json:"cantidad"`
	PrecioUnitario      pgtype.Numeric `json:"precio_unitario"`
	DescuentoPorcentaje pgtype.Numeric `json:"descuento_porcentaje"`
	DescuentoMonto      pgtype.Numeric `json:"descuento_monto"`
	Subtotal            pgtype.Numeric `json:"subtotal"`
	AlicuotaIva         NullAlicuotaIva `json:"alicuota_iva"`
	CantidadEntregada   pgtype.Numeric `json:"cantidad_entregada"`
	Orden               int32          `json:"orden"`
}

type Direccione struct {
	ID           pgtype.UUID        `json:"id"`
	ClienteID    pgtype.UUID        `json:"cliente_id"`
	Calle        string             `json:"calle"`
	Numero       pgtype.Text        `json:"numero"`
	Piso         pgtype.Text        `json:"piso"`
	Departamento pgtype.Text        `json:"departamento"`
	Ciudad       pgtype.Text        `json:"ciudad"`
	Provincia    pgtype.Text        `json:"provincia"`
	CodigoPostal pgtype.Text        `json:"codigo_postal"`
	Latitud      pgtype.Numeric     `json:"latitud"`
	Longitud     pgtype.Numeric     `json:"longitud"`
	Principal    bool               `json:"principal"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type EmailVerificationToken struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Used      bool               `json:"used"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Empleado struct {
	ID            pgtype.UUID        `json:"id"`
	Nombre        string             `json:"nombre"`
	Apellido      string             `json:"apellido"`
	Email         pgtype.Text        `json:"email"`
	Cuil          pgtype.Text        `json:"cuil"`
	AccessCode    pgtype.Text        `json:"access_code"`
	Rol           Rol                `json:"rol"`
	SucursalID    pgtype.UUID        `json:"sucursal_id"`
	UsuarioID     pgtype.UUID        `json:"usuario_id"`
	Active        bool               `json:"active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Telefono      pgtype.Text        `json:"telefono"`
	FechaIngreso  pgtype.Date        `json:"fecha_ingreso"`
	FechaEgreso   pgtype.Date        `json:"fecha_egreso"`
	Estado        EstadoEmpleado     `json:"estado"`
	Dni           pgtype.Text        `json:"dni"`
	Direccion     pgtype.Text        `json:"direccion"`
	SalarioBase   pgtype.Numeric     `json:"salario_base"`
	Observaciones pgtype.Text        `json:"observaciones"`
	TipoContrato  TipoContrato       `json:"tipo_contrato"`
	ObraSocial    pgtype.Text        `json:"obra_social"`
	NumeroLegajo  pgtype.Text        `json:"numero_legajo"`
	Banco         pgtype.Text        `json:"banco"`
	Cbu           pgtype.Text        `json:"cbu"`
}

type EmpleadoSucursale struct {
	ID         pgtype.UUID        `json:"id"`
	EmpleadoID pgtype.UUID        `json:"empleado_id"`
	SucursalID pgtype.UUID        `json:"sucursal_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type EntidadesBancaria struct {
	ID            pgtype.UUID        `json:"id"`
	Nombre        string             `json:"nombre"`
	SucursalBanco pgtype.Text        `json:"sucursal_banco"`
	NumeroCuenta  pgtype.Text        `json:"numero_cuenta"`
	Cbu           pgtype.Text        `json:"cbu"`
	Alias         pgtype.Text        `json:"alias"`
	SucursalID    pgtype.UUID        `json:"sucursal_id"`
	Active        bool               `json:"active"`
	UsuarioID     pgtype.UUID        `json:"usuario_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type EventosReparto struct {
	ID           pgtype.UUID        `json:"id"`
	RepartoID    pgtype.UUID        `json:"reparto_id"`
	PedidoID     pgtype.UUID        `json:"pedido_id"`
	Tipo         TipoEventoReparto  `json:"tipo"`
	Latitud      pgtype.Numeric     `json:"latitud"`
	Longitud     pgtype.Numeric     `json:"longitud"`
	Comentario   pgtype.Text        `json:"comentario"`
	MontoCobrado pgtype.Numeric     `json:"monto_cobrado"`
	EmpleadoID   pgtype.UUID        `json:"empleado_id"`
	FirmaURL     pgtype.Text        `json:"firma_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type FamiliasProducto struct {
	ID          pgtype.UUID        `json:"id"`
	Nombre      string             `json:"nombre"`
	Descripcion pgtype.Text        `json:"descripcion"`
	UsuarioID   pgtype.UUID        `json:"usuario_id"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Gasto struct {
	ID          pgtype.UUID        `json:"id"`
	Concepto    string             `json:"concepto"`
	Monto       pgtype.Numeric     `json:"monto"`
	Categoria   TipoGasto          `json:"categoria"`
	Fecha       pgtype.Date        `json:"fecha"`
	Comprobante pgtype.Text        `json:"comprobante"`
	SucursalID  pgtype.UUID        `json:"sucursal_id"`
	Active      bool               `json:"active"`
	UsuarioID   pgtype.UUID        `json:"usuario_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type GastosRecurrente struct {
	ID           pgtype.UUID        `json:"id"`
	Concepto     string             `json:"concepto"`
	Monto        pgtype.Numeric     `json:"monto"`
	Categoria    TipoGasto          `json:"categoria"`
	Frecuencia   string             `json:"frecuencia"`
	ProximaFecha pgtype.Date        `json:"proxima_fecha"`
	Activo       bool               `json:"activo"`
	SucursalID   pgtype.UUID        `json:"sucursal_id"`
	UsuarioID    pgtype.UUID        `json:"usuario_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type HistorialOrdenCompra struct {
	ID             pgtype.UUID           `json:"id"`
	OrdenCompraID  pgtype.UUID           `json:"orden_compra_id"`
	EstadoAnterior NullEstadoOrdenCompra `json:"estado_anterior"`
	EstadoNuevo    EstadoOrdenCompra     `json:"estado_nuevo"`
	Comentario     pgtype.Text           `json:"comentario"`
	EmpleadoID     pgtype.UUID           `json:"empleado_id"`
	CreatedAt      pgtype.Timestamptz    `json:"created_at"`
}

type HistorialPedido struct {
	ID             pgtype.UUID        `json:"id"`
	PedidoID       pgtype.UUID        `json:"pedido_id"`
	EstadoAnterior NullEstadoPedido   `json:"estado_anterior"`
	EstadoNuevo    EstadoPedido       `json:"estado_nuevo"`
	EmpleadoID     pgtype.UUID        `json:"empleado_id"`
	Comentario     pgtype.Text        `json:"comentario"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ImpuestosOrdenCompra struct {
	ID            pgtype.UUID    `json:"id"`
	OrdenCompraID pgtype.UUID    `json:"orden_compra_id"`
	Tipo          TipoImpuesto   `json:"tipo"`
	Nombre        string         `json:"nombre"`
	Porcentaje    pgtype.Numeric `json:"porcentaje"`
	BaseImponible pgtype.Numeric `json:"base_imponible"`
	Monto         pgtype.Numeric `json:"monto"`
}

type ImpuestosPedido struct {
	ID            pgtype.UUID    `json:"id"`
	PedidoID      pgtype.UUID    `json:"pedido_id"`
	Tipo          TipoImpuesto   `json:"tipo"`
	Nombre        string         `json:"nombre"`
	Porcentaje    pgtype.Numeric `json:"porcentaje"`
	BaseImponible pgtype.Numeric `json:"base_imponible"`
	Monto         pgtype.Numeric `json:"monto"`
}

type ItemsTransferencium struct {
	ID                 pgtype.UUID `json:"id"`
	TransferenciaID    pgtype.UUID `json:"transferencia_id"`
	ProductoID         pgtype.UUID `json:"producto_id"`
	ProductoNombre     string      `json:"producto_nombre"`
	ProductoCodigo     pgtype.Text `json:"producto_codigo"`
	CantidadSolicitada int32       `json:"cantidad_solicitada"`
	CantidadEnviada    int32       `json:"cantidad_enviada"`
	CantidadRecibida   int32       `json:"cantidad_recibida"`
}

type MetodosPago struct {
	ID                  pgtype.UUID        `json:"id"`
	Nombre              string             `json:"nombre"`
	Tipo                string             `json:"tipo"`
	ComisionPorcentaje  pgtype.Numeric     `json:"comision_porcentaje"`
	DescuentoPorcentaje pgtype.Numeric     `json:"descuento_porcentaje"`
	Activo              bool               `json:"activo"`
	SucursalID          pgtype.UUID        `json:"sucursal_id"`
	UsuarioID           pgtype.UUID        `json:"usuario_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type MovimientosCaja struct {
	ID             pgtype.UUID        `json:"id"`
	CajaID         pgtype.UUID        `json:"caja_id"`
	Tipo           TipoMovimiento     `json:"tipo"`
	Monto          pgtype.Numeric     `json:"monto"`
	Concepto       string             `json:"concepto"`
	ReferenciaID   pgtype.UUID        `json:"referencia_id"`
	ReferenciaTipo pgtype.Text        `json:"referencia_tipo"`
	UsuarioID      pgtype.UUID        `json:"usuario_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type MovimientosStock struct {
	ID             pgtype.UUID         `json:"id"`
	ProductoID     pgtype.UUID         `json:"producto_id"`
	SucursalID     pgtype.UUID         `json:"sucursal_id"`
	Tipo           TipoMovimientoStock `json:"tipo"`
	Cantidad       int32               `json:"cantidad"`
	StockAnterior  int32               `json:"stock_anterior"`
	StockNuevo     int32               `json:"stock_nuevo"`
	Motivo         pgtype.Text         `json:"motivo"`
	ReferenciaID   pgtype.UUID         `json:"referencia_id"`
	ReferenciaTipo pgtype.Text         `json:"referencia_tipo"`
	EmpleadoID     pgtype.UUID         `json:"empleado_id"`
	UsuarioID      pgtype.UUID         `json:"usuario_id"`
	CreatedAt      pgtype.Timestamptz  `json:"created_at"`
}

type OrdenesCompra struct {
	ID                   pgtype.UUID        `json:"id"`
	Numero               string             `json:"numero"`
	ProveedorID          pgtype.UUID        `json:"proveedor_id"`
	SucursalID           pgtype.UUID        `json:"sucursal_id"`
	Estado               EstadoOrdenCompra  `json:"estado"`
	CondicionPago        CondicionPago      `json:"condicion_pago"`
	FechaOrden           pgtype.Date        `json:"fecha_orden"`
	FechaEntregaEstimada pgtype.Date        `json:"fecha_entrega_estimada"`
	Subtotal             pgtype.Numeric     `json:"subtotal"`
	DescuentoPorcentaje  pgtype.Numeric     `json:"descuento_porcentaje"`
	DescuentoMonto       pgtype.Numeric     `json:"descuento_monto"`
	BaseImponible        pgtype.Numeric     `json:"base_imponible"`
	TotalImpuestos       pgtype.Numeric     `json:"total_impuestos"`
	Total                pgtype.Numeric     `json:"total"`
	Observaciones        pgtype.Text        `json:"observaciones"`
	UsuarioID            pgtype.UUID        `json:"usuario_id"`
	Active               bool               `json:"active"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type PasswordResetToken struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Used      bool               `json:"used"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Pedido struct {
	ID                    pgtype.UUID        `json:"id"`
	Numero                string             `json:"numero"`
	ClienteID             pgtype.UUID        `json:"cliente_id"`
	DireccionID           pgtype.UUID        `json:"direccion_id"`
	SucursalID            pgtype.UUID        `json:"sucursal_id"`
	EmpleadoID            pgtype.UUID        `json:"empleado_id"`
	Estado                EstadoPedido       `json:"estado"`
	CondicionPago         CondicionPago      `json:"condicion_pago"`
	FechaPedido           pgtype.Timestamptz `json:"fecha_pedido"`
	FechaEntregaEstimada  pgtype.Date        `json:"fecha_entrega_estimada"`
	FechaEntregaReal      pgtype.Timestamptz `json:"fecha_entrega_real"`
	Subtotal              pgtype.Numeric     `json:"subtotal"`
	DescuentoPorcentaje   pgtype.Numeric     `json:"descuento_porcentaje"`
	DescuentoMonto        pgtype.Numeric     `json:"descuento_monto"`
	BaseImponible         pgtype.Numeric     `json:"base_imponible"`
	TotalImpuestos        pgtype.Numeric     `json:"total_impuestos"`
	Total                 pgtype.Numeric     `json:"total"`
	Observaciones         pgtype.Text        `json:"observaciones"`
	ObservacionesInternas pgtype.Text        `json:"observaciones_internas"`
	UsuarioID             pgtype.UUID        `json:"usuario_id"`
	Active                bool               `json:"active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type PermissionOverride struct {
	ID         pgtype.UUID        `json:"id"`
	Rol        Rol                `json:"rol"`
	Permission string             `json:"permission"`
	Granted    bool               `json:"granted"`
	UsuarioID  pgtype.UUID        `json:"usuario_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Presupuesto struct {
	ID             pgtype.UUID        `json:"id"`
	Nombre         string             `json:"nombre"`
	MontoAsignado  pgtype.Numeric     `json:"monto_asignado"`
	MontoUtilizado pgtype.Numeric     `json:"monto_utilizado"`
	Periodo        pgtype.Text        `json:"periodo"`
	FechaInicio    pgtype.Date        `json:"fecha_inicio"`
	FechaFin       pgtype.Date        `json:"fecha_fin"`
	Estado         EstadoPresupuesto  `json:"estado"`
	SucursalID     pgtype.UUID        `json:"sucursal_id"`
	Active         bool               `json:"active"`
	UsuarioID      pgtype.UUID        `json:"usuario_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Producto struct {
	ID          pgtype.UUID        `json:"id"`
	Codigo      pgtype.Text        `json:"codigo"`
	Nombre      string             `json:"nombre"`
	Descripcion pgtype.Text        `json:"descripcion"`
	PrecioBase  pgtype.Numeric     `json:"precio_base"`
	Unidad      UnidadDeMedida     `json:"unidad"`
	CategoriaID pgtype.UUID        `json:"categoria_id"`
	AlicuotaIva AlicuotaIva        `json:"alicuota_iva"`
	UsuarioID   pgtype.UUID        `json:"usuario_id"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Proveedore struct {
	ID           pgtype.UUID        `json:"id"`
	Nombre       string             `json:"nombre"`
	Cuit         pgtype.Text        `json:"cuit"`
	CondicionIva NullCondicionIva   `json:"condicion_iva"`
	Email        pgtype.Text        `json:"email"`
	Telefono     pgtype.Text        `json:"telefono"`
	Direccion    pgtype.Text        `json:"direccion"`
	Contacto     pgtype.Text        `json:"contacto"`
	Banco        pgtype.Text        `json:"banco"`
	Cbu          pgtype.Text        `json:"cbu"`
	Alias        pgtype.Text        `json:"alias"`
	Notas        pgtype.Text        `json:"notas"`
	UsuarioID    pgtype.UUID        `json:"usuario_id"`
	Active       bool               `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UsuarioID pgtype.UUID        `json:"usuario_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Revoked   bool               `json:"revoked"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Reparto struct {
	ID            pgtype.UUID        `json:"id"`
	Numero        string             `json:"numero"`
	Fecha         pgtype.Date        `json:"fecha"`
	Estado        EstadoReparto      `json:"estado"`
	EmpleadoID    pgtype.UUID        `json:"empleado_id"`
	VehiculoID    pgtype.UUID        `json:"vehiculo_id"`
	ZonaID        pgtype.UUID        `json:"zona_id"`
	SucursalID    pgtype.UUID        `json:"sucursal_id"`
	HoraSalida    pgtype.Timestamptz `json:"hora_salida"`
	HoraRegreso   pgtype.Timestamptz `json:"hora_regreso"`
	KmInicio      pgtype.Numeric     `json:"km_inicio"`
	KmFin         pgtype.Numeric     `json:"km_fin"`
	Observaciones pgtype.Text        `json:"observaciones"`
	UsuarioID     pgtype.UUID        `json:"usuario_id"`
	Active        bool               `json:"active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type RepartoPedido struct {
	ID        pgtype.UUID `json:"id"`
	RepartoID pgtype.UUID `json:"reparto_id"`
	PedidoID  pgtype.UUID `json:"pedido_id"`
	Orden     int32       `json:"orden"`
}

type Sucursale struct {
	ID        pgtype.UUID        `json:"id"`
	Nombre    string             `json:"nombre"`
	Direccion pgtype.Text        `json:"direccion"`
	Telefono  pgtype.Text        `json:"telefono"`
	UsuarioID pgtype.UUID        `json:"usuario_id"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TransferenciasSucursal struct {
	ID                pgtype.UUID         `json:"id"`
	Numero            string              `json:"numero"`
	SucursalOrigenID  pgtype.UUID         `json:"sucursal_origen_id"`
	SucursalDestinoID pgtype.UUID         `json:"sucursal_destino_id"`
	Estado            EstadoTransferencia `json:"estado"`
	FechaSolicitud    pgtype.Timestamptz  `json:"fecha_solicitud"`
	FechaAprobacion   pgtype.Timestamptz  `json:"fecha_aprobacion"`
	FechaEnvio        pgtype.Timestamptz  `json:"fecha_envio"`
	FechaRecepcion    pgtype.Timestamptz  `json:"fecha_recepcion"`
	Observaciones     pgtype.Text         `json:"observaciones"`
	AprobadoPor       pgtype.UUID         `json:"aprobado_por"`
	SolicitadoPor     pgtype.UUID         `json:"solicitado_por"`
	UsuarioID         pgtype.UUID         `json:"usuario_id"`
	Active            bool                `json:"active"`
	CreatedAt         pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz  `json:"updated_at"`
}

type UserSetting struct {
	ID              pgtype.UUID        `json:"id"`
	UsuarioID       pgtype.UUID        `json:"usuario_id"`
	DashboardLayout []byte             `json:"dashboard_layout"`
	ApiKey          pgtype.Text        `json:"api_key"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Usuario struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	Nombre        string             `json:"nombre"`
	Apellido      string             `json:"apellido"`
	Rol           Rol                `json:"rol"`
	EmailVerified bool               `json:"email_verified"`
	Active        bool               `json:"active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Vehiculo struct {
	ID               pgtype.UUID        `json:"id"`
	Marca            string             `json:"marca"`
	Modelo           string             `json:"modelo"`
	Patente          string             `json:"patente"`
	Anio             pgtype.Int4        `json:"anio"`
	CapacidadKg      pgtype.Numeric     `json:"capacidad_kg"`
	CapacidadVolumen pgtype.Numeric     `json:"capacidad_volumen"`
	SucursalID       pgtype.UUID        `json:"sucursal_id"`
	UsuarioID        pgtype.UUID        `json:"usuario_id"`
	Active           bool               `json:"active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Zona struct {
	ID          pgtype.UUID        `json:"id"`
	Nombre      string             `json:"nombre"`
	Descripcion pgtype.Text        `json:"descripcion"`
	SucursalID  pgtype.UUID        `json:"sucursal_id"`
	UsuarioID   pgtype.UUID        `json:"usuario_id"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// --- Missing model types (pending sqlc regen) ---

type Ruta struct {
	ID                 pgtype.UUID        `json:"id"`
	Nombre             string             `json:"nombre"`
	ZonaID             pgtype.UUID        `json:"zona_id"`
	VehiculoID         pgtype.UUID        `json:"vehiculo_id"`
	DiaSemana          pgtype.Int4        `json:"dia_semana"`
	HoraSalidaEstimada pgtype.Text        `json:"hora_salida_estimada"`
	Notas              pgtype.Text        `json:"notas"`
	SucursalID         pgtype.UUID        `json:"sucursal_id"`
	UsuarioID          pgtype.UUID        `json:"usuario_id"`
	Active             bool               `json:"active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type RutaParada struct {
	ID                    pgtype.UUID `json:"id"`
	RutaID                pgtype.UUID `json:"ruta_id"`
	ClienteID             pgtype.UUID `json:"cliente_id"`
	DireccionID           pgtype.UUID `json:"direccion_id"`
	Orden                 int32       `json:"orden"`
	TiempoEstimadoMinutos int32      `json:"tiempo_estimado_minutos"`
	Notas                 pgtype.Text `json:"notas"`
}

type Task struct {
	ID          pgtype.UUID        `json:"id"`
	Titulo      string             `json:"titulo"`
	Descripcion pgtype.Text        `json:"descripcion"`
	Prioridad   TaskPriority       `json:"prioridad"`
	Estado      TaskStatus         `json:"estado"`
	AsignadoA   pgtype.UUID        `json:"asignado_a"`
	FechaLimite pgtype.Date        `json:"fecha_limite"`
	UsuarioID   pgtype.UUID        `json:"usuario_id"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AfipConfig struct {
	ID              pgtype.UUID        `json:"id"`
	SucursalID      pgtype.UUID        `json:"sucursal_id"`
	Cuit            string             `json:"cuit"`
	PuntoVenta      int32              `json:"punto_venta"`
	CertificadoPem  pgtype.Text        `json:"certificado_pem"`
	ClavePrivadaPem pgtype.Text        `json:"clave_privada_pem"`
	Modo            string             `json:"modo"`
	Activo          bool               `json:"activo"`
	Token           pgtype.Text        `json:"token"`
	Sign            pgtype.Text        `json:"sign"`
	TokenExpiracion pgtype.Timestamptz `json:"token_expiracion"`
	UsuarioID       pgtype.UUID        `json:"usuario_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CategoriaCliente struct {
	ID                  pgtype.UUID        `json:"id"`
	Nombre              string             `json:"nombre"`
	Descripcion         pgtype.Text        `json:"descripcion"`
	DescuentoPorcentaje pgtype.Numeric     `json:"descuento_porcentaje"`
	UsuarioID           pgtype.UUID        `json:"usuario_id"`
	Active              bool               `json:"active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type Promocion struct {
	ID             pgtype.UUID        `json:"id"`
	Nombre         string             `json:"nombre"`
	Tipo           TipoPromocion      `json:"tipo"`
	Valor          pgtype.Numeric     `json:"valor"`
	CantidadMinima pgtype.Int4        `json:"cantidad_minima"`
	ProductoID     pgtype.UUID        `json:"producto_id"`
	CategoriaID    pgtype.UUID        `json:"categoria_id"`
	FechaInicio    pgtype.Date        `json:"fecha_inicio"`
	FechaFin       pgtype.Date        `json:"fecha_fin"`
	Activa         bool               `json:"activa"`
	SucursalID     pgtype.UUID        `json:"sucursal_id"`
	UsuarioID      pgtype.UUID        `json:"usuario_id"`
	Active         bool               `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ExtractosBancario struct {
	ID                pgtype.UUID        `json:"id"`
	EntidadBancariaID pgtype.UUID        `json:"entidad_bancaria_id"`
	FechaDesde        pgtype.Date        `json:"fecha_desde"`
	FechaHasta        pgtype.Date        `json:"fecha_hasta"`
	ArchivoNombre     pgtype.Text        `json:"archivo_nombre"`
	UsuarioID         pgtype.UUID        `json:"usuario_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type MovimientosBancario struct {
	ID                 pgtype.UUID        `json:"id"`
	ExtractoID         pgtype.UUID        `json:"extracto_id"`
	Fecha              pgtype.Date        `json:"fecha"`
	Descripcion        string             `json:"descripcion"`
	Monto              pgtype.Numeric     `json:"monto"`
	Referencia         pgtype.Text        `json:"referencia"`
	EstadoConciliacion EstadoConciliacion `json:"estado_conciliacion"`
	MovimientoCajaID   pgtype.UUID        `json:"movimiento_caja_id"`
	UsuarioID          pgtype.UUID        `json:"usuario_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

// --- Missing enum types (pending sqlc regen) ---

type AfipEstado string

func (e *AfipEstado) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AfipEstado(s)
	case string:
		*e = AfipEstado(s)
	default:
		return fmt.Errorf("unsupported scan type for AfipEstado: %T", src)
	}
	return nil
}

type NullAfipEstado struct {
	AfipEstado AfipEstado `json:"afip_estado"`
	Valid      bool       `json:"valid"`
}

func (ns *NullAfipEstado) Scan(value interface{}) error {
	if value == nil {
		ns.AfipEstado, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AfipEstado.Scan(value)
}

func (ns NullAfipEstado) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AfipEstado), nil
}

type TipoPromocion string

func (e *TipoPromocion) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TipoPromocion(s)
	case string:
		*e = TipoPromocion(s)
	default:
		return fmt.Errorf("unsupported scan type for TipoPromocion: %T", src)
	}
	return nil
}

type NullTipoPromocion struct {
	TipoPromocion TipoPromocion `json:"tipo_promocion"`
	Valid         bool          `json:"valid"`
}

func (ns *NullTipoPromocion) Scan(value interface{}) error {
	if value == nil {
		ns.TipoPromocion, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TipoPromocion.Scan(value)
}

func (ns NullTipoPromocion) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TipoPromocion), nil
}

type EstadoConciliacion string

const (
	EstadoConciliacionPENDIENTE  EstadoConciliacion = "PENDIENTE"
	EstadoConciliacionCONCILIADO EstadoConciliacion = "CONCILIADO"
	EstadoConciliacionDESCARTADO EstadoConciliacion = "DESCARTADO"
)

func (e *EstadoConciliacion) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EstadoConciliacion(s)
	case string:
		*e = EstadoConciliacion(s)
	default:
		return fmt.Errorf("unsupported scan type for EstadoConciliacion: %T", src)
	}
	return nil
}

type NullEstadoConciliacion struct {
	EstadoConciliacion EstadoConciliacion `json:"estado_conciliacion"`
	Valid              bool               `json:"valid"`
}

func (ns *NullEstadoConciliacion) Scan(value interface{}) error {
	if value == nil {
		ns.EstadoConciliacion, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EstadoConciliacion.Scan(value)
}

func (ns NullEstadoConciliacion) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EstadoConciliacion), nil
}

type TaskPriority string

func (e *TaskPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskPriority(s)
	case string:
		*e = TaskPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskPriority: %T", src)
	}
	return nil
}

type NullTaskPriority struct {
	TaskPriority TaskPriority `json:"task_priority"`
	Valid        bool         `json:"valid"`
}

func (ns *NullTaskPriority) Scan(value interface{}) error {
	if value == nil {
		ns.TaskPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskPriority.Scan(value)
}

func (ns NullTaskPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskPriority), nil
}

type TaskStatus string

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"`
}

func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}
