// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movimientos_stock.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMovimientosStock = `-- name: CountMovimientosStock :one
SELECT COUNT(*) FROM movimientos_stock
WHERE usuario_id = $1
`

func (q *Queries) CountMovimientosStock(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMovimientosStock, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMovimientosStockByProducto = `-- name: CountMovimientosStockByProducto :one
SELECT COUNT(*) FROM movimientos_stock
WHERE usuario_id = $1 AND producto_id = $2
`

type CountMovimientosStockByProductoParams struct {
	UsuarioID  pgtype.UUID `json:"usuario_id"`
	ProductoID pgtype.UUID `json:"producto_id"`
}

func (q *Queries) CountMovimientosStockByProducto(ctx context.Context, arg CountMovimientosStockByProductoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMovimientosStockByProducto, arg.UsuarioID, arg.ProductoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMovimientosStockBySucursal = `-- name: CountMovimientosStockBySucursal :one
SELECT COUNT(*) FROM movimientos_stock
WHERE usuario_id = $1 AND sucursal_id = $2
`

type CountMovimientosStockBySucursalParams struct {
	UsuarioID  pgtype.UUID `json:"usuario_id"`
	SucursalID pgtype.UUID `json:"sucursal_id"`
}

func (q *Queries) CountMovimientosStockBySucursal(ctx context.Context, arg CountMovimientosStockBySucursalParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMovimientosStockBySucursal, arg.UsuarioID, arg.SucursalID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMovimientosStockByTipo = `-- name: CountMovimientosStockByTipo :one
SELECT COUNT(*) FROM movimientos_stock
WHERE usuario_id = $1 AND tipo = $2
`

type CountMovimientosStockByTipoParams struct {
	UsuarioID pgtype.UUID         `json:"usuario_id"`
	Tipo      TipoMovimientoStock `json:"tipo"`
}

func (q *Queries) CountMovimientosStockByTipo(ctx context.Context, arg CountMovimientosStockByTipoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMovimientosStockByTipo, arg.UsuarioID, arg.Tipo)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMovimientosStockFiltered = `-- name: CountMovimientosStockFiltered :one
SELECT COUNT(*) FROM movimientos_stock ms
WHERE ms.usuario_id = $1
  AND ($2::uuid IS NULL OR ms.producto_id = $2)
  AND ($3::uuid IS NULL OR ms.sucursal_id = $3)
  AND ($4::text IS NULL OR $4::text = '' OR ms.tipo::text = $4)
  AND ($5::timestamptz IS NULL OR ms.created_at >= $5)
  AND ($6::timestamptz IS NULL OR ms.created_at <= $6)
`

type CountMovimientosStockFilteredParams struct {
	UsuarioID  pgtype.UUID        `json:"usuario_id"`
	ProductoID pgtype.UUID        `json:"producto_id"`
	SucursalID pgtype.UUID        `json:"sucursal_id"`
	Tipo       pgtype.Text        `json:"tipo"`
	FechaDesde pgtype.Timestamptz `json:"fecha_desde"`
	FechaHasta pgtype.Timestamptz `json:"fecha_hasta"`
}

func (q *Queries) CountMovimientosStockFiltered(ctx context.Context, arg CountMovimientosStockFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMovimientosStockFiltered,
		arg.UsuarioID,
		arg.ProductoID,
		arg.SucursalID,
		arg.Tipo,
		arg.FechaDesde,
		arg.FechaHasta,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMovimientoStock = `-- name: CreateMovimientoStock :one
INSERT INTO movimientos_stock (
    producto_id, sucursal_id, tipo, cantidad, stock_anterior, stock_nuevo,
    motivo, referencia_id, referencia_tipo, empleado_id, usuario_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, producto_id, sucursal_id, tipo, cantidad, stock_anterior, stock_nuevo, motivo, referencia_id, referencia_tipo, empleado_id, usuario_id, created_at
`

type CreateMovimientoStockParams struct {
	ProductoID     pgtype.UUID         `json:"producto_id"`
	SucursalID     pgtype.UUID         `json:"sucursal_id"`
	Tipo           TipoMovimientoStock `json:"tipo"`
	Cantidad       int32               `json:"cantidad"`
	StockAnterior  int32               `json:"stock_anterior"`
	StockNuevo     int32               `json:"stock_nuevo"`
	Motivo         pgtype.Text         `json:"motivo"`
	ReferenciaID   pgtype.UUID         `json:"referencia_id"`
	ReferenciaTipo pgtype.Text         `json:"referencia_tipo"`
	EmpleadoID     pgtype.UUID         `json:"empleado_id"`
	UsuarioID      pgtype.UUID         `json:"usuario_id"`
}

func (q *Queries) CreateMovimientoStock(ctx context.Context, arg CreateMovimientoStockParams) (MovimientosStock, error) {
	row := q.db.QueryRow(ctx, createMovimientoStock,
		arg.ProductoID,
		arg.SucursalID,
		arg.Tipo,
		arg.Cantidad,
		arg.StockAnterior,
		arg.StockNuevo,
		arg.Motivo,
		arg.ReferenciaID,
		arg.ReferenciaTipo,
		arg.EmpleadoID,
		arg.UsuarioID,
	)
	var i MovimientosStock
	err := row.Scan(
		&i.ID,
		&i.ProductoID,
		&i.SucursalID,
		&i.Tipo,
		&i.Cantidad,
		&i.StockAnterior,
		&i.StockNuevo,
		&i.Motivo,
		&i.ReferenciaID,
		&i.ReferenciaTipo,
		&i.EmpleadoID,
		&i.UsuarioID,
		&i.CreatedAt,
	)
	return i, err
}

const listMovimientosStock = `-- name: ListMovimientosStock :many
SELECT ms.id, ms.producto_id, ms.sucursal_id, ms.tipo, ms.cantidad, ms.stock_anterior, ms.stock_nuevo, ms.motivo, ms.referencia_id, ms.referencia_tipo, ms.empleado_id, ms.usuario_id, ms.created_at,
       p.nombre AS producto_nombre,
       p.codigo AS producto_codigo,
       s.nombre AS sucursal_nombre
FROM movimientos_stock ms
JOIN productos p ON p.id = ms.producto_id
JOIN sucursales s ON s.id = ms.sucursal_id
WHERE ms.usuario_id = $1
ORDER BY ms.created_at DESC
LIMIT $2 OFFSET $3
`

type ListMovimientosStockParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListMovimientosStockRow struct {
	ID             pgtype.UUID         `json:"id"`
	ProductoID     pgtype.UUID         `json:"producto_id"`
	SucursalID     pgtype.UUID         `json:"sucursal_id"`
	Tipo           TipoMovimientoStock `json:"tipo"`
	Cantidad       int32               `json:"cantidad"`
	StockAnterior  int32               `json:"stock_anterior"`
	StockNuevo     int32               `json:"stock_nuevo"`
	Motivo         pgtype.Text         `json:"motivo"`
	ReferenciaID   pgtype.UUID         `json:"referencia_id"`
	ReferenciaTipo pgtype.Text         `json:"referencia_tipo"`
	EmpleadoID     pgtype.UUID         `json:"empleado_id"`
	UsuarioID      pgtype.UUID         `json:"usuario_id"`
	CreatedAt      pgtype.Timestamptz  `json:"created_at"`
	ProductoNombre string              `json:"producto_nombre"`
	ProductoCodigo pgtype.Text         `json:"producto_codigo"`
	SucursalNombre string              `json:"sucursal_nombre"`
}

func (q *Queries) ListMovimientosStock(ctx context.Context, arg ListMovimientosStockParams) ([]ListMovimientosStockRow, error) {
	rows, err := q.db.Query(ctx, listMovimientosStock, arg.UsuarioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMovimientosStockRow
	for rows.Next() {
		var i ListMovimientosStockRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductoID,
			&i.SucursalID,
			&i.Tipo,
			&i.Cantidad,
			&i.StockAnterior,
			&i.StockNuevo,
			&i.Motivo,
			&i.ReferenciaID,
			&i.ReferenciaTipo,
			&i.EmpleadoID,
			&i.UsuarioID,
			&i.CreatedAt,
			&i.ProductoNombre,
			&i.ProductoCodigo,
			&i.SucursalNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovimientosStockByProducto = `-- name: ListMovimientosStockByProducto :many
SELECT ms.id, ms.producto_id, ms.sucursal_id, ms.tipo, ms.cantidad, ms.stock_anterior, ms.stock_nuevo, ms.motivo, ms.referencia_id, ms.referencia_tipo, ms.empleado_id, ms.usuario_id, ms.created_at,
       p.nombre AS producto_nombre,
       p.codigo AS producto_codigo,
       s.nombre AS sucursal_nombre
FROM movimientos_stock ms
JOIN productos p ON p.id = ms.producto_id
JOIN sucursales s ON s.id = ms.sucursal_id
WHERE ms.usuario_id = $1 AND ms.producto_id = $2
ORDER BY ms.created_at DESC
LIMIT $3 OFFSET $4
`

type ListMovimientosStockByProductoParams struct {
	UsuarioID  pgtype.UUID `json:"usuario_id"`
	ProductoID pgtype.UUID `json:"producto_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

type ListMovimientosStockByProductoRow struct {
	ID             pgtype.UUID         `json:"id"`
	ProductoID     pgtype.UUID         `json:"producto_id"`
	SucursalID     pgtype.UUID         `json:"sucursal_id"`
	Tipo           TipoMovimientoStock `json:"tipo"`
	Cantidad       int32               `json:"cantidad"`
	StockAnterior  int32               `json:"stock_anterior"`
	StockNuevo     int32               `json:"stock_nuevo"`
	Motivo         pgtype.Text         `json:"motivo"`
	ReferenciaID   pgtype.UUID         `json:"referencia_id"`
	ReferenciaTipo pgtype.Text         `json:"referencia_tipo"`
	EmpleadoID     pgtype.UUID         `json:"empleado_id"`
	UsuarioID      pgtype.UUID         `json:"usuario_id"`
	CreatedAt      pgtype.Timestamptz  `json:"created_at"`
	ProductoNombre string              `json:"producto_nombre"`
	ProductoCodigo pgtype.Text         `json:"producto_codigo"`
	SucursalNombre string              `json:"sucursal_nombre"`
}

func (q *Queries) ListMovimientosStockByProducto(ctx context.Context, arg ListMovimientosStockByProductoParams) ([]ListMovimientosStockByProductoRow, error) {
	rows, err := q.db.Query(ctx, listMovimientosStockByProducto,
		arg.UsuarioID,
		arg.ProductoID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMovimientosStockByProductoRow
	for rows.Next() {
		var i ListMovimientosStockByProductoRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductoID,
			&i.SucursalID,
			&i.Tipo,
			&i.Cantidad,
			&i.StockAnterior,
			&i.StockNuevo,
			&i.Motivo,
			&i.ReferenciaID,
			&i.ReferenciaTipo,
			&i.EmpleadoID,
			&i.UsuarioID,
			&i.CreatedAt,
			&i.ProductoNombre,
			&i.ProductoCodigo,
			&i.SucursalNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovimientosStockBySucursal = `-- name: ListMovimientosStockBySucursal :many
SELECT ms.id, ms.producto_id, ms.sucursal_id, ms.tipo, ms.cantidad, ms.stock_anterior, ms.stock_nuevo, ms.motivo, ms.referencia_id, ms.referencia_tipo, ms.empleado_id, ms.usuario_id, ms.created_at,
       p.nombre AS producto_nombre,
       p.codigo AS producto_codigo,
       s.nombre AS sucursal_nombre
FROM movimientos_stock ms
JOIN productos p ON p.id = ms.producto_id
JOIN sucursales s ON s.id = ms.sucursal_id
WHERE ms.usuario_id = $1 AND ms.sucursal_id = $2
ORDER BY ms.created_at DESC
LIMIT $3 OFFSET $4
`

type ListMovimientosStockBySucursalParams struct {
	UsuarioID  pgtype.UUID `json:"usuario_id"`
	SucursalID pgtype.UUID `json:"sucursal_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

type ListMovimientosStockBySucursalRow struct {
	ID             pgtype.UUID         `json:"id"`
	ProductoID     pgtype.UUID         `json:"producto_id"`
	SucursalID     pgtype.UUID         `json:"sucursal_id"`
	Tipo           TipoMovimientoStock `json:"tipo"`
	Cantidad       int32               `json:"cantidad"`
	StockAnterior  int32               `json:"stock_anterior"`
	StockNuevo     int32               `json:"stock_nuevo"`
	Motivo         pgtype.Text         `json:"motivo"`
	ReferenciaID   pgtype.UUID         `json:"referencia_id"`
	ReferenciaTipo pgtype.Text         `json:"referencia_tipo"`
	EmpleadoID     pgtype.UUID         `json:"empleado_id"`
	UsuarioID      pgtype.UUID         `json:"usuario_id"`
	CreatedAt      pgtype.Timestamptz  `json:"created_at"`
	ProductoNombre string              `json:"producto_nombre"`
	ProductoCodigo pgtype.Text         `json:"producto_codigo"`
	SucursalNombre string              `json:"sucursal_nombre"`
}

func (q *Queries) ListMovimientosStockBySucursal(ctx context.Context, arg ListMovimientosStockBySucursalParams) ([]ListMovimientosStockBySucursalRow, error) {
	rows, err := q.db.Query(ctx, listMovimientosStockBySucursal,
		arg.UsuarioID,
		arg.SucursalID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMovimientosStockBySucursalRow
	for rows.Next() {
		var i ListMovimientosStockBySucursalRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductoID,
			&i.SucursalID,
			&i.Tipo,
			&i.Cantidad,
			&i.StockAnterior,
			&i.StockNuevo,
			&i.Motivo,
			&i.ReferenciaID,
			&i.ReferenciaTipo,
			&i.EmpleadoID,
			&i.UsuarioID,
			&i.CreatedAt,
			&i.ProductoNombre,
			&i.ProductoCodigo,
			&i.SucursalNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovimientosStockByTipo = `-- name: ListMovimientosStockByTipo :many
SELECT ms.id, ms.producto_id, ms.sucursal_id, ms.tipo, ms.cantidad, ms.stock_anterior, ms.stock_nuevo, ms.motivo, ms.referencia_id, ms.referencia_tipo, ms.empleado_id, ms.usuario_id, ms.created_at,
       p.nombre AS producto_nombre,
       p.codigo AS producto_codigo,
       s.nombre AS sucursal_nombre
FROM movimientos_stock ms
JOIN productos p ON p.id = ms.producto_id
JOIN sucursales s ON s.id = ms.sucursal_id
WHERE ms.usuario_id = $1 AND ms.tipo = $2
ORDER BY ms.created_at DESC
LIMIT $3 OFFSET $4
`

type ListMovimientosStockByTipoParams struct {
	UsuarioID pgtype.UUID         `json:"usuario_id"`
	Tipo      TipoMovimientoStock `json:"tipo"`
	Limit     int32               `json:"limit"`
	Offset    int32               `json:"offset"`
}

type ListMovimientosStockByTipoRow struct {
	ID             pgtype.UUID         `json:"id"`
	ProductoID     pgtype.UUID         `json:"producto_id"`
	SucursalID     pgtype.UUID         `json:"sucursal_id"`
	Tipo           TipoMovimientoStock `json:"tipo"`
	Cantidad       int32               `json:"cantidad"`
	StockAnterior  int32               `json:"stock_anterior"`
	StockNuevo     int32               `json:"stock_nuevo"`
	Motivo         pgtype.Text         `json:"motivo"`
	ReferenciaID   pgtype.UUID         `json:"referencia_id"`
	ReferenciaTipo pgtype.Text         `json:"referencia_tipo"`
	EmpleadoID     pgtype.UUID         `json:"empleado_id"`
	UsuarioID      pgtype.UUID         `json:"usuario_id"`
	CreatedAt      pgtype.Timestamptz  `json:"created_at"`
	ProductoNombre string              `json:"producto_nombre"`
	ProductoCodigo pgtype.Text         `json:"producto_codigo"`
	SucursalNombre string              `json:"sucursal_nombre"`
}

func (q *Queries) ListMovimientosStockByTipo(ctx context.Context, arg ListMovimientosStockByTipoParams) ([]ListMovimientosStockByTipoRow, error) {
	rows, err := q.db.Query(ctx, listMovimientosStockByTipo,
		arg.UsuarioID,
		arg.Tipo,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMovimientosStockByTipoRow
	for rows.Next() {
		var i ListMovimientosStockByTipoRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductoID,
			&i.SucursalID,
			&i.Tipo,
			&i.Cantidad,
			&i.StockAnterior,
			&i.StockNuevo,
			&i.Motivo,
			&i.ReferenciaID,
			&i.ReferenciaTipo,
			&i.EmpleadoID,
			&i.UsuarioID,
			&i.CreatedAt,
			&i.ProductoNombre,
			&i.ProductoCodigo,
			&i.SucursalNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovimientosStockFiltered = `-- name: ListMovimientosStockFiltered :many
SELECT ms.id, ms.producto_id, ms.sucursal_id, ms.tipo, ms.cantidad, ms.stock_anterior, ms.stock_nuevo, ms.motivo, ms.referencia_id, ms.referencia_tipo, ms.empleado_id, ms.usuario_id, ms.created_at,
       p.nombre AS producto_nombre,
       p.codigo AS producto_codigo,
       s.nombre AS sucursal_nombre,
       e.nombre AS empleado_nombre
FROM movimientos_stock ms
JOIN productos p ON p.id = ms.producto_id
JOIN sucursales s ON s.id = ms.sucursal_id
LEFT JOIN empleados e ON e.id = ms.empleado_id
WHERE ms.usuario_id = $1
  AND ($2::uuid IS NULL OR ms.producto_id = $2)
  AND ($3::uuid IS NULL OR ms.sucursal_id = $3)
  AND ($4::text IS NULL OR $4::text = '' OR ms.tipo::text = $4)
  AND ($5::timestamptz IS NULL OR ms.created_at >= $5)
  AND ($6::timestamptz IS NULL OR ms.created_at <= $6)
ORDER BY ms.created_at DESC
LIMIT $8 OFFSET $7
`

type ListMovimientosStockFilteredParams struct {
	UsuarioID   pgtype.UUID        `json:"usuario_id"`
	ProductoID  pgtype.UUID        `json:"producto_id"`
	SucursalID  pgtype.UUID        `json:"sucursal_id"`
	Tipo        pgtype.Text        `json:"tipo"`
	FechaDesde  pgtype.Timestamptz `json:"fecha_desde"`
	FechaHasta  pgtype.Timestamptz `json:"fecha_hasta"`
	QueryOffset int32              `json:"query_offset"`
	QueryLimit  int32              `json:"query_limit"`
}

type ListMovimientosStockFilteredRow struct {
	ID             pgtype.UUID         `json:"id"`
	ProductoID     pgtype.UUID         `json:"producto_id"`
	SucursalID     pgtype.UUID         `json:"sucursal_id"`
	Tipo           TipoMovimientoStock `json:"tipo"`
	Cantidad       int32               `json:"cantidad"`
	StockAnterior  int32               `json:"stock_anterior"`
	StockNuevo     int32               `json:"stock_nuevo"`
	Motivo         pgtype.Text         `json:"motivo"`
	ReferenciaID   pgtype.UUID         `json:"referencia_id"`
	ReferenciaTipo pgtype.Text         `json:"referencia_tipo"`
	EmpleadoID     pgtype.UUID         `json:"empleado_id"`
	UsuarioID      pgtype.UUID         `json:"usuario_id"`
	CreatedAt      pgtype.Timestamptz  `json:"created_at"`
	ProductoNombre string              `json:"producto_nombre"`
	ProductoCodigo pgtype.Text         `json:"producto_codigo"`
	SucursalNombre string              `json:"sucursal_nombre"`
	EmpleadoNombre pgtype.Text         `json:"empleado_nombre"`
}

func (q *Queries) ListMovimientosStockFiltered(ctx context.Context, arg ListMovimientosStockFilteredParams) ([]ListMovimientosStockFilteredRow, error) {
	rows, err := q.db.Query(ctx, listMovimientosStockFiltered,
		arg.UsuarioID,
		arg.ProductoID,
		arg.SucursalID,
		arg.Tipo,
		arg.FechaDesde,
		arg.FechaHasta,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMovimientosStockFilteredRow
	for rows.Next() {
		var i ListMovimientosStockFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductoID,
			&i.SucursalID,
			&i.Tipo,
			&i.Cantidad,
			&i.StockAnterior,
			&i.StockNuevo,
			&i.Motivo,
			&i.ReferenciaID,
			&i.ReferenciaTipo,
			&i.EmpleadoID,
			&i.UsuarioID,
			&i.CreatedAt,
			&i.ProductoNombre,
			&i.ProductoCodigo,
			&i.SucursalNombre,
			&i.EmpleadoNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
