// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notificaciones.sql

package repository

import (
	"context"
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

// --- Enum ---

type TipoNotificacion string

const (
	TipoNotificacionINFO           TipoNotificacion = "INFO"
	TipoNotificacionALERTA         TipoNotificacion = "ALERTA"
	TipoNotificacionAPROBACION     TipoNotificacion = "APROBACION"
	TipoNotificacionSTOCKBAJO      TipoNotificacion = "STOCK_BAJO"
	TipoNotificacionPAGOVENCIDO    TipoNotificacion = "PAGO_VENCIDO"
	TipoNotificacionPEDIDOESTADO   TipoNotificacion = "PEDIDO_ESTADO"
	TipoNotificacionREPARTOESTADO  TipoNotificacion = "REPARTO_ESTADO"
	TipoNotificacionSISTEMA        TipoNotificacion = "SISTEMA"
)

func (e *TipoNotificacion) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TipoNotificacion(s)
	case string:
		*e = TipoNotificacion(s)
	default:
		return fmt.Errorf("unsupported scan type for TipoNotificacion: %T", src)
	}
	return nil
}

type NullTipoNotificacion struct {
	TipoNotificacion TipoNotificacion `json:"tipo_notificacion"`
	Valid            bool             `json:"valid"`
}

func (ns *NullTipoNotificacion) Scan(value interface{}) error {
	if value == nil {
		ns.TipoNotificacion, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TipoNotificacion.Scan(value)
}

func (ns NullTipoNotificacion) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TipoNotificacion), nil
}

// --- Model ---

type Notificacion struct {
	ID              pgtype.UUID        `json:"id"`
	DestinatarioID  pgtype.UUID        `json:"destinatario_id"`
	Tipo            TipoNotificacion   `json:"tipo"`
	Titulo          string             `json:"titulo"`
	Mensaje         string             `json:"mensaje"`
	Enlace          pgtype.Text        `json:"enlace"`
	Leida           bool               `json:"leida"`
	FechaLeida      pgtype.Timestamptz `json:"fecha_leida"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

// --- Params ---

type CreateNotificacionParams struct {
	DestinatarioID pgtype.UUID      `json:"destinatario_id"`
	Tipo           TipoNotificacion `json:"tipo"`
	Titulo         string           `json:"titulo"`
	Mensaje        string           `json:"mensaje"`
	Enlace         pgtype.Text      `json:"enlace"`
	Metadata       []byte           `json:"metadata"`
}

type ListNotificacionesParams struct {
	DestinatarioID pgtype.UUID `json:"destinatario_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

type MarkNotificacionReadParams struct {
	ID             pgtype.UUID `json:"id"`
	DestinatarioID pgtype.UUID `json:"destinatario_id"`
}

// --- SQL constants and methods ---

const createNotificacion = `-- name: CreateNotificacion :one
INSERT INTO notificaciones (
  destinatario_id, tipo, titulo, mensaje, enlace, metadata
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, destinatario_id, tipo, titulo, mensaje, enlace, leida, fecha_leida, metadata, created_at
`

func (q *Queries) CreateNotificacion(ctx context.Context, arg CreateNotificacionParams) (Notificacion, error) {
	row := q.db.QueryRow(ctx, createNotificacion,
		arg.DestinatarioID,
		arg.Tipo,
		arg.Titulo,
		arg.Mensaje,
		arg.Enlace,
		arg.Metadata,
	)
	var i Notificacion
	err := row.Scan(
		&i.ID,
		&i.DestinatarioID,
		&i.Tipo,
		&i.Titulo,
		&i.Mensaje,
		&i.Enlace,
		&i.Leida,
		&i.FechaLeida,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificaciones = `-- name: ListNotificaciones :many
SELECT id, destinatario_id, tipo, titulo, mensaje, enlace, leida, fecha_leida, metadata, created_at
FROM notificaciones
WHERE destinatario_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) ListNotificaciones(ctx context.Context, arg ListNotificacionesParams) ([]Notificacion, error) {
	rows, err := q.db.Query(ctx, listNotificaciones, arg.DestinatarioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notificacion
	for rows.Next() {
		var i Notificacion
		if err := rows.Scan(
			&i.ID,
			&i.DestinatarioID,
			&i.Tipo,
			&i.Titulo,
			&i.Mensaje,
			&i.Enlace,
			&i.Leida,
			&i.FechaLeida,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countNotificaciones = `-- name: CountNotificaciones :one
SELECT COUNT(*) FROM notificaciones
WHERE destinatario_id = $1
`

func (q *Queries) CountNotificaciones(ctx context.Context, destinatarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificaciones, destinatarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUnreadCount = `-- name: GetUnreadCount :one
SELECT COUNT(*) FROM notificaciones
WHERE destinatario_id = $1 AND leida = FALSE
`

func (q *Queries) GetUnreadCount(ctx context.Context, destinatarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadCount, destinatarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const markAsRead = `-- name: MarkAsRead :exec
UPDATE notificaciones
SET leida = TRUE, fecha_leida = NOW()
WHERE id = $1 AND destinatario_id = $2 AND leida = FALSE
`

func (q *Queries) MarkAsRead(ctx context.Context, arg MarkNotificacionReadParams) error {
	_, err := q.db.Exec(ctx, markAsRead, arg.ID, arg.DestinatarioID)
	return err
}

const markAllAsRead = `-- name: MarkAllAsRead :exec
UPDATE notificaciones
SET leida = TRUE, fecha_leida = NOW()
WHERE destinatario_id = $1 AND leida = FALSE
`

func (q *Queries) MarkAllAsRead(ctx context.Context, destinatarioID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllAsRead, destinatarioID)
	return err
}
