// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ordenes_compra.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrdenesCompra = `-- name: CountOrdenesCompra :one
SELECT COUNT(*) FROM ordenes_compra
WHERE usuario_id = $1 AND active = TRUE
`

func (q *Queries) CountOrdenesCompra(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdenesCompra, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrdenesCompraByEstado = `-- name: CountOrdenesCompraByEstado :one
SELECT COUNT(*) FROM ordenes_compra
WHERE usuario_id = $1 AND active = TRUE AND estado = $2
`

type CountOrdenesCompraByEstadoParams struct {
	UsuarioID pgtype.UUID       `json:"usuario_id"`
	Estado    EstadoOrdenCompra `json:"estado"`
}

func (q *Queries) CountOrdenesCompraByEstado(ctx context.Context, arg CountOrdenesCompraByEstadoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdenesCompraByEstado, arg.UsuarioID, arg.Estado)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchOrdenesCompra = `-- name: CountSearchOrdenesCompra :one
SELECT COUNT(*) FROM ordenes_compra oc
JOIN proveedores p ON oc.proveedor_id = p.id
WHERE oc.usuario_id = $1 AND oc.active = TRUE
  AND (oc.numero ILIKE $2 OR p.nombre ILIKE $2)
`

type CountSearchOrdenesCompraParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Numero    string      `json:"numero"`
}

func (q *Queries) CountSearchOrdenesCompra(ctx context.Context, arg CountSearchOrdenesCompraParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchOrdenesCompra, arg.UsuarioID, arg.Numero)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDetalleOrdenCompra = `-- name: CreateDetalleOrdenCompra :one
INSERT INTO detalle_ordenes_compra (
  orden_compra_id, producto_id, producto_nombre, producto_codigo,
  cantidad, cantidad_recibida, precio_unitario,
  descuento_porcentaje, descuento_monto, subtotal, orden
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, orden_compra_id, producto_id, producto_nombre, producto_codigo, cantidad, cantidad_recibida, precio_unitario, descuento_porcentaje, descuento_monto, subtotal, orden
`

type CreateDetalleOrdenCompraParams struct {
	OrdenCompraID       pgtype.UUID    `json:"orden_compra_id"`
	ProductoID          pgtype.UUID    `json:"producto_id"`
	ProductoNombre      string         `json:"producto_nombre"`
	ProductoCodigo      pgtype.Text    `json:"producto_codigo"`
	Cantidad            pgtype.Numeric `json:"cantidad"`
	CantidadRecibida    pgtype.Numeric `json:"cantidad_recibida"`
	PrecioUnitario      pgtype.Numeric `json:"precio_unitario"`
	DescuentoPorcentaje pgtype.Numeric `json:"descuento_porcentaje"`
	DescuentoMonto      pgtype.Numeric `json:"descuento_monto"`
	Subtotal            pgtype.Numeric `json:"subtotal"`
	Orden               int32          `json:"orden"`
}

func (q *Queries) CreateDetalleOrdenCompra(ctx context.Context, arg CreateDetalleOrdenCompraParams) (DetalleOrdenesCompra, error) {
	row := q.db.QueryRow(ctx, createDetalleOrdenCompra,
		arg.OrdenCompraID,
		arg.ProductoID,
		arg.ProductoNombre,
		arg.ProductoCodigo,
		arg.Cantidad,
		arg.CantidadRecibida,
		arg.PrecioUnitario,
		arg.DescuentoPorcentaje,
		arg.DescuentoMonto,
		arg.Subtotal,
		arg.Orden,
	)
	var i DetalleOrdenesCompra
	err := row.Scan(
		&i.ID,
		&i.OrdenCompraID,
		&i.ProductoID,
		&i.ProductoNombre,
		&i.ProductoCodigo,
		&i.Cantidad,
		&i.CantidadRecibida,
		&i.PrecioUnitario,
		&i.DescuentoPorcentaje,
		&i.DescuentoMonto,
		&i.Subtotal,
		&i.Orden,
	)
	return i, err
}

const createHistorialOrdenCompra = `-- name: CreateHistorialOrdenCompra :one
INSERT INTO historial_orden_compra (orden_compra_id, estado_anterior, estado_nuevo, comentario, empleado_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, orden_compra_id, estado_anterior, estado_nuevo, comentario, empleado_id, created_at
`

type CreateHistorialOrdenCompraParams struct {
	OrdenCompraID  pgtype.UUID           `json:"orden_compra_id"`
	EstadoAnterior NullEstadoOrdenCompra `json:"estado_anterior"`
	EstadoNuevo    EstadoOrdenCompra     `json:"estado_nuevo"`
	Comentario     pgtype.Text           `json:"comentario"`
	EmpleadoID     pgtype.UUID           `json:"empleado_id"`
}

func (q *Queries) CreateHistorialOrdenCompra(ctx context.Context, arg CreateHistorialOrdenCompraParams) (HistorialOrdenCompra, error) {
	row := q.db.QueryRow(ctx, createHistorialOrdenCompra,
		arg.OrdenCompraID,
		arg.EstadoAnterior,
		arg.EstadoNuevo,
		arg.Comentario,
		arg.EmpleadoID,
	)
	var i HistorialOrdenCompra
	err := row.Scan(
		&i.ID,
		&i.OrdenCompraID,
		&i.EstadoAnterior,
		&i.EstadoNuevo,
		&i.Comentario,
		&i.EmpleadoID,
		&i.CreatedAt,
	)
	return i, err
}

const createImpuestoOrdenCompra = `-- name: CreateImpuestoOrdenCompra :one
INSERT INTO impuestos_orden_compra (
  orden_compra_id, tipo, nombre, porcentaje, base_imponible, monto
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, orden_compra_id, tipo, nombre, porcentaje, base_imponible, monto
`

type CreateImpuestoOrdenCompraParams struct {
	OrdenCompraID pgtype.UUID    `json:"orden_compra_id"`
	Tipo          TipoImpuesto   `json:"tipo"`
	Nombre        string         `json:"nombre"`
	Porcentaje    pgtype.Numeric `json:"porcentaje"`
	BaseImponible pgtype.Numeric `json:"base_imponible"`
	Monto         pgtype.Numeric `json:"monto"`
}

func (q *Queries) CreateImpuestoOrdenCompra(ctx context.Context, arg CreateImpuestoOrdenCompraParams) (ImpuestosOrdenCompra, error) {
	row := q.db.QueryRow(ctx, createImpuestoOrdenCompra,
		arg.OrdenCompraID,
		arg.Tipo,
		arg.Nombre,
		arg.Porcentaje,
		arg.BaseImponible,
		arg.Monto,
	)
	var i ImpuestosOrdenCompra
	err := row.Scan(
		&i.ID,
		&i.OrdenCompraID,
		&i.Tipo,
		&i.Nombre,
		&i.Porcentaje,
		&i.BaseImponible,
		&i.Monto,
	)
	return i, err
}

const createOrdenCompra = `-- name: CreateOrdenCompra :one
INSERT INTO ordenes_compra (
  numero, proveedor_id, sucursal_id, estado, condicion_pago,
  fecha_orden, fecha_entrega_estimada,
  subtotal, descuento_porcentaje, descuento_monto,
  base_imponible, total_impuestos, total,
  observaciones, usuario_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, numero, proveedor_id, sucursal_id, estado, condicion_pago, fecha_orden, fecha_entrega_estimada, subtotal, descuento_porcentaje, descuento_monto, base_imponible, total_impuestos, total, observaciones, usuario_id, active, created_at, updated_at
`

type CreateOrdenCompraParams struct {
	Numero               string            `json:"numero"`
	ProveedorID          pgtype.UUID       `json:"proveedor_id"`
	SucursalID           pgtype.UUID       `json:"sucursal_id"`
	Estado               EstadoOrdenCompra `json:"estado"`
	CondicionPago        CondicionPago     `json:"condicion_pago"`
	FechaOrden           pgtype.Date       `json:"fecha_orden"`
	FechaEntregaEstimada pgtype.Date       `json:"fecha_entrega_estimada"`
	Subtotal             pgtype.Numeric    `json:"subtotal"`
	DescuentoPorcentaje  pgtype.Numeric    `json:"descuento_porcentaje"`
	DescuentoMonto       pgtype.Numeric    `json:"descuento_monto"`
	BaseImponible        pgtype.Numeric    `json:"base_imponible"`
	TotalImpuestos       pgtype.Numeric    `json:"total_impuestos"`
	Total                pgtype.Numeric    `json:"total"`
	Observaciones        pgtype.Text       `json:"observaciones"`
	UsuarioID            pgtype.UUID       `json:"usuario_id"`
}

func (q *Queries) CreateOrdenCompra(ctx context.Context, arg CreateOrdenCompraParams) (OrdenesCompra, error) {
	row := q.db.QueryRow(ctx, createOrdenCompra,
		arg.Numero,
		arg.ProveedorID,
		arg.SucursalID,
		arg.Estado,
		arg.CondicionPago,
		arg.FechaOrden,
		arg.FechaEntregaEstimada,
		arg.Subtotal,
		arg.DescuentoPorcentaje,
		arg.DescuentoMonto,
		arg.BaseImponible,
		arg.TotalImpuestos,
		arg.Total,
		arg.Observaciones,
		arg.UsuarioID,
	)
	var i OrdenesCompra
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.ProveedorID,
		&i.SucursalID,
		&i.Estado,
		&i.CondicionPago,
		&i.FechaOrden,
		&i.FechaEntregaEstimada,
		&i.Subtotal,
		&i.DescuentoPorcentaje,
		&i.DescuentoMonto,
		&i.BaseImponible,
		&i.TotalImpuestos,
		&i.Total,
		&i.Observaciones,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDetalleOrdenCompra = `-- name: DeleteDetalleOrdenCompra :exec
DELETE FROM detalle_ordenes_compra
WHERE orden_compra_id = $1
`

func (q *Queries) DeleteDetalleOrdenCompra(ctx context.Context, ordenCompraID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDetalleOrdenCompra, ordenCompraID)
	return err
}

const deleteImpuestosOrdenCompra = `-- name: DeleteImpuestosOrdenCompra :exec
DELETE FROM impuestos_orden_compra
WHERE orden_compra_id = $1
`

func (q *Queries) DeleteImpuestosOrdenCompra(ctx context.Context, ordenCompraID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteImpuestosOrdenCompra, ordenCompraID)
	return err
}

const getDetalleOrdenCompraByID = `-- name: GetDetalleOrdenCompraByID :one
SELECT d.id, d.orden_compra_id, d.producto_id, d.producto_nombre, d.producto_codigo, d.cantidad, d.cantidad_recibida, d.precio_unitario, d.descuento_porcentaje, d.descuento_monto, d.subtotal, d.orden, pr.unidad AS producto_unidad
FROM detalle_ordenes_compra d
JOIN productos pr ON d.producto_id = pr.id
WHERE d.id = $1
`

type GetDetalleOrdenCompraByIDRow struct {
	ID                  pgtype.UUID    `json:"id"`
	OrdenCompraID       pgtype.UUID    `json:"orden_compra_id"`
	ProductoID          pgtype.UUID    `json:"producto_id"`
	ProductoNombre      string         `json:"producto_nombre"`
	ProductoCodigo      pgtype.Text    `json:"producto_codigo"`
	Cantidad            pgtype.Numeric `json:"cantidad"`
	CantidadRecibida    pgtype.Numeric `json:"cantidad_recibida"`
	PrecioUnitario      pgtype.Numeric `json:"precio_unitario"`
	DescuentoPorcentaje pgtype.Numeric `json:"descuento_porcentaje"`
	DescuentoMonto      pgtype.Numeric `json:"descuento_monto"`
	Subtotal            pgtype.Numeric `json:"subtotal"`
	Orden               int32          `json:"orden"`
	ProductoUnidad      UnidadDeMedida `json:"producto_unidad"`
}

func (q *Queries) GetDetalleOrdenCompraByID(ctx context.Context, id pgtype.UUID) (GetDetalleOrdenCompraByIDRow, error) {
	row := q.db.QueryRow(ctx, getDetalleOrdenCompraByID, id)
	var i GetDetalleOrdenCompraByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrdenCompraID,
		&i.ProductoID,
		&i.ProductoNombre,
		&i.ProductoCodigo,
		&i.Cantidad,
		&i.CantidadRecibida,
		&i.PrecioUnitario,
		&i.DescuentoPorcentaje,
		&i.DescuentoMonto,
		&i.Subtotal,
		&i.Orden,
		&i.ProductoUnidad,
	)
	return i, err
}

const getOrdenCompraByID = `-- name: GetOrdenCompraByID :one
SELECT oc.id, oc.numero, oc.proveedor_id, oc.sucursal_id, oc.estado, oc.condicion_pago, oc.fecha_orden, oc.fecha_entrega_estimada, oc.subtotal, oc.descuento_porcentaje, oc.descuento_monto, oc.base_imponible, oc.total_impuestos, oc.total, oc.observaciones, oc.usuario_id, oc.active, oc.created_at, oc.updated_at,
  p.nombre AS proveedor_nombre,
  p.cuit AS proveedor_cuit,
  p.condicion_iva AS proveedor_condicion_iva,
  s.nombre AS sucursal_nombre
FROM ordenes_compra oc
JOIN proveedores p ON oc.proveedor_id = p.id
JOIN sucursales s ON oc.sucursal_id = s.id
WHERE oc.id = $1 AND oc.usuario_id = $2 AND oc.active = TRUE
`

type GetOrdenCompraByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

type GetOrdenCompraByIDRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Numero                string             `json:"numero"`
	ProveedorID           pgtype.UUID        `json:"proveedor_id"`
	SucursalID            pgtype.UUID        `json:"sucursal_id"`
	Estado                EstadoOrdenCompra  `json:"estado"`
	CondicionPago         CondicionPago      `json:"condicion_pago"`
	FechaOrden            pgtype.Date        `json:"fecha_orden"`
	FechaEntregaEstimada  pgtype.Date        `json:"fecha_entrega_estimada"`
	Subtotal              pgtype.Numeric     `json:"subtotal"`
	DescuentoPorcentaje   pgtype.Numeric     `json:"descuento_porcentaje"`
	DescuentoMonto        pgtype.Numeric     `json:"descuento_monto"`
	BaseImponible         pgtype.Numeric     `json:"base_imponible"`
	TotalImpuestos        pgtype.Numeric     `json:"total_impuestos"`
	Total                 pgtype.Numeric     `json:"total"`
	Observaciones         pgtype.Text        `json:"observaciones"`
	UsuarioID             pgtype.UUID        `json:"usuario_id"`
	Active                bool               `json:"active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	ProveedorNombre       string             `json:"proveedor_nombre"`
	ProveedorCuit         pgtype.Text        `json:"proveedor_cuit"`
	ProveedorCondicionIva NullCondicionIva   `json:"proveedor_condicion_iva"`
	SucursalNombre        string             `json:"sucursal_nombre"`
}

func (q *Queries) GetOrdenCompraByID(ctx context.Context, arg GetOrdenCompraByIDParams) (GetOrdenCompraByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrdenCompraByID, arg.ID, arg.UsuarioID)
	var i GetOrdenCompraByIDRow
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.ProveedorID,
		&i.SucursalID,
		&i.Estado,
		&i.CondicionPago,
		&i.FechaOrden,
		&i.FechaEntregaEstimada,
		&i.Subtotal,
		&i.DescuentoPorcentaje,
		&i.DescuentoMonto,
		&i.BaseImponible,
		&i.TotalImpuestos,
		&i.Total,
		&i.Observaciones,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProveedorNombre,
		&i.ProveedorCuit,
		&i.ProveedorCondicionIva,
		&i.SucursalNombre,
	)
	return i, err
}

const listDetalleOrdenCompra = `-- name: ListDetalleOrdenCompra :many
SELECT d.id, d.orden_compra_id, d.producto_id, d.producto_nombre, d.producto_codigo, d.cantidad, d.cantidad_recibida, d.precio_unitario, d.descuento_porcentaje, d.descuento_monto, d.subtotal, d.orden, pr.unidad AS producto_unidad
FROM detalle_ordenes_compra d
JOIN productos pr ON d.producto_id = pr.id
WHERE d.orden_compra_id = $1
ORDER BY d.orden ASC
`

type ListDetalleOrdenCompraRow struct {
	ID                  pgtype.UUID    `json:"id"`
	OrdenCompraID       pgtype.UUID    `json:"orden_compra_id"`
	ProductoID          pgtype.UUID    `json:"producto_id"`
	ProductoNombre      string         `json:"producto_nombre"`
	ProductoCodigo      pgtype.Text    `json:"producto_codigo"`
	Cantidad            pgtype.Numeric `json:"cantidad"`
	CantidadRecibida    pgtype.Numeric `json:"cantidad_recibida"`
	PrecioUnitario      pgtype.Numeric `json:"precio_unitario"`
	DescuentoPorcentaje pgtype.Numeric `json:"descuento_porcentaje"`
	DescuentoMonto      pgtype.Numeric `json:"descuento_monto"`
	Subtotal            pgtype.Numeric `json:"subtotal"`
	Orden               int32          `json:"orden"`
	ProductoUnidad      UnidadDeMedida `json:"producto_unidad"`
}

func (q *Queries) ListDetalleOrdenCompra(ctx context.Context, ordenCompraID pgtype.UUID) ([]ListDetalleOrdenCompraRow, error) {
	rows, err := q.db.Query(ctx, listDetalleOrdenCompra, ordenCompraID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDetalleOrdenCompraRow
	for rows.Next() {
		var i ListDetalleOrdenCompraRow
		if err := rows.Scan(
			&i.ID,
			&i.OrdenCompraID,
			&i.ProductoID,
			&i.ProductoNombre,
			&i.ProductoCodigo,
			&i.Cantidad,
			&i.CantidadRecibida,
			&i.PrecioUnitario,
			&i.DescuentoPorcentaje,
			&i.DescuentoMonto,
			&i.Subtotal,
			&i.Orden,
			&i.ProductoUnidad,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistorialOrdenCompra = `-- name: ListHistorialOrdenCompra :many
SELECT h.id, h.orden_compra_id, h.estado_anterior, h.estado_nuevo, h.comentario, h.empleado_id, h.created_at,
  e.nombre AS empleado_nombre,
  e.apellido AS empleado_apellido
FROM historial_orden_compra h
LEFT JOIN empleados e ON h.empleado_id = e.id
WHERE h.orden_compra_id = $1
ORDER BY h.created_at ASC
`

type ListHistorialOrdenCompraRow struct {
	ID               pgtype.UUID           `json:"id"`
	OrdenCompraID    pgtype.UUID           `json:"orden_compra_id"`
	EstadoAnterior   NullEstadoOrdenCompra `json:"estado_anterior"`
	EstadoNuevo      EstadoOrdenCompra     `json:"estado_nuevo"`
	Comentario       pgtype.Text           `json:"comentario"`
	EmpleadoID       pgtype.UUID           `json:"empleado_id"`
	CreatedAt        pgtype.Timestamptz    `json:"created_at"`
	EmpleadoNombre   pgtype.Text           `json:"empleado_nombre"`
	EmpleadoApellido pgtype.Text           `json:"empleado_apellido"`
}

func (q *Queries) ListHistorialOrdenCompra(ctx context.Context, ordenCompraID pgtype.UUID) ([]ListHistorialOrdenCompraRow, error) {
	rows, err := q.db.Query(ctx, listHistorialOrdenCompra, ordenCompraID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHistorialOrdenCompraRow
	for rows.Next() {
		var i ListHistorialOrdenCompraRow
		if err := rows.Scan(
			&i.ID,
			&i.OrdenCompraID,
			&i.EstadoAnterior,
			&i.EstadoNuevo,
			&i.Comentario,
			&i.EmpleadoID,
			&i.CreatedAt,
			&i.EmpleadoNombre,
			&i.EmpleadoApellido,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImpuestosOrdenCompra = `-- name: ListImpuestosOrdenCompra :many
SELECT id, orden_compra_id, tipo, nombre, porcentaje, base_imponible, monto FROM impuestos_orden_compra
WHERE orden_compra_id = $1
`

func (q *Queries) ListImpuestosOrdenCompra(ctx context.Context, ordenCompraID pgtype.UUID) ([]ImpuestosOrdenCompra, error) {
	rows, err := q.db.Query(ctx, listImpuestosOrdenCompra, ordenCompraID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImpuestosOrdenCompra
	for rows.Next() {
		var i ImpuestosOrdenCompra
		if err := rows.Scan(
			&i.ID,
			&i.OrdenCompraID,
			&i.Tipo,
			&i.Nombre,
			&i.Porcentaje,
			&i.BaseImponible,
			&i.Monto,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdenesCompra = `-- name: ListOrdenesCompra :many
SELECT oc.id, oc.numero, oc.proveedor_id,
  p.nombre AS proveedor_nombre,
  oc.sucursal_id, s.nombre AS sucursal_nombre,
  oc.estado, oc.condicion_pago,
  oc.fecha_orden, oc.fecha_entrega_estimada,
  oc.subtotal, oc.total, oc.created_at
FROM ordenes_compra oc
JOIN proveedores p ON oc.proveedor_id = p.id
JOIN sucursales s ON oc.sucursal_id = s.id
WHERE oc.usuario_id = $1 AND oc.active = TRUE
ORDER BY oc.created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdenesCompraParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListOrdenesCompraRow struct {
	ID                   pgtype.UUID        `json:"id"`
	Numero               string             `json:"numero"`
	ProveedorID          pgtype.UUID        `json:"proveedor_id"`
	ProveedorNombre      string             `json:"proveedor_nombre"`
	SucursalID           pgtype.UUID        `json:"sucursal_id"`
	SucursalNombre       string             `json:"sucursal_nombre"`
	Estado               EstadoOrdenCompra  `json:"estado"`
	CondicionPago        CondicionPago      `json:"condicion_pago"`
	FechaOrden           pgtype.Date        `json:"fecha_orden"`
	FechaEntregaEstimada pgtype.Date        `json:"fecha_entrega_estimada"`
	Subtotal             pgtype.Numeric     `json:"subtotal"`
	Total                pgtype.Numeric     `json:"total"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOrdenesCompra(ctx context.Context, arg ListOrdenesCompraParams) ([]ListOrdenesCompraRow, error) {
	rows, err := q.db.Query(ctx, listOrdenesCompra, arg.UsuarioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdenesCompraRow
	for rows.Next() {
		var i ListOrdenesCompraRow
		if err := rows.Scan(
			&i.ID,
			&i.Numero,
			&i.ProveedorID,
			&i.ProveedorNombre,
			&i.SucursalID,
			&i.SucursalNombre,
			&i.Estado,
			&i.CondicionPago,
			&i.FechaOrden,
			&i.FechaEntregaEstimada,
			&i.Subtotal,
			&i.Total,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdenesCompraByEstado = `-- name: ListOrdenesCompraByEstado :many
SELECT oc.id, oc.numero, oc.proveedor_id,
  p.nombre AS proveedor_nombre,
  oc.sucursal_id, s.nombre AS sucursal_nombre,
  oc.estado, oc.condicion_pago,
  oc.fecha_orden, oc.fecha_entrega_estimada,
  oc.subtotal, oc.total, oc.created_at
FROM ordenes_compra oc
JOIN proveedores p ON oc.proveedor_id = p.id
JOIN sucursales s ON oc.sucursal_id = s.id
WHERE oc.usuario_id = $1 AND oc.active = TRUE AND oc.estado = $2
ORDER BY oc.created_at DESC
LIMIT $3 OFFSET $4
`

type ListOrdenesCompraByEstadoParams struct {
	UsuarioID pgtype.UUID       `json:"usuario_id"`
	Estado    EstadoOrdenCompra `json:"estado"`
	Limit     int32             `json:"limit"`
	Offset    int32             `json:"offset"`
}

type ListOrdenesCompraByEstadoRow struct {
	ID                   pgtype.UUID        `json:"id"`
	Numero               string             `json:"numero"`
	ProveedorID          pgtype.UUID        `json:"proveedor_id"`
	ProveedorNombre      string             `json:"proveedor_nombre"`
	SucursalID           pgtype.UUID        `json:"sucursal_id"`
	SucursalNombre       string             `json:"sucursal_nombre"`
	Estado               EstadoOrdenCompra  `json:"estado"`
	CondicionPago        CondicionPago      `json:"condicion_pago"`
	FechaOrden           pgtype.Date        `json:"fecha_orden"`
	FechaEntregaEstimada pgtype.Date        `json:"fecha_entrega_estimada"`
	Subtotal             pgtype.Numeric     `json:"subtotal"`
	Total                pgtype.Numeric     `json:"total"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOrdenesCompraByEstado(ctx context.Context, arg ListOrdenesCompraByEstadoParams) ([]ListOrdenesCompraByEstadoRow, error) {
	rows, err := q.db.Query(ctx, listOrdenesCompraByEstado,
		arg.UsuarioID,
		arg.Estado,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdenesCompraByEstadoRow
	for rows.Next() {
		var i ListOrdenesCompraByEstadoRow
		if err := rows.Scan(
			&i.ID,
			&i.Numero,
			&i.ProveedorID,
			&i.ProveedorNombre,
			&i.SucursalID,
			&i.SucursalNombre,
			&i.Estado,
			&i.CondicionPago,
			&i.FechaOrden,
			&i.FechaEntregaEstimada,
			&i.Subtotal,
			&i.Total,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextOrdenCompraNumero = `-- name: NextOrdenCompraNumero :one
SELECT nextval('orden_compra_numero_seq')
`

func (q *Queries) NextOrdenCompraNumero(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextOrdenCompraNumero)
	var nextval int64
	err := row.Scan(&nextval)
	return nextval, err
}

const searchOrdenesCompra = `-- name: SearchOrdenesCompra :many
SELECT oc.id, oc.numero, oc.proveedor_id,
  p.nombre AS proveedor_nombre,
  oc.sucursal_id, s.nombre AS sucursal_nombre,
  oc.estado, oc.condicion_pago,
  oc.fecha_orden, oc.fecha_entrega_estimada,
  oc.subtotal, oc.total, oc.created_at
FROM ordenes_compra oc
JOIN proveedores p ON oc.proveedor_id = p.id
JOIN sucursales s ON oc.sucursal_id = s.id
WHERE oc.usuario_id = $1 AND oc.active = TRUE
  AND (oc.numero ILIKE $2 OR p.nombre ILIKE $2)
ORDER BY oc.created_at DESC
LIMIT $3 OFFSET $4
`

type SearchOrdenesCompraParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Numero    string      `json:"numero"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type SearchOrdenesCompraRow struct {
	ID                   pgtype.UUID        `json:"id"`
	Numero               string             `json:"numero"`
	ProveedorID          pgtype.UUID        `json:"proveedor_id"`
	ProveedorNombre      string             `json:"proveedor_nombre"`
	SucursalID           pgtype.UUID        `json:"sucursal_id"`
	SucursalNombre       string             `json:"sucursal_nombre"`
	Estado               EstadoOrdenCompra  `json:"estado"`
	CondicionPago        CondicionPago      `json:"condicion_pago"`
	FechaOrden           pgtype.Date        `json:"fecha_orden"`
	FechaEntregaEstimada pgtype.Date        `json:"fecha_entrega_estimada"`
	Subtotal             pgtype.Numeric     `json:"subtotal"`
	Total                pgtype.Numeric     `json:"total"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) SearchOrdenesCompra(ctx context.Context, arg SearchOrdenesCompraParams) ([]SearchOrdenesCompraRow, error) {
	rows, err := q.db.Query(ctx, searchOrdenesCompra,
		arg.UsuarioID,
		arg.Numero,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchOrdenesCompraRow
	for rows.Next() {
		var i SearchOrdenesCompraRow
		if err := rows.Scan(
			&i.ID,
			&i.Numero,
			&i.ProveedorID,
			&i.ProveedorNombre,
			&i.SucursalID,
			&i.SucursalNombre,
			&i.Estado,
			&i.CondicionPago,
			&i.FechaOrden,
			&i.FechaEntregaEstimada,
			&i.Subtotal,
			&i.Total,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteOrdenCompra = `-- name: SoftDeleteOrdenCompra :exec
UPDATE ordenes_compra SET active = FALSE, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND active = TRUE AND estado = 'BORRADOR'
`

type SoftDeleteOrdenCompraParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) SoftDeleteOrdenCompra(ctx context.Context, arg SoftDeleteOrdenCompraParams) error {
	_, err := q.db.Exec(ctx, softDeleteOrdenCompra, arg.ID, arg.UsuarioID)
	return err
}

const updateDetalleRecibida = `-- name: UpdateDetalleRecibida :exec
UPDATE detalle_ordenes_compra
SET cantidad_recibida = $2
WHERE id = $1
`

type UpdateDetalleRecibidaParams struct {
	ID               pgtype.UUID    `json:"id"`
	CantidadRecibida pgtype.Numeric `json:"cantidad_recibida"`
}

func (q *Queries) UpdateDetalleRecibida(ctx context.Context, arg UpdateDetalleRecibidaParams) error {
	_, err := q.db.Exec(ctx, updateDetalleRecibida, arg.ID, arg.CantidadRecibida)
	return err
}

const updateOrdenCompra = `-- name: UpdateOrdenCompra :one
UPDATE ordenes_compra SET
  proveedor_id = $3,
  sucursal_id = $4,
  condicion_pago = $5,
  fecha_entrega_estimada = $6,
  subtotal = $7,
  descuento_porcentaje = $8,
  descuento_monto = $9,
  base_imponible = $10,
  total_impuestos = $11,
  total = $12,
  observaciones = $13,
  updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND active = TRUE AND estado = 'BORRADOR'
RETURNING id, numero, proveedor_id, sucursal_id, estado, condicion_pago, fecha_orden, fecha_entrega_estimada, subtotal, descuento_porcentaje, descuento_monto, base_imponible, total_impuestos, total, observaciones, usuario_id, active, created_at, updated_at
`

type UpdateOrdenCompraParams struct {
	ID                   pgtype.UUID    `json:"id"`
	UsuarioID            pgtype.UUID    `json:"usuario_id"`
	ProveedorID          pgtype.UUID    `json:"proveedor_id"`
	SucursalID           pgtype.UUID    `json:"sucursal_id"`
	CondicionPago        CondicionPago  `json:"condicion_pago"`
	FechaEntregaEstimada pgtype.Date    `json:"fecha_entrega_estimada"`
	Subtotal             pgtype.Numeric `json:"subtotal"`
	DescuentoPorcentaje  pgtype.Numeric `json:"descuento_porcentaje"`
	DescuentoMonto       pgtype.Numeric `json:"descuento_monto"`
	BaseImponible        pgtype.Numeric `json:"base_imponible"`
	TotalImpuestos       pgtype.Numeric `json:"total_impuestos"`
	Total                pgtype.Numeric `json:"total"`
	Observaciones        pgtype.Text    `json:"observaciones"`
}

func (q *Queries) UpdateOrdenCompra(ctx context.Context, arg UpdateOrdenCompraParams) (OrdenesCompra, error) {
	row := q.db.QueryRow(ctx, updateOrdenCompra,
		arg.ID,
		arg.UsuarioID,
		arg.ProveedorID,
		arg.SucursalID,
		arg.CondicionPago,
		arg.FechaEntregaEstimada,
		arg.Subtotal,
		arg.DescuentoPorcentaje,
		arg.DescuentoMonto,
		arg.BaseImponible,
		arg.TotalImpuestos,
		arg.Total,
		arg.Observaciones,
	)
	var i OrdenesCompra
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.ProveedorID,
		&i.SucursalID,
		&i.Estado,
		&i.CondicionPago,
		&i.FechaOrden,
		&i.FechaEntregaEstimada,
		&i.Subtotal,
		&i.DescuentoPorcentaje,
		&i.DescuentoMonto,
		&i.BaseImponible,
		&i.TotalImpuestos,
		&i.Total,
		&i.Observaciones,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrdenCompraEstado = `-- name: UpdateOrdenCompraEstado :one
UPDATE ordenes_compra SET estado = $3, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
RETURNING id, numero, proveedor_id, sucursal_id, estado, condicion_pago, fecha_orden, fecha_entrega_estimada, subtotal, descuento_porcentaje, descuento_monto, base_imponible, total_impuestos, total, observaciones, usuario_id, active, created_at, updated_at
`

type UpdateOrdenCompraEstadoParams struct {
	ID        pgtype.UUID       `json:"id"`
	UsuarioID pgtype.UUID       `json:"usuario_id"`
	Estado    EstadoOrdenCompra `json:"estado"`
}

func (q *Queries) UpdateOrdenCompraEstado(ctx context.Context, arg UpdateOrdenCompraEstadoParams) (OrdenesCompra, error) {
	row := q.db.QueryRow(ctx, updateOrdenCompraEstado, arg.ID, arg.UsuarioID, arg.Estado)
	var i OrdenesCompra
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.ProveedorID,
		&i.SucursalID,
		&i.Estado,
		&i.CondicionPago,
		&i.FechaOrden,
		&i.FechaEntregaEstimada,
		&i.Subtotal,
		&i.DescuentoPorcentaje,
		&i.DescuentoMonto,
		&i.BaseImponible,
		&i.TotalImpuestos,
		&i.Total,
		&i.Observaciones,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
