// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pedidos.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPedidos = `-- name: CountPedidos :one
SELECT COUNT(*) FROM pedidos
WHERE usuario_id = $1 AND active = TRUE
`

func (q *Queries) CountPedidos(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPedidos, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPedidosByCliente = `-- name: CountPedidosByCliente :one
SELECT COUNT(*) FROM pedidos
WHERE usuario_id = $1 AND cliente_id = $2 AND active = TRUE
`

type CountPedidosByClienteParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	ClienteID pgtype.UUID `json:"cliente_id"`
}

func (q *Queries) CountPedidosByCliente(ctx context.Context, arg CountPedidosByClienteParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPedidosByCliente, arg.UsuarioID, arg.ClienteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPedidosByEstado = `-- name: CountPedidosByEstado :one
SELECT COUNT(*) FROM pedidos
WHERE usuario_id = $1 AND estado = $2 AND active = TRUE
`

type CountPedidosByEstadoParams struct {
	UsuarioID pgtype.UUID  `json:"usuario_id"`
	Estado    EstadoPedido `json:"estado"`
}

func (q *Queries) CountPedidosByEstado(ctx context.Context, arg CountPedidosByEstadoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPedidosByEstado, arg.UsuarioID, arg.Estado)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchPedidos = `-- name: CountSearchPedidos :one
SELECT COUNT(*)
FROM pedidos p
JOIN clientes c ON c.id = p.cliente_id
WHERE p.usuario_id = $1 AND p.active = TRUE
  AND (p.numero ILIKE $2 OR c.nombre ILIKE $2 OR c.apellido ILIKE $2 OR c.razon_social ILIKE $2)
`

type CountSearchPedidosParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Numero    string      `json:"numero"`
}

func (q *Queries) CountSearchPedidos(ctx context.Context, arg CountSearchPedidosParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchPedidos, arg.UsuarioID, arg.Numero)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPedido = `-- name: CreatePedido :one
INSERT INTO pedidos (
  numero, cliente_id, direccion_id, sucursal_id, empleado_id,
  estado, condicion_pago, fecha_entrega_estimada,
  subtotal, descuento_porcentaje, descuento_monto,
  base_imponible, total_impuestos, total,
  observaciones, observaciones_internas, usuario_id
) VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8,
  $9, $10, $11,
  $12, $13, $14,
  $15, $16, $17
) RETURNING id, numero, cliente_id, direccion_id, sucursal_id, empleado_id, estado, condicion_pago, fecha_pedido, fecha_entrega_estimada, fecha_entrega_real, subtotal, descuento_porcentaje, descuento_monto, base_imponible, total_impuestos, total, observaciones, observaciones_internas, usuario_id, active, created_at, updated_at
`

type CreatePedidoParams struct {
	Numero                string         `json:"numero"`
	ClienteID             pgtype.UUID    `json:"cliente_id"`
	DireccionID           pgtype.UUID    `json:"direccion_id"`
	SucursalID            pgtype.UUID    `json:"sucursal_id"`
	EmpleadoID            pgtype.UUID    `json:"empleado_id"`
	Estado                EstadoPedido   `json:"estado"`
	CondicionPago         CondicionPago  `json:"condicion_pago"`
	FechaEntregaEstimada  pgtype.Date    `json:"fecha_entrega_estimada"`
	Subtotal              pgtype.Numeric `json:"subtotal"`
	DescuentoPorcentaje   pgtype.Numeric `json:"descuento_porcentaje"`
	DescuentoMonto        pgtype.Numeric `json:"descuento_monto"`
	BaseImponible         pgtype.Numeric `json:"base_imponible"`
	TotalImpuestos        pgtype.Numeric `json:"total_impuestos"`
	Total                 pgtype.Numeric `json:"total"`
	Observaciones         pgtype.Text    `json:"observaciones"`
	ObservacionesInternas pgtype.Text    `json:"observaciones_internas"`
	UsuarioID             pgtype.UUID    `json:"usuario_id"`
}

func (q *Queries) CreatePedido(ctx context.Context, arg CreatePedidoParams) (Pedido, error) {
	row := q.db.QueryRow(ctx, createPedido,
		arg.Numero,
		arg.ClienteID,
		arg.DireccionID,
		arg.SucursalID,
		arg.EmpleadoID,
		arg.Estado,
		arg.CondicionPago,
		arg.FechaEntregaEstimada,
		arg.Subtotal,
		arg.DescuentoPorcentaje,
		arg.DescuentoMonto,
		arg.BaseImponible,
		arg.TotalImpuestos,
		arg.Total,
		arg.Observaciones,
		arg.ObservacionesInternas,
		arg.UsuarioID,
	)
	var i Pedido
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.ClienteID,
		&i.DireccionID,
		&i.SucursalID,
		&i.EmpleadoID,
		&i.Estado,
		&i.CondicionPago,
		&i.FechaPedido,
		&i.FechaEntregaEstimada,
		&i.FechaEntregaReal,
		&i.Subtotal,
		&i.DescuentoPorcentaje,
		&i.DescuentoMonto,
		&i.BaseImponible,
		&i.TotalImpuestos,
		&i.Total,
		&i.Observaciones,
		&i.ObservacionesInternas,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPedidoByID = `-- name: GetPedidoByID :one
SELECT p.id, p.numero, p.cliente_id, p.direccion_id, p.sucursal_id, p.empleado_id, p.estado, p.condicion_pago, p.fecha_pedido, p.fecha_entrega_estimada, p.fecha_entrega_real, p.subtotal, p.descuento_porcentaje, p.descuento_monto, p.base_imponible, p.total_impuestos, p.total, p.observaciones, p.observaciones_internas, p.usuario_id, p.active, p.created_at, p.updated_at,
       c.nombre AS cliente_nombre,
       c.apellido AS cliente_apellido,
       c.cuit AS cliente_cuit,
       s.nombre AS sucursal_nombre,
       e.nombre AS empleado_nombre,
       e.apellido AS empleado_apellido
FROM pedidos p
JOIN clientes c ON c.id = p.cliente_id
JOIN sucursales s ON s.id = p.sucursal_id
LEFT JOIN empleados e ON e.id = p.empleado_id
WHERE p.id = $1 AND p.usuario_id = $2 AND p.active = TRUE
`

type GetPedidoByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

type GetPedidoByIDRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Numero                string             `json:"numero"`
	ClienteID             pgtype.UUID        `json:"cliente_id"`
	DireccionID           pgtype.UUID        `json:"direccion_id"`
	SucursalID            pgtype.UUID        `json:"sucursal_id"`
	EmpleadoID            pgtype.UUID        `json:"empleado_id"`
	Estado                EstadoPedido       `json:"estado"`
	CondicionPago         CondicionPago      `json:"condicion_pago"`
	FechaPedido           pgtype.Timestamptz `json:"fecha_pedido"`
	FechaEntregaEstimada  pgtype.Date        `json:"fecha_entrega_estimada"`
	FechaEntregaReal      pgtype.Timestamptz `json:"fecha_entrega_real"`
	Subtotal              pgtype.Numeric     `json:"subtotal"`
	DescuentoPorcentaje   pgtype.Numeric     `json:"descuento_porcentaje"`
	DescuentoMonto        pgtype.Numeric     `json:"descuento_monto"`
	BaseImponible         pgtype.Numeric     `json:"base_imponible"`
	TotalImpuestos        pgtype.Numeric     `json:"total_impuestos"`
	Total                 pgtype.Numeric     `json:"total"`
	Observaciones         pgtype.Text        `json:"observaciones"`
	ObservacionesInternas pgtype.Text        `json:"observaciones_internas"`
	UsuarioID             pgtype.UUID        `json:"usuario_id"`
	Active                bool               `json:"active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	ClienteNombre         string             `json:"cliente_nombre"`
	ClienteApellido       pgtype.Text        `json:"cliente_apellido"`
	ClienteCuit           pgtype.Text        `json:"cliente_cuit"`
	SucursalNombre        string             `json:"sucursal_nombre"`
	EmpleadoNombre        pgtype.Text        `json:"empleado_nombre"`
	EmpleadoApellido      pgtype.Text        `json:"empleado_apellido"`
}

func (q *Queries) GetPedidoByID(ctx context.Context, arg GetPedidoByIDParams) (GetPedidoByIDRow, error) {
	row := q.db.QueryRow(ctx, getPedidoByID, arg.ID, arg.UsuarioID)
	var i GetPedidoByIDRow
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.ClienteID,
		&i.DireccionID,
		&i.SucursalID,
		&i.EmpleadoID,
		&i.Estado,
		&i.CondicionPago,
		&i.FechaPedido,
		&i.FechaEntregaEstimada,
		&i.FechaEntregaReal,
		&i.Subtotal,
		&i.DescuentoPorcentaje,
		&i.DescuentoMonto,
		&i.BaseImponible,
		&i.TotalImpuestos,
		&i.Total,
		&i.Observaciones,
		&i.ObservacionesInternas,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClienteNombre,
		&i.ClienteApellido,
		&i.ClienteCuit,
		&i.SucursalNombre,
		&i.EmpleadoNombre,
		&i.EmpleadoApellido,
	)
	return i, err
}

const listPedidos = `-- name: ListPedidos :many
SELECT p.id, p.numero, p.cliente_id, p.direccion_id, p.sucursal_id, p.empleado_id, p.estado, p.condicion_pago, p.fecha_pedido, p.fecha_entrega_estimada, p.fecha_entrega_real, p.subtotal, p.descuento_porcentaje, p.descuento_monto, p.base_imponible, p.total_impuestos, p.total, p.observaciones, p.observaciones_internas, p.usuario_id, p.active, p.created_at, p.updated_at,
       c.nombre AS cliente_nombre,
       c.apellido AS cliente_apellido,
       s.nombre AS sucursal_nombre
FROM pedidos p
JOIN clientes c ON c.id = p.cliente_id
JOIN sucursales s ON s.id = p.sucursal_id
WHERE p.usuario_id = $1 AND p.active = TRUE
ORDER BY p.fecha_pedido DESC
LIMIT $2 OFFSET $3
`

type ListPedidosParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListPedidosRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Numero                string             `json:"numero"`
	ClienteID             pgtype.UUID        `json:"cliente_id"`
	DireccionID           pgtype.UUID        `json:"direccion_id"`
	SucursalID            pgtype.UUID        `json:"sucursal_id"`
	EmpleadoID            pgtype.UUID        `json:"empleado_id"`
	Estado                EstadoPedido       `json:"estado"`
	CondicionPago         CondicionPago      `json:"condicion_pago"`
	FechaPedido           pgtype.Timestamptz `json:"fecha_pedido"`
	FechaEntregaEstimada  pgtype.Date        `json:"fecha_entrega_estimada"`
	FechaEntregaReal      pgtype.Timestamptz `json:"fecha_entrega_real"`
	Subtotal              pgtype.Numeric     `json:"subtotal"`
	DescuentoPorcentaje   pgtype.Numeric     `json:"descuento_porcentaje"`
	DescuentoMonto        pgtype.Numeric     `json:"descuento_monto"`
	BaseImponible         pgtype.Numeric     `json:"base_imponible"`
	TotalImpuestos        pgtype.Numeric     `json:"total_impuestos"`
	Total                 pgtype.Numeric     `json:"total"`
	Observaciones         pgtype.Text        `json:"observaciones"`
	ObservacionesInternas pgtype.Text        `json:"observaciones_internas"`
	UsuarioID             pgtype.UUID        `json:"usuario_id"`
	Active                bool               `json:"active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	ClienteNombre         string             `json:"cliente_nombre"`
	ClienteApellido       pgtype.Text        `json:"cliente_apellido"`
	SucursalNombre        string             `json:"sucursal_nombre"`
}

func (q *Queries) ListPedidos(ctx context.Context, arg ListPedidosParams) ([]ListPedidosRow, error) {
	rows, err := q.db.Query(ctx, listPedidos, arg.UsuarioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPedidosRow
	for rows.Next() {
		var i ListPedidosRow
		if err := rows.Scan(
			&i.ID,
			&i.Numero,
			&i.ClienteID,
			&i.DireccionID,
			&i.SucursalID,
			&i.EmpleadoID,
			&i.Estado,
			&i.CondicionPago,
			&i.FechaPedido,
			&i.FechaEntregaEstimada,
			&i.FechaEntregaReal,
			&i.Subtotal,
			&i.DescuentoPorcentaje,
			&i.DescuentoMonto,
			&i.BaseImponible,
			&i.TotalImpuestos,
			&i.Total,
			&i.Observaciones,
			&i.ObservacionesInternas,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClienteNombre,
			&i.ClienteApellido,
			&i.SucursalNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPedidosByCliente = `-- name: ListPedidosByCliente :many
SELECT p.id, p.numero, p.cliente_id, p.direccion_id, p.sucursal_id, p.empleado_id, p.estado, p.condicion_pago, p.fecha_pedido, p.fecha_entrega_estimada, p.fecha_entrega_real, p.subtotal, p.descuento_porcentaje, p.descuento_monto, p.base_imponible, p.total_impuestos, p.total, p.observaciones, p.observaciones_internas, p.usuario_id, p.active, p.created_at, p.updated_at,
       c.nombre AS cliente_nombre,
       c.apellido AS cliente_apellido,
       s.nombre AS sucursal_nombre
FROM pedidos p
JOIN clientes c ON c.id = p.cliente_id
JOIN sucursales s ON s.id = p.sucursal_id
WHERE p.usuario_id = $1 AND p.cliente_id = $2 AND p.active = TRUE
ORDER BY p.fecha_pedido DESC
LIMIT $3 OFFSET $4
`

type ListPedidosByClienteParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	ClienteID pgtype.UUID `json:"cliente_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListPedidosByClienteRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Numero                string             `json:"numero"`
	ClienteID             pgtype.UUID        `json:"cliente_id"`
	DireccionID           pgtype.UUID        `json:"direccion_id"`
	SucursalID            pgtype.UUID        `json:"sucursal_id"`
	EmpleadoID            pgtype.UUID        `json:"empleado_id"`
	Estado                EstadoPedido       `json:"estado"`
	CondicionPago         CondicionPago      `json:"condicion_pago"`
	FechaPedido           pgtype.Timestamptz `json:"fecha_pedido"`
	FechaEntregaEstimada  pgtype.Date        `json:"fecha_entrega_estimada"`
	FechaEntregaReal      pgtype.Timestamptz `json:"fecha_entrega_real"`
	Subtotal              pgtype.Numeric     `json:"subtotal"`
	DescuentoPorcentaje   pgtype.Numeric     `json:"descuento_porcentaje"`
	DescuentoMonto        pgtype.Numeric     `json:"descuento_monto"`
	BaseImponible         pgtype.Numeric     `json:"base_imponible"`
	TotalImpuestos        pgtype.Numeric     `json:"total_impuestos"`
	Total                 pgtype.Numeric     `json:"total"`
	Observaciones         pgtype.Text        `json:"observaciones"`
	ObservacionesInternas pgtype.Text        `json:"observaciones_internas"`
	UsuarioID             pgtype.UUID        `json:"usuario_id"`
	Active                bool               `json:"active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	ClienteNombre         string             `json:"cliente_nombre"`
	ClienteApellido       pgtype.Text        `json:"cliente_apellido"`
	SucursalNombre        string             `json:"sucursal_nombre"`
}

func (q *Queries) ListPedidosByCliente(ctx context.Context, arg ListPedidosByClienteParams) ([]ListPedidosByClienteRow, error) {
	rows, err := q.db.Query(ctx, listPedidosByCliente,
		arg.UsuarioID,
		arg.ClienteID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPedidosByClienteRow
	for rows.Next() {
		var i ListPedidosByClienteRow
		if err := rows.Scan(
			&i.ID,
			&i.Numero,
			&i.ClienteID,
			&i.DireccionID,
			&i.SucursalID,
			&i.EmpleadoID,
			&i.Estado,
			&i.CondicionPago,
			&i.FechaPedido,
			&i.FechaEntregaEstimada,
			&i.FechaEntregaReal,
			&i.Subtotal,
			&i.DescuentoPorcentaje,
			&i.DescuentoMonto,
			&i.BaseImponible,
			&i.TotalImpuestos,
			&i.Total,
			&i.Observaciones,
			&i.ObservacionesInternas,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClienteNombre,
			&i.ClienteApellido,
			&i.SucursalNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPedidosByEstado = `-- name: ListPedidosByEstado :many
SELECT p.id, p.numero, p.cliente_id, p.direccion_id, p.sucursal_id, p.empleado_id, p.estado, p.condicion_pago, p.fecha_pedido, p.fecha_entrega_estimada, p.fecha_entrega_real, p.subtotal, p.descuento_porcentaje, p.descuento_monto, p.base_imponible, p.total_impuestos, p.total, p.observaciones, p.observaciones_internas, p.usuario_id, p.active, p.created_at, p.updated_at,
       c.nombre AS cliente_nombre,
       c.apellido AS cliente_apellido,
       s.nombre AS sucursal_nombre
FROM pedidos p
JOIN clientes c ON c.id = p.cliente_id
JOIN sucursales s ON s.id = p.sucursal_id
WHERE p.usuario_id = $1 AND p.estado = $2 AND p.active = TRUE
ORDER BY p.fecha_pedido DESC
LIMIT $3 OFFSET $4
`

type ListPedidosByEstadoParams struct {
	UsuarioID pgtype.UUID  `json:"usuario_id"`
	Estado    EstadoPedido `json:"estado"`
	Limit     int32        `json:"limit"`
	Offset    int32        `json:"offset"`
}

type ListPedidosByEstadoRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Numero                string             `json:"numero"`
	ClienteID             pgtype.UUID        `json:"cliente_id"`
	DireccionID           pgtype.UUID        `json:"direccion_id"`
	SucursalID            pgtype.UUID        `json:"sucursal_id"`
	EmpleadoID            pgtype.UUID        `json:"empleado_id"`
	Estado                EstadoPedido       `json:"estado"`
	CondicionPago         CondicionPago      `json:"condicion_pago"`
	FechaPedido           pgtype.Timestamptz `json:"fecha_pedido"`
	FechaEntregaEstimada  pgtype.Date        `json:"fecha_entrega_estimada"`
	FechaEntregaReal      pgtype.Timestamptz `json:"fecha_entrega_real"`
	Subtotal              pgtype.Numeric     `json:"subtotal"`
	DescuentoPorcentaje   pgtype.Numeric     `json:"descuento_porcentaje"`
	DescuentoMonto        pgtype.Numeric     `json:"descuento_monto"`
	BaseImponible         pgtype.Numeric     `json:"base_imponible"`
	TotalImpuestos        pgtype.Numeric     `json:"total_impuestos"`
	Total                 pgtype.Numeric     `json:"total"`
	Observaciones         pgtype.Text        `json:"observaciones"`
	ObservacionesInternas pgtype.Text        `json:"observaciones_internas"`
	UsuarioID             pgtype.UUID        `json:"usuario_id"`
	Active                bool               `json:"active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	ClienteNombre         string             `json:"cliente_nombre"`
	ClienteApellido       pgtype.Text        `json:"cliente_apellido"`
	SucursalNombre        string             `json:"sucursal_nombre"`
}

func (q *Queries) ListPedidosByEstado(ctx context.Context, arg ListPedidosByEstadoParams) ([]ListPedidosByEstadoRow, error) {
	rows, err := q.db.Query(ctx, listPedidosByEstado,
		arg.UsuarioID,
		arg.Estado,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPedidosByEstadoRow
	for rows.Next() {
		var i ListPedidosByEstadoRow
		if err := rows.Scan(
			&i.ID,
			&i.Numero,
			&i.ClienteID,
			&i.DireccionID,
			&i.SucursalID,
			&i.EmpleadoID,
			&i.Estado,
			&i.CondicionPago,
			&i.FechaPedido,
			&i.FechaEntregaEstimada,
			&i.FechaEntregaReal,
			&i.Subtotal,
			&i.DescuentoPorcentaje,
			&i.DescuentoMonto,
			&i.BaseImponible,
			&i.TotalImpuestos,
			&i.Total,
			&i.Observaciones,
			&i.ObservacionesInternas,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClienteNombre,
			&i.ClienteApellido,
			&i.SucursalNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextPedidoNumero = `-- name: NextPedidoNumero :one
SELECT nextval('pedido_numero_seq')::bigint
`

func (q *Queries) NextPedidoNumero(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextPedidoNumero)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const searchPedidos = `-- name: SearchPedidos :many
SELECT p.id, p.numero, p.cliente_id, p.direccion_id, p.sucursal_id, p.empleado_id, p.estado, p.condicion_pago, p.fecha_pedido, p.fecha_entrega_estimada, p.fecha_entrega_real, p.subtotal, p.descuento_porcentaje, p.descuento_monto, p.base_imponible, p.total_impuestos, p.total, p.observaciones, p.observaciones_internas, p.usuario_id, p.active, p.created_at, p.updated_at,
       c.nombre AS cliente_nombre,
       c.apellido AS cliente_apellido,
       s.nombre AS sucursal_nombre
FROM pedidos p
JOIN clientes c ON c.id = p.cliente_id
JOIN sucursales s ON s.id = p.sucursal_id
WHERE p.usuario_id = $1 AND p.active = TRUE
  AND (p.numero ILIKE $2 OR c.nombre ILIKE $2 OR c.apellido ILIKE $2 OR c.razon_social ILIKE $2)
ORDER BY p.fecha_pedido DESC
LIMIT $3 OFFSET $4
`

type SearchPedidosParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Numero    string      `json:"numero"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type SearchPedidosRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Numero                string             `json:"numero"`
	ClienteID             pgtype.UUID        `json:"cliente_id"`
	DireccionID           pgtype.UUID        `json:"direccion_id"`
	SucursalID            pgtype.UUID        `json:"sucursal_id"`
	EmpleadoID            pgtype.UUID        `json:"empleado_id"`
	Estado                EstadoPedido       `json:"estado"`
	CondicionPago         CondicionPago      `json:"condicion_pago"`
	FechaPedido           pgtype.Timestamptz `json:"fecha_pedido"`
	FechaEntregaEstimada  pgtype.Date        `json:"fecha_entrega_estimada"`
	FechaEntregaReal      pgtype.Timestamptz `json:"fecha_entrega_real"`
	Subtotal              pgtype.Numeric     `json:"subtotal"`
	DescuentoPorcentaje   pgtype.Numeric     `json:"descuento_porcentaje"`
	DescuentoMonto        pgtype.Numeric     `json:"descuento_monto"`
	BaseImponible         pgtype.Numeric     `json:"base_imponible"`
	TotalImpuestos        pgtype.Numeric     `json:"total_impuestos"`
	Total                 pgtype.Numeric     `json:"total"`
	Observaciones         pgtype.Text        `json:"observaciones"`
	ObservacionesInternas pgtype.Text        `json:"observaciones_internas"`
	UsuarioID             pgtype.UUID        `json:"usuario_id"`
	Active                bool               `json:"active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	ClienteNombre         string             `json:"cliente_nombre"`
	ClienteApellido       pgtype.Text        `json:"cliente_apellido"`
	SucursalNombre        string             `json:"sucursal_nombre"`
}

func (q *Queries) SearchPedidos(ctx context.Context, arg SearchPedidosParams) ([]SearchPedidosRow, error) {
	rows, err := q.db.Query(ctx, searchPedidos,
		arg.UsuarioID,
		arg.Numero,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPedidosRow
	for rows.Next() {
		var i SearchPedidosRow
		if err := rows.Scan(
			&i.ID,
			&i.Numero,
			&i.ClienteID,
			&i.DireccionID,
			&i.SucursalID,
			&i.EmpleadoID,
			&i.Estado,
			&i.CondicionPago,
			&i.FechaPedido,
			&i.FechaEntregaEstimada,
			&i.FechaEntregaReal,
			&i.Subtotal,
			&i.DescuentoPorcentaje,
			&i.DescuentoMonto,
			&i.BaseImponible,
			&i.TotalImpuestos,
			&i.Total,
			&i.Observaciones,
			&i.ObservacionesInternas,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClienteNombre,
			&i.ClienteApellido,
			&i.SucursalNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePedido = `-- name: SoftDeletePedido :exec
UPDATE pedidos
SET active = FALSE, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND estado = 'PENDIENTE_APROBACION'
`

type SoftDeletePedidoParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) SoftDeletePedido(ctx context.Context, arg SoftDeletePedidoParams) error {
	_, err := q.db.Exec(ctx, softDeletePedido, arg.ID, arg.UsuarioID)
	return err
}

const updatePedido = `-- name: UpdatePedido :one
UPDATE pedidos
SET cliente_id = $3, direccion_id = $4, sucursal_id = $5, empleado_id = $6,
    condicion_pago = $7, fecha_entrega_estimada = $8,
    subtotal = $9, descuento_porcentaje = $10, descuento_monto = $11,
    base_imponible = $12, total_impuestos = $13, total = $14,
    observaciones = $15, observaciones_internas = $16, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND active = TRUE AND estado = 'PENDIENTE_APROBACION'
RETURNING id, numero, cliente_id, direccion_id, sucursal_id, empleado_id, estado, condicion_pago, fecha_pedido, fecha_entrega_estimada, fecha_entrega_real, subtotal, descuento_porcentaje, descuento_monto, base_imponible, total_impuestos, total, observaciones, observaciones_internas, usuario_id, active, created_at, updated_at
`

type UpdatePedidoParams struct {
	ID                    pgtype.UUID    `json:"id"`
	UsuarioID             pgtype.UUID    `json:"usuario_id"`
	ClienteID             pgtype.UUID    `json:"cliente_id"`
	DireccionID           pgtype.UUID    `json:"direccion_id"`
	SucursalID            pgtype.UUID    `json:"sucursal_id"`
	EmpleadoID            pgtype.UUID    `json:"empleado_id"`
	CondicionPago         CondicionPago  `json:"condicion_pago"`
	FechaEntregaEstimada  pgtype.Date    `json:"fecha_entrega_estimada"`
	Subtotal              pgtype.Numeric `json:"subtotal"`
	DescuentoPorcentaje   pgtype.Numeric `json:"descuento_porcentaje"`
	DescuentoMonto        pgtype.Numeric `json:"descuento_monto"`
	BaseImponible         pgtype.Numeric `json:"base_imponible"`
	TotalImpuestos        pgtype.Numeric `json:"total_impuestos"`
	Total                 pgtype.Numeric `json:"total"`
	Observaciones         pgtype.Text    `json:"observaciones"`
	ObservacionesInternas pgtype.Text    `json:"observaciones_internas"`
}

func (q *Queries) UpdatePedido(ctx context.Context, arg UpdatePedidoParams) (Pedido, error) {
	row := q.db.QueryRow(ctx, updatePedido,
		arg.ID,
		arg.UsuarioID,
		arg.ClienteID,
		arg.DireccionID,
		arg.SucursalID,
		arg.EmpleadoID,
		arg.CondicionPago,
		arg.FechaEntregaEstimada,
		arg.Subtotal,
		arg.DescuentoPorcentaje,
		arg.DescuentoMonto,
		arg.BaseImponible,
		arg.TotalImpuestos,
		arg.Total,
		arg.Observaciones,
		arg.ObservacionesInternas,
	)
	var i Pedido
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.ClienteID,
		&i.DireccionID,
		&i.SucursalID,
		&i.EmpleadoID,
		&i.Estado,
		&i.CondicionPago,
		&i.FechaPedido,
		&i.FechaEntregaEstimada,
		&i.FechaEntregaReal,
		&i.Subtotal,
		&i.DescuentoPorcentaje,
		&i.DescuentoMonto,
		&i.BaseImponible,
		&i.TotalImpuestos,
		&i.Total,
		&i.Observaciones,
		&i.ObservacionesInternas,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePedidoEstado = `-- name: UpdatePedidoEstado :one
UPDATE pedidos
SET estado = $3, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
RETURNING id, numero, cliente_id, direccion_id, sucursal_id, empleado_id, estado, condicion_pago, fecha_pedido, fecha_entrega_estimada, fecha_entrega_real, subtotal, descuento_porcentaje, descuento_monto, base_imponible, total_impuestos, total, observaciones, observaciones_internas, usuario_id, active, created_at, updated_at
`

type UpdatePedidoEstadoParams struct {
	ID        pgtype.UUID  `json:"id"`
	UsuarioID pgtype.UUID  `json:"usuario_id"`
	Estado    EstadoPedido `json:"estado"`
}

func (q *Queries) UpdatePedidoEstado(ctx context.Context, arg UpdatePedidoEstadoParams) (Pedido, error) {
	row := q.db.QueryRow(ctx, updatePedidoEstado, arg.ID, arg.UsuarioID, arg.Estado)
	var i Pedido
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.ClienteID,
		&i.DireccionID,
		&i.SucursalID,
		&i.EmpleadoID,
		&i.Estado,
		&i.CondicionPago,
		&i.FechaPedido,
		&i.FechaEntregaEstimada,
		&i.FechaEntregaReal,
		&i.Subtotal,
		&i.DescuentoPorcentaje,
		&i.DescuentoMonto,
		&i.BaseImponible,
		&i.TotalImpuestos,
		&i.Total,
		&i.Observaciones,
		&i.ObservacionesInternas,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePedidoFechaEntregaReal = `-- name: UpdatePedidoFechaEntregaReal :exec
UPDATE pedidos
SET fecha_entrega_real = NOW(), updated_at = NOW()
WHERE id = $1 AND usuario_id = $2
`

type UpdatePedidoFechaEntregaRealParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) UpdatePedidoFechaEntregaReal(ctx context.Context, arg UpdatePedidoFechaEntregaRealParams) error {
	_, err := q.db.Exec(ctx, updatePedidoFechaEntregaReal, arg.ID, arg.UsuarioID)
	return err
}
