// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permission_overrides.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllPermissionOverridesForRole = `-- name: DeleteAllPermissionOverridesForRole :exec
DELETE FROM permission_overrides
WHERE rol = $1 AND usuario_id = $2
`

type DeleteAllPermissionOverridesForRoleParams struct {
	Rol       Rol         `json:"rol"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) DeleteAllPermissionOverridesForRole(ctx context.Context, arg DeleteAllPermissionOverridesForRoleParams) error {
	_, err := q.db.Exec(ctx, deleteAllPermissionOverridesForRole, arg.Rol, arg.UsuarioID)
	return err
}

const deletePermissionOverride = `-- name: DeletePermissionOverride :exec
DELETE FROM permission_overrides
WHERE rol = $1 AND permission = $2 AND usuario_id = $3
`

type DeletePermissionOverrideParams struct {
	Rol        Rol         `json:"rol"`
	Permission string      `json:"permission"`
	UsuarioID  pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) DeletePermissionOverride(ctx context.Context, arg DeletePermissionOverrideParams) error {
	_, err := q.db.Exec(ctx, deletePermissionOverride, arg.Rol, arg.Permission, arg.UsuarioID)
	return err
}

const listPermissionOverridesByUser = `-- name: ListPermissionOverridesByUser :many
SELECT id, rol, permission, granted, usuario_id, created_at, updated_at FROM permission_overrides
WHERE usuario_id = $1
ORDER BY rol, permission
`

func (q *Queries) ListPermissionOverridesByUser(ctx context.Context, usuarioID pgtype.UUID) ([]PermissionOverride, error) {
	rows, err := q.db.Query(ctx, listPermissionOverridesByUser, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PermissionOverride
	for rows.Next() {
		var i PermissionOverride
		if err := rows.Scan(
			&i.ID,
			&i.Rol,
			&i.Permission,
			&i.Granted,
			&i.UsuarioID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionOverridesByUserAndRole = `-- name: ListPermissionOverridesByUserAndRole :many
SELECT id, rol, permission, granted, usuario_id, created_at, updated_at FROM permission_overrides
WHERE usuario_id = $1 AND rol = $2
ORDER BY permission
`

type ListPermissionOverridesByUserAndRoleParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Rol       Rol         `json:"rol"`
}

func (q *Queries) ListPermissionOverridesByUserAndRole(ctx context.Context, arg ListPermissionOverridesByUserAndRoleParams) ([]PermissionOverride, error) {
	rows, err := q.db.Query(ctx, listPermissionOverridesByUserAndRole, arg.UsuarioID, arg.Rol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PermissionOverride
	for rows.Next() {
		var i PermissionOverride
		if err := rows.Scan(
			&i.ID,
			&i.Rol,
			&i.Permission,
			&i.Granted,
			&i.UsuarioID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPermissionOverride = `-- name: UpsertPermissionOverride :one
INSERT INTO permission_overrides (rol, permission, granted, usuario_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (rol, permission, usuario_id)
DO UPDATE SET granted = $3, updated_at = NOW()
RETURNING id, rol, permission, granted, usuario_id, created_at, updated_at
`

type UpsertPermissionOverrideParams struct {
	Rol        Rol         `json:"rol"`
	Permission string      `json:"permission"`
	Granted    bool        `json:"granted"`
	UsuarioID  pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) UpsertPermissionOverride(ctx context.Context, arg UpsertPermissionOverrideParams) (PermissionOverride, error) {
	row := q.db.QueryRow(ctx, upsertPermissionOverride,
		arg.Rol,
		arg.Permission,
		arg.Granted,
		arg.UsuarioID,
	)
	var i PermissionOverride
	err := row.Scan(
		&i.ID,
		&i.Rol,
		&i.Permission,
		&i.Granted,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
