// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: presupuestos.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPresupuestos = `-- name: CountPresupuestos :one
SELECT COUNT(*) FROM presupuestos
WHERE usuario_id = $1 AND active = TRUE
`

func (q *Queries) CountPresupuestos(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPresupuestos, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPresupuestosByEstado = `-- name: CountPresupuestosByEstado :one
SELECT COUNT(*) FROM presupuestos
WHERE usuario_id = $1 AND estado = $2 AND active = TRUE
`

type CountPresupuestosByEstadoParams struct {
	UsuarioID pgtype.UUID       `json:"usuario_id"`
	Estado    EstadoPresupuesto `json:"estado"`
}

func (q *Queries) CountPresupuestosByEstado(ctx context.Context, arg CountPresupuestosByEstadoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPresupuestosByEstado, arg.UsuarioID, arg.Estado)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPresupuesto = `-- name: CreatePresupuesto :one
INSERT INTO presupuestos (nombre, monto_asignado, monto_utilizado, periodo, fecha_inicio, fecha_fin, estado, sucursal_id, usuario_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, nombre, monto_asignado, monto_utilizado, periodo, fecha_inicio, fecha_fin, estado, sucursal_id, active, usuario_id, created_at, updated_at
`

type CreatePresupuestoParams struct {
	Nombre         string            `json:"nombre"`
	MontoAsignado  pgtype.Numeric    `json:"monto_asignado"`
	MontoUtilizado pgtype.Numeric    `json:"monto_utilizado"`
	Periodo        pgtype.Text       `json:"periodo"`
	FechaInicio    pgtype.Date       `json:"fecha_inicio"`
	FechaFin       pgtype.Date       `json:"fecha_fin"`
	Estado         EstadoPresupuesto `json:"estado"`
	SucursalID     pgtype.UUID       `json:"sucursal_id"`
	UsuarioID      pgtype.UUID       `json:"usuario_id"`
}

func (q *Queries) CreatePresupuesto(ctx context.Context, arg CreatePresupuestoParams) (Presupuesto, error) {
	row := q.db.QueryRow(ctx, createPresupuesto,
		arg.Nombre,
		arg.MontoAsignado,
		arg.MontoUtilizado,
		arg.Periodo,
		arg.FechaInicio,
		arg.FechaFin,
		arg.Estado,
		arg.SucursalID,
		arg.UsuarioID,
	)
	var i Presupuesto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.MontoAsignado,
		&i.MontoUtilizado,
		&i.Periodo,
		&i.FechaInicio,
		&i.FechaFin,
		&i.Estado,
		&i.SucursalID,
		&i.Active,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPresupuestoByID = `-- name: GetPresupuestoByID :one
SELECT id, nombre, monto_asignado, monto_utilizado, periodo, fecha_inicio, fecha_fin, estado, sucursal_id, active, usuario_id, created_at, updated_at FROM presupuestos
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
`

type GetPresupuestoByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) GetPresupuestoByID(ctx context.Context, arg GetPresupuestoByIDParams) (Presupuesto, error) {
	row := q.db.QueryRow(ctx, getPresupuestoByID, arg.ID, arg.UsuarioID)
	var i Presupuesto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.MontoAsignado,
		&i.MontoUtilizado,
		&i.Periodo,
		&i.FechaInicio,
		&i.FechaFin,
		&i.Estado,
		&i.SucursalID,
		&i.Active,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPresupuestos = `-- name: ListPresupuestos :many
SELECT id, nombre, monto_asignado, monto_utilizado, periodo, fecha_inicio, fecha_fin, estado, sucursal_id, active, usuario_id, created_at, updated_at FROM presupuestos
WHERE usuario_id = $1 AND active = TRUE
ORDER BY fecha_inicio DESC
LIMIT $2 OFFSET $3
`

type ListPresupuestosParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListPresupuestos(ctx context.Context, arg ListPresupuestosParams) ([]Presupuesto, error) {
	rows, err := q.db.Query(ctx, listPresupuestos, arg.UsuarioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Presupuesto
	for rows.Next() {
		var i Presupuesto
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.MontoAsignado,
			&i.MontoUtilizado,
			&i.Periodo,
			&i.FechaInicio,
			&i.FechaFin,
			&i.Estado,
			&i.SucursalID,
			&i.Active,
			&i.UsuarioID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresupuestosByEstado = `-- name: ListPresupuestosByEstado :many
SELECT id, nombre, monto_asignado, monto_utilizado, periodo, fecha_inicio, fecha_fin, estado, sucursal_id, active, usuario_id, created_at, updated_at FROM presupuestos
WHERE usuario_id = $1 AND estado = $2 AND active = TRUE
ORDER BY fecha_inicio DESC
LIMIT $3 OFFSET $4
`

type ListPresupuestosByEstadoParams struct {
	UsuarioID pgtype.UUID       `json:"usuario_id"`
	Estado    EstadoPresupuesto `json:"estado"`
	Limit     int32             `json:"limit"`
	Offset    int32             `json:"offset"`
}

func (q *Queries) ListPresupuestosByEstado(ctx context.Context, arg ListPresupuestosByEstadoParams) ([]Presupuesto, error) {
	rows, err := q.db.Query(ctx, listPresupuestosByEstado,
		arg.UsuarioID,
		arg.Estado,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Presupuesto
	for rows.Next() {
		var i Presupuesto
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.MontoAsignado,
			&i.MontoUtilizado,
			&i.Periodo,
			&i.FechaInicio,
			&i.FechaFin,
			&i.Estado,
			&i.SucursalID,
			&i.Active,
			&i.UsuarioID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePresupuesto = `-- name: SoftDeletePresupuesto :exec
UPDATE presupuestos
SET active = FALSE, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2
`

type SoftDeletePresupuestoParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) SoftDeletePresupuesto(ctx context.Context, arg SoftDeletePresupuestoParams) error {
	_, err := q.db.Exec(ctx, softDeletePresupuesto, arg.ID, arg.UsuarioID)
	return err
}

const updatePresupuesto = `-- name: UpdatePresupuesto :one
UPDATE presupuestos
SET nombre = $3, monto_asignado = $4, periodo = $5, fecha_inicio = $6, fecha_fin = $7,
    estado = $8, sucursal_id = $9, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
RETURNING id, nombre, monto_asignado, monto_utilizado, periodo, fecha_inicio, fecha_fin, estado, sucursal_id, active, usuario_id, created_at, updated_at
`

type UpdatePresupuestoParams struct {
	ID            pgtype.UUID       `json:"id"`
	UsuarioID     pgtype.UUID       `json:"usuario_id"`
	Nombre        string            `json:"nombre"`
	MontoAsignado pgtype.Numeric    `json:"monto_asignado"`
	Periodo       pgtype.Text       `json:"periodo"`
	FechaInicio   pgtype.Date       `json:"fecha_inicio"`
	FechaFin      pgtype.Date       `json:"fecha_fin"`
	Estado        EstadoPresupuesto `json:"estado"`
	SucursalID    pgtype.UUID       `json:"sucursal_id"`
}

func (q *Queries) UpdatePresupuesto(ctx context.Context, arg UpdatePresupuestoParams) (Presupuesto, error) {
	row := q.db.QueryRow(ctx, updatePresupuesto,
		arg.ID,
		arg.UsuarioID,
		arg.Nombre,
		arg.MontoAsignado,
		arg.Periodo,
		arg.FechaInicio,
		arg.FechaFin,
		arg.Estado,
		arg.SucursalID,
	)
	var i Presupuesto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.MontoAsignado,
		&i.MontoUtilizado,
		&i.Periodo,
		&i.FechaInicio,
		&i.FechaFin,
		&i.Estado,
		&i.SucursalID,
		&i.Active,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePresupuestoMontoUtilizado = `-- name: UpdatePresupuestoMontoUtilizado :one
UPDATE presupuestos
SET monto_utilizado = $3, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
RETURNING id, nombre, monto_asignado, monto_utilizado, periodo, fecha_inicio, fecha_fin, estado, sucursal_id, active, usuario_id, created_at, updated_at
`

type UpdatePresupuestoMontoUtilizadoParams struct {
	ID             pgtype.UUID    `json:"id"`
	UsuarioID      pgtype.UUID    `json:"usuario_id"`
	MontoUtilizado pgtype.Numeric `json:"monto_utilizado"`
}

func (q *Queries) UpdatePresupuestoMontoUtilizado(ctx context.Context, arg UpdatePresupuestoMontoUtilizadoParams) (Presupuesto, error) {
	row := q.db.QueryRow(ctx, updatePresupuestoMontoUtilizado, arg.ID, arg.UsuarioID, arg.MontoUtilizado)
	var i Presupuesto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.MontoAsignado,
		&i.MontoUtilizado,
		&i.Periodo,
		&i.FechaInicio,
		&i.FechaFin,
		&i.Estado,
		&i.SucursalID,
		&i.Active,
		&i.UsuarioID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
