// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: productos.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProductos = `-- name: CountProductos :one
SELECT COUNT(*) FROM productos
WHERE usuario_id = $1 AND active = TRUE
`

func (q *Queries) CountProductos(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProductos, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchProductos = `-- name: CountSearchProductos :one
SELECT COUNT(*) FROM productos
WHERE usuario_id = $1 AND active = TRUE
  AND (nombre ILIKE $2 OR codigo ILIKE $2)
`

type CountSearchProductosParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Nombre    string      `json:"nombre"`
}

func (q *Queries) CountSearchProductos(ctx context.Context, arg CountSearchProductosParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchProductos, arg.UsuarioID, arg.Nombre)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProducto = `-- name: CreateProducto :one
INSERT INTO productos (codigo, nombre, descripcion, precio_base, unidad, categoria_id, usuario_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, codigo, nombre, descripcion, precio_base, unidad, categoria_id, usuario_id, active, created_at, updated_at
`

type CreateProductoParams struct {
	Codigo      pgtype.Text    `json:"codigo"`
	Nombre      string         `json:"nombre"`
	Descripcion pgtype.Text    `json:"descripcion"`
	PrecioBase  pgtype.Numeric `json:"precio_base"`
	Unidad      UnidadDeMedida `json:"unidad"`
	CategoriaID pgtype.UUID    `json:"categoria_id"`
	UsuarioID   pgtype.UUID    `json:"usuario_id"`
}

func (q *Queries) CreateProducto(ctx context.Context, arg CreateProductoParams) (Producto, error) {
	row := q.db.QueryRow(ctx, createProducto,
		arg.Codigo,
		arg.Nombre,
		arg.Descripcion,
		arg.PrecioBase,
		arg.Unidad,
		arg.CategoriaID,
		arg.UsuarioID,
	)
	var i Producto
	err := row.Scan(
		&i.ID,
		&i.Codigo,
		&i.Nombre,
		&i.Descripcion,
		&i.PrecioBase,
		&i.Unidad,
		&i.CategoriaID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductoByCodigo = `-- name: GetProductoByCodigo :one
SELECT id, codigo, nombre, descripcion, precio_base, unidad, categoria_id, usuario_id, active, created_at, updated_at FROM productos
WHERE codigo = $1 AND usuario_id = $2 AND active = TRUE
`

type GetProductoByCodigoParams struct {
	Codigo    pgtype.Text `json:"codigo"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) GetProductoByCodigo(ctx context.Context, arg GetProductoByCodigoParams) (Producto, error) {
	row := q.db.QueryRow(ctx, getProductoByCodigo, arg.Codigo, arg.UsuarioID)
	var i Producto
	err := row.Scan(
		&i.ID,
		&i.Codigo,
		&i.Nombre,
		&i.Descripcion,
		&i.PrecioBase,
		&i.Unidad,
		&i.CategoriaID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductoByID = `-- name: GetProductoByID :one
SELECT p.id, p.codigo, p.nombre, p.descripcion, p.precio_base, p.unidad, p.categoria_id, p.usuario_id, p.active, p.created_at, p.updated_at,
       c.nombre AS categoria_nombre,
       f.nombre AS familia_nombre
FROM productos p
LEFT JOIN categorias_producto c ON c.id = p.categoria_id
LEFT JOIN familias_producto f ON f.id = c.familia_id
WHERE p.id = $1 AND p.usuario_id = $2 AND p.active = TRUE
`

type GetProductoByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

type GetProductoByIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	Codigo          pgtype.Text        `json:"codigo"`
	Nombre          string             `json:"nombre"`
	Descripcion     pgtype.Text        `json:"descripcion"`
	PrecioBase      pgtype.Numeric     `json:"precio_base"`
	Unidad          UnidadDeMedida     `json:"unidad"`
	CategoriaID     pgtype.UUID        `json:"categoria_id"`
	UsuarioID       pgtype.UUID        `json:"usuario_id"`
	Active          bool               `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CategoriaNombre pgtype.Text        `json:"categoria_nombre"`
	FamiliaNombre   pgtype.Text        `json:"familia_nombre"`
}

func (q *Queries) GetProductoByID(ctx context.Context, arg GetProductoByIDParams) (GetProductoByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductoByID, arg.ID, arg.UsuarioID)
	var i GetProductoByIDRow
	err := row.Scan(
		&i.ID,
		&i.Codigo,
		&i.Nombre,
		&i.Descripcion,
		&i.PrecioBase,
		&i.Unidad,
		&i.CategoriaID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoriaNombre,
		&i.FamiliaNombre,
	)
	return i, err
}

const listProductos = `-- name: ListProductos :many
SELECT p.id, p.codigo, p.nombre, p.descripcion, p.precio_base, p.unidad, p.categoria_id, p.usuario_id, p.active, p.created_at, p.updated_at,
       c.nombre AS categoria_nombre,
       f.nombre AS familia_nombre
FROM productos p
LEFT JOIN categorias_producto c ON c.id = p.categoria_id
LEFT JOIN familias_producto f ON f.id = c.familia_id
WHERE p.usuario_id = $1 AND p.active = TRUE
ORDER BY p.nombre
LIMIT $2 OFFSET $3
`

type ListProductosParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListProductosRow struct {
	ID              pgtype.UUID        `json:"id"`
	Codigo          pgtype.Text        `json:"codigo"`
	Nombre          string             `json:"nombre"`
	Descripcion     pgtype.Text        `json:"descripcion"`
	PrecioBase      pgtype.Numeric     `json:"precio_base"`
	Unidad          UnidadDeMedida     `json:"unidad"`
	CategoriaID     pgtype.UUID        `json:"categoria_id"`
	UsuarioID       pgtype.UUID        `json:"usuario_id"`
	Active          bool               `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CategoriaNombre pgtype.Text        `json:"categoria_nombre"`
	FamiliaNombre   pgtype.Text        `json:"familia_nombre"`
}

func (q *Queries) ListProductos(ctx context.Context, arg ListProductosParams) ([]ListProductosRow, error) {
	rows, err := q.db.Query(ctx, listProductos, arg.UsuarioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductosRow
	for rows.Next() {
		var i ListProductosRow
		if err := rows.Scan(
			&i.ID,
			&i.Codigo,
			&i.Nombre,
			&i.Descripcion,
			&i.PrecioBase,
			&i.Unidad,
			&i.CategoriaID,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoriaNombre,
			&i.FamiliaNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductosByCategoria = `-- name: ListProductosByCategoria :many
SELECT p.id, p.codigo, p.nombre, p.descripcion, p.precio_base, p.unidad, p.categoria_id, p.usuario_id, p.active, p.created_at, p.updated_at,
       c.nombre AS categoria_nombre,
       f.nombre AS familia_nombre
FROM productos p
LEFT JOIN categorias_producto c ON c.id = p.categoria_id
LEFT JOIN familias_producto f ON f.id = c.familia_id
WHERE p.categoria_id = $1 AND p.usuario_id = $2 AND p.active = TRUE
ORDER BY p.nombre
`

type ListProductosByCategoriaParams struct {
	CategoriaID pgtype.UUID `json:"categoria_id"`
	UsuarioID   pgtype.UUID `json:"usuario_id"`
}

type ListProductosByCategoriaRow struct {
	ID              pgtype.UUID        `json:"id"`
	Codigo          pgtype.Text        `json:"codigo"`
	Nombre          string             `json:"nombre"`
	Descripcion     pgtype.Text        `json:"descripcion"`
	PrecioBase      pgtype.Numeric     `json:"precio_base"`
	Unidad          UnidadDeMedida     `json:"unidad"`
	CategoriaID     pgtype.UUID        `json:"categoria_id"`
	UsuarioID       pgtype.UUID        `json:"usuario_id"`
	Active          bool               `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CategoriaNombre pgtype.Text        `json:"categoria_nombre"`
	FamiliaNombre   pgtype.Text        `json:"familia_nombre"`
}

func (q *Queries) ListProductosByCategoria(ctx context.Context, arg ListProductosByCategoriaParams) ([]ListProductosByCategoriaRow, error) {
	rows, err := q.db.Query(ctx, listProductosByCategoria, arg.CategoriaID, arg.UsuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductosByCategoriaRow
	for rows.Next() {
		var i ListProductosByCategoriaRow
		if err := rows.Scan(
			&i.ID,
			&i.Codigo,
			&i.Nombre,
			&i.Descripcion,
			&i.PrecioBase,
			&i.Unidad,
			&i.CategoriaID,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoriaNombre,
			&i.FamiliaNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProductos = `-- name: SearchProductos :many
SELECT p.id, p.codigo, p.nombre, p.descripcion, p.precio_base, p.unidad, p.categoria_id, p.usuario_id, p.active, p.created_at, p.updated_at,
       c.nombre AS categoria_nombre,
       f.nombre AS familia_nombre
FROM productos p
LEFT JOIN categorias_producto c ON c.id = p.categoria_id
LEFT JOIN familias_producto f ON f.id = c.familia_id
WHERE p.usuario_id = $1 AND p.active = TRUE
  AND (p.nombre ILIKE $2 OR p.codigo ILIKE $2)
ORDER BY p.nombre
LIMIT $3 OFFSET $4
`

type SearchProductosParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Nombre    string      `json:"nombre"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type SearchProductosRow struct {
	ID              pgtype.UUID        `json:"id"`
	Codigo          pgtype.Text        `json:"codigo"`
	Nombre          string             `json:"nombre"`
	Descripcion     pgtype.Text        `json:"descripcion"`
	PrecioBase      pgtype.Numeric     `json:"precio_base"`
	Unidad          UnidadDeMedida     `json:"unidad"`
	CategoriaID     pgtype.UUID        `json:"categoria_id"`
	UsuarioID       pgtype.UUID        `json:"usuario_id"`
	Active          bool               `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CategoriaNombre pgtype.Text        `json:"categoria_nombre"`
	FamiliaNombre   pgtype.Text        `json:"familia_nombre"`
}

func (q *Queries) SearchProductos(ctx context.Context, arg SearchProductosParams) ([]SearchProductosRow, error) {
	rows, err := q.db.Query(ctx, searchProductos,
		arg.UsuarioID,
		arg.Nombre,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProductosRow
	for rows.Next() {
		var i SearchProductosRow
		if err := rows.Scan(
			&i.ID,
			&i.Codigo,
			&i.Nombre,
			&i.Descripcion,
			&i.PrecioBase,
			&i.Unidad,
			&i.CategoriaID,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoriaNombre,
			&i.FamiliaNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProducto = `-- name: SoftDeleteProducto :exec
UPDATE productos
SET active = FALSE, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2
`

type SoftDeleteProductoParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) SoftDeleteProducto(ctx context.Context, arg SoftDeleteProductoParams) error {
	_, err := q.db.Exec(ctx, softDeleteProducto, arg.ID, arg.UsuarioID)
	return err
}

const updateProducto = `-- name: UpdateProducto :one
UPDATE productos
SET codigo = $3, nombre = $4, descripcion = $5, precio_base = $6,
    unidad = $7, categoria_id = $8, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
RETURNING id, codigo, nombre, descripcion, precio_base, unidad, categoria_id, usuario_id, active, created_at, updated_at
`

type UpdateProductoParams struct {
	ID          pgtype.UUID    `json:"id"`
	UsuarioID   pgtype.UUID    `json:"usuario_id"`
	Codigo      pgtype.Text    `json:"codigo"`
	Nombre      string         `json:"nombre"`
	Descripcion pgtype.Text    `json:"descripcion"`
	PrecioBase  pgtype.Numeric `json:"precio_base"`
	Unidad      UnidadDeMedida `json:"unidad"`
	CategoriaID pgtype.UUID    `json:"categoria_id"`
}

func (q *Queries) UpdateProducto(ctx context.Context, arg UpdateProductoParams) (Producto, error) {
	row := q.db.QueryRow(ctx, updateProducto,
		arg.ID,
		arg.UsuarioID,
		arg.Codigo,
		arg.Nombre,
		arg.Descripcion,
		arg.PrecioBase,
		arg.Unidad,
		arg.CategoriaID,
	)
	var i Producto
	err := row.Scan(
		&i.ID,
		&i.Codigo,
		&i.Nombre,
		&i.Descripcion,
		&i.PrecioBase,
		&i.Unidad,
		&i.CategoriaID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
