// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: promociones.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPromociones = `-- name: CountPromociones :one
SELECT COUNT(*) FROM promociones
WHERE usuario_id = $1 AND active = TRUE
`

func (q *Queries) CountPromociones(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPromociones, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPromocion = `-- name: CreatePromocion :one
INSERT INTO promociones (nombre, tipo, valor, cantidad_minima, producto_id, categoria_id, fecha_inicio, fecha_fin, activa, sucursal_id, usuario_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, nombre, tipo, valor, cantidad_minima, producto_id, categoria_id, fecha_inicio, fecha_fin, activa, sucursal_id, usuario_id, active, created_at
`

type CreatePromocionParams struct {
	Nombre         string         `json:"nombre"`
	Tipo           TipoPromocion  `json:"tipo"`
	Valor          pgtype.Numeric `json:"valor"`
	CantidadMinima pgtype.Int4    `json:"cantidad_minima"`
	ProductoID     pgtype.UUID    `json:"producto_id"`
	CategoriaID    pgtype.UUID    `json:"categoria_id"`
	FechaInicio    pgtype.Date    `json:"fecha_inicio"`
	FechaFin       pgtype.Date    `json:"fecha_fin"`
	Activa         bool           `json:"activa"`
	SucursalID     pgtype.UUID    `json:"sucursal_id"`
	UsuarioID      pgtype.UUID    `json:"usuario_id"`
}

func (q *Queries) CreatePromocion(ctx context.Context, arg CreatePromocionParams) (Promocion, error) {
	row := q.db.QueryRow(ctx, createPromocion,
		arg.Nombre,
		arg.Tipo,
		arg.Valor,
		arg.CantidadMinima,
		arg.ProductoID,
		arg.CategoriaID,
		arg.FechaInicio,
		arg.FechaFin,
		arg.Activa,
		arg.SucursalID,
		arg.UsuarioID,
	)
	var i Promocion
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Tipo,
		&i.Valor,
		&i.CantidadMinima,
		&i.ProductoID,
		&i.CategoriaID,
		&i.FechaInicio,
		&i.FechaFin,
		&i.Activa,
		&i.SucursalID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getPromocionByID = `-- name: GetPromocionByID :one
SELECT p.id, p.nombre, p.tipo, p.valor, p.cantidad_minima, p.producto_id, p.categoria_id, p.fecha_inicio, p.fecha_fin, p.activa, p.sucursal_id, p.usuario_id, p.active, p.created_at,
       prod.nombre AS producto_nombre,
       cat.nombre AS categoria_nombre,
       s.nombre AS sucursal_nombre
FROM promociones p
LEFT JOIN productos prod ON prod.id = p.producto_id
LEFT JOIN categorias_producto cat ON cat.id = p.categoria_id
LEFT JOIN sucursales s ON s.id = p.sucursal_id
WHERE p.id = $1 AND p.usuario_id = $2 AND p.active = TRUE
`

type GetPromocionByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

type GetPromocionByIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	Nombre         string             `json:"nombre"`
	Tipo           TipoPromocion      `json:"tipo"`
	Valor          pgtype.Numeric     `json:"valor"`
	CantidadMinima pgtype.Int4        `json:"cantidad_minima"`
	ProductoID     pgtype.UUID        `json:"producto_id"`
	CategoriaID    pgtype.UUID        `json:"categoria_id"`
	FechaInicio    pgtype.Date        `json:"fecha_inicio"`
	FechaFin       pgtype.Date        `json:"fecha_fin"`
	Activa         bool               `json:"activa"`
	SucursalID     pgtype.UUID        `json:"sucursal_id"`
	UsuarioID      pgtype.UUID        `json:"usuario_id"`
	Active         bool               `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ProductoNombre pgtype.Text        `json:"producto_nombre"`
	CategoriaNombre pgtype.Text       `json:"categoria_nombre"`
	SucursalNombre pgtype.Text        `json:"sucursal_nombre"`
}

func (q *Queries) GetPromocionByID(ctx context.Context, arg GetPromocionByIDParams) (GetPromocionByIDRow, error) {
	row := q.db.QueryRow(ctx, getPromocionByID, arg.ID, arg.UsuarioID)
	var i GetPromocionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Tipo,
		&i.Valor,
		&i.CantidadMinima,
		&i.ProductoID,
		&i.CategoriaID,
		&i.FechaInicio,
		&i.FechaFin,
		&i.Activa,
		&i.SucursalID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.ProductoNombre,
		&i.CategoriaNombre,
		&i.SucursalNombre,
	)
	return i, err
}

const listPromociones = `-- name: ListPromociones :many
SELECT p.id, p.nombre, p.tipo, p.valor, p.cantidad_minima, p.producto_id, p.categoria_id, p.fecha_inicio, p.fecha_fin, p.activa, p.sucursal_id, p.usuario_id, p.active, p.created_at,
       prod.nombre AS producto_nombre,
       cat.nombre AS categoria_nombre,
       s.nombre AS sucursal_nombre
FROM promociones p
LEFT JOIN productos prod ON prod.id = p.producto_id
LEFT JOIN categorias_producto cat ON cat.id = p.categoria_id
LEFT JOIN sucursales s ON s.id = p.sucursal_id
WHERE p.usuario_id = $1 AND p.active = TRUE
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type ListPromocionesParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListPromocionesRow struct {
	ID             pgtype.UUID        `json:"id"`
	Nombre         string             `json:"nombre"`
	Tipo           TipoPromocion      `json:"tipo"`
	Valor          pgtype.Numeric     `json:"valor"`
	CantidadMinima pgtype.Int4        `json:"cantidad_minima"`
	ProductoID     pgtype.UUID        `json:"producto_id"`
	CategoriaID    pgtype.UUID        `json:"categoria_id"`
	FechaInicio    pgtype.Date        `json:"fecha_inicio"`
	FechaFin       pgtype.Date        `json:"fecha_fin"`
	Activa         bool               `json:"activa"`
	SucursalID     pgtype.UUID        `json:"sucursal_id"`
	UsuarioID      pgtype.UUID        `json:"usuario_id"`
	Active         bool               `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ProductoNombre pgtype.Text        `json:"producto_nombre"`
	CategoriaNombre pgtype.Text       `json:"categoria_nombre"`
	SucursalNombre pgtype.Text        `json:"sucursal_nombre"`
}

func (q *Queries) ListPromociones(ctx context.Context, arg ListPromocionesParams) ([]ListPromocionesRow, error) {
	rows, err := q.db.Query(ctx, listPromociones, arg.UsuarioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPromocionesRow
	for rows.Next() {
		var i ListPromocionesRow
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Tipo,
			&i.Valor,
			&i.CantidadMinima,
			&i.ProductoID,
			&i.CategoriaID,
			&i.FechaInicio,
			&i.FechaFin,
			&i.Activa,
			&i.SucursalID,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.ProductoNombre,
			&i.CategoriaNombre,
			&i.SucursalNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePromocion = `-- name: UpdatePromocion :one
UPDATE promociones
SET nombre = $3, tipo = $4, valor = $5, cantidad_minima = $6,
    producto_id = $7, categoria_id = $8, fecha_inicio = $9,
    fecha_fin = $10, activa = $11, sucursal_id = $12
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
RETURNING id, nombre, tipo, valor, cantidad_minima, producto_id, categoria_id, fecha_inicio, fecha_fin, activa, sucursal_id, usuario_id, active, created_at
`

type UpdatePromocionParams struct {
	ID             pgtype.UUID    `json:"id"`
	UsuarioID      pgtype.UUID    `json:"usuario_id"`
	Nombre         string         `json:"nombre"`
	Tipo           TipoPromocion  `json:"tipo"`
	Valor          pgtype.Numeric `json:"valor"`
	CantidadMinima pgtype.Int4    `json:"cantidad_minima"`
	ProductoID     pgtype.UUID    `json:"producto_id"`
	CategoriaID    pgtype.UUID    `json:"categoria_id"`
	FechaInicio    pgtype.Date    `json:"fecha_inicio"`
	FechaFin       pgtype.Date    `json:"fecha_fin"`
	Activa         bool           `json:"activa"`
	SucursalID     pgtype.UUID    `json:"sucursal_id"`
}

func (q *Queries) UpdatePromocion(ctx context.Context, arg UpdatePromocionParams) (Promocion, error) {
	row := q.db.QueryRow(ctx, updatePromocion,
		arg.ID,
		arg.UsuarioID,
		arg.Nombre,
		arg.Tipo,
		arg.Valor,
		arg.CantidadMinima,
		arg.ProductoID,
		arg.CategoriaID,
		arg.FechaInicio,
		arg.FechaFin,
		arg.Activa,
		arg.SucursalID,
	)
	var i Promocion
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Tipo,
		&i.Valor,
		&i.CantidadMinima,
		&i.ProductoID,
		&i.CategoriaID,
		&i.FechaInicio,
		&i.FechaFin,
		&i.Activa,
		&i.SucursalID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const softDeletePromocion = `-- name: SoftDeletePromocion :exec
UPDATE promociones
SET active = FALSE
WHERE id = $1 AND usuario_id = $2
`

type SoftDeletePromocionParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) SoftDeletePromocion(ctx context.Context, arg SoftDeletePromocionParams) error {
	_, err := q.db.Exec(ctx, softDeletePromocion, arg.ID, arg.UsuarioID)
	return err
}
