// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExtracto = `-- name: CreateExtracto :one
INSERT INTO extractos_bancarios (entidad_bancaria_id, fecha_desde, fecha_hasta, archivo_nombre, usuario_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, entidad_bancaria_id, fecha_desde, fecha_hasta, archivo_nombre, usuario_id, created_at
`

type CreateExtractoParams struct {
	EntidadBancariaID pgtype.UUID `json:"entidad_bancaria_id"`
	FechaDesde        pgtype.Date `json:"fecha_desde"`
	FechaHasta        pgtype.Date `json:"fecha_hasta"`
	ArchivoNombre     pgtype.Text `json:"archivo_nombre"`
	UsuarioID         pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) CreateExtracto(ctx context.Context, arg CreateExtractoParams) (ExtractosBancario, error) {
	row := q.db.QueryRow(ctx, createExtracto,
		arg.EntidadBancariaID, arg.FechaDesde, arg.FechaHasta, arg.ArchivoNombre, arg.UsuarioID,
	)
	var i ExtractosBancario
	err := row.Scan(
		&i.ID, &i.EntidadBancariaID, &i.FechaDesde, &i.FechaHasta,
		&i.ArchivoNombre, &i.UsuarioID, &i.CreatedAt,
	)
	return i, err
}

const listExtractos = `-- name: ListExtractos :many
SELECT e.id, e.entidad_bancaria_id, e.fecha_desde, e.fecha_hasta, e.archivo_nombre, e.usuario_id, e.created_at,
       eb.nombre as entidad_nombre
FROM extractos_bancarios e
LEFT JOIN entidades_bancarias eb ON eb.id = e.entidad_bancaria_id
WHERE e.usuario_id = $1
ORDER BY e.created_at DESC
LIMIT $2 OFFSET $3
`

type ListExtractosParams struct {
	UsuarioID   pgtype.UUID `json:"usuario_id"`
	QueryLimit  int32       `json:"query_limit"`
	QueryOffset int32       `json:"query_offset"`
}

type ListExtractosRow struct {
	ID                pgtype.UUID        `json:"id"`
	EntidadBancariaID pgtype.UUID        `json:"entidad_bancaria_id"`
	FechaDesde        pgtype.Date        `json:"fecha_desde"`
	FechaHasta        pgtype.Date        `json:"fecha_hasta"`
	ArchivoNombre     pgtype.Text        `json:"archivo_nombre"`
	UsuarioID         pgtype.UUID        `json:"usuario_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	EntidadNombre     pgtype.Text        `json:"entidad_nombre"`
}

func (q *Queries) ListExtractos(ctx context.Context, arg ListExtractosParams) ([]ListExtractosRow, error) {
	rows, err := q.db.Query(ctx, listExtractos, arg.UsuarioID, arg.QueryLimit, arg.QueryOffset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExtractosRow
	for rows.Next() {
		var i ListExtractosRow
		if err := rows.Scan(
			&i.ID, &i.EntidadBancariaID, &i.FechaDesde, &i.FechaHasta,
			&i.ArchivoNombre, &i.UsuarioID, &i.CreatedAt, &i.EntidadNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, nil
}

const countExtractos = `-- name: CountExtractos :one
SELECT COUNT(*) FROM extractos_bancarios WHERE usuario_id = $1
`

func (q *Queries) CountExtractos(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countExtractos, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getExtracto = `-- name: GetExtracto :one
SELECT e.id, e.entidad_bancaria_id, e.fecha_desde, e.fecha_hasta, e.archivo_nombre, e.usuario_id, e.created_at,
       eb.nombre as entidad_nombre
FROM extractos_bancarios e
LEFT JOIN entidades_bancarias eb ON eb.id = e.entidad_bancaria_id
WHERE e.id = $1 AND e.usuario_id = $2
`

type GetExtractoParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

type GetExtractoRow struct {
	ID                pgtype.UUID        `json:"id"`
	EntidadBancariaID pgtype.UUID        `json:"entidad_bancaria_id"`
	FechaDesde        pgtype.Date        `json:"fecha_desde"`
	FechaHasta        pgtype.Date        `json:"fecha_hasta"`
	ArchivoNombre     pgtype.Text        `json:"archivo_nombre"`
	UsuarioID         pgtype.UUID        `json:"usuario_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	EntidadNombre     pgtype.Text        `json:"entidad_nombre"`
}

func (q *Queries) GetExtracto(ctx context.Context, arg GetExtractoParams) (GetExtractoRow, error) {
	row := q.db.QueryRow(ctx, getExtracto, arg.ID, arg.UsuarioID)
	var i GetExtractoRow
	err := row.Scan(
		&i.ID, &i.EntidadBancariaID, &i.FechaDesde, &i.FechaHasta,
		&i.ArchivoNombre, &i.UsuarioID, &i.CreatedAt, &i.EntidadNombre,
	)
	return i, err
}

const createMovimientoBancario = `-- name: CreateMovimientoBancario :one
INSERT INTO movimientos_bancarios (extracto_id, fecha, descripcion, monto, referencia, usuario_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, extracto_id, fecha, descripcion, monto, referencia, estado_conciliacion, movimiento_caja_id, usuario_id, created_at
`

type CreateMovimientoBancarioParams struct {
	ExtractoID  pgtype.UUID    `json:"extracto_id"`
	Fecha       pgtype.Date    `json:"fecha"`
	Descripcion string         `json:"descripcion"`
	Monto       pgtype.Numeric `json:"monto"`
	Referencia  pgtype.Text    `json:"referencia"`
	UsuarioID   pgtype.UUID    `json:"usuario_id"`
}

func (q *Queries) CreateMovimientoBancario(ctx context.Context, arg CreateMovimientoBancarioParams) (MovimientosBancario, error) {
	row := q.db.QueryRow(ctx, createMovimientoBancario,
		arg.ExtractoID, arg.Fecha, arg.Descripcion, arg.Monto, arg.Referencia, arg.UsuarioID,
	)
	var i MovimientosBancario
	err := row.Scan(
		&i.ID, &i.ExtractoID, &i.Fecha, &i.Descripcion, &i.Monto,
		&i.Referencia, &i.EstadoConciliacion, &i.MovimientoCajaID, &i.UsuarioID, &i.CreatedAt,
	)
	return i, err
}

const listMovimientosBancarios = `-- name: ListMovimientosBancarios :many
SELECT id, extracto_id, fecha, descripcion, monto, referencia, estado_conciliacion, movimiento_caja_id, usuario_id, created_at
FROM movimientos_bancarios
WHERE extracto_id = $1 AND usuario_id = $2
ORDER BY fecha, created_at
`

type ListMovimientosBancariosParams struct {
	ExtractoID pgtype.UUID `json:"extracto_id"`
	UsuarioID  pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) ListMovimientosBancarios(ctx context.Context, arg ListMovimientosBancariosParams) ([]MovimientosBancario, error) {
	rows, err := q.db.Query(ctx, listMovimientosBancarios, arg.ExtractoID, arg.UsuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MovimientosBancario
	for rows.Next() {
		var i MovimientosBancario
		if err := rows.Scan(
			&i.ID, &i.ExtractoID, &i.Fecha, &i.Descripcion, &i.Monto,
			&i.Referencia, &i.EstadoConciliacion, &i.MovimientoCajaID, &i.UsuarioID, &i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, nil
}

const updateConciliacion = `-- name: UpdateConciliacion :one
UPDATE movimientos_bancarios
SET estado_conciliacion = $1, movimiento_caja_id = $2
WHERE id = $3 AND usuario_id = $4
RETURNING id, extracto_id, fecha, descripcion, monto, referencia, estado_conciliacion, movimiento_caja_id, usuario_id, created_at
`

type UpdateConciliacionParams struct {
	EstadoConciliacion EstadoConciliacion `json:"estado_conciliacion"`
	MovimientoCajaID   pgtype.UUID        `json:"movimiento_caja_id"`
	ID                 pgtype.UUID        `json:"id"`
	UsuarioID          pgtype.UUID        `json:"usuario_id"`
}

func (q *Queries) UpdateConciliacion(ctx context.Context, arg UpdateConciliacionParams) (MovimientosBancario, error) {
	row := q.db.QueryRow(ctx, updateConciliacion,
		arg.EstadoConciliacion, arg.MovimientoCajaID, arg.ID, arg.UsuarioID,
	)
	var i MovimientosBancario
	err := row.Scan(
		&i.ID, &i.ExtractoID, &i.Fecha, &i.Descripcion, &i.Monto,
		&i.Referencia, &i.EstadoConciliacion, &i.MovimientoCajaID, &i.UsuarioID, &i.CreatedAt,
	)
	return i, err
}

const listMovimientosCajaParaConciliar = `-- name: ListMovimientosCajaParaConciliar :many
SELECT mc.id, mc.caja_id, mc.tipo, mc.monto, mc.concepto, mc.created_at,
       c.nombre as caja_nombre
FROM movimientos_caja mc
JOIN cajas c ON c.id = mc.caja_id
WHERE c.sucursal_id IN (SELECT sucursal_id FROM entidades_bancarias WHERE id = $1)
  AND mc.created_at >= $2
  AND mc.created_at <= $3
  AND mc.id NOT IN (SELECT movimiento_caja_id FROM movimientos_bancarios WHERE movimiento_caja_id IS NOT NULL AND usuario_id = $4)
ORDER BY mc.created_at
`

type ListMovimientosCajaParaConciliarParams struct {
	EntidadBancariaID pgtype.UUID        `json:"entidad_bancaria_id"`
	Desde             pgtype.Timestamptz `json:"desde"`
	Hasta             pgtype.Timestamptz `json:"hasta"`
	UsuarioID         pgtype.UUID        `json:"usuario_id"`
}

type ListMovimientosCajaParaConciliarRow struct {
	ID        pgtype.UUID        `json:"id"`
	CajaID    pgtype.UUID        `json:"caja_id"`
	Tipo      TipoMovimiento     `json:"tipo"`
	Monto     pgtype.Numeric     `json:"monto"`
	Concepto  string             `json:"concepto"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CajaNombre string            `json:"caja_nombre"`
}

func (q *Queries) ListMovimientosCajaParaConciliar(ctx context.Context, arg ListMovimientosCajaParaConciliarParams) ([]ListMovimientosCajaParaConciliarRow, error) {
	rows, err := q.db.Query(ctx, listMovimientosCajaParaConciliar,
		arg.EntidadBancariaID, arg.Desde, arg.Hasta, arg.UsuarioID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMovimientosCajaParaConciliarRow
	for rows.Next() {
		var i ListMovimientosCajaParaConciliarRow
		if err := rows.Scan(
			&i.ID, &i.CajaID, &i.Tipo, &i.Monto, &i.Concepto, &i.CreatedAt, &i.CajaNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, nil
}
