// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rutas.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRutas = `-- name: CountRutas :one
SELECT COUNT(*) FROM rutas
WHERE usuario_id = $1 AND active = TRUE
`

func (q *Queries) CountRutas(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRutas, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRuta = `-- name: CreateRuta :one
INSERT INTO rutas (nombre, zona_id, vehiculo_id, dia_semana, hora_salida_estimada, notas, sucursal_id, usuario_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, nombre, zona_id, vehiculo_id, dia_semana, hora_salida_estimada, notas, sucursal_id, usuario_id, active, created_at, updated_at
`

type CreateRutaParams struct {
	Nombre             string      `json:"nombre"`
	ZonaID             pgtype.UUID `json:"zona_id"`
	VehiculoID         pgtype.UUID `json:"vehiculo_id"`
	DiaSemana          pgtype.Int4 `json:"dia_semana"`
	HoraSalidaEstimada pgtype.Time `json:"hora_salida_estimada"`
	Notas              pgtype.Text `json:"notas"`
	SucursalID         pgtype.UUID `json:"sucursal_id"`
	UsuarioID          pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) CreateRuta(ctx context.Context, arg CreateRutaParams) (Ruta, error) {
	row := q.db.QueryRow(ctx, createRuta,
		arg.Nombre,
		arg.ZonaID,
		arg.VehiculoID,
		arg.DiaSemana,
		arg.HoraSalidaEstimada,
		arg.Notas,
		arg.SucursalID,
		arg.UsuarioID,
	)
	var i Ruta
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.ZonaID,
		&i.VehiculoID,
		&i.DiaSemana,
		&i.HoraSalidaEstimada,
		&i.Notas,
		&i.SucursalID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRutaParada = `-- name: CreateRutaParada :one
INSERT INTO ruta_paradas (ruta_id, cliente_id, direccion_id, orden, tiempo_estimado_minutos, notas)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, ruta_id, cliente_id, direccion_id, orden, tiempo_estimado_minutos, notas
`

type CreateRutaParadaParams struct {
	RutaID                pgtype.UUID `json:"ruta_id"`
	ClienteID             pgtype.UUID `json:"cliente_id"`
	DireccionID           pgtype.UUID `json:"direccion_id"`
	Orden                 int32       `json:"orden"`
	TiempoEstimadoMinutos pgtype.Int4 `json:"tiempo_estimado_minutos"`
	Notas                 pgtype.Text `json:"notas"`
}

func (q *Queries) CreateRutaParada(ctx context.Context, arg CreateRutaParadaParams) (RutaParada, error) {
	row := q.db.QueryRow(ctx, createRutaParada,
		arg.RutaID,
		arg.ClienteID,
		arg.DireccionID,
		arg.Orden,
		arg.TiempoEstimadoMinutos,
		arg.Notas,
	)
	var i RutaParada
	err := row.Scan(
		&i.ID,
		&i.RutaID,
		&i.ClienteID,
		&i.DireccionID,
		&i.Orden,
		&i.TiempoEstimadoMinutos,
		&i.Notas,
	)
	return i, err
}

const deleteRutaParadasByRuta = `-- name: DeleteRutaParadasByRuta :exec
DELETE FROM ruta_paradas WHERE ruta_id = $1
`

func (q *Queries) DeleteRutaParadasByRuta(ctx context.Context, rutaID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRutaParadasByRuta, rutaID)
	return err
}

const getRutaByID = `-- name: GetRutaByID :one
SELECT r.id, r.nombre, r.zona_id, r.vehiculo_id, r.dia_semana, r.hora_salida_estimada, r.notas, r.sucursal_id, r.usuario_id, r.active, r.created_at, r.updated_at,
       z.nombre AS zona_nombre,
       v.patente AS vehiculo_patente,
       v.marca || ' ' || v.modelo AS vehiculo_descripcion,
       s.nombre AS sucursal_nombre
FROM rutas r
LEFT JOIN zonas z ON z.id = r.zona_id
LEFT JOIN vehiculos v ON v.id = r.vehiculo_id
JOIN sucursales s ON s.id = r.sucursal_id
WHERE r.id = $1 AND r.usuario_id = $2 AND r.active = TRUE
`

type GetRutaByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

type GetRutaByIDRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Nombre              string             `json:"nombre"`
	ZonaID              pgtype.UUID        `json:"zona_id"`
	VehiculoID          pgtype.UUID        `json:"vehiculo_id"`
	DiaSemana           pgtype.Int4        `json:"dia_semana"`
	HoraSalidaEstimada  pgtype.Time        `json:"hora_salida_estimada"`
	Notas               pgtype.Text        `json:"notas"`
	SucursalID          pgtype.UUID        `json:"sucursal_id"`
	UsuarioID           pgtype.UUID        `json:"usuario_id"`
	Active              bool               `json:"active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ZonaNombre          pgtype.Text        `json:"zona_nombre"`
	VehiculoPatente     pgtype.Text        `json:"vehiculo_patente"`
	VehiculoDescripcion interface{}        `json:"vehiculo_descripcion"`
	SucursalNombre      string             `json:"sucursal_nombre"`
}

func (q *Queries) GetRutaByID(ctx context.Context, arg GetRutaByIDParams) (GetRutaByIDRow, error) {
	row := q.db.QueryRow(ctx, getRutaByID, arg.ID, arg.UsuarioID)
	var i GetRutaByIDRow
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.ZonaID,
		&i.VehiculoID,
		&i.DiaSemana,
		&i.HoraSalidaEstimada,
		&i.Notas,
		&i.SucursalID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ZonaNombre,
		&i.VehiculoPatente,
		&i.VehiculoDescripcion,
		&i.SucursalNombre,
	)
	return i, err
}

const listCatalogoForExport = `-- name: ListCatalogoForExport :many
SELECT cp.precio, cp.stock,
       p.nombre AS producto_nombre,
       p.codigo AS producto_codigo,
       p.unidad AS producto_unidad,
       p.precio_base AS producto_precio_base,
       f.nombre AS familia_nombre,
       cat.nombre AS categoria_nombre,
       s.nombre AS sucursal_nombre
FROM catalogo_productos cp
JOIN productos p ON p.id = cp.producto_id
LEFT JOIN categorias_producto cat ON cat.id = p.categoria_id
LEFT JOIN familias_producto f ON f.id = cat.familia_id
JOIN sucursales s ON s.id = cp.sucursal_id
WHERE cp.sucursal_id = $1 AND cp.active = TRUE AND p.active = TRUE
ORDER BY f.nombre, cat.nombre, p.nombre
`

type ListCatalogoForExportRow struct {
	Precio             pgtype.Numeric `json:"precio"`
	Stock              int32          `json:"stock"`
	ProductoNombre     string         `json:"producto_nombre"`
	ProductoCodigo     pgtype.Text    `json:"producto_codigo"`
	ProductoUnidad     UnidadDeMedida `json:"producto_unidad"`
	ProductoPrecioBase pgtype.Numeric `json:"producto_precio_base"`
	FamiliaNombre      pgtype.Text    `json:"familia_nombre"`
	CategoriaNombre    pgtype.Text    `json:"categoria_nombre"`
	SucursalNombre     string         `json:"sucursal_nombre"`
}

func (q *Queries) ListCatalogoForExport(ctx context.Context, sucursalID pgtype.UUID) ([]ListCatalogoForExportRow, error) {
	rows, err := q.db.Query(ctx, listCatalogoForExport, sucursalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCatalogoForExportRow
	for rows.Next() {
		var i ListCatalogoForExportRow
		if err := rows.Scan(
			&i.Precio,
			&i.Stock,
			&i.ProductoNombre,
			&i.ProductoCodigo,
			&i.ProductoUnidad,
			&i.ProductoPrecioBase,
			&i.FamiliaNombre,
			&i.CategoriaNombre,
			&i.SucursalNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingPedidosByCliente = `-- name: ListPendingPedidosByCliente :many
SELECT p.id, p.numero, p.total, p.estado, p.fecha_pedido,
       c.nombre AS cliente_nombre
FROM pedidos p
JOIN clientes c ON c.id = p.cliente_id
WHERE p.cliente_id = $1 AND p.usuario_id = $2
  AND p.active = TRUE
  AND p.estado IN ('APROBADO', 'EN_PREPARACION', 'PREPARADO')
ORDER BY p.fecha_pedido
`

type ListPendingPedidosByClienteParams struct {
	ClienteID pgtype.UUID `json:"cliente_id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

type ListPendingPedidosByClienteRow struct {
	ID            pgtype.UUID        `json:"id"`
	Numero        string             `json:"numero"`
	Total         pgtype.Numeric     `json:"total"`
	Estado        EstadoPedido       `json:"estado"`
	FechaPedido   pgtype.Timestamptz `json:"fecha_pedido"`
	ClienteNombre string             `json:"cliente_nombre"`
}

func (q *Queries) ListPendingPedidosByCliente(ctx context.Context, arg ListPendingPedidosByClienteParams) ([]ListPendingPedidosByClienteRow, error) {
	rows, err := q.db.Query(ctx, listPendingPedidosByCliente, arg.ClienteID, arg.UsuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingPedidosByClienteRow
	for rows.Next() {
		var i ListPendingPedidosByClienteRow
		if err := rows.Scan(
			&i.ID,
			&i.Numero,
			&i.Total,
			&i.Estado,
			&i.FechaPedido,
			&i.ClienteNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRutaParadas = `-- name: ListRutaParadas :many
SELECT rp.id, rp.ruta_id, rp.cliente_id, rp.direccion_id, rp.orden, rp.tiempo_estimado_minutos, rp.notas,
       c.nombre AS cliente_nombre,
       c.apellido AS cliente_apellido,
       d.calle AS direccion_calle,
       d.numero AS direccion_numero,
       d.ciudad AS direccion_ciudad
FROM ruta_paradas rp
JOIN clientes c ON c.id = rp.cliente_id
LEFT JOIN direcciones d ON d.id = rp.direccion_id
WHERE rp.ruta_id = $1
ORDER BY rp.orden
`

type ListRutaParadasRow struct {
	ID                    pgtype.UUID `json:"id"`
	RutaID                pgtype.UUID `json:"ruta_id"`
	ClienteID             pgtype.UUID `json:"cliente_id"`
	DireccionID           pgtype.UUID `json:"direccion_id"`
	Orden                 int32       `json:"orden"`
	TiempoEstimadoMinutos pgtype.Int4 `json:"tiempo_estimado_minutos"`
	Notas                 pgtype.Text `json:"notas"`
	ClienteNombre         string      `json:"cliente_nombre"`
	ClienteApellido       pgtype.Text `json:"cliente_apellido"`
	DireccionCalle        pgtype.Text `json:"direccion_calle"`
	DireccionNumero       pgtype.Text `json:"direccion_numero"`
	DireccionCiudad       pgtype.Text `json:"direccion_ciudad"`
}

func (q *Queries) ListRutaParadas(ctx context.Context, rutaID pgtype.UUID) ([]ListRutaParadasRow, error) {
	rows, err := q.db.Query(ctx, listRutaParadas, rutaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRutaParadasRow
	for rows.Next() {
		var i ListRutaParadasRow
		if err := rows.Scan(
			&i.ID,
			&i.RutaID,
			&i.ClienteID,
			&i.DireccionID,
			&i.Orden,
			&i.TiempoEstimadoMinutos,
			&i.Notas,
			&i.ClienteNombre,
			&i.ClienteApellido,
			&i.DireccionCalle,
			&i.DireccionNumero,
			&i.DireccionCiudad,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRutas = `-- name: ListRutas :many
SELECT r.id, r.nombre, r.zona_id, r.vehiculo_id, r.dia_semana, r.hora_salida_estimada, r.notas, r.sucursal_id, r.usuario_id, r.active, r.created_at, r.updated_at,
       z.nombre AS zona_nombre,
       v.patente AS vehiculo_patente,
       s.nombre AS sucursal_nombre,
       (SELECT COUNT(*) FROM ruta_paradas rp WHERE rp.ruta_id = r.id) AS paradas_count
FROM rutas r
LEFT JOIN zonas z ON z.id = r.zona_id
LEFT JOIN vehiculos v ON v.id = r.vehiculo_id
JOIN sucursales s ON s.id = r.sucursal_id
WHERE r.usuario_id = $1 AND r.active = TRUE
ORDER BY r.nombre
LIMIT $2 OFFSET $3
`

type ListRutasParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListRutasRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Nombre             string             `json:"nombre"`
	ZonaID             pgtype.UUID        `json:"zona_id"`
	VehiculoID         pgtype.UUID        `json:"vehiculo_id"`
	DiaSemana          pgtype.Int4        `json:"dia_semana"`
	HoraSalidaEstimada pgtype.Time        `json:"hora_salida_estimada"`
	Notas              pgtype.Text        `json:"notas"`
	SucursalID         pgtype.UUID        `json:"sucursal_id"`
	UsuarioID          pgtype.UUID        `json:"usuario_id"`
	Active             bool               `json:"active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ZonaNombre         pgtype.Text        `json:"zona_nombre"`
	VehiculoPatente    pgtype.Text        `json:"vehiculo_patente"`
	SucursalNombre     string             `json:"sucursal_nombre"`
	ParadasCount       int64              `json:"paradas_count"`
}

func (q *Queries) ListRutas(ctx context.Context, arg ListRutasParams) ([]ListRutasRow, error) {
	rows, err := q.db.Query(ctx, listRutas, arg.UsuarioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRutasRow
	for rows.Next() {
		var i ListRutasRow
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.ZonaID,
			&i.VehiculoID,
			&i.DiaSemana,
			&i.HoraSalidaEstimada,
			&i.Notas,
			&i.SucursalID,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ZonaNombre,
			&i.VehiculoPatente,
			&i.SucursalNombre,
			&i.ParadasCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRuta = `-- name: SoftDeleteRuta :exec
UPDATE rutas
SET active = FALSE, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2
`

type SoftDeleteRutaParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) SoftDeleteRuta(ctx context.Context, arg SoftDeleteRutaParams) error {
	_, err := q.db.Exec(ctx, softDeleteRuta, arg.ID, arg.UsuarioID)
	return err
}

const updateRuta = `-- name: UpdateRuta :one
UPDATE rutas
SET nombre = $3, zona_id = $4, vehiculo_id = $5, dia_semana = $6,
    hora_salida_estimada = $7, notas = $8, sucursal_id = $9, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
RETURNING id, nombre, zona_id, vehiculo_id, dia_semana, hora_salida_estimada, notas, sucursal_id, usuario_id, active, created_at, updated_at
`

type UpdateRutaParams struct {
	ID                 pgtype.UUID `json:"id"`
	UsuarioID          pgtype.UUID `json:"usuario_id"`
	Nombre             string      `json:"nombre"`
	ZonaID             pgtype.UUID `json:"zona_id"`
	VehiculoID         pgtype.UUID `json:"vehiculo_id"`
	DiaSemana          pgtype.Int4 `json:"dia_semana"`
	HoraSalidaEstimada pgtype.Time `json:"hora_salida_estimada"`
	Notas              pgtype.Text `json:"notas"`
	SucursalID         pgtype.UUID `json:"sucursal_id"`
}

func (q *Queries) UpdateRuta(ctx context.Context, arg UpdateRutaParams) (Ruta, error) {
	row := q.db.QueryRow(ctx, updateRuta,
		arg.ID,
		arg.UsuarioID,
		arg.Nombre,
		arg.ZonaID,
		arg.VehiculoID,
		arg.DiaSemana,
		arg.HoraSalidaEstimada,
		arg.Notas,
		arg.SucursalID,
	)
	var i Ruta
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.ZonaID,
		&i.VehiculoID,
		&i.DiaSemana,
		&i.HoraSalidaEstimada,
		&i.Notas,
		&i.SucursalID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
