// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transferencias.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTransferencias = `-- name: CountTransferencias :one
SELECT COUNT(*) FROM transferencias_sucursal
WHERE usuario_id = $1 AND active = TRUE
`

func (q *Queries) CountTransferencias(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTransferencias, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransferenciasByEstado = `-- name: CountTransferenciasByEstado :one
SELECT COUNT(*) FROM transferencias_sucursal
WHERE usuario_id = $1 AND active = TRUE AND estado = $2
`

type CountTransferenciasByEstadoParams struct {
	UsuarioID pgtype.UUID         `json:"usuario_id"`
	Estado    EstadoTransferencia `json:"estado"`
}

func (q *Queries) CountTransferenciasByEstado(ctx context.Context, arg CountTransferenciasByEstadoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTransferenciasByEstado, arg.UsuarioID, arg.Estado)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItemTransferencia = `-- name: CreateItemTransferencia :one
INSERT INTO items_transferencia (
    transferencia_id, producto_id, producto_nombre, producto_codigo, cantidad_solicitada
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, transferencia_id, producto_id, producto_nombre, producto_codigo, cantidad_solicitada, cantidad_enviada, cantidad_recibida
`

type CreateItemTransferenciaParams struct {
	TransferenciaID    pgtype.UUID `json:"transferencia_id"`
	ProductoID         pgtype.UUID `json:"producto_id"`
	ProductoNombre     string      `json:"producto_nombre"`
	ProductoCodigo     pgtype.Text `json:"producto_codigo"`
	CantidadSolicitada int32       `json:"cantidad_solicitada"`
}

func (q *Queries) CreateItemTransferencia(ctx context.Context, arg CreateItemTransferenciaParams) (ItemsTransferencium, error) {
	row := q.db.QueryRow(ctx, createItemTransferencia,
		arg.TransferenciaID,
		arg.ProductoID,
		arg.ProductoNombre,
		arg.ProductoCodigo,
		arg.CantidadSolicitada,
	)
	var i ItemsTransferencium
	err := row.Scan(
		&i.ID,
		&i.TransferenciaID,
		&i.ProductoID,
		&i.ProductoNombre,
		&i.ProductoCodigo,
		&i.CantidadSolicitada,
		&i.CantidadEnviada,
		&i.CantidadRecibida,
	)
	return i, err
}

const createTransferencia = `-- name: CreateTransferencia :one
INSERT INTO transferencias_sucursal (
    numero, sucursal_origen_id, sucursal_destino_id, observaciones,
    solicitado_por, usuario_id
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, numero, sucursal_origen_id, sucursal_destino_id, estado, fecha_solicitud, fecha_aprobacion, fecha_envio, fecha_recepcion, observaciones, aprobado_por, solicitado_por, usuario_id, active, created_at, updated_at
`

type CreateTransferenciaParams struct {
	Numero            string      `json:"numero"`
	SucursalOrigenID  pgtype.UUID `json:"sucursal_origen_id"`
	SucursalDestinoID pgtype.UUID `json:"sucursal_destino_id"`
	Observaciones     pgtype.Text `json:"observaciones"`
	SolicitadoPor     pgtype.UUID `json:"solicitado_por"`
	UsuarioID         pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) CreateTransferencia(ctx context.Context, arg CreateTransferenciaParams) (TransferenciasSucursal, error) {
	row := q.db.QueryRow(ctx, createTransferencia,
		arg.Numero,
		arg.SucursalOrigenID,
		arg.SucursalDestinoID,
		arg.Observaciones,
		arg.SolicitadoPor,
		arg.UsuarioID,
	)
	var i TransferenciasSucursal
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.SucursalOrigenID,
		&i.SucursalDestinoID,
		&i.Estado,
		&i.FechaSolicitud,
		&i.FechaAprobacion,
		&i.FechaEnvio,
		&i.FechaRecepcion,
		&i.Observaciones,
		&i.AprobadoPor,
		&i.SolicitadoPor,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransferenciaByID = `-- name: GetTransferenciaByID :one
SELECT t.id, t.numero, t.sucursal_origen_id, t.sucursal_destino_id, t.estado, t.fecha_solicitud, t.fecha_aprobacion, t.fecha_envio, t.fecha_recepcion, t.observaciones, t.aprobado_por, t.solicitado_por, t.usuario_id, t.active, t.created_at, t.updated_at,
       so.nombre AS sucursal_origen_nombre,
       sd.nombre AS sucursal_destino_nombre,
       es.nombre AS solicitado_por_nombre,
       ea.nombre AS aprobado_por_nombre
FROM transferencias_sucursal t
JOIN sucursales so ON so.id = t.sucursal_origen_id
JOIN sucursales sd ON sd.id = t.sucursal_destino_id
LEFT JOIN empleados es ON es.id = t.solicitado_por
LEFT JOIN empleados ea ON ea.id = t.aprobado_por
WHERE t.id = $1 AND t.usuario_id = $2 AND t.active = TRUE
`

type GetTransferenciaByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

type GetTransferenciaByIDRow struct {
	ID                    pgtype.UUID         `json:"id"`
	Numero                string              `json:"numero"`
	SucursalOrigenID      pgtype.UUID         `json:"sucursal_origen_id"`
	SucursalDestinoID     pgtype.UUID         `json:"sucursal_destino_id"`
	Estado                EstadoTransferencia `json:"estado"`
	FechaSolicitud        pgtype.Timestamptz  `json:"fecha_solicitud"`
	FechaAprobacion       pgtype.Timestamptz  `json:"fecha_aprobacion"`
	FechaEnvio            pgtype.Timestamptz  `json:"fecha_envio"`
	FechaRecepcion        pgtype.Timestamptz  `json:"fecha_recepcion"`
	Observaciones         pgtype.Text         `json:"observaciones"`
	AprobadoPor           pgtype.UUID         `json:"aprobado_por"`
	SolicitadoPor         pgtype.UUID         `json:"solicitado_por"`
	UsuarioID             pgtype.UUID         `json:"usuario_id"`
	Active                bool                `json:"active"`
	CreatedAt             pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz  `json:"updated_at"`
	SucursalOrigenNombre  string              `json:"sucursal_origen_nombre"`
	SucursalDestinoNombre string              `json:"sucursal_destino_nombre"`
	SolicitadoPorNombre   pgtype.Text         `json:"solicitado_por_nombre"`
	AprobadoPorNombre     pgtype.Text         `json:"aprobado_por_nombre"`
}

func (q *Queries) GetTransferenciaByID(ctx context.Context, arg GetTransferenciaByIDParams) (GetTransferenciaByIDRow, error) {
	row := q.db.QueryRow(ctx, getTransferenciaByID, arg.ID, arg.UsuarioID)
	var i GetTransferenciaByIDRow
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.SucursalOrigenID,
		&i.SucursalDestinoID,
		&i.Estado,
		&i.FechaSolicitud,
		&i.FechaAprobacion,
		&i.FechaEnvio,
		&i.FechaRecepcion,
		&i.Observaciones,
		&i.AprobadoPor,
		&i.SolicitadoPor,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SucursalOrigenNombre,
		&i.SucursalDestinoNombre,
		&i.SolicitadoPorNombre,
		&i.AprobadoPorNombre,
	)
	return i, err
}

const listItemsTransferencia = `-- name: ListItemsTransferencia :many
SELECT id, transferencia_id, producto_id, producto_nombre, producto_codigo, cantidad_solicitada, cantidad_enviada, cantidad_recibida FROM items_transferencia
WHERE transferencia_id = $1
ORDER BY producto_nombre
`

func (q *Queries) ListItemsTransferencia(ctx context.Context, transferenciaID pgtype.UUID) ([]ItemsTransferencium, error) {
	rows, err := q.db.Query(ctx, listItemsTransferencia, transferenciaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemsTransferencium
	for rows.Next() {
		var i ItemsTransferencium
		if err := rows.Scan(
			&i.ID,
			&i.TransferenciaID,
			&i.ProductoID,
			&i.ProductoNombre,
			&i.ProductoCodigo,
			&i.CantidadSolicitada,
			&i.CantidadEnviada,
			&i.CantidadRecibida,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsTransferenciaSimple = `-- name: ListItemsTransferenciaSimple :many
SELECT id, producto_id, producto_nombre, producto_codigo,
       cantidad_solicitada, cantidad_enviada, cantidad_recibida
FROM items_transferencia
WHERE transferencia_id = $1
`

type ListItemsTransferenciaSimpleRow struct {
	ID                 pgtype.UUID `json:"id"`
	ProductoID         pgtype.UUID `json:"producto_id"`
	ProductoNombre     string      `json:"producto_nombre"`
	ProductoCodigo     pgtype.Text `json:"producto_codigo"`
	CantidadSolicitada int32       `json:"cantidad_solicitada"`
	CantidadEnviada    int32       `json:"cantidad_enviada"`
	CantidadRecibida   int32       `json:"cantidad_recibida"`
}

func (q *Queries) ListItemsTransferenciaSimple(ctx context.Context, transferenciaID pgtype.UUID) ([]ListItemsTransferenciaSimpleRow, error) {
	rows, err := q.db.Query(ctx, listItemsTransferenciaSimple, transferenciaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsTransferenciaSimpleRow
	for rows.Next() {
		var i ListItemsTransferenciaSimpleRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductoID,
			&i.ProductoNombre,
			&i.ProductoCodigo,
			&i.CantidadSolicitada,
			&i.CantidadEnviada,
			&i.CantidadRecibida,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransferencias = `-- name: ListTransferencias :many
SELECT t.id, t.numero, t.sucursal_origen_id, t.sucursal_destino_id, t.estado, t.fecha_solicitud, t.fecha_aprobacion, t.fecha_envio, t.fecha_recepcion, t.observaciones, t.aprobado_por, t.solicitado_por, t.usuario_id, t.active, t.created_at, t.updated_at,
       so.nombre AS sucursal_origen_nombre,
       sd.nombre AS sucursal_destino_nombre,
       (SELECT COUNT(*) FROM items_transferencia it WHERE it.transferencia_id = t.id) AS items_count
FROM transferencias_sucursal t
JOIN sucursales so ON so.id = t.sucursal_origen_id
JOIN sucursales sd ON sd.id = t.sucursal_destino_id
WHERE t.usuario_id = $1 AND t.active = TRUE
ORDER BY t.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransferenciasParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListTransferenciasRow struct {
	ID                    pgtype.UUID         `json:"id"`
	Numero                string              `json:"numero"`
	SucursalOrigenID      pgtype.UUID         `json:"sucursal_origen_id"`
	SucursalDestinoID     pgtype.UUID         `json:"sucursal_destino_id"`
	Estado                EstadoTransferencia `json:"estado"`
	FechaSolicitud        pgtype.Timestamptz  `json:"fecha_solicitud"`
	FechaAprobacion       pgtype.Timestamptz  `json:"fecha_aprobacion"`
	FechaEnvio            pgtype.Timestamptz  `json:"fecha_envio"`
	FechaRecepcion        pgtype.Timestamptz  `json:"fecha_recepcion"`
	Observaciones         pgtype.Text         `json:"observaciones"`
	AprobadoPor           pgtype.UUID         `json:"aprobado_por"`
	SolicitadoPor         pgtype.UUID         `json:"solicitado_por"`
	UsuarioID             pgtype.UUID         `json:"usuario_id"`
	Active                bool                `json:"active"`
	CreatedAt             pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz  `json:"updated_at"`
	SucursalOrigenNombre  string              `json:"sucursal_origen_nombre"`
	SucursalDestinoNombre string              `json:"sucursal_destino_nombre"`
	ItemsCount            int64               `json:"items_count"`
}

func (q *Queries) ListTransferencias(ctx context.Context, arg ListTransferenciasParams) ([]ListTransferenciasRow, error) {
	rows, err := q.db.Query(ctx, listTransferencias, arg.UsuarioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransferenciasRow
	for rows.Next() {
		var i ListTransferenciasRow
		if err := rows.Scan(
			&i.ID,
			&i.Numero,
			&i.SucursalOrigenID,
			&i.SucursalDestinoID,
			&i.Estado,
			&i.FechaSolicitud,
			&i.FechaAprobacion,
			&i.FechaEnvio,
			&i.FechaRecepcion,
			&i.Observaciones,
			&i.AprobadoPor,
			&i.SolicitadoPor,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SucursalOrigenNombre,
			&i.SucursalDestinoNombre,
			&i.ItemsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransferenciasByEstado = `-- name: ListTransferenciasByEstado :many
SELECT t.id, t.numero, t.sucursal_origen_id, t.sucursal_destino_id, t.estado, t.fecha_solicitud, t.fecha_aprobacion, t.fecha_envio, t.fecha_recepcion, t.observaciones, t.aprobado_por, t.solicitado_por, t.usuario_id, t.active, t.created_at, t.updated_at,
       so.nombre AS sucursal_origen_nombre,
       sd.nombre AS sucursal_destino_nombre,
       (SELECT COUNT(*) FROM items_transferencia it WHERE it.transferencia_id = t.id) AS items_count
FROM transferencias_sucursal t
JOIN sucursales so ON so.id = t.sucursal_origen_id
JOIN sucursales sd ON sd.id = t.sucursal_destino_id
WHERE t.usuario_id = $1 AND t.active = TRUE AND t.estado = $2
ORDER BY t.created_at DESC
LIMIT $3 OFFSET $4
`

type ListTransferenciasByEstadoParams struct {
	UsuarioID pgtype.UUID         `json:"usuario_id"`
	Estado    EstadoTransferencia `json:"estado"`
	Limit     int32               `json:"limit"`
	Offset    int32               `json:"offset"`
}

type ListTransferenciasByEstadoRow struct {
	ID                    pgtype.UUID         `json:"id"`
	Numero                string              `json:"numero"`
	SucursalOrigenID      pgtype.UUID         `json:"sucursal_origen_id"`
	SucursalDestinoID     pgtype.UUID         `json:"sucursal_destino_id"`
	Estado                EstadoTransferencia `json:"estado"`
	FechaSolicitud        pgtype.Timestamptz  `json:"fecha_solicitud"`
	FechaAprobacion       pgtype.Timestamptz  `json:"fecha_aprobacion"`
	FechaEnvio            pgtype.Timestamptz  `json:"fecha_envio"`
	FechaRecepcion        pgtype.Timestamptz  `json:"fecha_recepcion"`
	Observaciones         pgtype.Text         `json:"observaciones"`
	AprobadoPor           pgtype.UUID         `json:"aprobado_por"`
	SolicitadoPor         pgtype.UUID         `json:"solicitado_por"`
	UsuarioID             pgtype.UUID         `json:"usuario_id"`
	Active                bool                `json:"active"`
	CreatedAt             pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz  `json:"updated_at"`
	SucursalOrigenNombre  string              `json:"sucursal_origen_nombre"`
	SucursalDestinoNombre string              `json:"sucursal_destino_nombre"`
	ItemsCount            int64               `json:"items_count"`
}

func (q *Queries) ListTransferenciasByEstado(ctx context.Context, arg ListTransferenciasByEstadoParams) ([]ListTransferenciasByEstadoRow, error) {
	rows, err := q.db.Query(ctx, listTransferenciasByEstado,
		arg.UsuarioID,
		arg.Estado,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransferenciasByEstadoRow
	for rows.Next() {
		var i ListTransferenciasByEstadoRow
		if err := rows.Scan(
			&i.ID,
			&i.Numero,
			&i.SucursalOrigenID,
			&i.SucursalDestinoID,
			&i.Estado,
			&i.FechaSolicitud,
			&i.FechaAprobacion,
			&i.FechaEnvio,
			&i.FechaRecepcion,
			&i.Observaciones,
			&i.AprobadoPor,
			&i.SolicitadoPor,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SucursalOrigenNombre,
			&i.SucursalDestinoNombre,
			&i.ItemsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextTransferenciaNumero = `-- name: NextTransferenciaNumero :one
SELECT 'TR-' || LPAD(nextval('transferencia_numero_seq')::text, 6, '0')
`

func (q *Queries) NextTransferenciaNumero(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, nextTransferenciaNumero)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}

const softDeleteTransferencia = `-- name: SoftDeleteTransferencia :exec
UPDATE transferencias_sucursal
SET active = FALSE, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2
`

type SoftDeleteTransferenciaParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) SoftDeleteTransferencia(ctx context.Context, arg SoftDeleteTransferenciaParams) error {
	_, err := q.db.Exec(ctx, softDeleteTransferencia, arg.ID, arg.UsuarioID)
	return err
}

const updateItemEnviado = `-- name: UpdateItemEnviado :exec
UPDATE items_transferencia
SET cantidad_enviada = $2
WHERE id = $1
`

type UpdateItemEnviadoParams struct {
	ID              pgtype.UUID `json:"id"`
	CantidadEnviada int32       `json:"cantidad_enviada"`
}

func (q *Queries) UpdateItemEnviado(ctx context.Context, arg UpdateItemEnviadoParams) error {
	_, err := q.db.Exec(ctx, updateItemEnviado, arg.ID, arg.CantidadEnviada)
	return err
}

const updateItemRecibido = `-- name: UpdateItemRecibido :exec
UPDATE items_transferencia
SET cantidad_recibida = $2
WHERE id = $1
`

type UpdateItemRecibidoParams struct {
	ID               pgtype.UUID `json:"id"`
	CantidadRecibida int32       `json:"cantidad_recibida"`
}

func (q *Queries) UpdateItemRecibido(ctx context.Context, arg UpdateItemRecibidoParams) error {
	_, err := q.db.Exec(ctx, updateItemRecibido, arg.ID, arg.CantidadRecibida)
	return err
}

const updateTransferenciaAprobacion = `-- name: UpdateTransferenciaAprobacion :exec
UPDATE transferencias_sucursal
SET estado = 'APROBADA', fecha_aprobacion = NOW(), aprobado_por = $3, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2
`

type UpdateTransferenciaAprobacionParams struct {
	ID          pgtype.UUID `json:"id"`
	UsuarioID   pgtype.UUID `json:"usuario_id"`
	AprobadoPor pgtype.UUID `json:"aprobado_por"`
}

func (q *Queries) UpdateTransferenciaAprobacion(ctx context.Context, arg UpdateTransferenciaAprobacionParams) error {
	_, err := q.db.Exec(ctx, updateTransferenciaAprobacion, arg.ID, arg.UsuarioID, arg.AprobadoPor)
	return err
}

const updateTransferenciaEnvio = `-- name: UpdateTransferenciaEnvio :exec
UPDATE transferencias_sucursal
SET estado = 'EN_TRANSITO', fecha_envio = NOW(), updated_at = NOW()
WHERE id = $1 AND usuario_id = $2
`

type UpdateTransferenciaEnvioParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) UpdateTransferenciaEnvio(ctx context.Context, arg UpdateTransferenciaEnvioParams) error {
	_, err := q.db.Exec(ctx, updateTransferenciaEnvio, arg.ID, arg.UsuarioID)
	return err
}

const updateTransferenciaEstado = `-- name: UpdateTransferenciaEstado :exec
UPDATE transferencias_sucursal
SET estado = $3, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2
`

type UpdateTransferenciaEstadoParams struct {
	ID        pgtype.UUID         `json:"id"`
	UsuarioID pgtype.UUID         `json:"usuario_id"`
	Estado    EstadoTransferencia `json:"estado"`
}

func (q *Queries) UpdateTransferenciaEstado(ctx context.Context, arg UpdateTransferenciaEstadoParams) error {
	_, err := q.db.Exec(ctx, updateTransferenciaEstado, arg.ID, arg.UsuarioID, arg.Estado)
	return err
}

const updateTransferenciaRecepcion = `-- name: UpdateTransferenciaRecepcion :exec
UPDATE transferencias_sucursal
SET estado = 'COMPLETADA', fecha_recepcion = NOW(), updated_at = NOW()
WHERE id = $1 AND usuario_id = $2
`

type UpdateTransferenciaRecepcionParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) UpdateTransferenciaRecepcion(ctx context.Context, arg UpdateTransferenciaRecepcionParams) error {
	_, err := q.db.Exec(ctx, updateTransferenciaRecepcion, arg.ID, arg.UsuarioID)
	return err
}
