// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_settings.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserSettings = `-- name: CreateUserSettings :one
INSERT INTO user_settings (usuario_id)
VALUES ($1)
RETURNING id, usuario_id, dashboard_layout, api_key, created_at, updated_at
`

func (q *Queries) CreateUserSettings(ctx context.Context, usuarioID pgtype.UUID) (UserSetting, error) {
	row := q.db.QueryRow(ctx, createUserSettings, usuarioID)
	var i UserSetting
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.DashboardLayout,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSettings = `-- name: GetUserSettings :one
SELECT id, usuario_id, dashboard_layout, api_key, created_at, updated_at FROM user_settings WHERE usuario_id = $1
`

func (q *Queries) GetUserSettings(ctx context.Context, usuarioID pgtype.UUID) (UserSetting, error) {
	row := q.db.QueryRow(ctx, getUserSettings, usuarioID)
	var i UserSetting
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.DashboardLayout,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
