// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO usuarios (email, password_hash, nombre, apellido, rol)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password_hash, nombre, apellido, rol, email_verified, active, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Nombre       string `json:"nombre"`
	Apellido     string `json:"apellido"`
	Rol          Rol    `json:"rol"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Usuario, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Nombre,
		arg.Apellido,
		arg.Rol,
	)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Nombre,
		&i.Apellido,
		&i.Rol,
		&i.EmailVerified,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, nombre, apellido, rol, email_verified, active, created_at, updated_at FROM usuarios WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (Usuario, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Nombre,
		&i.Apellido,
		&i.Rol,
		&i.EmailVerified,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, nombre, apellido, rol, email_verified, active, created_at, updated_at FROM usuarios WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (Usuario, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Nombre,
		&i.Apellido,
		&i.Rol,
		&i.EmailVerified,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserEmailVerified = `-- name: UpdateUserEmailVerified :exec
UPDATE usuarios SET email_verified = TRUE, updated_at = NOW() WHERE email = $1
`

func (q *Queries) UpdateUserEmailVerified(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, updateUserEmailVerified, email)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE usuarios SET password_hash = $1, updated_at = NOW() WHERE email = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	Email        string `json:"email"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.Email)
	return err
}
