// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vehiculos.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVehiculos = `-- name: CountVehiculos :one
SELECT COUNT(*) FROM vehiculos
WHERE usuario_id = $1 AND active = TRUE
`

func (q *Queries) CountVehiculos(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVehiculos, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVehiculo = `-- name: CreateVehiculo :one
INSERT INTO vehiculos (marca, modelo, patente, anio, capacidad_kg, capacidad_volumen, sucursal_id, usuario_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, marca, modelo, patente, anio, capacidad_kg, capacidad_volumen, sucursal_id, usuario_id, active, created_at, updated_at
`

type CreateVehiculoParams struct {
	Marca            string         `json:"marca"`
	Modelo           string         `json:"modelo"`
	Patente          string         `json:"patente"`
	Anio             pgtype.Int4    `json:"anio"`
	CapacidadKg      pgtype.Numeric `json:"capacidad_kg"`
	CapacidadVolumen pgtype.Numeric `json:"capacidad_volumen"`
	SucursalID       pgtype.UUID    `json:"sucursal_id"`
	UsuarioID        pgtype.UUID    `json:"usuario_id"`
}

func (q *Queries) CreateVehiculo(ctx context.Context, arg CreateVehiculoParams) (Vehiculo, error) {
	row := q.db.QueryRow(ctx, createVehiculo,
		arg.Marca,
		arg.Modelo,
		arg.Patente,
		arg.Anio,
		arg.CapacidadKg,
		arg.CapacidadVolumen,
		arg.SucursalID,
		arg.UsuarioID,
	)
	var i Vehiculo
	err := row.Scan(
		&i.ID,
		&i.Marca,
		&i.Modelo,
		&i.Patente,
		&i.Anio,
		&i.CapacidadKg,
		&i.CapacidadVolumen,
		&i.SucursalID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVehiculoByID = `-- name: GetVehiculoByID :one
SELECT v.id, v.marca, v.modelo, v.patente, v.anio, v.capacidad_kg, v.capacidad_volumen, v.sucursal_id, v.usuario_id, v.active, v.created_at, v.updated_at, s.nombre AS sucursal_nombre
FROM vehiculos v
LEFT JOIN sucursales s ON s.id = v.sucursal_id
WHERE v.id = $1 AND v.usuario_id = $2 AND v.active = TRUE
`

type GetVehiculoByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

type GetVehiculoByIDRow struct {
	ID               pgtype.UUID        `json:"id"`
	Marca            string             `json:"marca"`
	Modelo           string             `json:"modelo"`
	Patente          string             `json:"patente"`
	Anio             pgtype.Int4        `json:"anio"`
	CapacidadKg      pgtype.Numeric     `json:"capacidad_kg"`
	CapacidadVolumen pgtype.Numeric     `json:"capacidad_volumen"`
	SucursalID       pgtype.UUID        `json:"sucursal_id"`
	UsuarioID        pgtype.UUID        `json:"usuario_id"`
	Active           bool               `json:"active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	SucursalNombre   pgtype.Text        `json:"sucursal_nombre"`
}

func (q *Queries) GetVehiculoByID(ctx context.Context, arg GetVehiculoByIDParams) (GetVehiculoByIDRow, error) {
	row := q.db.QueryRow(ctx, getVehiculoByID, arg.ID, arg.UsuarioID)
	var i GetVehiculoByIDRow
	err := row.Scan(
		&i.ID,
		&i.Marca,
		&i.Modelo,
		&i.Patente,
		&i.Anio,
		&i.CapacidadKg,
		&i.CapacidadVolumen,
		&i.SucursalID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SucursalNombre,
	)
	return i, err
}

const listVehiculos = `-- name: ListVehiculos :many
SELECT v.id, v.marca, v.modelo, v.patente, v.anio, v.capacidad_kg, v.capacidad_volumen, v.sucursal_id, v.usuario_id, v.active, v.created_at, v.updated_at, s.nombre AS sucursal_nombre
FROM vehiculos v
LEFT JOIN sucursales s ON s.id = v.sucursal_id
WHERE v.usuario_id = $1 AND v.active = TRUE
ORDER BY v.patente
LIMIT $2 OFFSET $3
`

type ListVehiculosParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListVehiculosRow struct {
	ID               pgtype.UUID        `json:"id"`
	Marca            string             `json:"marca"`
	Modelo           string             `json:"modelo"`
	Patente          string             `json:"patente"`
	Anio             pgtype.Int4        `json:"anio"`
	CapacidadKg      pgtype.Numeric     `json:"capacidad_kg"`
	CapacidadVolumen pgtype.Numeric     `json:"capacidad_volumen"`
	SucursalID       pgtype.UUID        `json:"sucursal_id"`
	UsuarioID        pgtype.UUID        `json:"usuario_id"`
	Active           bool               `json:"active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	SucursalNombre   pgtype.Text        `json:"sucursal_nombre"`
}

func (q *Queries) ListVehiculos(ctx context.Context, arg ListVehiculosParams) ([]ListVehiculosRow, error) {
	rows, err := q.db.Query(ctx, listVehiculos, arg.UsuarioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVehiculosRow
	for rows.Next() {
		var i ListVehiculosRow
		if err := rows.Scan(
			&i.ID,
			&i.Marca,
			&i.Modelo,
			&i.Patente,
			&i.Anio,
			&i.CapacidadKg,
			&i.CapacidadVolumen,
			&i.SucursalID,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SucursalNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehiculosBySucursal = `-- name: ListVehiculosBySucursal :many
SELECT v.id, v.marca, v.modelo, v.patente, v.anio, v.capacidad_kg, v.capacidad_volumen, v.sucursal_id, v.usuario_id, v.active, v.created_at, v.updated_at, s.nombre AS sucursal_nombre
FROM vehiculos v
LEFT JOIN sucursales s ON s.id = v.sucursal_id
WHERE v.usuario_id = $1 AND v.sucursal_id = $2 AND v.active = TRUE
ORDER BY v.patente
`

type ListVehiculosBySucursalParams struct {
	UsuarioID  pgtype.UUID `json:"usuario_id"`
	SucursalID pgtype.UUID `json:"sucursal_id"`
}

type ListVehiculosBySucursalRow struct {
	ID               pgtype.UUID        `json:"id"`
	Marca            string             `json:"marca"`
	Modelo           string             `json:"modelo"`
	Patente          string             `json:"patente"`
	Anio             pgtype.Int4        `json:"anio"`
	CapacidadKg      pgtype.Numeric     `json:"capacidad_kg"`
	CapacidadVolumen pgtype.Numeric     `json:"capacidad_volumen"`
	SucursalID       pgtype.UUID        `json:"sucursal_id"`
	UsuarioID        pgtype.UUID        `json:"usuario_id"`
	Active           bool               `json:"active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	SucursalNombre   pgtype.Text        `json:"sucursal_nombre"`
}

func (q *Queries) ListVehiculosBySucursal(ctx context.Context, arg ListVehiculosBySucursalParams) ([]ListVehiculosBySucursalRow, error) {
	rows, err := q.db.Query(ctx, listVehiculosBySucursal, arg.UsuarioID, arg.SucursalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVehiculosBySucursalRow
	for rows.Next() {
		var i ListVehiculosBySucursalRow
		if err := rows.Scan(
			&i.ID,
			&i.Marca,
			&i.Modelo,
			&i.Patente,
			&i.Anio,
			&i.CapacidadKg,
			&i.CapacidadVolumen,
			&i.SucursalID,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SucursalNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteVehiculo = `-- name: SoftDeleteVehiculo :exec
UPDATE vehiculos
SET active = FALSE, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2
`

type SoftDeleteVehiculoParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) SoftDeleteVehiculo(ctx context.Context, arg SoftDeleteVehiculoParams) error {
	_, err := q.db.Exec(ctx, softDeleteVehiculo, arg.ID, arg.UsuarioID)
	return err
}

const updateVehiculo = `-- name: UpdateVehiculo :one
UPDATE vehiculos
SET marca = $3, modelo = $4, patente = $5, anio = $6,
    capacidad_kg = $7, capacidad_volumen = $8, sucursal_id = $9, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
RETURNING id, marca, modelo, patente, anio, capacidad_kg, capacidad_volumen, sucursal_id, usuario_id, active, created_at, updated_at
`

type UpdateVehiculoParams struct {
	ID               pgtype.UUID    `json:"id"`
	UsuarioID        pgtype.UUID    `json:"usuario_id"`
	Marca            string         `json:"marca"`
	Modelo           string         `json:"modelo"`
	Patente          string         `json:"patente"`
	Anio             pgtype.Int4    `json:"anio"`
	CapacidadKg      pgtype.Numeric `json:"capacidad_kg"`
	CapacidadVolumen pgtype.Numeric `json:"capacidad_volumen"`
	SucursalID       pgtype.UUID    `json:"sucursal_id"`
}

func (q *Queries) UpdateVehiculo(ctx context.Context, arg UpdateVehiculoParams) (Vehiculo, error) {
	row := q.db.QueryRow(ctx, updateVehiculo,
		arg.ID,
		arg.UsuarioID,
		arg.Marca,
		arg.Modelo,
		arg.Patente,
		arg.Anio,
		arg.CapacidadKg,
		arg.CapacidadVolumen,
		arg.SucursalID,
	)
	var i Vehiculo
	err := row.Scan(
		&i.ID,
		&i.Marca,
		&i.Modelo,
		&i.Patente,
		&i.Anio,
		&i.CapacidadKg,
		&i.CapacidadVolumen,
		&i.SucursalID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
