// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: zonas.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countZonas = `-- name: CountZonas :one
SELECT COUNT(*) FROM zonas
WHERE usuario_id = $1 AND active = TRUE
`

func (q *Queries) CountZonas(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countZonas, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createZona = `-- name: CreateZona :one
INSERT INTO zonas (nombre, descripcion, sucursal_id, usuario_id)
VALUES ($1, $2, $3, $4)
RETURNING id, nombre, descripcion, sucursal_id, usuario_id, active, created_at, updated_at
`

type CreateZonaParams struct {
	Nombre      string      `json:"nombre"`
	Descripcion pgtype.Text `json:"descripcion"`
	SucursalID  pgtype.UUID `json:"sucursal_id"`
	UsuarioID   pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) CreateZona(ctx context.Context, arg CreateZonaParams) (Zona, error) {
	row := q.db.QueryRow(ctx, createZona,
		arg.Nombre,
		arg.Descripcion,
		arg.SucursalID,
		arg.UsuarioID,
	)
	var i Zona
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.SucursalID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getZonaByID = `-- name: GetZonaByID :one
SELECT z.id, z.nombre, z.descripcion, z.sucursal_id, z.usuario_id, z.active, z.created_at, z.updated_at, s.nombre AS sucursal_nombre
FROM zonas z
LEFT JOIN sucursales s ON s.id = z.sucursal_id
WHERE z.id = $1 AND z.usuario_id = $2 AND z.active = TRUE
`

type GetZonaByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

type GetZonaByIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	Nombre         string             `json:"nombre"`
	Descripcion    pgtype.Text        `json:"descripcion"`
	SucursalID     pgtype.UUID        `json:"sucursal_id"`
	UsuarioID      pgtype.UUID        `json:"usuario_id"`
	Active         bool               `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	SucursalNombre pgtype.Text        `json:"sucursal_nombre"`
}

func (q *Queries) GetZonaByID(ctx context.Context, arg GetZonaByIDParams) (GetZonaByIDRow, error) {
	row := q.db.QueryRow(ctx, getZonaByID, arg.ID, arg.UsuarioID)
	var i GetZonaByIDRow
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.SucursalID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SucursalNombre,
	)
	return i, err
}

const listZonas = `-- name: ListZonas :many
SELECT z.id, z.nombre, z.descripcion, z.sucursal_id, z.usuario_id, z.active, z.created_at, z.updated_at, s.nombre AS sucursal_nombre
FROM zonas z
LEFT JOIN sucursales s ON s.id = z.sucursal_id
WHERE z.usuario_id = $1 AND z.active = TRUE
ORDER BY z.nombre
LIMIT $2 OFFSET $3
`

type ListZonasParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListZonasRow struct {
	ID             pgtype.UUID        `json:"id"`
	Nombre         string             `json:"nombre"`
	Descripcion    pgtype.Text        `json:"descripcion"`
	SucursalID     pgtype.UUID        `json:"sucursal_id"`
	UsuarioID      pgtype.UUID        `json:"usuario_id"`
	Active         bool               `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	SucursalNombre pgtype.Text        `json:"sucursal_nombre"`
}

func (q *Queries) ListZonas(ctx context.Context, arg ListZonasParams) ([]ListZonasRow, error) {
	rows, err := q.db.Query(ctx, listZonas, arg.UsuarioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListZonasRow
	for rows.Next() {
		var i ListZonasRow
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Descripcion,
			&i.SucursalID,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SucursalNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZonasBySucursal = `-- name: ListZonasBySucursal :many
SELECT z.id, z.nombre, z.descripcion, z.sucursal_id, z.usuario_id, z.active, z.created_at, z.updated_at, s.nombre AS sucursal_nombre
FROM zonas z
LEFT JOIN sucursales s ON s.id = z.sucursal_id
WHERE z.usuario_id = $1 AND z.sucursal_id = $2 AND z.active = TRUE
ORDER BY z.nombre
`

type ListZonasBySucursalParams struct {
	UsuarioID  pgtype.UUID `json:"usuario_id"`
	SucursalID pgtype.UUID `json:"sucursal_id"`
}

type ListZonasBySucursalRow struct {
	ID             pgtype.UUID        `json:"id"`
	Nombre         string             `json:"nombre"`
	Descripcion    pgtype.Text        `json:"descripcion"`
	SucursalID     pgtype.UUID        `json:"sucursal_id"`
	UsuarioID      pgtype.UUID        `json:"usuario_id"`
	Active         bool               `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	SucursalNombre pgtype.Text        `json:"sucursal_nombre"`
}

func (q *Queries) ListZonasBySucursal(ctx context.Context, arg ListZonasBySucursalParams) ([]ListZonasBySucursalRow, error) {
	rows, err := q.db.Query(ctx, listZonasBySucursal, arg.UsuarioID, arg.SucursalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListZonasBySucursalRow
	for rows.Next() {
		var i ListZonasBySucursalRow
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Descripcion,
			&i.SucursalID,
			&i.UsuarioID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SucursalNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteZona = `-- name: SoftDeleteZona :exec
UPDATE zonas
SET active = FALSE, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2
`

type SoftDeleteZonaParams struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) SoftDeleteZona(ctx context.Context, arg SoftDeleteZonaParams) error {
	_, err := q.db.Exec(ctx, softDeleteZona, arg.ID, arg.UsuarioID)
	return err
}

const updateZona = `-- name: UpdateZona :one
UPDATE zonas
SET nombre = $3, descripcion = $4, sucursal_id = $5, updated_at = NOW()
WHERE id = $1 AND usuario_id = $2 AND active = TRUE
RETURNING id, nombre, descripcion, sucursal_id, usuario_id, active, created_at, updated_at
`

type UpdateZonaParams struct {
	ID          pgtype.UUID `json:"id"`
	UsuarioID   pgtype.UUID `json:"usuario_id"`
	Nombre      string      `json:"nombre"`
	Descripcion pgtype.Text `json:"descripcion"`
	SucursalID  pgtype.UUID `json:"sucursal_id"`
}

func (q *Queries) UpdateZona(ctx context.Context, arg UpdateZonaParams) (Zona, error) {
	row := q.db.QueryRow(ctx, updateZona,
		arg.ID,
		arg.UsuarioID,
		arg.Nombre,
		arg.Descripcion,
		arg.SucursalID,
	)
	var i Zona
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.SucursalID,
		&i.UsuarioID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
